from collections.abc import Iterable
from re import Pattern
from typing import Final, overload

always_safe: Final[str]
urlencoded: Final[set[str]]
INVALID_HEX_PATTERN: Final[Pattern[str]]

def url_encode(params: Iterable[tuple[str, str]]) -> str: ...
def url_decode(query: str) -> list[tuple[str, str]]: ...
def add_params_to_qs(query: str, params: Iterable[tuple[str, str]] | dict[str, str]) -> str: ...
def add_params_to_uri(uri: str, params: Iterable[tuple[str, str]] | dict[str, str], fragment: bool = False) -> str: ...
def quote(s: str | bytes | float, safe: bytes = b"/") -> str: ...
def unquote(s: str | bytes) -> str: ...
def quote_url(s: str | bytes | float) -> str: ...

@overload
def extract_params(raw: None) -> None: ...
@overload
def extract_params(raw: dict[str, str]) -> list[tuple[str, str]]: ...
@overload
def extract_params(raw: list[tuple[str, str]] | tuple[tuple[str, str], ...] | str) -> list[tuple[str, str]] | None: ...

def is_valid_url(url: str, fragments_allowed: bool = True) -> bool: ...
