# managed by go/iml_to_build
java_import(
    name = "ant-commons-net",
    jars = ["ant-commons-net.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-jmf",
    jars = ["ant-jmf.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-apache-resolver",
    jars = ["ant-apache-resolver.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-jai",
    jars = ["ant-jai.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-apache-bsf",
    jars = ["ant-apache-bsf.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-commons-logging",
    jars = ["ant-commons-logging.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-junit",
    jars = ["ant-junit.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-jsch",
    jars = ["ant-jsch.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-apache-bcel",
    jars = ["ant-apache-bcel.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant",
    jars = ["ant.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-netrexx",
    jars = ["ant-netrexx.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-apache-oro",
    jars = ["ant-apache-oro.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-antlr",
    jars = ["ant-antlr.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-jdepend",
    jars = ["ant-jdepend.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-launcher",
    jars = ["ant-launcher.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-apache-regexp",
    jars = ["ant-apache-regexp.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-apache-log4j",
    jars = ["ant-apache-log4j.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-swing",
    jars = ["ant-swing.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-javamail",
    jars = ["ant-javamail.jar"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "all-libs",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-apache-xalan2",
    jars = ["ant-apache-xalan2.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-junit4",
    jars = ["ant-junit4.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-testutil",
    jars = ["ant-testutil.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-junitlauncher",
    jars = ["ant-junitlauncher.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ant-xz",
    jars = ["ant-xz.jar"],
    visibility = ["//visibility:public"],
)
