load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "xslt-rt",
    srcs = ["src"],
    iml_files = ["xslt-rt.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
