from collections.abc import Iterator, Mapping
from typing import Any, Literal, TypeAlias

from django.core.mail.backends.base import BaseEmailBackend

DEFAULT_MAILER_ALIAS: Literal["default"]
DEFAULT_MAILER_BACKEND: Literal["django.core.mail.backends.smtp.EmailBackend"]

_MailerSetting: TypeAlias = Mapping[str, Any]

class MailersHandler:
    def __getitem__(self, /, alias: str) -> BaseEmailBackend: ...
    def __contains__(self, /, alias: str) -> bool: ...
    def __iter__(self) -> Iterator[_MailerSetting]: ...
    def get(self, alias: str, /, default: Any | None = None) -> BaseEmailBackend: ...
    @property
    def default(self) -> BaseEmailBackend: ...
    @property
    def settings(self) -> _MailerSetting: ...
    def create_connection(
        self, alias: str, /, *, _deprecated_kwargs: Mapping[str, Any] | None = None
    ) -> BaseEmailBackend: ...
