java_import(
    name = "junit-jupiter-engine-5.0.0-M4",
    jars = ["junit-jupiter-engine-5.0.0-M4.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "junit-platform-commons-1.0.0-M4",
    jars = ["junit-platform-commons-1.0.0-M4.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "junit-platform-engine-1.0.0-M4",
    jars = ["junit-platform-engine-1.0.0-M4.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "junit-platform-launcher-1.0.0-M4",
    jars = ["junit-platform-launcher-1.0.0-M4.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "junit-platform-runner-1.0.0-M4",
    jars = ["junit-platform-runner-1.0.0-M4.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "junit-vintage-engine-4.12.0-M4",
    jars = ["junit-vintage-engine-4.12.0-M4.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "junit-platform-suite-api-1.0.0-M4",
    jars = ["junit-platform-suite-api-1.0.0-M4.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "opentest4j-1.0.0-M2",
    jars = ["opentest4j-1.0.0-M2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "junit-jupiter-api-5.0.0-M4",
    jars = ["junit-jupiter-api-5.0.0-M4.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
