load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.annotations.common",
    srcs = ["src"],
    iml_files = ["intellij.platform.annotations.common.iml"],
    visibility = ["//visibility:public"],
)
