load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "intellij.platform.annotations.common",
    srcs = ["src"],
    iml_files = ["intellij.platform.annotations.common.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
