load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "annotations-common",
    srcs = ["src"],
    iml_files = ["annotations-common.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
