version = "4.12.*"
upstream_repository = "https://git.launchpad.net/beautifulsoup/tree"
requires = ["types-html5lib"]
partial_stub = true

[tool.stubtest]
ignore_missing_stub = true
extras = ["html5lib", "lxml"]
