from .default import DefaultPartitioner

class StickyPartitioner(DefaultPartitioner):
    def __init__(self) -> None: ...
    def partition(self, topic, key, serialized_key, value, serialized_value, cluster): ...
    def on_new_batch(self, topic, cluster, prev_partition) -> None: ...
