class Percentile:
    __slots__ = ("_metric_name", "_percentile")
    def __init__(self, metric_name, percentile) -> None: ...
    @property
    def name(self): ...
    @property
    def percentile(self): ...
