from typing import Final

import _win32typing
from ntsecuritycon import FILE_READ_DATA as FILE_READ_DATA, FILE_WRITE_DATA as FILE_WRITE_DATA

def CTL_CODE(DeviceType: int, Function: int, Method: int, Access: int) -> int: ...
def DEVICE_TYPE_FROM_CTL_CODE(ctrlCode: int) -> int: ...

FILE_DEVICE_BEEP: Final = 0x00000001
FILE_DEVICE_CD_ROM: Final = 0x00000002
FILE_DEVICE_CD_ROM_FILE_SYSTEM: Final = 0x00000003
FILE_DEVICE_CONTROLLER: Final = 0x00000004
FILE_DEVICE_DATALINK: Final = 0x00000005
FILE_DEVICE_DFS: Final = 0x00000006
FILE_DEVICE_DISK: Final = 0x00000007
FILE_DEVICE_DISK_FILE_SYSTEM: Final = 0x00000008
FILE_DEVICE_FILE_SYSTEM: Final = 0x00000009
FILE_DEVICE_INPORT_PORT: Final = 0x0000000A
FILE_DEVICE_KEYBOARD: Final = 0x0000000B
FILE_DEVICE_MAILSLOT: Final = 0x0000000C
FILE_DEVICE_MIDI_IN: Final = 0x0000000D
FILE_DEVICE_MIDI_OUT: Final = 0x0000000E
FILE_DEVICE_MOUSE: Final = 0x0000000F
FILE_DEVICE_MULTI_UNC_PROVIDER: Final = 0x00000010
FILE_DEVICE_NAMED_PIPE: Final = 0x00000011
FILE_DEVICE_NETWORK: Final = 0x00000012
FILE_DEVICE_NETWORK_BROWSER: Final = 0x00000013
FILE_DEVICE_NETWORK_FILE_SYSTEM: Final = 0x00000014
FILE_DEVICE_NULL: Final = 0x00000015
FILE_DEVICE_PARALLEL_PORT: Final = 0x00000016
FILE_DEVICE_PHYSICAL_NETCARD: Final = 0x00000017
FILE_DEVICE_PRINTER: Final = 0x00000018
FILE_DEVICE_SCANNER: Final = 0x00000019
FILE_DEVICE_SERIAL_MOUSE_PORT: Final = 0x0000001A
FILE_DEVICE_SERIAL_PORT: Final = 0x0000001B
FILE_DEVICE_SCREEN: Final = 0x0000001C
FILE_DEVICE_SOUND: Final = 0x0000001D
FILE_DEVICE_STREAMS: Final = 0x0000001E
FILE_DEVICE_TAPE: Final = 0x0000001F
FILE_DEVICE_TAPE_FILE_SYSTEM: Final = 0x00000020
FILE_DEVICE_TRANSPORT: Final = 0x00000021
FILE_DEVICE_UNKNOWN: Final = 0x00000022
FILE_DEVICE_VIDEO: Final = 0x00000023
FILE_DEVICE_VIRTUAL_DISK: Final = 0x00000024
FILE_DEVICE_WAVE_IN: Final = 0x00000025
FILE_DEVICE_WAVE_OUT: Final = 0x00000026
FILE_DEVICE_8042_PORT: Final = 0x00000027
FILE_DEVICE_NETWORK_REDIRECTOR: Final = 0x00000028
FILE_DEVICE_BATTERY: Final = 0x00000029
FILE_DEVICE_BUS_EXTENDER: Final = 0x0000002A
FILE_DEVICE_MODEM: Final = 0x0000002B
FILE_DEVICE_VDM: Final = 0x0000002C
FILE_DEVICE_MASS_STORAGE: Final = 0x0000002D
FILE_DEVICE_SMB: Final = 0x0000002E
FILE_DEVICE_KS: Final = 0x0000002F
FILE_DEVICE_CHANGER: Final = 0x00000030
FILE_DEVICE_SMARTCARD: Final = 0x00000031
FILE_DEVICE_ACPI: Final = 0x00000032
FILE_DEVICE_DVD: Final = 0x00000033
FILE_DEVICE_FULLSCREEN_VIDEO: Final = 0x00000034
FILE_DEVICE_DFS_FILE_SYSTEM: Final = 0x00000035
FILE_DEVICE_DFS_VOLUME: Final = 0x00000036
FILE_DEVICE_SERENUM: Final = 0x00000037
FILE_DEVICE_TERMSRV: Final = 0x00000038
FILE_DEVICE_KSEC: Final = 0x00000039
FILE_DEVICE_FIPS: Final = 0x0000003A
FILE_DEVICE_INFINIBAND: Final = 0x0000003B
METHOD_BUFFERED: Final = 0
METHOD_IN_DIRECT: Final = 1
METHOD_OUT_DIRECT: Final = 2
METHOD_NEITHER: Final = 3
METHOD_DIRECT_TO_HARDWARE: Final = METHOD_IN_DIRECT
METHOD_DIRECT_FROM_HARDWARE: Final = METHOD_OUT_DIRECT
FILE_ANY_ACCESS: Final = 0
FILE_SPECIAL_ACCESS: Final = FILE_ANY_ACCESS
FILE_READ_ACCESS: Final = 0x0001
FILE_WRITE_ACCESS: Final = 0x0002
IOCTL_STORAGE_BASE: Final = FILE_DEVICE_MASS_STORAGE
RECOVERED_WRITES_VALID: Final = 0x00000001
UNRECOVERED_WRITES_VALID: Final = 0x00000002
RECOVERED_READS_VALID: Final = 0x00000004
UNRECOVERED_READS_VALID: Final = 0x00000008
WRITE_COMPRESSION_INFO_VALID: Final = 0x00000010
READ_COMPRESSION_INFO_VALID: Final = 0x00000020
TAPE_RETURN_STATISTICS: Final = 0
TAPE_RETURN_ENV_INFO: Final = 1
TAPE_RESET_STATISTICS: Final = 2
MEDIA_ERASEABLE: Final = 0x00000001
MEDIA_WRITE_ONCE: Final = 0x00000002
MEDIA_READ_ONLY: Final = 0x00000004
MEDIA_READ_WRITE: Final = 0x00000008
MEDIA_WRITE_PROTECTED: Final = 0x00000100
MEDIA_CURRENTLY_MOUNTED: Final = 0x80000000
IOCTL_DISK_BASE: Final = FILE_DEVICE_DISK
PARTITION_ENTRY_UNUSED: Final = 0x00
PARTITION_FAT_12: Final = 0x01
PARTITION_XENIX_1: Final = 0x02
PARTITION_XENIX_2: Final = 0x03
PARTITION_FAT_16: Final = 0x04
PARTITION_EXTENDED: Final = 0x05
PARTITION_HUGE: Final = 0x06
PARTITION_IFS: Final = 0x07
PARTITION_OS2BOOTMGR: Final = 0x0A
PARTITION_FAT32: Final = 0x0B
PARTITION_FAT32_XINT13: Final = 0x0C
PARTITION_XINT13: Final = 0x0E
PARTITION_XINT13_EXTENDED: Final = 0x0F
PARTITION_PREP: Final = 0x41
PARTITION_LDM: Final = 0x42
PARTITION_UNIX: Final = 0x63
VALID_NTFT: Final = 0xC0
PARTITION_NTFT: Final = 0x80
GPT_ATTRIBUTE_PLATFORM_REQUIRED: Final = 0x00000001
GPT_BASIC_DATA_ATTRIBUTE_NO_DRIVE_LETTER: Final[int]
GPT_BASIC_DATA_ATTRIBUTE_HIDDEN: Final[int]
GPT_BASIC_DATA_ATTRIBUTE_SHADOW_COPY: Final[int]
GPT_BASIC_DATA_ATTRIBUTE_READ_ONLY: Final[int]
HIST_NO_OF_BUCKETS: Final = 24
DISK_LOGGING_START: Final = 0
DISK_LOGGING_STOP: Final = 1
DISK_LOGGING_DUMP: Final = 2
DISK_BINNING: Final = 3
CAP_ATA_ID_CMD: Final = 1
CAP_ATAPI_ID_CMD: Final = 2
CAP_SMART_CMD: Final = 4
ATAPI_ID_CMD: Final = 0xA1
ID_CMD: Final = 0xEC
SMART_CMD: Final = 0xB0
SMART_CYL_LOW: Final = 0x4F
SMART_CYL_HI: Final = 0xC2
SMART_NO_ERROR: Final = 0
SMART_IDE_ERROR: Final = 1
SMART_INVALID_FLAG: Final = 2
SMART_INVALID_COMMAND: Final = 3
SMART_INVALID_BUFFER: Final = 4
SMART_INVALID_DRIVE: Final = 5
SMART_INVALID_IOCTL: Final = 6
SMART_ERROR_NO_MEM: Final = 7
SMART_INVALID_REGISTER: Final = 8
SMART_NOT_SUPPORTED: Final = 9
SMART_NO_IDE_DEVICE: Final = 10
SMART_OFFLINE_ROUTINE_OFFLINE: Final = 0
SMART_SHORT_SELFTEST_OFFLINE: Final = 1
SMART_EXTENDED_SELFTEST_OFFLINE: Final = 2
SMART_ABORT_OFFLINE_SELFTEST: Final = 127
SMART_SHORT_SELFTEST_CAPTIVE: Final = 129
SMART_EXTENDED_SELFTEST_CAPTIVE: Final = 130
READ_ATTRIBUTE_BUFFER_SIZE: Final = 512
IDENTIFY_BUFFER_SIZE: Final = 512
READ_THRESHOLD_BUFFER_SIZE: Final = 512
SMART_LOG_SECTOR_SIZE: Final = 512
READ_ATTRIBUTES: Final = 0xD0
READ_THRESHOLDS: Final = 0xD1
ENABLE_DISABLE_AUTOSAVE: Final = 0xD2
SAVE_ATTRIBUTE_VALUES: Final = 0xD3
EXECUTE_OFFLINE_DIAGS: Final = 0xD4
SMART_READ_LOG: Final = 0xD5
SMART_WRITE_LOG: Final = 0xD6
ENABLE_SMART: Final = 0xD8
DISABLE_SMART: Final = 0xD9
RETURN_SMART_STATUS: Final = 0xDA
ENABLE_DISABLE_AUTO_OFFLINE: Final = 0xDB
IOCTL_CHANGER_BASE: Final = FILE_DEVICE_CHANGER
MAX_VOLUME_ID_SIZE: Final = 36
MAX_VOLUME_TEMPLATE_SIZE: Final = 40
VENDOR_ID_LENGTH: Final = 8
PRODUCT_ID_LENGTH: Final = 16
REVISION_LENGTH: Final = 4
SERIAL_NUMBER_LENGTH: Final = 32
CHANGER_BAR_CODE_SCANNER_INSTALLED: Final = 0x00000001
CHANGER_INIT_ELEM_STAT_WITH_RANGE: Final = 0x00000002
CHANGER_CLOSE_IEPORT: Final = 0x00000004
CHANGER_OPEN_IEPORT: Final = 0x00000008
CHANGER_STATUS_NON_VOLATILE: Final = 0x00000010
CHANGER_EXCHANGE_MEDIA: Final = 0x00000020
CHANGER_CLEANER_SLOT: Final = 0x00000040
CHANGER_LOCK_UNLOCK: Final = 0x00000080
CHANGER_CARTRIDGE_MAGAZINE: Final = 0x00000100
CHANGER_MEDIUM_FLIP: Final = 0x00000200
CHANGER_POSITION_TO_ELEMENT: Final = 0x00000400
CHANGER_REPORT_IEPORT_STATE: Final = 0x00000800
CHANGER_STORAGE_DRIVE: Final = 0x00001000
CHANGER_STORAGE_IEPORT: Final = 0x00002000
CHANGER_STORAGE_SLOT: Final = 0x00004000
CHANGER_STORAGE_TRANSPORT: Final = 0x00008000
CHANGER_DRIVE_CLEANING_REQUIRED: Final = 0x00010000
CHANGER_PREDISMOUNT_EJECT_REQUIRED: Final = 0x00020000
CHANGER_CLEANER_ACCESS_NOT_VALID: Final = 0x00040000
CHANGER_PREMOUNT_EJECT_REQUIRED: Final = 0x00080000
CHANGER_VOLUME_IDENTIFICATION: Final = 0x00100000
CHANGER_VOLUME_SEARCH: Final = 0x00200000
CHANGER_VOLUME_ASSERT: Final = 0x00400000
CHANGER_VOLUME_REPLACE: Final = 0x00800000
CHANGER_VOLUME_UNDEFINE: Final = 0x01000000
CHANGER_SERIAL_NUMBER_VALID: Final = 0x04000000
CHANGER_DEVICE_REINITIALIZE_CAPABLE: Final = 0x08000000
CHANGER_KEYPAD_ENABLE_DISABLE: Final = 0x10000000
CHANGER_DRIVE_EMPTY_ON_DOOR_ACCESS: Final = 0x20000000
CHANGER_RESERVED_BIT: Final = 0x80000000
CHANGER_PREDISMOUNT_ALIGN_TO_SLOT: Final = 0x80000001
CHANGER_PREDISMOUNT_ALIGN_TO_DRIVE: Final = 0x80000002
CHANGER_CLEANER_AUTODISMOUNT: Final = 0x80000004
CHANGER_TRUE_EXCHANGE_CAPABLE: Final = 0x80000008
CHANGER_SLOTS_USE_TRAYS: Final = 0x80000010
CHANGER_RTN_MEDIA_TO_ORIGINAL_ADDR: Final = 0x80000020
CHANGER_CLEANER_OPS_NOT_SUPPORTED: Final = 0x80000040
CHANGER_IEPORT_USER_CONTROL_OPEN: Final = 0x80000080
CHANGER_IEPORT_USER_CONTROL_CLOSE: Final = 0x80000100
CHANGER_MOVE_EXTENDS_IEPORT: Final = 0x80000200
CHANGER_MOVE_RETRACTS_IEPORT: Final = 0x80000400
CHANGER_TO_TRANSPORT: Final = 0x01
CHANGER_TO_SLOT: Final = 0x02
CHANGER_TO_IEPORT: Final = 0x04
CHANGER_TO_DRIVE: Final = 0x08
LOCK_UNLOCK_IEPORT: Final = 0x01
LOCK_UNLOCK_DOOR: Final = 0x02
LOCK_UNLOCK_KEYPAD: Final = 0x04
LOCK_ELEMENT: Final = 0
UNLOCK_ELEMENT: Final = 1
EXTEND_IEPORT: Final = 2
RETRACT_IEPORT: Final = 3
ELEMENT_STATUS_FULL: Final = 0x00000001
ELEMENT_STATUS_IMPEXP: Final = 0x00000002
ELEMENT_STATUS_EXCEPT: Final = 0x00000004
ELEMENT_STATUS_ACCESS: Final = 0x00000008
ELEMENT_STATUS_EXENAB: Final = 0x00000010
ELEMENT_STATUS_INENAB: Final = 0x00000020
ELEMENT_STATUS_PRODUCT_DATA: Final = 0x00000040
ELEMENT_STATUS_LUN_VALID: Final = 0x00001000
ELEMENT_STATUS_ID_VALID: Final = 0x00002000
ELEMENT_STATUS_NOT_BUS: Final = 0x00008000
ELEMENT_STATUS_INVERT: Final = 0x00400000
ELEMENT_STATUS_SVALID: Final = 0x00800000
ELEMENT_STATUS_PVOLTAG: Final = 0x10000000
ELEMENT_STATUS_AVOLTAG: Final = 0x20000000
ERROR_LABEL_UNREADABLE: Final = 0x00000001
ERROR_LABEL_QUESTIONABLE: Final = 0x00000002
ERROR_SLOT_NOT_PRESENT: Final = 0x00000004
ERROR_DRIVE_NOT_INSTALLED: Final = 0x00000008
ERROR_TRAY_MALFUNCTION: Final = 0x00000010
ERROR_INIT_STATUS_NEEDED: Final = 0x00000011
ERROR_UNHANDLED_ERROR: Final = 0xFFFFFFFF
SEARCH_ALL: Final = 0x0
SEARCH_PRIMARY: Final = 0x1
SEARCH_ALTERNATE: Final = 0x2
SEARCH_ALL_NO_SEQ: Final = 0x4
SEARCH_PRI_NO_SEQ: Final = 0x5
SEARCH_ALT_NO_SEQ: Final = 0x6
ASSERT_PRIMARY: Final = 0x8
ASSERT_ALTERNATE: Final = 0x9
REPLACE_PRIMARY: Final = 0xA
REPLACE_ALTERNATE: Final = 0xB
UNDEFINE_PRIMARY: Final = 0xC
UNDEFINE_ALTERNATE: Final = 0xD
USN_PAGE_SIZE: Final = 0x1000
USN_REASON_DATA_OVERWRITE: Final = 0x00000001
USN_REASON_DATA_EXTEND: Final = 0x00000002
USN_REASON_DATA_TRUNCATION: Final = 0x00000004
USN_REASON_NAMED_DATA_OVERWRITE: Final = 0x00000010
USN_REASON_NAMED_DATA_EXTEND: Final = 0x00000020
USN_REASON_NAMED_DATA_TRUNCATION: Final = 0x00000040
USN_REASON_FILE_CREATE: Final = 0x00000100
USN_REASON_FILE_DELETE: Final = 0x00000200
USN_REASON_EA_CHANGE: Final = 0x00000400
USN_REASON_SECURITY_CHANGE: Final = 0x00000800
USN_REASON_RENAME_OLD_NAME: Final = 0x00001000
USN_REASON_RENAME_NEW_NAME: Final = 0x00002000
USN_REASON_INDEXABLE_CHANGE: Final = 0x00004000
USN_REASON_BASIC_INFO_CHANGE: Final = 0x00008000
USN_REASON_HARD_LINK_CHANGE: Final = 0x00010000
USN_REASON_COMPRESSION_CHANGE: Final = 0x00020000
USN_REASON_ENCRYPTION_CHANGE: Final = 0x00040000
USN_REASON_OBJECT_ID_CHANGE: Final = 0x00080000
USN_REASON_REPARSE_POINT_CHANGE: Final = 0x00100000
USN_REASON_STREAM_CHANGE: Final = 0x00200000
USN_REASON_TRANSACTED_CHANGE: Final = 0x00400000
USN_REASON_CLOSE: Final = 0x80000000
USN_DELETE_FLAG_DELETE: Final = 0x00000001
USN_DELETE_FLAG_NOTIFY: Final = 0x00000002
USN_DELETE_VALID_FLAGS: Final = 0x00000003
USN_SOURCE_DATA_MANAGEMENT: Final = 0x00000001
USN_SOURCE_AUXILIARY_DATA: Final = 0x00000002
USN_SOURCE_REPLICATION_MANAGEMENT: Final = 0x00000004
MARK_HANDLE_PROTECT_CLUSTERS: Final = 1
MARK_HANDLE_TXF_SYSTEM_LOG: Final = 4
MARK_HANDLE_NOT_TXF_SYSTEM_LOG: Final = 8
VOLUME_IS_DIRTY: Final = 0x00000001
VOLUME_UPGRADE_SCHEDULED: Final = 0x00000002
VOLUME_SESSION_OPEN: Final = 4
FILE_PREFETCH_TYPE_FOR_CREATE: Final = 1
FILE_PREFETCH_TYPE_FOR_DIRENUM: Final = 2
FILE_PREFETCH_TYPE_FOR_CREATE_EX: Final = 3
FILE_PREFETCH_TYPE_FOR_DIRENUM_EX: Final = 4
FILE_PREFETCH_TYPE_MAX: Final = 4
FILESYSTEM_STATISTICS_TYPE_NTFS: Final = 1
FILESYSTEM_STATISTICS_TYPE_FAT: Final = 2
FILE_SET_ENCRYPTION: Final = 0x00000001
FILE_CLEAR_ENCRYPTION: Final = 0x00000002
STREAM_SET_ENCRYPTION: Final = 0x00000003
STREAM_CLEAR_ENCRYPTION: Final = 0x00000004
MAXIMUM_ENCRYPTION_VALUE: Final = 0x00000004
ENCRYPTION_FORMAT_DEFAULT: Final = 0x01
COMPRESSION_FORMAT_SPARSE: Final = 0x4000
COPYFILE_SIS_LINK: Final = 0x0001
COPYFILE_SIS_REPLACE: Final = 0x0002
COPYFILE_SIS_FLAGS: Final = 0x0003
WMI_DISK_GEOMETRY_GUID: Final[_win32typing.PyIID]
GUID_DEVINTERFACE_CDROM: Final[_win32typing.PyIID]
GUID_DEVINTERFACE_FLOPPY: Final[_win32typing.PyIID]
GUID_DEVINTERFACE_SERENUM_BUS_ENUMERATOR: Final[_win32typing.PyIID]
GUID_DEVINTERFACE_COMPORT: Final[_win32typing.PyIID]
GUID_DEVINTERFACE_DISK: Final[_win32typing.PyIID]
GUID_DEVINTERFACE_STORAGEPORT: Final[_win32typing.PyIID]
GUID_DEVINTERFACE_CDCHANGER: Final[_win32typing.PyIID]
GUID_DEVINTERFACE_PARTITION: Final[_win32typing.PyIID]
GUID_DEVINTERFACE_VOLUME: Final[_win32typing.PyIID]
GUID_DEVINTERFACE_WRITEONCEDISK: Final[_win32typing.PyIID]
GUID_DEVINTERFACE_TAPE: Final[_win32typing.PyIID]
GUID_DEVINTERFACE_MEDIUMCHANGER: Final[_win32typing.PyIID]
GUID_SERENUM_BUS_ENUMERATOR: Final = GUID_DEVINTERFACE_SERENUM_BUS_ENUMERATOR
GUID_CLASS_COMPORT: Final = GUID_DEVINTERFACE_COMPORT
DiskClassGuid: Final = GUID_DEVINTERFACE_DISK
CdRomClassGuid: Final = GUID_DEVINTERFACE_CDROM
PartitionClassGuid: Final = GUID_DEVINTERFACE_PARTITION
TapeClassGuid: Final = GUID_DEVINTERFACE_TAPE
WriteOnceDiskClassGuid: Final = GUID_DEVINTERFACE_WRITEONCEDISK
VolumeClassGuid: Final = GUID_DEVINTERFACE_VOLUME
MediumChangerClassGuid: Final = GUID_DEVINTERFACE_MEDIUMCHANGER
FloppyClassGuid: Final = GUID_DEVINTERFACE_FLOPPY
CdChangerClassGuid: Final = GUID_DEVINTERFACE_CDCHANGER
StoragePortClassGuid: Final = GUID_DEVINTERFACE_STORAGEPORT
IOCTL_STORAGE_CHECK_VERIFY: Final = 2967552
IOCTL_STORAGE_CHECK_VERIFY2: Final[int]
IOCTL_STORAGE_MEDIA_REMOVAL: Final[int]
IOCTL_STORAGE_EJECT_MEDIA: Final[int]
IOCTL_STORAGE_LOAD_MEDIA: Final[int]
IOCTL_STORAGE_LOAD_MEDIA2: Final[int]
IOCTL_STORAGE_RESERVE: Final[int]
IOCTL_STORAGE_RELEASE: Final[int]
IOCTL_STORAGE_FIND_NEW_DEVICES: Final[int]
IOCTL_STORAGE_EJECTION_CONTROL: Final[int]
IOCTL_STORAGE_MCN_CONTROL: Final[int]
IOCTL_STORAGE_GET_MEDIA_TYPES: Final[int]
IOCTL_STORAGE_GET_MEDIA_TYPES_EX: Final[int]
IOCTL_STORAGE_GET_MEDIA_SERIAL_NUMBER: Final[int]
IOCTL_STORAGE_GET_HOTPLUG_INFO: Final[int]
IOCTL_STORAGE_SET_HOTPLUG_INFO: Final[int]
IOCTL_STORAGE_RESET_BUS: Final[int]
IOCTL_STORAGE_RESET_DEVICE: Final[int]
IOCTL_STORAGE_BREAK_RESERVATION: Final[int]
IOCTL_STORAGE_GET_DEVICE_NUMBER: Final[int]
IOCTL_STORAGE_PREDICT_FAILURE: Final[int]
IOCTL_DISK_GET_DRIVE_GEOMETRY: Final[int]
IOCTL_DISK_GET_PARTITION_INFO: Final[int]
IOCTL_DISK_SET_PARTITION_INFO: Final[int]
IOCTL_DISK_GET_DRIVE_LAYOUT: Final[int]
IOCTL_DISK_SET_DRIVE_LAYOUT: Final[int]
IOCTL_DISK_VERIFY: Final[int]
IOCTL_DISK_FORMAT_TRACKS: Final[int]
IOCTL_DISK_REASSIGN_BLOCKS: Final[int]
IOCTL_DISK_PERFORMANCE: Final[int]
IOCTL_DISK_IS_WRITABLE: Final[int]
IOCTL_DISK_LOGGING: Final[int]
IOCTL_DISK_FORMAT_TRACKS_EX: Final[int]
IOCTL_DISK_HISTOGRAM_STRUCTURE: Final[int]
IOCTL_DISK_HISTOGRAM_DATA: Final[int]
IOCTL_DISK_HISTOGRAM_RESET: Final[int]
IOCTL_DISK_REQUEST_STRUCTURE: Final[int]
IOCTL_DISK_REQUEST_DATA: Final[int]
IOCTL_DISK_PERFORMANCE_OFF: Final[int]
IOCTL_DISK_CONTROLLER_NUMBER: Final[int]
SMART_GET_VERSION: Final[int]
SMART_SEND_DRIVE_COMMAND: Final[int]
SMART_RCV_DRIVE_DATA: Final[int]
IOCTL_DISK_GET_PARTITION_INFO_EX: Final[int]
IOCTL_DISK_SET_PARTITION_INFO_EX: Final[int]
IOCTL_DISK_GET_DRIVE_LAYOUT_EX: Final[int]
IOCTL_DISK_SET_DRIVE_LAYOUT_EX: Final[int]
IOCTL_DISK_CREATE_DISK: Final[int]
IOCTL_DISK_GET_LENGTH_INFO: Final[int]
IOCTL_DISK_GET_DRIVE_GEOMETRY_EX: Final[int]
IOCTL_DISK_REASSIGN_BLOCKS_EX: Final[int]
IOCTL_DISK_UPDATE_DRIVE_SIZE: Final[int]
IOCTL_DISK_GROW_PARTITION: Final[int]
IOCTL_DISK_GET_CACHE_INFORMATION: Final[int]
IOCTL_DISK_SET_CACHE_INFORMATION: Final[int]
OBSOLETE_IOCTL_STORAGE_RESET_BUS: Final[int]
OBSOLETE_IOCTL_STORAGE_RESET_DEVICE: Final[int]
OBSOLETE_DISK_GET_WRITE_CACHE_STATE: Final[int]
IOCTL_DISK_GET_WRITE_CACHE_STATE: Final = OBSOLETE_DISK_GET_WRITE_CACHE_STATE
IOCTL_DISK_DELETE_DRIVE_LAYOUT: Final[int]
IOCTL_DISK_UPDATE_PROPERTIES: Final[int]
IOCTL_DISK_FORMAT_DRIVE: Final[int]
IOCTL_DISK_SENSE_DEVICE: Final[int]
IOCTL_DISK_CHECK_VERIFY: Final[int]
IOCTL_DISK_MEDIA_REMOVAL: Final[int]
IOCTL_DISK_EJECT_MEDIA: Final[int]
IOCTL_DISK_LOAD_MEDIA: Final[int]
IOCTL_DISK_RESERVE: Final[int]
IOCTL_DISK_RELEASE: Final[int]
IOCTL_DISK_FIND_NEW_DEVICES: Final[int]
IOCTL_DISK_GET_MEDIA_TYPES: Final[int]
DISK_HISTOGRAM_SIZE: Final = 72
HISTOGRAM_BUCKET_SIZE: Final = 8
IOCTL_CHANGER_GET_PARAMETERS: Final[int]
IOCTL_CHANGER_GET_STATUS: Final[int]
IOCTL_CHANGER_GET_PRODUCT_DATA: Final[int]
IOCTL_CHANGER_SET_ACCESS: Final[int]
IOCTL_CHANGER_GET_ELEMENT_STATUS: Final[int]
IOCTL_CHANGER_INITIALIZE_ELEMENT_STATUS: Final[int]
IOCTL_CHANGER_SET_POSITION: Final[int]
IOCTL_CHANGER_EXCHANGE_MEDIUM: Final[int]
IOCTL_CHANGER_MOVE_MEDIUM: Final[int]
IOCTL_CHANGER_REINITIALIZE_TRANSPORT: Final[int]
IOCTL_CHANGER_QUERY_VOLUME_TAGS: Final[int]
IOCTL_SERIAL_LSRMST_INSERT: Final[int]
IOCTL_SERENUM_EXPOSE_HARDWARE: Final[int]
IOCTL_SERENUM_REMOVE_HARDWARE: Final[int]
IOCTL_SERENUM_PORT_DESC: Final[int]
IOCTL_SERENUM_GET_PORT_NAME: Final[int]
SERIAL_LSRMST_ESCAPE: Final = 0x00
SERIAL_LSRMST_LSR_DATA: Final = 0x01
SERIAL_LSRMST_LSR_NODATA: Final = 0x02
SERIAL_LSRMST_MST: Final = 0x03
SERIAL_IOC_FCR_FIFO_ENABLE: Final = 0x00000001
SERIAL_IOC_FCR_RCVR_RESET: Final = 0x00000002
SERIAL_IOC_FCR_XMIT_RESET: Final = 0x00000004
SERIAL_IOC_FCR_DMA_MODE: Final = 0x00000008
SERIAL_IOC_FCR_RES1: Final = 0x00000010
SERIAL_IOC_FCR_RES2: Final = 0x00000020
SERIAL_IOC_FCR_RCVR_TRIGGER_LSB: Final = 0x00000040
SERIAL_IOC_FCR_RCVR_TRIGGER_MSB: Final = 0x00000080
SERIAL_IOC_MCR_DTR: Final = 0x00000001
SERIAL_IOC_MCR_RTS: Final = 0x00000002
SERIAL_IOC_MCR_OUT1: Final = 0x00000004
SERIAL_IOC_MCR_OUT2: Final = 0x00000008
SERIAL_IOC_MCR_LOOP: Final = 0x00000010
FSCTL_REQUEST_OPLOCK_LEVEL_1: Final[int]
FSCTL_REQUEST_OPLOCK_LEVEL_2: Final[int]
FSCTL_REQUEST_BATCH_OPLOCK: Final[int]
FSCTL_OPLOCK_BREAK_ACKNOWLEDGE: Final[int]
FSCTL_OPBATCH_ACK_CLOSE_PENDING: Final[int]
FSCTL_OPLOCK_BREAK_NOTIFY: Final[int]
FSCTL_LOCK_VOLUME: Final[int]
FSCTL_UNLOCK_VOLUME: Final[int]
FSCTL_DISMOUNT_VOLUME: Final[int]
FSCTL_IS_VOLUME_MOUNTED: Final[int]
FSCTL_IS_PATHNAME_VALID: Final[int]
FSCTL_MARK_VOLUME_DIRTY: Final[int]
FSCTL_QUERY_RETRIEVAL_POINTERS: Final[int]
FSCTL_GET_COMPRESSION: Final[int]
FSCTL_SET_COMPRESSION: Final[int]
FSCTL_MARK_AS_SYSTEM_HIVE: Final[int]
FSCTL_OPLOCK_BREAK_ACK_NO_2: Final[int]
FSCTL_INVALIDATE_VOLUMES: Final[int]
FSCTL_QUERY_FAT_BPB: Final[int]
FSCTL_REQUEST_FILTER_OPLOCK: Final[int]
FSCTL_FILESYSTEM_GET_STATISTICS: Final[int]
FSCTL_GET_NTFS_VOLUME_DATA: Final[int]
FSCTL_GET_NTFS_FILE_RECORD: Final[int]
FSCTL_GET_VOLUME_BITMAP: Final[int]
FSCTL_GET_RETRIEVAL_POINTERS: Final[int]
FSCTL_MOVE_FILE: Final[int]
FSCTL_IS_VOLUME_DIRTY: Final[int]
FSCTL_ALLOW_EXTENDED_DASD_IO: Final[int]
FSCTL_FIND_FILES_BY_SID: Final[int]
FSCTL_SET_OBJECT_ID: Final[int]
FSCTL_GET_OBJECT_ID: Final[int]
FSCTL_DELETE_OBJECT_ID: Final[int]
FSCTL_SET_REPARSE_POINT: Final[int]
FSCTL_GET_REPARSE_POINT: Final[int]
FSCTL_DELETE_REPARSE_POINT: Final[int]
FSCTL_ENUM_USN_DATA: Final[int]
FSCTL_SECURITY_ID_CHECK: Final[int]
FSCTL_READ_USN_JOURNAL: Final[int]
FSCTL_SET_OBJECT_ID_EXTENDED: Final[int]
FSCTL_CREATE_OR_GET_OBJECT_ID: Final[int]
FSCTL_SET_SPARSE: Final[int]
FSCTL_SET_ZERO_DATA: Final[int]
FSCTL_QUERY_ALLOCATED_RANGES: Final[int]
FSCTL_SET_ENCRYPTION: Final[int]
FSCTL_ENCRYPTION_FSCTL_IO: Final[int]
FSCTL_WRITE_RAW_ENCRYPTED: Final[int]
FSCTL_READ_RAW_ENCRYPTED: Final[int]
FSCTL_CREATE_USN_JOURNAL: Final[int]
FSCTL_READ_FILE_USN_DATA: Final[int]
FSCTL_WRITE_USN_CLOSE_RECORD: Final[int]
FSCTL_EXTEND_VOLUME: Final[int]
FSCTL_QUERY_USN_JOURNAL: Final[int]
FSCTL_DELETE_USN_JOURNAL: Final[int]
FSCTL_MARK_HANDLE: Final[int]
FSCTL_SIS_COPYFILE: Final[int]
FSCTL_SIS_LINK_FILES: Final[int]
FSCTL_HSM_MSG: Final[int]
FSCTL_HSM_DATA: Final[int]
FSCTL_RECALL_FILE: Final[int]
FSCTL_READ_FROM_PLEX: Final[int]
FSCTL_FILE_PREFETCH: Final[int]
FSCTL_MAKE_MEDIA_COMPATIBLE: Final[int]
FSCTL_SET_DEFECT_MANAGEMENT: Final[int]
FSCTL_QUERY_SPARING_INFO: Final[int]
FSCTL_QUERY_ON_DISK_VOLUME_INFO: Final[int]
FSCTL_SET_VOLUME_COMPRESSION_STATE: Final[int]
FSCTL_TXFS_MODIFY_RM: Final[int]
FSCTL_TXFS_QUERY_RM_INFORMATION: Final[int]
FSCTL_TXFS_ROLLFORWARD_REDO: Final[int]
FSCTL_TXFS_ROLLFORWARD_UNDO: Final[int]
FSCTL_TXFS_START_RM: Final[int]
FSCTL_TXFS_SHUTDOWN_RM: Final[int]
FSCTL_TXFS_READ_BACKUP_INFORMATION: Final[int]
FSCTL_TXFS_WRITE_BACKUP_INFORMATION: Final[int]
FSCTL_TXFS_CREATE_SECONDARY_RM: Final[int]
FSCTL_TXFS_GET_METADATA_INFO: Final[int]
FSCTL_TXFS_GET_TRANSACTED_VERSION: Final[int]
FSCTL_TXFS_CREATE_MINIVERSION: Final[int]
FSCTL_TXFS_TRANSACTION_ACTIVE: Final[int]
FSCTL_SET_ZERO_ON_DEALLOCATION: Final[int]
FSCTL_SET_REPAIR: Final[int]
FSCTL_GET_REPAIR: Final[int]
FSCTL_WAIT_FOR_REPAIR: Final[int]
FSCTL_INITIATE_REPAIR: Final[int]
FSCTL_CSC_INTERNAL: Final[int]
FSCTL_SHRINK_VOLUME: Final[int]
FSCTL_SET_SHORT_NAME_BEHAVIOR: Final[int]
FSCTL_DFSR_SET_GHOST_HANDLE_STATE: Final[int]
FSCTL_TXFS_LIST_TRANSACTION_LOCKED_FILES: Final[int]
FSCTL_TXFS_LIST_TRANSACTIONS: Final[int]
FSCTL_QUERY_PAGEFILE_ENCRYPTION: Final[int]
IOCTL_VOLUME_BASE: Final = 86
IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS: Final[int]
IOCTL_VOLUME_ONLINE: Final[int]
IOCTL_VOLUME_OFFLINE: Final[int]
IOCTL_VOLUME_IS_CLUSTERED: Final[int]
IOCTL_VOLUME_GET_GPT_ATTRIBUTES: Final[int]
DDS_4mm: Final = 32
MiniQic: Final = 33
Travan: Final = 34
QIC: Final = 35
MP_8mm: Final = 36
AME_8mm: Final = 37
AIT1_8mm: Final = 38
DLT: Final = 39
NCTP: Final = 40
IBM_3480: Final = 41
IBM_3490E: Final = 42
IBM_Magstar_3590: Final = 43
IBM_Magstar_MP: Final = 44
STK_DATA_D3: Final = 45
SONY_DTF: Final = 46
DV_6mm: Final = 47
DMI: Final = 48
SONY_D2: Final = 49
CLEANER_CARTRIDGE: Final = 50
CD_ROM: Final = 51
CD_R: Final = 52
CD_RW: Final = 53
DVD_ROM: Final = 54
DVD_R: Final = 55
DVD_RW: Final = 56
MO_3_RW: Final = 57
MO_5_WO: Final = 58
MO_5_RW: Final = 59
MO_5_LIMDOW: Final = 60
PC_5_WO: Final = 61
PC_5_RW: Final = 62
PD_5_RW: Final = 63
ABL_5_WO: Final = 64
PINNACLE_APEX_5_RW: Final = 65
SONY_12_WO: Final = 66
PHILIPS_12_WO: Final = 67
HITACHI_12_WO: Final = 68
CYGNET_12_WO: Final = 69
KODAK_14_WO: Final = 70
MO_NFR_525: Final = 71
NIKON_12_RW: Final = 72
IOMEGA_ZIP: Final = 73
IOMEGA_JAZ: Final = 74
SYQUEST_EZ135: Final = 75
SYQUEST_EZFLYER: Final = 76
SYQUEST_SYJET: Final = 77
AVATAR_F2: Final = 78
MP2_8mm: Final = 79
DST_S: Final = 80
DST_M: Final = 81
DST_L: Final = 82
VXATape_1: Final = 83
VXATape_2: Final = 84
STK_9840: Final = 85
LTO_Ultrium: Final = 86
LTO_Accelis: Final = 87
DVD_RAM: Final = 88
AIT_8mm: Final = 89
ADR_1: Final = 90
ADR_2: Final = 91
STK_9940: Final = 92
BusTypeUnknown: Final = 0
BusTypeScsi: Final = 1
BusTypeAtapi: Final = 2
BusTypeAta: Final = 3
BusType1394: Final = 4
BusTypeSsa: Final = 5
BusTypeFibre: Final = 6
BusTypeUsb: Final = 7
BusTypeRAID: Final = 8
BusTypeiScsi: Final = 9
BusTypeSas: Final = 10
BusTypeSata: Final = 11
BusTypeMaxReserved: Final = 127
Unknown: Final = 0
F5_1Pt2_512: Final = 1
F3_1Pt44_512: Final = 2
F3_2Pt88_512: Final = 3
F3_20Pt8_512: Final = 4
F3_720_512: Final = 5
F5_360_512: Final = 6
F5_320_512: Final = 7
F5_320_1024: Final = 8
F5_180_512: Final = 9
F5_160_512: Final = 10
RemovableMedia: Final = 11
FixedMedia: Final = 12
F3_120M_512: Final = 13
F3_640_512: Final = 14
F5_640_512: Final = 15
F5_720_512: Final = 16
F3_1Pt2_512: Final = 17
F3_1Pt23_1024: Final = 18
F5_1Pt23_1024: Final = 19
F3_128Mb_512: Final = 20
F3_230Mb_512: Final = 21
F8_256_128: Final = 22
F3_200Mb_512: Final = 23
F3_240M_512: Final = 24
F3_32M_512: Final = 25
PARTITION_STYLE_MBR: Final = 0
PARTITION_STYLE_GPT: Final = 1
PARTITION_STYLE_RAW: Final = 2
DetectNone: Final = 0
DetectInt13: Final = 1
DetectExInt13: Final = 2
EqualPriority: Final = 0
KeepPrefetchedData: Final = 1
KeepReadData: Final = 2
DiskWriteCacheNormal: Final = 0
DiskWriteCacheForceDisable: Final = 1
DiskWriteCacheDisableNotSupported: Final = 2
RequestSize: Final = 0
RequestLocation: Final = 1
DeviceProblemNone: Final = 0
DeviceProblemHardware: Final = 1
DeviceProblemCHMError: Final = 2
DeviceProblemDoorOpen: Final = 3
DeviceProblemCalibrationError: Final = 4
DeviceProblemTargetFailure: Final = 5
DeviceProblemCHMMoveError: Final = 6
DeviceProblemCHMZeroError: Final = 7
DeviceProblemCartridgeInsertError: Final = 8
DeviceProblemPositionError: Final = 9
DeviceProblemSensorError: Final = 10
DeviceProblemCartridgeEjectError: Final = 11
DeviceProblemGripperError: Final = 12
DeviceProblemDriveError: Final = 13
