FROM registry.jetbrains.team/p/ij/docker-hub/python:3.8-alpine@sha256:3d93b1f77efce339aa77db726656872517b0d67837989aa7c4b35bd5ae7e81ba
RUN pip install ntia-conformance-checker==3.0.0
ENTRYPOINT ["ntia-checker"]