// Copyright 2000-2026 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package com.intellij.common.file.icons

import com.intellij.icons.AllIcons
import java.util.Locale
import javax.swing.Icon

internal object CommonFileIconsByExtension {
  private val iconsByExtension: Map<String, Icon> = mapOf(
    "gitignore" to AllIcons.FileTypes.Gitignore,
    "java" to AllIcons.FileTypes.Java,
    "xml" to AllIcons.FileTypes.Xml,
    "md" to AllIcons.FileTypes.Markdown,
    "properties" to AllIcons.FileTypes.Properties,
    "json" to AllIcons.FileTypes.Json,
    "yml" to AllIcons.FileTypes.Yaml,
    "txt" to AllIcons.FileTypes.Text,
    "html" to AllIcons.FileTypes.Html,
    "iml" to AllIcons.Nodes.IdeaModule,
    "sh" to AllIcons.Nodes.Console,
    "sql" to AllIcons.FileTypes.Sql,
    "js" to AllIcons.FileTypes.JavaScript,
    "yaml" to AllIcons.FileTypes.Yaml,
    "css" to AllIcons.FileTypes.Css,
    "bat" to AllIcons.FileTypes.MicrosoftWindows,
    "svg" to AllIcons.FileTypes.Image,
    "csv" to AllIcons.FileTypes.Csv,
    "cmd" to AllIcons.FileTypes.MicrosoftWindows,
    "py" to AllIcons.Language.Python,
    "ts" to AllIcons.FileTypes.JavaScript,
    "editorconfig" to AllIcons.Nodes.Editorconfig,
    "gradle" to AllIcons.FileTypes.Gradle,
    "scss" to AllIcons.FileTypes.Css,
    "toml" to AllIcons.FileTypes.Toml,
    "xsd" to AllIcons.FileTypes.XsdFile,
    "kt" to AllIcons.Language.Kotlin,
    "ps1" to AllIcons.FileTypes.MicrosoftWindows,
    "mjs" to AllIcons.FileTypes.JavaScript,
    "kts" to AllIcons.Language.Kotlin,
    "tsx" to AllIcons.FileTypes.JavaScript,
    "cfg" to AllIcons.FileTypes.Config,
    "ini" to AllIcons.FileTypes.Config,
    "groovy" to AllIcons.FileTypes.Groovy,
    "http" to AllIcons.FileTypes.Http,
    "jsp" to AllIcons.FileTypes.Jsp,
    "wsdl" to AllIcons.FileTypes.WsdlFile,
    "h" to AllIcons.FileTypes.H,
    "proto" to AllIcons.FileTypes.Idl,
    "vue" to AllIcons.FileTypes.Vue,
    "less" to AllIcons.FileTypes.Css,
    "patch" to AllIcons.Vcs.Patch_file,
    "cjs" to AllIcons.FileTypes.JavaScript,
    "xsl" to AllIcons.FileTypes.Xml,
    "puml" to AllIcons.FileTypes.Diagram,
    "tf" to AllIcons.FileTypes.Terraform,
    "c" to AllIcons.FileTypes.C,
    "php" to AllIcons.Language.Php,
    "go" to AllIcons.Language.GO,
    "htm" to AllIcons.FileTypes.Html,
    "hcl" to AllIcons.FileTypes.Terraform,
    "cpp" to AllIcons.FileTypes.Cpp,
    "rb" to AllIcons.Language.Ruby,
    "rst" to AllIcons.FileTypes.Rst,
    "tab" to AllIcons.FileTypes.Csv,
    "jsx" to AllIcons.FileTypes.JavaScript,
    "plist" to AllIcons.FileTypes.Xml,
    "cnf" to AllIcons.FileTypes.Config,
    "fish" to AllIcons.Nodes.Console,
    "scala" to AllIcons.Language.Scala,
    "avsc" to AllIcons.FileTypes.Json,
    "tfvars" to AllIcons.FileTypes.Terraform,
    "pl" to AllIcons.FileTypes.Perl,
    "graphql" to AllIcons.FileTypes.Graphql,
    "csh" to AllIcons.Nodes.Console,
    "pyi" to AllIcons.Language.Python,
    "webmanifest" to AllIcons.FileTypes.Manifest,
    "bash" to AllIcons.Nodes.Console,
    "markdown" to AllIcons.FileTypes.Markdown,
    "cc" to AllIcons.FileTypes.Cpp,
    "jsonl" to AllIcons.FileTypes.Json,
    "cs" to AllIcons.FileTypes.Csharp,
    "swift" to AllIcons.FileTypes.SwiftLang,
    "mts" to AllIcons.FileTypes.JavaScript,
    "xslt" to AllIcons.FileTypes.Xml,
    "ipynb" to AllIcons.FileTypes.Jupyter,
    "tsv" to AllIcons.FileTypes.Csv,
    "sbt" to AllIcons.Language.Scala,
    "xhtml" to AllIcons.FileTypes.Xhtml,
  )

  fun find(extension: String?): Icon? {
    return extension
      ?.lowercase(Locale.ROOT)
      ?.let(iconsByExtension::get)
  }
}
