load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.util.text.matching",
    srcs = ["src"],
    iml_files = ["intellij.platform.util.text.matching.iml"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//tools/idea/.idea/libraries:jetbrains-annotations",
        "//tools/idea/platform/util/strings:intellij.platform.util.strings[module]",
        "//tools/idea/platform/util/collections:intellij.platform.util.collections[module]",
        "//tools/idea/platform/util-rt:intellij.platform.util.rt[module]",
    ],
)
