GET https://yt-ij-integration-tests.myjetbrains.com/youtrack/api/issues?fields={{issue-fields}}
Accept: application/json
Authorization: Bearer {{token}}

### Multiple issues. Invalid query.
GET https://yt-ij-integration-tests.myjetbrains.com/youtrack/api/issues?fields={{issue-fields}}&query=#Foo
Accept: application/json
Authorization: Bearer {{token}}

### Multiple issues. Pagination.
GET https://yt-ij-integration-tests.myjetbrains.com/youtrack/api/issues?fields={{issue-fields-min}}&$skip=0&$top=5&query={{pagination-query}}
Accept: application/json
Authorization: Bearer {{token}}

### Single issue
GET https://yt-ij-integration-tests.myjetbrains.com/youtrack/api/issues/TEST-6?fields={{issue-fields}}
Accept: application/json
Authorization: Bearer {{token}}

### Available states
POST https://yt-ij-integration-tests.myjetbrains.com/youtrack/api/commands/assist?fields={{command-suggestion-fields}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "query": "state ",
  "caret": 6,
  "issues": [
    {
      "idReadable": "TEST-4"
    }
  ]
}

### Query highlighting
POST https://yt-ij-integration-tests.myjetbrains.com/youtrack/api/search/assist?fields={{search-assist-fields}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "query": "for: me #Unresolved 'foo'"
}

### Set state
POST https://yt-ij-integration-tests.myjetbrains.com/youtrack/api/commands/assist
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "query": "state Fixed",
  "caret": 11,
  "issues": [
    {
      "idReadable": "TEST-4"
    }
  ]
}

### Fetch time tracking records
GET https://yt-ij-integration-tests.myjetbrains.com/youtrack/api/issues/TEST-6/timeTracking/workItems
Accept: application/json
Authorization: Bearer {{token}}

### Post a time tracking record
POST https://yt-ij-integration-tests.myjetbrains.com/youtrack/api/issues/TEST-6/timeTracking/workItems
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "usesMarkdown": true,
  "text": "I keep on testing *samples*.",
  "duration": {
    "minutes": 10
  }
}
