load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "remote-servers-agent-rt",
    srcs = ["src"],
    iml_files = ["remote-servers-agent-rt.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
