load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.remoteServers.agent.rt",
    srcs = ["src"],
    iml_files = ["intellij.platform.remoteServers.agent.rt.iml"],
    visibility = ["//visibility:public"],
)
