apiVersion: apps/v1
kind: Deployment
metadata:
  name: ij-settings-docs
  labels:
    app: ij-settings-docs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ij-settings-docs
  template:
    metadata:
      labels:
        app: ij-settings-docs
    spec:
      imagePullSecrets:
        - name: space-registry-ij
      containers:
        - name: ij-settings-docs
          image: registry.jetbrains.team/p/ij/structurizr/settings-docs@sha256:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ij-settings-docs
  labels:
    app: ij-settings-docs
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: ij-settings-docs
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ij-settings-docs
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-labs-jb-gg-dns
spec:
  ingressClassName: nginx
  tls:
  - secretName: ij-settings-docs-labs-jb-gg-tls
    hosts:
    - ij-settings-docs.labs.jb.gg
  rules:
  - host: ij-settings-docs.labs.jb.gg
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ij-settings-docs
            port:
              number: 80