load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "community-tests",
    iml_files = ["community-tests.iml"],
    tags = ["managed"],
    test_srcs = ["src"],
    test_tags = ["manual"],
    visibility = ["//visibility:public"],
)
