from typing import Any

def BuildMessageAndEnumDescriptors(file_des, module: dict[str, Any]) -> None: ...
def BuildTopDescriptorsAndMessages(file_des, module_name: str, module: dict[str, Any]) -> None: ...
