from collections.abc import Callable
from typing import TypeAlias

from google.protobuf.descriptor import FieldDescriptor

_Sizer: TypeAlias = Callable[[int, bool, bool], int]

Int32Sizer: _Sizer
Int64Sizer: _Sizer
EnumSizer: _Sizer
UInt32Sizer: _Sizer
UInt64Sizer: _Sizer
SInt32Sizer: _Sizer
SInt64Sizer: _Sizer
Fixed32Sizer: _Sizer
SFixed32Sizer: _Sizer
FloatSizer: _Sizer
Fixed64Sizer: _Sizer
SFixed64Sizer: _Sizer
DoubleSizer: _Sizer
BoolSizer: _Sizer

def StringSizer(field_number: int, is_repeated: bool, is_packed: bool) -> _Sizer: ...
def BytesSizer(field_number: int, is_repeated: bool, is_packed: bool) -> _Sizer: ...
def GroupSizer(field_number: int, is_repeated: bool, is_packed: bool) -> _Sizer: ...
def MessageSizer(field_number: int, is_repeated: bool, is_packed: bool) -> _Sizer: ...
def MessageSetItemSizer(field_number: int) -> _Sizer: ...
def MapSizer(field_descriptor: FieldDescriptor, is_message_map: bool) -> _Sizer: ...
def TagBytes(field_number: int, wire_type: int) -> bytes: ...

_Encoder: TypeAlias = Callable[[Callable[[bytes], int], bytes, bool], int]

def Int32Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def Int64Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def EnumEncoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def UInt32Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def UInt64Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def SInt32Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def SInt64Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def Fixed32Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def Fixed64Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def SFixed32Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def SFixed64Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def FloatEncoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def DoubleEncoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def BoolEncoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def StringEncoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def BytesEncoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def GroupEncoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def MessageEncoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def MessageSetItemEncoder(field_number: int) -> _Encoder: ...
def MapEncoder(field_descriptor: FieldDescriptor) -> _Encoder: ...
