import logging
import os
from collections.abc import Iterable, Sequence
from types import TracebackType
from typing import Any, Final
from typing_extensions import Self, deprecated

from rasterio._affine_types import Affine
from rasterio._path import _ParsedPath, _UnparsedPath
from rasterio._typing import Colormap, CRSInput, _OpenOption
from rasterio.control import GroundControlPoint
from rasterio.coords import BoundingBox
from rasterio.crs import CRS
from rasterio.enums import ColorInterp, Compression, Interleaving, MaskFlags, PhotometricInterp
from rasterio.profiles import Profile
from rasterio.rpc import RPC
from rasterio.windows import Window

log: Final[logging.Logger]

def get_dataset_driver(path: str) -> str: ...
def driver_supports_mode(drivername: str, creation_mode: str) -> bool: ...
def driver_can_create(drivername: str) -> bool: ...
def driver_can_create_copy(drivername: str) -> bool: ...
def tastes_like_gdal(seq: Affine | Sequence[float]) -> bool: ...
def _raster_driver_extensions() -> dict[str, str]: ...
def _can_create_osr(crs: CRSInput) -> bool: ...
def _transform(
    src_crs: CRSInput, dst_crs: CRSInput, xs: Sequence[float], ys: Sequence[float], zs: Sequence[float] | None
) -> tuple[list[float], list[float], list[float]]: ...

class DatasetBase:
    name: str
    mode: str
    options: dict[str, Any]
    width: int
    height: int
    shape: tuple[int, int]
    driver: str

    def __init__(
        self,
        path: str | os.PathLike[str] | _ParsedPath | _UnparsedPath | None = None,
        driver: str | Sequence[str] | None = None,
        sharing: bool = False,
        thread_safe: bool = False,
        **kwargs: _OpenOption,
    ) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None
    ) -> None: ...
    def read_crs(self) -> CRS | None: ...
    def read_transform(self) -> list[float]: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def close(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    @property
    def count(self) -> int: ...
    @property
    def indexes(self) -> tuple[int, ...]: ...
    @property
    def dtypes(self) -> tuple[str, ...]: ...
    @property
    def block_shapes(self) -> tuple[tuple[int, int], ...]: ...
    def get_nodatavals(self) -> tuple[float | None, ...]: ...
    @property
    def nodatavals(self) -> tuple[float | None, ...]: ...

    @property
    def nodata(self) -> float | None: ...
    @nodata.setter
    def nodata(self, value: float | None) -> None: ...

    @property
    def mask_flag_enums(self) -> tuple[list[MaskFlags], ...]: ...

    @property
    def crs(self) -> CRS: ...
    @crs.setter
    def crs(self, value: CRSInput) -> None: ...

    @property
    def descriptions(self) -> tuple[str | None, ...]: ...
    @descriptions.setter
    def descriptions(self, value: Sequence[str | None]) -> None: ...

    def write_transform(self, transform: Sequence[float]) -> None: ...

    @property
    def transform(self) -> Affine: ...
    @transform.setter
    def transform(self, value: Affine) -> None: ...

    @property
    def offsets(self) -> tuple[float, ...]: ...
    @offsets.setter
    def offsets(self, value: Sequence[float]) -> None: ...

    @property
    def scales(self) -> tuple[float, ...]: ...
    @scales.setter
    def scales(self, value: Sequence[float]) -> None: ...

    @property
    def units(self) -> tuple[str | None, ...]: ...
    @units.setter
    def units(self, value: Sequence[str | None]) -> None: ...

    def block_window(self, bidx: int, i: int, j: int) -> Window: ...
    def block_size(self, bidx: int, i: int, j: int) -> int: ...
    def block_windows(self, bidx: int = 0) -> Iterable[tuple[tuple[int, int], Window]]: ...
    @property
    def bounds(self) -> BoundingBox: ...
    @property
    def res(self) -> tuple[float, float]: ...
    @property
    def meta(self) -> dict[str, Any]: ...
    @property
    def compression(self) -> Compression | None: ...
    @property
    def interleaving(self) -> Interleaving | None: ...
    @property
    def photometric(self) -> PhotometricInterp | None: ...
    @property
    @deprecated("DatasetBase.is_tiled will be removed in a future rasterio release; inspect block_shapes / profile directly.")
    def is_tiled(self) -> bool: ...
    @property
    def profile(self) -> Profile: ...
    def lnglat(self) -> tuple[float, float]: ...
    def get_transform(self) -> list[float]: ...
    @property
    def subdatasets(self) -> list[str]: ...
    def tag_namespaces(self, bidx: int = 0) -> list[str]: ...
    def tags(self, bidx: int = 0, ns: str | None = None) -> dict[str, str]: ...
    def get_tag_item(self, ns: str, dm: str | None = None, bidx: int = 0, ovr: int | None = None) -> str | None: ...

    @property
    def colorinterp(self) -> tuple[ColorInterp, ...]: ...
    @colorinterp.setter
    def colorinterp(self, value: Sequence[ColorInterp]) -> None: ...

    def colormap(self, bidx: int) -> Colormap: ...
    def overviews(self, bidx: int) -> list[int]: ...
    def checksum(self, bidx: int, window: Window | None = None) -> int: ...
    def get_gcps(self) -> tuple[list[GroundControlPoint], CRS]: ...

    @property
    def gcps(self) -> tuple[list[GroundControlPoint], CRS]: ...
    @gcps.setter
    def gcps(self, value: tuple[Sequence[GroundControlPoint], CRSInput]) -> None: ...

    @property
    def rpcs(self) -> RPC | None: ...
    @rpcs.setter
    def rpcs(self, value: RPC | None) -> None: ...

    @property
    def files(self) -> list[str]: ...

_GDAL_AT_LEAST_3_10: Final[bool]

complex64: Final[str]
complex128: Final[str]
complex_int16: Final[str]
float32: Final[str]
float64: Final[str]
int16: Final[str]

def _parse_path(path: str) -> _ParsedPath | _UnparsedPath: ...
