from contextlib import AbstractContextManager
from typing import Final

from rasterio._typing import _GDALOption as _GDALOption

ca_bundle: Final[str]
code_map: Final[dict[int, int]]
level_map: Final[dict[int, int]]

def gdal_version() -> str: ...
def get_gdal_config(key: str, normalize: bool = True) -> _GDALOption: ...
def set_gdal_config(key: str, val: _GDALOption, normalize: bool = True) -> None: ...
def del_gdal_config(key: str) -> None: ...
def get_gdal_data() -> str | None: ...
def get_proj_data_search_paths() -> list[str]: ...
def set_proj_data_search_path(path: str) -> None: ...
def driver_count() -> int: ...
def catch_errors() -> AbstractContextManager[None]: ...

class ConfigEnv:
    options: dict[str, _GDALOption]
    def __init__(self, **options: _GDALOption) -> None: ...
    def update_config_options(self, **kwargs: _GDALOption) -> None: ...
    def clear_config_options(self) -> None: ...
    def get_config_options(self) -> dict[str, _GDALOption]: ...

class GDALEnv(ConfigEnv):
    def __init__(self, **options: _GDALOption) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...

class GDALDataFinder:
    def find_file(self, basename: str) -> str | None: ...
    def search(self, prefix: str | None = None) -> str | None: ...
    def search_wheel(self, prefix: str | None = None) -> str | None: ...
    def search_prefix(self, prefix: str) -> str | None: ...
    def search_debian(self, prefix: str) -> str | None: ...

class PROJDataFinder:
    def has_data(self) -> bool: ...
    def search(self, prefix: str | None = None) -> str | None: ...
    def search_wheel(self, prefix: str | None = None) -> str | None: ...
    def search_prefix(self, prefix: str) -> str | None: ...
