from contextlib import AbstractContextManager
from enum import IntEnum
from typing import Final

class GDALError(IntEnum):
    none = 0
    debug = 1
    warning = 2
    failure = 3
    fatal = 4

class CPLE_BaseError(Exception):
    error: int
    errno: int
    errmsg: str
    def __init__(self, error: int, errno: int, errmsg: str) -> None: ...

class CPLE_AppDefinedError(CPLE_BaseError): ...
class CPLE_AssertionFailedError(CPLE_BaseError): ...
class CPLE_FileIOError(CPLE_BaseError): ...
class CPLE_HttpResponseError(CPLE_BaseError): ...
class CPLE_IllegalArgError(CPLE_BaseError): ...
class CPLE_NoWriteAccessError(CPLE_BaseError): ...
class CPLE_NotSupportedError(CPLE_BaseError): ...
class CPLE_OpenFailedError(CPLE_BaseError): ...
class CPLE_OutOfMemoryError(CPLE_BaseError): ...
class CPLE_UserInterruptError(CPLE_BaseError): ...
class CPLE_AWSAccessDeniedError(CPLE_BaseError): ...
class CPLE_AWSBucketNotFoundError(CPLE_BaseError): ...
class CPLE_AWSError(CPLE_BaseError): ...
class CPLE_AWSInvalidCredentialsError(CPLE_BaseError): ...
class CPLE_AWSObjectNotFoundError(CPLE_BaseError): ...
class CPLE_AWSSignatureDoesNotMatchError(CPLE_BaseError): ...
class ObjectNullError(CPLE_BaseError): ...

exception_map: Final[dict[int, type[CPLE_BaseError]]]

class StackChecker:
    def __init__(self) -> None: ...

def stack_errors() -> AbstractContextManager[StackChecker]: ...
