def gdal_version() -> str: ...
def get_gdal_version_info(key: str) -> str: ...
def check_gdal_version(major: int, minor: int) -> bool: ...
def get_geos_version() -> tuple[int, int, int]: ...
def get_proj_version() -> tuple[int, int, int]: ...
