import os
from typing import Final

blacklist: Final[dict[str, tuple[str, ...]]]

def raster_driver_extensions() -> dict[str, str]: ...
def driver_from_extension(path: str | os.PathLike[str]) -> str: ...
def is_blacklisted(name: str, mode: str) -> bool: ...
