load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "maven-artifact-resolver-common",
    srcs = ["src"],
    iml_files = ["maven-artifact-resolver-common.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/plugins/maven/maven30-server-impl/lib/maven3/lib:maven-artifact-3.0.5"],
)
