load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.maven.artifactResolver.common",
    srcs = ["src"],
    iml_files = ["intellij.maven.artifactResolver.common.iml"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//prebuilts/tools/common/m2/repository/org/apache/maven/maven-artifact/3.0.5:jar",
        "//prebuilts/tools/common/m2/repository/org/codehaus/plexus/plexus-utils/2.0.6:jar",
    ],
)
