load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.maven.artifactResolver.common",
    srcs = ["src"],
    iml_files = ["intellij.maven.artifactResolver.common.iml"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/plugins/maven/maven30-server-impl/lib/maven3/lib:maven-artifact-3.0.5"],
)
