java_import(
    name = "maven-artifact-3.0.5",
    jars = ["maven-artifact-3.0.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "aether-api-1.13.1",
    jars = ["aether-api-1.13.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "maven-core-3.0.5",
    jars = ["maven-core-3.0.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "plexus-component-annotations-1.5.5",
    jars = ["plexus-component-annotations-1.5.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
