from _typeshed import Incomplete

class BaseField:
    FIELD_TYPES: list[type[Incomplete]]
    def __init_subclass__(cls, **kw) -> None: ...
    @classmethod
    def parse_json_fields(cls, json): ...
    @classmethod
    def parse_json(cls, json): ...
    @classmethod
    def underscore_name(cls, name: str) -> str: ...
    @classmethod
    def parse_versions(cls, versions: str) -> tuple[int, ...] | None: ...
    name: str
    def __init__(self, json) -> None: ...
    @property
    def type_str(self): ...
    @property
    def tag(self): ...
    def is_array(self) -> bool: ...
    def is_struct(self) -> bool: ...
    def is_struct_array(self) -> bool: ...
    def is_batchable(self) -> bool: ...
    def has_data_class(self) -> bool: ...
    def __call__(self, *args, **kwargs): ...
    @property
    def fields(self): ...
    @property
    def min_version(self): ...
    @property
    def max_version(self): ...
    def for_version_q(self, version) -> bool: ...
    def nullable_for_version_q(self, version) -> bool: ...
    def tagged_field_q(self, version) -> bool: ...
    @property
    def default(self): ...
    def encode(self, value, version=None, compact: bool = False, tagged: bool = False): ...
    def decode(self, data, version=None, compact: bool = False, tagged: bool = False): ...
    def __eq__(self, other) -> bool: ...
