from _typeshed import Incomplete

class CodegenContext:
    lines: list[str]
    globs: dict[str, Incomplete]
    def __init__(self) -> None: ...
    def next_var(self, prefix: str = "v") -> str: ...
    def emit(self, indent, line) -> None: ...
    def emit_reserve(self, indent, nbytes) -> None: ...
    def source(self) -> None: ...
    def print(self) -> None: ...
