from _typeshed import Incomplete
from typing_extensions import Self

from .array import ArrayField
from .struct import StructField

class StructArrayField(ArrayField):
    @classmethod
    def parse_inner_type(cls, json) -> StructField | None: ...  # type: ignore[override]
    @classmethod
    def parse_json(cls, json) -> Self | None: ...
    map_key: Incomplete | None
    def __init__(self, json, array_of=None) -> None: ...
    @property
    def type_str(self): ...
    def is_struct_array(self): ...
    @property
    def fields(self): ...
    def tagged_fields(self, version): ...
    def untagged_fields(self, version): ...
    def has_data_class(self): ...
    def set_data_class(self, data_class): ...
    @property
    def data_class(self): ...
    def __call__(self, *args, **kw): ...
    def emit_decode_from(self, ctx, var_name, indent, version=None, compact: bool = False, tagged: bool = False) -> None: ...
    def emit_encode_into(self, ctx, val_expr, indent, version=None, compact: bool = False, tagged: bool = False) -> None: ...
