// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

/**
 * Gnu command line public PSI interfaces: Command, option, argument etc.
 *
 * <strong>Warning</strong>: most files in this package is autogenerated. Do not touch them directly.
 * @author Ilya.Kazakevich
 */
package com.intellij.commandInterface.commandLine.psi;