load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "xdebugger-api",
    srcs = ["src"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/platform/lang-api"],
    deps = ["//tools/idea/platform/lang-api[module]"],
)
