load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "jps-launcher",
    srcs = ["src"],
    iml_files = ["jps-launcher.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
