java_import(
    name = "jmock-2.5.1",
    jars = ["jmock-2.5.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jmock-junit4-2.5.1",
    jars = ["jmock-junit4-2.5.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jmock-legacy-2.5.1",
    jars = ["jmock-legacy-2.5.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "objenesis-1.0",
    jars = ["objenesis-1.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "easymock-3.4",
    jars = ["easymock-3.4.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
