# managed by go/iml_to_build
java_import(
    name = "jmock-2.5.1",
    jars = ["jmock-2.5.1.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jmock-junit4-2.5.1",
    jars = ["jmock-junit4-2.5.1.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jmock-legacy-2.5.1",
    jars = ["jmock-legacy-2.5.1.jar"],
    visibility = ["//visibility:public"],
)
