# managed by go/iml_to_build
java_import(
    name = "griffon-rt-1.1.0",
    jars = ["griffon-rt-1.1.0.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "griffon-cli-1.1.0",
    jars = ["griffon-cli-1.1.0.jar"],
    visibility = ["//visibility:public"],
)
