java_import(
    name = "griffon-rt-1.1.0",
    jars = ["griffon-rt-1.1.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "griffon-cli-1.1.0",
    jars = ["griffon-cli-1.1.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
