load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.icons",
    iml_files = ["intellij.platform.icons.iml"],
    # do not sort: must match IML order
    resources = [
        "compatibilityResources",
        "src",
    ],
    visibility = ["//visibility:public"],
)
