load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.icons",
    # do not sort: must match IML order
    srcs = [
        "src",
        "old_icons_src",
    ],
    iml_files = ["intellij.platform.icons.iml"],
    visibility = ["//visibility:public"],
)
