version = "1.17.*"
upstream_repository = "https://github.com/python-cffi/cffi/"
requires = ["types-setuptools"]

[tool.stubtest]
# linux and darwin are mostly equivalent, except for a single `RTLD_DEEPBIND` variable
ci_platforms = ["linux", "win32"]
