version = "2.0.*"
upstream-repository = "https://github.com/python-cffi/cffi/"
dependencies = ["types-setuptools"]

[tool.stubtest]
# linux and darwin are mostly equivalent, except for a single `RTLD_DEEPBIND` variable
ci-platforms = ["linux", "win32"]
