from _typeshed import Incomplete

class ConfigApiMixin:
    def create_config(
        self,
        name: str,
        data: bytes,
        labels: dict[Incomplete, Incomplete] | None = None,
        templating: dict[Incomplete, Incomplete] | None = None,
    ): ...
    def inspect_config(self, id): ...
    def remove_config(self, id): ...
    def configs(self, filters=None): ...
