// Generated by delombok at Sat Jun 11 11:12:44 CEST 2016

import java.util.List;

class BuilderSimpleProtected<T> {
	private List<T> also;

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	BuilderSimpleProtected(final List<T> also) {
		this.also = also;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected static class BuilderSimpleProtectedBuilder<T> {
		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		private List<T> also;

		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		BuilderSimpleProtectedBuilder() {
		}

		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		public BuilderSimpleProtectedBuilder<T> also(final List<T> also) {
			this.also = also;
			return this;
		}

		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		public BuilderSimpleProtected<T> build() {
			return new BuilderSimpleProtected<T>(also);
		}

		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		@javax.annotation.Generated("lombok")
		public java.lang.String toString() {
			return "BuilderSimpleProtected.BuilderSimpleProtectedBuilder(also=" + this.also + ")";
		}
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	protected static <T> BuilderSimpleProtectedBuilder<T> builder() {
		return new BuilderSimpleProtectedBuilder<T>();
	}
}
