def in_transaction(): ...
def transaction(callback, retries=..., read_only: bool = False, join: bool = False, xg: bool = True, propagation=None): ...
def transaction_async(callback, retries=..., read_only: bool = False, join: bool = False, xg: bool = True, propagation=None): ...
def transaction_async_(callback, retries=..., read_only: bool = False, join: bool = False, xg: bool = True, propagation=None): ...
def transactional(retries=..., read_only: bool = False, join: bool = True, xg: bool = True, propagation=None): ...
def transactional_async(retries=..., read_only: bool = False, join: bool = True, xg: bool = True, propagation=None): ...
def transactional_tasklet(retries=..., read_only: bool = False, join: bool = True, xg: bool = True, propagation=None): ...
def non_transactional(allow_existing: bool = True): ...
