load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "intellij.platform.lvcs",
    srcs = ["src"],
    iml_files = ["intellij.platform.lvcs.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/platform/platform-api:intellij.platform.ide[module]"],
)
