load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.lvcs",
    srcs = ["src"],
    iml_files = ["intellij.platform.lvcs.iml"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/platform/platform-api:intellij.platform.ide[module]"],
)
