# managed by go/iml_to_build
java_import(
    name = "saxon",
    jars = ["saxon.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "saxon9he",
    jars = ["saxon9he.jar"],
    visibility = ["//visibility:public"],
)
