java_import(
    name = "saxon",
    jars = ["saxon.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "saxon9he",
    jars = ["saxon9he.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "xalan",
    jars = ["xalan.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "serializer",
    jars = ["serializer.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
