#  Copyright 2000-2025 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

from typing import Any

def Table(*args, **kw): ...
def Column(*args, **kw): ...

class eq_type_affinity:
    target: Any
    def __init__(self, target) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...

class eq_clause_element:
    target: Any
    def __init__(self, target) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
