// Copyright 2000-2019 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE file.
package training.statistic

object FeatureUsageStatisticConsts {
  const val LESSON_ID = "lesson_id"
  const val LANGUAGE = "language"
  const val DURATION = "duration"
  const val START = "start"
  const val PASSED = "passed"
  const val STOPPED = "stopped"
  const val START_MODULE_ACTION = "start_module_action"
  const val MODULE_NAME = "module_name"
  const val PROGRESS = "progress"
  const val COMPLETED_COUNT = "completed_count"
  const val COURSE_SIZE = "course_size"
  const val EXPAND_WELCOME_PANEL = "expand_welcome_screen"
  const val SHORTCUT_CLICKED = "shortcut_clicked"
  const val RESTORE = "restore"
  const val LEARN_PROJECT_OPENED_FIRST_TIME = "learn_project_opened_first_time"
  const val NON_LEARNING_PROJECT_OPENED = "non_learning_project_opened"
  const val LEARN_PROJECT_OPENING_WAY = "learn_opening_way"
  const val ACTION_ID = "action_id"
  const val TASK_ID = "task_id"
  const val KEYMAP_SCHEME = "keymap_scheme"
  const val REASON = "reason"
  const val NEW_LESSONS_NOTIFICATION_SHOWN = "new_lessons_notification_shown"
  const val SHOW_NEW_LESSONS = "show_new_lessons"
  const val NEED_SHOW_NEW_LESSONS_NOTIFICATIONS = "need_show_new_lessons_notifications"
  const val NEW_LESSONS_COUNT = "new_lessons_count"
  const val LAST_BUILD_LEARNING_OPENED = "last_build_learning_opened"
  const val SHOULD_SHOW_NEW_LESSONS = "show_it"
  const val TIP_FILENAME = "filename"
  const val LESSON_LINK_CLICKED_FROM_TIP = "lesson_link_clicked_from_tip"
  const val LESSON_STARTING_WAY = "starting_way"
  const val HELP_LINK_CLICKED = "help_link_clicked"
  const val ONBOARDING_FEEDBACK_NOTIFICATION_SHOWN = "onboarding_feedback_notification_shown"
  const val ONBOARDING_FEEDBACK_DIALOG_RESULT = "onboarding_feedback_dialog_result"
  const val FEEDBACK_ENTRY_PLACE = "feedback_entry_place"
  const val FEEDBACK_HAS_BEEN_SENT = "feedback_has_been_sent"
  const val FEEDBACK_OPENED_VIA_NOTIFICATION = "feedback_opened_via_notification"
  const val FEEDBACK_LIKENESS_ANSWER = "feedback_likeness_answer"
  const val FEEDBACK_EXPERIENCED_USER = "feedback_experienced_user"
  const val PROBLEM = "problem"
  const val INTERNAL_PROBLEM = "internal_problem"
}
