package icons;

import com.intellij.openapi.util.IconLoader;

import javax.swing.*;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class GithubIcons {
  public static final Icon Github_icon = IconLoader.getIcon("/org/jetbrains/plugins/github/github_icon.png"); // 16x16
}
