load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.maven.artifactResolver.m3",
    srcs = ["src"],
    iml_files = ["intellij.maven.artifactResolver.m3.iml"],
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/plugins/maven/artifact-resolver/common:intellij.maven.artifactResolver.common"],
    # do not sort: must match IML order
    deps = [
        "//prebuilts/tools/common/m2/repository/org/sonatype/aether/aether-api/1.13.1:jar",
        "//prebuilts/tools/common/m2/repository/org/apache/maven/maven-aether-provider/3.0.5:jar",
        "//prebuilts/tools/common/m2/repository/org/apache/maven/maven-artifact/3.0.5:jar",
        "//prebuilts/tools/common/m2/repository/org/apache/maven/maven-core/3.0.5:jar",
        "//prebuilts/tools/common/m2/repository/org/apache/maven/maven-model-builder/3.0.5:jar",
        "//prebuilts/tools/common/m2/repository/org/apache/maven/maven-model/3.0.5:jar",
        "//prebuilts/tools/common/m2/repository/org/apache/maven/maven-plugin-api/3.0.5:jar",
        "//prebuilts/tools/common/m2/repository/org/apache/maven/maven-repository-metadata/3.0.5:jar",
        "//prebuilts/tools/common/m2/repository/org/apache/maven/maven-settings-builder/3.0.5:jar",
        "//prebuilts/tools/common/m2/repository/org/apache/maven/maven-settings/3.0.5:jar",
        "//prebuilts/tools/common/m2/repository/org/codehaus/plexus/plexus-classworlds/2.4:jar",
        "//prebuilts/tools/common/m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5:jar",
        "//prebuilts/tools/common/m2/repository/org/codehaus/plexus/plexus-interpolation/1.14:jar",
        "//prebuilts/tools/common/m2/repository/org/codehaus/plexus/plexus-utils/2.0.6:jar",
        "//prebuilts/tools/common/m2/repository/org/sonatype/aether/aether-impl/1.13.1:jar",
        "//prebuilts/tools/common/m2/repository/org/sonatype/aether/aether-spi/1.13.1:jar",
        "//prebuilts/tools/common/m2/repository/org/sonatype/aether/aether-util/1.13.1:jar",
        "//prebuilts/tools/common/m2/repository/org/sonatype/plexus/plexus-cipher/1.4:jar",
        "//prebuilts/tools/common/m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3:jar",
        "//prebuilts/tools/common/m2/repository/org/sonatype/sisu/sisu-inject-bean/2.3.0:jar",
        "//prebuilts/tools/common/m2/repository/org/sonatype/sisu/sisu-inject-plexus/2.3.0:jar",
        "//prebuilts/tools/common/m2/repository/javax/inject/javax.inject/1:jar",
        "//prebuilts/tools/common/m2/repository/org/sonatype/sisu/sisu-guava/0.9.9:jar",
        "//prebuilts/tools/common/m2/repository/org/sonatype/sisu/sisu-guice/3.1.0:jar",
        "//tools/idea/plugins/maven/artifact-resolver/common:intellij.maven.artifactResolver.common[module]",
    ],
)
