// Copyright 2000-2022 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

package org.jetbrains.kotlin.idea.fir.completion;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.idea.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.idea.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TestMetadata;
import org.jetbrains.kotlin.idea.test.TestRoot;
import org.junit.runner.RunWith;

/**
 * This class is generated by {@link org.jetbrains.kotlin.testGenerator.generator.TestGenerator}.
 * DO NOT MODIFY MANUALLY.
 */
@SuppressWarnings("all")
@TestRoot("fir")
@TestDataPath("$CONTENT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public abstract class FirKeywordCompletionTestGenerated extends AbstractFirKeywordCompletionTest {
    @RunWith(JUnit3RunnerWithInners.class)
    @TestMetadata("../idea/tests/testData-completion/keywords")
    public static class Keywords extends AbstractFirKeywordCompletionTest {
        private void runTest(String testDataFilePath) throws Exception {
            KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
        }

        @TestMetadata("AfterClassName.kt")
        public void testAfterClassName() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/AfterClassName.kt");
        }

        @TestMetadata("AfterClassProperty.kt")
        public void testAfterClassProperty() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/AfterClassProperty.kt");
        }

        @TestMetadata("AfterClasses.kt")
        public void testAfterClasses() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/AfterClasses.kt");
        }

        @TestMetadata("AfterClasses_LangLevel10.kt")
        public void testAfterClasses_LangLevel10() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/AfterClasses_LangLevel10.kt");
        }

        @TestMetadata("AfterClasses_LangLevel11.kt")
        public void testAfterClasses_LangLevel11() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/AfterClasses_LangLevel11.kt");
        }

        @TestMetadata("AfterDot.kt")
        public void testAfterDot() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/AfterDot.kt");
        }

        @TestMetadata("AfterFuns.kt")
        public void testAfterFuns() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/AfterFuns.kt");
        }

        @TestMetadata("AfterIf.kt")
        public void testAfterIf() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/AfterIf.kt");
        }

        @TestMetadata("AfterSafeDot.kt")
        public void testAfterSafeDot() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/AfterSafeDot.kt");
        }

        @TestMetadata("AfterSpaceAndDot.kt")
        public void testAfterSpaceAndDot() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/AfterSpaceAndDot.kt");
        }

        @TestMetadata("AfterTry.kt")
        public void testAfterTry() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/AfterTry.kt");
        }

        @TestMetadata("AfterTryCatch.kt")
        public void testAfterTryCatch() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/AfterTryCatch.kt");
        }

        @TestMetadata("AfterTryFinally.kt")
        public void testAfterTryFinally() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/AfterTryFinally.kt");
        }

        @TestMetadata("AfterTryInAssignment.kt")
        public void testAfterTryInAssignment() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/AfterTryInAssignment.kt");
        }

        @TestMetadata("BeforeClass.kt")
        public void testBeforeClass() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/BeforeClass.kt");
        }

        @TestMetadata("BeforeDelegationCall.kt")
        public void testBeforeDelegationCall() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/BeforeDelegationCall.kt");
        }

        @TestMetadata("BreakContinue.kt")
        public void testBreakContinue() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/BreakContinue.kt");
        }

        @TestMetadata("BreakPrefixMatching.kt")
        public void testBreakPrefixMatching() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/BreakPrefixMatching.kt");
        }

        @TestMetadata("BreakWithLabel.kt")
        public void testBreakWithLabel() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/BreakWithLabel.kt");
        }

        @TestMetadata("BreakWithLabelPrefix.kt")
        public void testBreakWithLabelPrefix() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/BreakWithLabelPrefix.kt");
        }

        @TestMetadata("CommaExpected.kt")
        public void testCommaExpected() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/CommaExpected.kt");
        }

        @TestMetadata("CompanionObjectBeforeObject.kt")
        public void testCompanionObjectBeforeObject() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/CompanionObjectBeforeObject.kt");
        }

        @TestMetadata("ContinuePrefixMatching.kt")
        public void testContinuePrefixMatching() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/ContinuePrefixMatching.kt");
        }

        @TestMetadata("ContinueWithLabel.kt")
        public void testContinueWithLabel() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/ContinueWithLabel.kt");
        }

        @TestMetadata("ContinueWithLabelPrefix.kt")
        public void testContinueWithLabelPrefix() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/ContinueWithLabelPrefix.kt");
        }

        @TestMetadata("Else1.kt")
        public void testElse1() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/Else1.kt");
        }

        @TestMetadata("Else2.kt")
        public void testElse2() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/Else2.kt");
        }

        @TestMetadata("FileKeyword.kt")
        public void testFileKeyword() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/FileKeyword.kt");
        }

        @TestMetadata("FixingLayoutAndReturn.kt")
        public void testFixingLayoutAndReturn() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/FixingLayoutAndReturn.kt");
        }

        @TestMetadata("GlobalPropertyAccessors.kt")
        public void testGlobalPropertyAccessors() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/GlobalPropertyAccessors.kt");
        }

        @TestMetadata("IfTry.kt")
        public void testIfTry() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/IfTry.kt");
        }

        @TestMetadata("IfTryCatch.kt")
        public void testIfTryCatch() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/IfTryCatch.kt");
        }

        @TestMetadata("InAnnotationClassScope.kt")
        public void testInAnnotationClassScope() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InAnnotationClassScope.kt");
        }

        @TestMetadata("InArgumentList.kt")
        public void testInArgumentList() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InArgumentList.kt");
        }

        @TestMetadata("InBlockComment.kt")
        public void testInBlockComment() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InBlockComment.kt");
        }

        @TestMetadata("InChar.kt")
        public void testInChar() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InChar.kt");
        }

        @TestMetadata("InClassBeforeFun.kt")
        public void testInClassBeforeFun() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InClassBeforeFun.kt");
        }

        @TestMetadata("InClassNoCompletionInValName.kt")
        public void testInClassNoCompletionInValName() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InClassNoCompletionInValName.kt");
        }

        @TestMetadata("InClassProperty.kt")
        public void testInClassProperty() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InClassProperty.kt");
        }

        @TestMetadata("InClassScope.kt")
        public void testInClassScope() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InClassScope.kt");
        }

        @TestMetadata("InClassTypeParameters.kt")
        public void testInClassTypeParameters() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InClassTypeParameters.kt");
        }

        @TestMetadata("InCodeBlock.kt")
        public void testInCodeBlock() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InCodeBlock.kt");
        }

        @TestMetadata("InElse.kt")
        public void testInElse() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InElse.kt");
        }

        @TestMetadata("InEnumScope1.kt")
        public void testInEnumScope1() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InEnumScope1.kt");
        }

        @TestMetadata("InEnumScope2.kt")
        public void testInEnumScope2() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InEnumScope2.kt");
        }

        @TestMetadata("InFunctionExpressionBody.kt")
        public void testInFunctionExpressionBody() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InFunctionExpressionBody.kt");
        }

        @TestMetadata("InFunctionName.kt")
        public void testInFunctionName() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InFunctionName.kt");
        }

        @TestMetadata("InFunctionRecieverType.kt")
        public void testInFunctionRecieverType() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InFunctionRecieverType.kt");
        }

        @TestMetadata("InFunctionTypePosition.kt")
        public void testInFunctionTypePosition() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InFunctionTypePosition.kt");
        }

        @TestMetadata("InGetterExpressionBody.kt")
        public void testInGetterExpressionBody() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InGetterExpressionBody.kt");
        }

        @TestMetadata("InIf.kt")
        public void testInIf() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InIf.kt");
        }

        @TestMetadata("InInterfaceScope.kt")
        public void testInInterfaceScope() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InInterfaceScope.kt");
        }

        @TestMetadata("InMemberFunParametersList.kt")
        public void testInMemberFunParametersList() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InMemberFunParametersList.kt");
        }

        @TestMetadata("InModifierListInsideClass.kt")
        public void testInModifierListInsideClass() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InModifierListInsideClass.kt");
        }

        @TestMetadata("InNotFinishedGenericWithFunAfter.kt")
        public void testInNotFinishedGenericWithFunAfter() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InNotFinishedGenericWithFunAfter.kt");
        }

        @TestMetadata("InObjectScope.kt")
        public void testInObjectScope() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InObjectScope.kt");
        }

        @TestMetadata("InParameterDefaultValue.kt")
        public void testInParameterDefaultValue() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InParameterDefaultValue.kt");
        }

        @TestMetadata("InPrimaryConstructorParametersList.kt")
        public void testInPrimaryConstructorParametersList() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InPrimaryConstructorParametersList.kt");
        }

        @TestMetadata("InPropertyInitializer.kt")
        public void testInPropertyInitializer() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InPropertyInitializer.kt");
        }

        @TestMetadata("InPropertyTypeReference.kt")
        public void testInPropertyTypeReference() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InPropertyTypeReference.kt");
        }

        @TestMetadata("InString.kt")
        public void testInString() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InString.kt");
        }

        @TestMetadata("InTopFunParametersList.kt")
        public void testInTopFunParametersList() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InTopFunParametersList.kt");
        }

        @TestMetadata("InTopScopeAfterPackage.kt")
        public void testInTopScopeAfterPackage() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InTopScopeAfterPackage.kt");
        }

        @TestMetadata("InTypePosition.kt")
        public void testInTypePosition() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/InTypePosition.kt");
        }

        @TestMetadata("LabeledLambdaThis.kt")
        public void testLabeledLambdaThis() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/LabeledLambdaThis.kt");
        }

        @TestMetadata("LineComment.kt")
        public void testLineComment() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/LineComment.kt");
        }

        @TestMetadata("NoBreak1.kt")
        public void testNoBreak1() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/NoBreak1.kt");
        }

        @TestMetadata("NoBreak2.kt")
        public void testNoBreak2() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/NoBreak2.kt");
        }

        @TestMetadata("NoCompanionThis.kt")
        public void testNoCompanionThis() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/NoCompanionThis.kt");
        }

        @TestMetadata("NoCompletionForCapitalPrefix.kt")
        public void testNoCompletionForCapitalPrefix() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/NoCompletionForCapitalPrefix.kt");
        }

        @TestMetadata("NoConstructorInCompanion.kt")
        public void testNoConstructorInCompanion() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/NoConstructorInCompanion.kt");
        }

        @TestMetadata("NoConstructorInObject.kt")
        public void testNoConstructorInObject() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/NoConstructorInObject.kt");
        }

        @TestMetadata("NoConstructorInObjectLiteral.kt")
        public void testNoConstructorInObjectLiteral() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/NoConstructorInObjectLiteral.kt");
        }

        @TestMetadata("NoContinue.kt")
        public void testNoContinue() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/NoContinue.kt");
        }

        @TestMetadata("NoFinalInParameterList.kt")
        public void testNoFinalInParameterList() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/NoFinalInParameterList.kt");
        }

        @TestMetadata("NoValVarInFunctionParameters.kt")
        public void testNoValVarInFunctionParameters() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/NoValVarInFunctionParameters.kt");
        }

        @TestMetadata("NoValVarInSecondaryConstructorParameters.kt")
        public void testNoValVarInSecondaryConstructorParameters() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/NoValVarInSecondaryConstructorParameters.kt");
        }

        @TestMetadata("NotInNotIs.kt")
        public void testNotInNotIs() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/NotInNotIs.kt");
        }

        @TestMetadata("NotInNotIs2.kt")
        public void testNotInNotIs2() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/NotInNotIs2.kt");
        }

        @TestMetadata("PrefixMatcher.kt")
        public void testPrefixMatcher() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/PrefixMatcher.kt");
        }

        @TestMetadata("PropertyAccessors.kt")
        public void testPropertyAccessors() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/PropertyAccessors.kt");
        }

        @TestMetadata("PropertyAccessors2.kt")
        public void testPropertyAccessors2() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/PropertyAccessors2.kt");
        }

        @TestMetadata("PropertyAccessors_ExplicitBackingFieldsEnabled.kt")
        public void testPropertyAccessors_ExplicitBackingFieldsEnabled() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/PropertyAccessors_ExplicitBackingFieldsEnabled.kt");
        }

        @TestMetadata("PropertySetter.kt")
        public void testPropertySetter() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/PropertySetter.kt");
        }

        @TestMetadata("QualifiedThis.kt")
        public void testQualifiedThis() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/QualifiedThis.kt");
        }

        @TestMetadata("QualifiedThisInAccessor.kt")
        public void testQualifiedThisInAccessor() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/QualifiedThisInAccessor.kt");
        }

        @TestMetadata("Receiver.kt")
        public void testReceiver() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/Receiver.kt");
        }

        @TestMetadata("Return1.kt")
        public void testReturn1() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/Return1.kt");
        }

        @TestMetadata("Return2.kt")
        public void testReturn2() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/Return2.kt");
        }

        @TestMetadata("Return3.kt")
        public void testReturn3() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/Return3.kt");
        }

        @TestMetadata("Return4.kt")
        public void testReturn4() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/Return4.kt");
        }

        @TestMetadata("Return5.kt")
        public void testReturn5() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/Return5.kt");
        }

        @TestMetadata("Return6_1.kt")
        public void testReturn6_1() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/Return6_1.kt");
        }

        @TestMetadata("Return6_2.kt")
        public void testReturn6_2() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/Return6_2.kt");
        }

        @TestMetadata("Return7.kt")
        public void testReturn7() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/Return7.kt");
        }

        @TestMetadata("Return8.kt")
        public void testReturn8() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/Return8.kt");
        }

        @TestMetadata("Return9.kt")
        public void testReturn9() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/Return9.kt");
        }

        @TestMetadata("ReturnBoolean.kt")
        public void testReturnBoolean() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/ReturnBoolean.kt");
        }

        @TestMetadata("ReturnCollection.kt")
        public void testReturnCollection() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/ReturnCollection.kt");
        }

        @TestMetadata("ReturnIterable.kt")
        public void testReturnIterable() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/ReturnIterable.kt");
        }

        @TestMetadata("ReturnKeywordName.kt")
        public void testReturnKeywordName() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/ReturnKeywordName.kt");
        }

        @TestMetadata("ReturnList.kt")
        public void testReturnList() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/ReturnList.kt");
        }

        @TestMetadata("ReturnNotNull.kt")
        public void testReturnNotNull() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/ReturnNotNull.kt");
        }

        @TestMetadata("ReturnNull.kt")
        public void testReturnNull() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/ReturnNull.kt");
        }

        @TestMetadata("ReturnNullableBoolean.kt")
        public void testReturnNullableBoolean() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/ReturnNullableBoolean.kt");
        }

        @TestMetadata("ReturnPrefixMatching.kt")
        public void testReturnPrefixMatching() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/ReturnPrefixMatching.kt");
        }

        @TestMetadata("ReturnSet.kt")
        public void testReturnSet() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/ReturnSet.kt");
        }

        @TestMetadata("SealedForAlreadySealed.kt")
        public void testSealedForAlreadySealed() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/SealedForAlreadySealed.kt");
        }

        @TestMetadata("SealedForAnnotationClass.kt")
        public void testSealedForAnnotationClass() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/SealedForAnnotationClass.kt");
        }

        @TestMetadata("SealedForDataClass.kt")
        public void testSealedForDataClass() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/SealedForDataClass.kt");
        }

        @TestMetadata("SealedForDeclaredClass.kt")
        public void testSealedForDeclaredClass() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/SealedForDeclaredClass.kt");
        }

        @TestMetadata("SealedForDeclaredInterface.kt")
        public void testSealedForDeclaredInterface() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/SealedForDeclaredInterface.kt");
        }

        @TestMetadata("SealedForEnumClass.kt")
        public void testSealedForEnumClass() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/SealedForEnumClass.kt");
        }

        @TestMetadata("SealedForFunInterface.kt")
        public void testSealedForFunInterface() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/SealedForFunInterface.kt");
        }

        @TestMetadata("SealedForInnerClass.kt")
        public void testSealedForInnerClass() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/SealedForInnerClass.kt");
        }

        @TestMetadata("SealedForOpenClass.kt")
        public void testSealedForOpenClass() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/SealedForOpenClass.kt");
        }

        @TestMetadata("SealedWithName.kt")
        public void testSealedWithName() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/SealedWithName.kt");
        }

        @TestMetadata("SealedWithoutName.kt")
        public void testSealedWithoutName() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/SealedWithoutName.kt");
        }

        @TestMetadata("SuspendInParameterTypePosition.kt")
        public void testSuspendInParameterTypePosition() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/SuspendInParameterTypePosition.kt");
        }

        @TestMetadata("SuspendInsideTypeArguments.kt")
        public void testSuspendInsideTypeArguments() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/SuspendInsideTypeArguments.kt");
        }

        @TestMetadata("SuspendInsideTypeArguments1.kt")
        public void testSuspendInsideTypeArguments1() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/SuspendInsideTypeArguments1.kt");
        }

        @TestMetadata("This.kt")
        public void testThis() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/This.kt");
        }

        @TestMetadata("ThisInCompanion.kt")
        public void testThisInCompanion() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/ThisInCompanion.kt");
        }

        @TestMetadata("ThisLabelPrefix.kt")
        public void testThisLabelPrefix() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/ThisLabelPrefix.kt");
        }

        @TestMetadata("ThisPrefixMatching.kt")
        public void testThisPrefixMatching() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/ThisPrefixMatching.kt");
        }

        @TestMetadata("TopScope.kt")
        public void testTopScope() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/TopScope.kt");
        }

        @TestMetadata("topScope2.kt")
        public void testTopScope2() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/topScope2.kt");
        }

        @TestMetadata("TopScope3-.kt")
        public void testTopScope3_() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/TopScope3-.kt");
        }

        @TestMetadata("UseSiteTargetForPrimaryConstructorParameter.kt")
        public void testUseSiteTargetForPrimaryConstructorParameter() throws Exception {
            runTest("../idea/tests/testData-completion/keywords/UseSiteTargetForPrimaryConstructorParameter.kt");
        }
    }

    @RunWith(JUnit3RunnerWithInners.class)
    @TestMetadata("../idea/idea-fir/testData/completion/keywords")
    public abstract static class KeywordsFir extends AbstractFirKeywordCompletionTest {

    }
}
