version = "4.0.*"
upstream_repository = "https://github.com/miguelgrinberg/flask-migrate"
# Requires versions of flask and Flask-SQLAlchemy with `py.typed` files
requires = ["Flask>=2.0.0", "Flask-SQLAlchemy>=3.0.1"]
partial_stub = true

[tool.stubtest]
ignore_missing_stub = true
