import json
import re
import types
from _typeshed import Incomplete
from collections.abc import Iterable
from typing import ClassVar

from pony.utils import localbase

class DBException(Exception):
    def __init__(self, original_exc, *args) -> None: ...

class Warning(DBException): ...
class Error(DBException): ...
class InterfaceError(Error): ...
class DatabaseError(Error): ...
class DataError(DatabaseError): ...
class OperationalError(DatabaseError): ...
class IntegrityError(DatabaseError): ...
class InternalError(DatabaseError): ...
class ProgrammingError(DatabaseError): ...
class NotSupportedError(DatabaseError): ...

def wrap_dbapi_exceptions(func, provider, *args, **kwargs): ...
def unexpected_args(attr, args) -> None: ...

version_re: re.Pattern[str]

def get_version_tuple(s: str): ...

class DBAPIProvider:
    paramstyle: ClassVar[str]
    quote_char: ClassVar[str]
    max_params_count: ClassVar[int]
    max_name_len: ClassVar[int]
    table_if_not_exists_syntax: ClassVar[bool]
    index_if_not_exists_syntax: ClassVar[bool]
    max_time_precision: ClassVar[int]
    default_time_precision: ClassVar[int]
    uint64_support: ClassVar[bool]
    varchar_default_max_len: ClassVar[int | None]
    dialect: ClassVar[str | None]
    dbapi_module: ClassVar[types.ModuleType | None]
    dbschema_cls: ClassVar[type | None]
    translator_cls: ClassVar[type | None]
    sqlbuilder_cls: ClassVar[type | None]
    array_converter_cls: ClassVar[type | None]
    name_before_table: ClassVar[str]
    default_schema_name: ClassVar[str | None]
    fk_types: ClassVar[dict[str, str]]
    converter_classes: Incomplete
    def __init__(self, _database, *args, **kwargs) -> None: ...
    def inspect_connection(self, connection) -> None: ...
    def normalize_name(self, name): ...
    def get_default_entity_table_name(self, entity): ...
    def get_default_m2m_table_name(self, attr, reverse): ...
    def get_default_column_names(self, attr, reverse_pk_columns=None): ...
    def get_default_m2m_column_names(self, entity): ...
    def get_default_index_name(
        self, table_name, column_names, is_pk: bool = False, is_unique: bool = False, m2m: bool = False
    ): ...
    def get_default_fk_name(self, child_table_name, parent_table_name, child_column_names): ...
    def split_table_name(self, table_name): ...
    def base_name(self, name): ...
    def quote_name(self, name: str | Iterable[str]) -> str: ...
    def format_table_name(self, name): ...
    def normalize_vars(self, vars, vartypes) -> None: ...
    def ast2sql(self, ast): ...
    def should_reconnect(self, exc): ...
    def connect(self): ...
    def set_transaction_mode(self, connection, cache) -> None: ...
    def commit(self, connection, cache=None) -> None: ...
    def rollback(self, connection, cache=None) -> None: ...
    def release(self, connection, cache=None) -> None: ...
    def drop(self, connection, cache=None) -> None: ...
    def disconnect(self) -> None: ...
    def execute(self, cursor, sql, arguments=None, returning_id: bool = False): ...
    def get_converter_by_py_type(self, py_type): ...
    def get_converter_by_attr(self, attr): ...
    def get_pool(self, *args, **kwargs): ...
    def table_exists(self, connection, table_name, case_sensitive: bool = True) -> None: ...
    def index_exists(self, connection, table_name, index_name, case_sensitive: bool = True) -> None: ...
    def fk_exists(self, connection, table_name, fk_name, case_sensitive: bool = True) -> None: ...
    def table_has_data(self, connection, table_name): ...
    def disable_fk_checks(self, connection) -> None: ...
    def enable_fk_checks(self, connection, prev_state) -> None: ...
    def drop_table(self, connection, table_name) -> None: ...

class Pool(localbase):
    forked_connections: list[tuple[Incomplete, int | None]]
    dbapi_module: types.ModuleType
    args: tuple[Incomplete, ...]
    kwargs: dict[str, Incomplete]
    con: Incomplete
    pid: int | None
    def __init__(self, dbapi_module: types.ModuleType, *args, **kwargs) -> None: ...
    def connect(self) -> tuple[Incomplete, bool]: ...
    def release(self, con) -> None: ...
    def drop(self, con) -> None: ...
    def disconnect(self) -> None: ...

class Converter:
    EQ: str
    NE: str
    optimistic: bool
    def __deepcopy__(converter, memo): ...
    def __init__(self, provider, py_type, attr=None) -> None: ...
    def init(self, kwargs) -> None: ...
    def validate(self, val, obj=None): ...
    def py2sql(self, val): ...
    def sql2py(self, val): ...
    def val2dbval(self, val, obj=None): ...
    def dbval2val(self, dbval, obj=None): ...
    def dbvals_equal(self, x, y): ...
    def get_sql_type(self, attr=None): ...
    def get_fk_type(self, sql_type): ...

class NoneConverter(Converter):
    def __init__(self, provider, py_type, attr=None) -> None: ...
    def get_sql_type(self, attr=None) -> None: ...
    def get_fk_type(self, sql_type) -> None: ...

class BoolConverter(Converter):
    def validate(self, val, obj=None): ...
    def sql2py(self, val): ...
    def sql_type(self): ...

class StrConverter(Converter):
    def __init__(self, provider, py_type, attr=None) -> None: ...
    def init(self, kwargs) -> None: ...
    def validate(self, val, obj=None): ...
    def sql_type(self): ...

class IntConverter(Converter):
    signed_types: Incomplete
    unsigned_types: Incomplete
    def init(self, kwargs) -> None: ...
    def validate(self, val, obj=None): ...
    def sql2py(self, val): ...
    def sql_type(self): ...

class RealConverter(Converter):
    EQ: str
    NE: str
    default_tolerance: float
    optimistic: bool
    def init(self, kwargs) -> None: ...
    def validate(self, val, obj=None): ...
    def dbvals_equal(self, x, y): ...
    def sql2py(self, val): ...
    def sql_type(self): ...

class DecimalConverter(Converter):
    def __init__(self, provider, py_type, attr=None) -> None: ...
    def init(self, kwargs) -> None: ...
    def validate(self, val, obj=None): ...
    def sql2py(self, val): ...
    def sql_type(self): ...

class BlobConverter(Converter):
    def validate(self, val, obj=None): ...
    def sql2py(self, val): ...
    def sql_type(self): ...

class DateConverter(Converter):
    def validate(self, val, obj=None): ...
    def sql2py(self, val): ...
    def sql_type(self): ...

class ConverterWithMicroseconds(Converter):
    def __init__(self, provider, py_type, attr=None) -> None: ...
    def init(self, kwargs) -> None: ...
    def round_microseconds_to_precision(self, microseconds, precision): ...
    def sql_type(self): ...

class TimeConverter(ConverterWithMicroseconds):
    sql_type_name: ClassVar[str]
    def validate(self, val, obj=None): ...
    def sql2py(self, val): ...

class TimedeltaConverter(ConverterWithMicroseconds):
    sql_type_name: ClassVar[str]
    def validate(self, val, obj=None): ...
    def sql2py(self, val): ...

class DatetimeConverter(ConverterWithMicroseconds):
    sql_type_name: ClassVar[str]
    def validate(self, val, obj=None): ...
    def sql2py(self, val): ...

class UuidConverter(Converter):
    def __init__(self, provider, py_type, attr=None) -> None: ...
    def validate(self, val, obj=None): ...
    def py2sql(self, val): ...
    sql2py = validate
    def sql_type(self): ...

class JsonConverter(Converter):
    json_kwargs: Incomplete

    class JsonEncoder(json.JSONEncoder):
        def default(self, obj): ...

    def validate(self, val, obj=None): ...
    def val2dbval(self, val, obj=None): ...
    def dbval2val(self, dbval, obj=None): ...
    def dbvals_equal(self, x, y): ...
    def sql_type(self): ...

class ArrayConverter(Converter):
    array_types: Incomplete
    def __init__(self, provider, py_type, attr=None) -> None: ...
    def validate(self, val, obj=None): ...
    def dbval2val(self, dbval, obj=None): ...
    def val2dbval(self, val, obj=None): ...
    def sql_type(self): ...
