from _typeshed import Incomplete
from typing import ClassVar

from pony.orm.dbapiprovider import DBAPIProvider

class DBSchema:
    dialect: ClassVar[str | None]
    inline_fk_syntax: ClassVar[bool]
    named_foreign_keys: ClassVar[bool]
    table_class: ClassVar[type[Table]]
    column_class: ClassVar[type[Column]]
    index_class: ClassVar[type[DBIndex]]
    fk_class: ClassVar[type[ForeignKey]]
    provider: DBAPIProvider
    tables: dict[Incomplete, Incomplete]
    constraints: dict[Incomplete, Incomplete]
    indent: str
    command_separator: str
    uppercase: bool
    names: dict[Incomplete, Incomplete]
    def __init__(self, provider: DBAPIProvider, uppercase: bool = True) -> None: ...
    def column_list(self, columns): ...
    def case(self, s: str) -> str: ...
    def add_table(self, table_name, entity=None): ...
    def order_tables_to_create(self): ...
    def generate_create_script(self): ...
    def create_tables(self, provider: DBAPIProvider, connection) -> None: ...
    def check_tables(self, provider: DBAPIProvider, connection) -> None: ...

class DBObject:
    def create(self, provider, connection) -> None: ...

class Table(DBObject):
    typename: ClassVar[str]
    def __init__(self, name, schema, entity=None) -> None: ...
    def add_entity(self, entity) -> None: ...
    def exists(self, provider: DBAPIProvider, connection, case_sensitive: bool = True): ...
    def get_create_command(self): ...
    def format_option(self, name, value): ...
    def get_objects_to_create(self, created_tables: set[Table] | None = None) -> list[Table]: ...
    def add_column(self, column_name, sql_type, converter, is_not_null: bool | None = None, sql_default=None): ...
    def add_index(self, index_name, columns, is_pk: bool = False, is_unique=None, m2m: bool = False): ...
    def add_foreign_key(
        self,
        fk_name,
        child_columns,
        parent_table,
        parent_columns,
        index_name=None,
        on_delete: bool = False,
        interleave: bool = False,
    ): ...

class Column:
    auto_template: ClassVar[str]
    def __init__(self, name, table, sql_type, converter, is_not_null: bool | None = None, sql_default=None) -> None: ...
    def get_sql(self) -> str: ...

class Constraint(DBObject):
    schema: DBSchema
    name: str | None
    def __init__(self, name: str | None, schema: DBSchema) -> None: ...

class DBIndex(Constraint):
    typename: ClassVar[str]
    def __init__(self, name: str | None, table, columns, is_pk: bool = False, is_unique=None) -> None: ...
    def exists(self, provider, connection, case_sensitive: bool = True): ...
    def get_sql(self) -> str: ...
    def get_create_command(self): ...

class ForeignKey(Constraint):
    typename: ClassVar[str]
    def __init__(
        self, name, child_table, child_columns, parent_table, parent_columns, index_name, on_delete, interleave: bool = False
    ) -> None: ...
    def exists(self, provider, connection, case_sensitive: bool = True): ...
    def get_sql(self) -> str: ...
    def get_create_command(self): ...
