import types
from _typeshed import Incomplete
from collections.abc import Iterable
from typing import ClassVar

class AstError(Exception): ...

class Param:
    __slots__ = ("style", "id", "paramkey", "converter", "optimistic")
    style: Incomplete
    id: Incomplete
    paramkey: Incomplete
    converter: Incomplete
    optimistic: bool
    def __init__(self, paramstyle, paramkey, converter=None, optimistic: bool = False) -> None: ...
    def eval(self, values): ...

class CompositeParam(Param):
    __slots__ = ("items", "func")
    items: Iterable[Param | Value]
    func: Incomplete
    def __init__(self, paramstyle, paramkey, items: Iterable[Param | Value], func) -> None: ...
    def eval(self, values): ...

class Value:
    __slots__ = ("paramstyle", "value")
    paramstyle: Incomplete
    value: Incomplete
    def __init__(self, paramstyle, value) -> None: ...
    def quote_str(self, s: str) -> str: ...

def flat(tree): ...
def flat_conditions(conditions): ...
def join(delimiter, items): ...
def move_conditions_from_inner_join_to_where(sections): ...
def make_binary_op(symbol, default_parentheses: bool = False): ...
def make_unary_func(symbol): ...
def indentable(method): ...

class SQLBuilder:
    dialect: ClassVar[str | None]
    param_class: ClassVar[type[Param]]
    composite_param_class: ClassVar[type[CompositeParam]]
    value_class: ClassVar[type[Value]]
    indent_spaces: ClassVar[str]
    least_func_name: ClassVar[str]
    greatest_func_name: ClassVar[str]
    def __init__(self, provider, ast) -> None: ...
    def __call__(self, ast): ...
    def INSERT(self, table_name, columns, values, returning=None): ...
    def DEFAULT(self): ...
    def UPDATE(self, table_name, pairs, where=None): ...
    def DELETE(self, alias, from_ast, where=None): ...
    def SELECT(self, *sections): ...
    def SELECT_FOR_UPDATE(self, nowait, skip_locked, *sections): ...
    def EXISTS(self, *sections): ...
    def NOT_EXISTS(self, *sections): ...
    def ALL(builder, *expr_list): ...
    def DISTINCT(builder, *expr_list): ...
    def AGGREGATES(builder, *expr_list): ...
    def AS(self, expr, alias): ...
    def compound_name(self, name_parts): ...
    def sql_join(self, join_type, sources): ...
    def FROM(self, *sources): ...
    def INNER_JOIN(self, *sources): ...
    def LEFT_JOIN(builder, *sources): ...
    def WHERE(self, *conditions): ...
    def HAVING(self, *conditions): ...
    def GROUP_BY(builder, *expr_list): ...
    def UNION(builder, kind, *sections): ...
    def INTERSECT(builder, *sections): ...
    def EXCEPT(builder, *sections): ...
    def ORDER_BY(builder, *order_list): ...
    def DESC(self, expr): ...
    def LIMIT(builder, limit, offset=None): ...
    def COLUMN(self, table_alias, col_name): ...
    def PARAM(self, paramkey, converter=None, optimistic: bool = False): ...
    def make_param(self, param_class, paramkey, *args): ...
    def make_composite_param(self, paramkey, items, func): ...
    def STAR(self, table_alias): ...
    def ROW(self, *items): ...
    def VALUE(self, value): ...
    def AND(self, *cond_list): ...
    def OR(self, *cond_list): ...
    def NOT(self, condition): ...
    def POW(self, expr1, expr2): ...
    EQ: Incomplete
    NE: Incomplete
    LT: Incomplete
    LE: Incomplete
    GT: Incomplete
    GE: Incomplete
    ADD: Incomplete
    SUB: Incomplete
    MUL: Incomplete
    DIV: Incomplete
    FLOORDIV: Incomplete
    def MOD(self, a, b): ...
    def FLOAT_EQ(self, a, b): ...
    def FLOAT_NE(self, a, b): ...
    def CONCAT(self, *args): ...
    def NEG(self, expr): ...
    def IS_NULL(self, expr): ...
    def IS_NOT_NULL(self, expr): ...
    def LIKE(self, expr, template, escape=None): ...
    def NOT_LIKE(self, expr, template, escape=None): ...
    def BETWEEN(self, expr1, expr2, expr3): ...
    def NOT_BETWEEN(self, expr1, expr2, expr3): ...
    def IN(self, expr1, x): ...
    def NOT_IN(self, expr1, x): ...
    def COUNT(self, distinct, *expr_list): ...
    def SUM(self, distinct, expr): ...
    def AVG(self, distinct, expr): ...
    def GROUP_CONCAT(self, distinct, expr, sep=None): ...
    UPPER: Incomplete
    LOWER: Incomplete
    LENGTH: Incomplete
    ABS: Incomplete
    def COALESCE(self, *args): ...
    def MIN(self, distinct, *args): ...
    def MAX(self, distinct, *args): ...
    def SUBSTR(self, expr, start, len=None): ...
    def STRING_SLICE(self, expr, start, stop): ...
    def CASE(self, expr, cases, default=None): ...
    def IF(self, cond, then, else_): ...
    def TRIM(self, expr, chars=None): ...
    def LTRIM(self, expr, chars=None): ...
    def RTRIM(self, expr, chars=None): ...
    def REPLACE(self, str, from_, to): ...
    def TO_INT(self, expr): ...
    def TO_STR(self, expr): ...
    def TO_REAL(self, expr): ...
    def TODAY(self): ...
    def NOW(self): ...
    def DATE(self, expr): ...
    def YEAR(self, expr): ...
    def MONTH(self, expr): ...
    def DAY(self, expr): ...
    def HOUR(self, expr): ...
    def MINUTE(self, expr): ...
    def SECOND(self, expr): ...
    def RANDOM(self): ...
    def RAWSQL(self, sql): ...
    def build_json_path(self, path): ...
    @classmethod
    def eval_json_path(cls, values: Iterable[int | str | types.EllipsisType | slice]) -> str: ...
    def JSON_QUERY(self, expr, path) -> None: ...
    def JSON_VALUE(self, expr, path, type) -> None: ...
    def JSON_NONZERO(self, expr) -> None: ...
    def JSON_CONCAT(self, left, right) -> None: ...
    def JSON_CONTAINS(self, expr, path, key) -> None: ...
    def JSON_ARRAY_LENGTH(self, value) -> None: ...
    def JSON_PARAM(self, expr): ...
    def ARRAY_INDEX(self, col, index) -> None: ...
    def ARRAY_CONTAINS(self, key, not_in, col) -> None: ...
    def ARRAY_SUBSET(self, array1, not_in, array2) -> None: ...
    def ARRAY_LENGTH(self, array) -> None: ...
    def ARRAY_SLICE(self, array, start, stop) -> None: ...
    def MAKE_ARRAY(self, *items) -> None: ...
