load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.cdsAgent",
    srcs = ["src"],
    iml_files = ["intellij.platform.cdsAgent.iml"],
    resources = ["resources"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/.idea/libraries:jetbrains-annotations"],
)
