from _typeshed import Incomplete

class Annoy:
    f: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def add_item(self, *args, **kwargs): ...
    def build(self, *args, **kwargs): ...
    def get_distance(self, *args, **kwargs): ...
    def get_item_vector(self, *args, **kwargs): ...
    def get_n_items(self, *args, **kwargs): ...
    def get_n_trees(self, *args, **kwargs): ...
    def get_nns_by_item(self, *args, **kwargs): ...
    def get_nns_by_vector(self, *args, **kwargs): ...
    def load(self, *args, **kwargs): ...
    def on_disk_build(self, *args, **kwargs): ...
    def save(self, *args, **kwargs): ...
    def set_seed(self, *args, **kwargs): ...
    def unbuild(self, *args, **kwargs): ...
    def unload(self, *args, **kwargs): ...
    def verbose(self, *args, **kwargs): ...
