load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "idea.vcs-log-graph-api",
    srcs = ["src"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//tools:idea.util-rt[module]",
        "//tools:idea.annotations[module]",
    ],
)
