java_import(
    name = "jgit",
    jars = ["jgit.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jackson-annotations-2.7.1",
    jars = ["jackson-annotations-2.7.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jackson-core-2.7.1",
    jars = ["jackson-core-2.7.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jackson-databind-2.7.1-1",
    jars = ["jackson-databind-2.7.1-1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
