# managed by go/iml_to_build
java_import(
    name = "jgit",
    jars = ["jgit.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jackson-annotations-2.8.1",
    jars = ["jackson-annotations-2.8.1.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jackson-core-2.8.1",
    jars = ["jackson-core-2.8.1.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jackson-databind-2.8.1",
    jars = ["jackson-databind-2.8.1.jar"],
    visibility = ["//visibility:public"],
)
