from .json import JSON
from .search import Search
from .timeseries import TimeSeries

class RedisModuleCommands:
    def json(self, encoder=..., decoder=...) -> JSON: ...
    def ft(self, index_name: str = ...) -> Search: ...
    def ts(self) -> TimeSeries: ...
