package icons;

import com.intellij.openapi.util.IconLoader;

import javax.swing.*;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class RestIcons {
  private static Icon load(String path) {
    return IconLoader.getIcon(path, RestIcons.class);
  }

  public static final Icon Rst = load("/icons/com/jetbrains/rest/rst.png"); // 16x16
}
