package com.intellij.xdebugger.impl.ui.attach.dialog.extensions

import org.jetbrains.annotations.ApiStatus

@ApiStatus.Experimental
interface XAttachDialogUiInvisibleDebuggerProvider

@ApiStatus.Experimental
interface XAttachDialogUiInvisiblePresentationGroup