from kafka.util import classproperty

from .data_container import DataContainer, SlotsBuilder

class JsonSchemaData(SlotsBuilder):
    def __new__(metacls, name, bases, attrs, **kw): ...
    def __init__(cls, name, bases, attrs, **kw) -> None: ...

class ApiData(DataContainer, metaclass=JsonSchemaData):
    def __init_subclass__(cls, **kw) -> None: ...
    def __init__(self, *args, **kwargs) -> None: ...
    @classproperty
    def name(cls): ...
    @classproperty
    def type(cls): ...
    @classproperty
    def json(cls): ...
    @classproperty
    def valid_versions(cls): ...
    @classproperty
    def min_version(cls): ...
    @classproperty
    def max_version(cls): ...
    @classmethod
    def flexible_version_q(cls, version): ...
    @classproperty
    def header_class(cls): ...
    def encode_header(self, flexible: bool = False): ...
    @classmethod
    def parse_header(cls, data): ...
    def encode(self, version=None, header: bool = True, framed: bool = False) -> bytes: ...
    @classmethod
    def decode(cls, data, version=None, header: bool = True, framed: bool = False): ...  # type: ignore[override]
