from typing_extensions import Self

from kafka.util import classproperty

from .api_data import JsonSchemaData
from .data_container import DataContainer

class VersionSubscriptable(type):
    def __init__(cls, name, bases, attrs, **kw) -> None: ...
    def __getitem__(cls, version): ...
    def __len__(cls): ...

class ApiMessageData(VersionSubscriptable, JsonSchemaData):
    def __init__(cls, name, bases, attrs, **kw) -> None: ...

class ApiMessage(DataContainer, metaclass=ApiMessageData):
    __slots__ = ("_header", "_min_version", "_max_version")
    def __init_subclass__(cls, **kw) -> None: ...
    def __new__(cls, *args, **kwargs) -> Self: ...
    def __init__(self, *args, **kwargs) -> None: ...
    @classproperty
    def name(cls): ...
    @classproperty
    def type(cls): ...
    @classproperty
    def API_KEY(cls): ...
    @classproperty
    def json(cls): ...
    @classproperty
    def valid_versions(cls): ...
    @classproperty
    def min_version(cls): ...
    @classproperty
    def max_version(cls): ...
    @classmethod
    def flexible_version_q(cls, version) -> bool: ...
    @classmethod
    def is_request(cls) -> bool: ...
    def expect_response(self): ...

    @property
    def API_VERSION(self): ...
    @API_VERSION.setter
    def API_VERSION(self, version): ...

    @property
    def header(self): ...
    @classproperty
    def header_class(cls): ...
    def with_header(self, correlation_id: int = 0, client_id: str = "kafka-python") -> None: ...
    def encode_header(self, flexible: bool = False): ...
    def encode_header_into(self, out, flexible: bool = False) -> None: ...
    @classmethod
    def parse_header(cls, data, version=None): ...
    @classmethod
    def encode_into__optimized_context(cls, version=None): ...
    def encode(self, version=None, header: bool = False, framed: bool = False): ...
    @classmethod
    def decode(cls, data, version=None, header: bool = False, framed: bool = False): ...  # type: ignore[override]
    def __eq__(self, other) -> bool: ...
