from _typeshed import Incomplete

class BrokerVersionData:
    __slots__ = ("broker_version", "api_versions")
    broker_version: Incomplete
    api_versions: Incomplete
    def __init__(self, broker_version=None, api_versions=None) -> None: ...
    def api_version(self, operation, min_version: int = 0, max_version: int = ...) -> int: ...
    @property
    def broker_version_str(self) -> str: ...
    def __eq__(self, other) -> bool: ...
    def __lt__(self, other) -> bool: ...
    def __le__(self, other) -> bool: ...
    def __gt__(self, other) -> bool: ...
    def __ge__(self, other) -> bool: ...

def infer_broker_version_from_api_versions(api_versions): ...

VERSION_CHECKS: tuple[tuple[tuple[int, ...], Incomplete], ...]
BROKER_API_VERSIONS: dict[tuple[int, ...], dict[int, tuple[int, ...]]]
