from _typeshed import Incomplete

log: Incomplete

class KafkaProtocol:
    in_flight_requests: Incomplete
    bytes_to_send: Incomplete
    def __init__(self, client_id=None, api_version=None) -> None: ...
    def send_request(self, request, correlation_id=None): ...
    def send_bytes(self): ...
    def receive_bytes(self, data): ...
