java_import(
    name = "gradle-reporting-3.1",
    jars = ["gradle-reporting-3.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-ear-3.1",
    jars = ["gradle-ear-3.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
