java_import(
    name = "gradle-workers-3.5",
    jars = ["gradle-workers-3.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-reporting-3.5",
    jars = ["gradle-reporting-3.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-ear-3.5",
    jars = ["gradle-ear-3.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
