load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.cucumber.jvmFormatter4",
    srcs = ["src"],
    iml_files = ["intellij.cucumber.jvmFormatter4.iml"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//prebuilts/tools/common/m2/repository/io/cucumber/cucumber-core/4.0.1:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/cucumber-expressions/6.1.0:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/cucumber-html/0.2.7:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/datatable-dependencies/1.1.3:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/datatable/1.1.3:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/gherkin/5.1.0:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/tag-expressions/1.1.1:jar",
        "//tools/idea/plugins/cucumber-jvm-formatter:intellij.cucumber.jvmFormatter[module]",
        "//tools/idea/plugins/cucumber-jvm-formatter3:intellij.cucumber.jvmFormatter3[module]",
    ],
)
