<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>yaws</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~E</string>
	<key>name</key>
	<string>HTML (Erlang)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(^\s*)?(?=&lt;erl&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.embedded.leading.html</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.embedded.block.erlang</string>
			<key>end</key>
			<string>(?!\G)(\s*\n)?</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.embedded.trailing.html</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)(erl)(&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.template.html</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.erlang</string>
					<key>end</key>
					<string>((&lt;/))(erl)(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.tag.template.html</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>source.erlang</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.html</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.erlang</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.erlang.yaws</string>
	<key>uuid</key>
	<string>3FBFF015-B650-4734-848C-47B53ACD5E32</string>
</dict>
</plist>
