classDiagram
  <fold text='class BankAccount {
  ...)
  }'>class BankAccount <fold text='{
    +String owner
  ...)
  }'>{
    +String owner
    +BigDecimal balance
    +deposit(amount)
    +withdrawal(amount)
  }</fold></fold>