stateDiagram-v2
  <fold text='State1: The state with...left.'>State1: The state with a note
  <fold text='note right of State1
 ... note'>note right of State1
    Important information! You can write
    notes. Important information! You can write
    notes.
  end note</fold>
  State1 --> State2
  note left of State2: This is the note to the left.</fold>