java_import(
    name = "plexus-utils-2.0.6",
    jars = ["plexus-utils-2.0.6.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "wadl-core",
    jars = ["wadl-core.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "plexus-archiver-2.4.4",
    jars = ["plexus-archiver-2.4.4.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "aether-1.1.0-all",
    jars = ["aether-1.1.0-all.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "maven-aether-provider-3.3.9-all",
    jars = ["maven-aether-provider-3.3.9-all.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
