# managed by go/iml_to_build
java_import(
    name = "plexus-utils-2.0.6",
    jars = ["plexus-utils-2.0.6.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "plexus-archiver-2.4.4",
    jars = ["plexus-archiver-2.4.4.jar"],
    visibility = ["//visibility:public"],
)
