java_import(
    name = "plexus-utils-2.0.6",
    jars = ["plexus-utils-2.0.6.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "plexus-archiver-2.4.4",
    jars = ["plexus-archiver-2.4.4.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
