java_import(
    name = "gradle-model-groovy-3.2",
    jars = ["gradle-model-groovy-3.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-wrapper-3.2",
    jars = ["gradle-wrapper-3.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-base-services-3.2",
    jars = ["gradle-base-services-3.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "guava-jdk5-17.0",
    jars = ["guava-jdk5-17.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "commons-io-2.2",
    jars = ["commons-io-2.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "commons-lang-2.6",
    jars = ["commons-lang-2.6.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-tooling-api-3.3",
    jars = ["gradle-tooling-api-3.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-core-3.3",
    jars = ["gradle-core-3.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-messaging-3.3",
    jars = ["gradle-messaging-3.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-model-core-3.3",
    jars = ["gradle-model-core-3.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-model-groovy-3.3",
    jars = ["gradle-model-groovy-3.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-wrapper-3.3",
    jars = ["gradle-wrapper-3.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-base-services-3.3",
    jars = ["gradle-base-services-3.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-base-services-groovy-3.3",
    jars = ["gradle-base-services-groovy-3.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-process-services-3.3",
    jars = ["gradle-process-services-3.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-resources-3.3",
    jars = ["gradle-resources-3.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-cli-3.3",
    jars = ["gradle-cli-3.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-logging-3.3",
    jars = ["gradle-logging-3.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-version-info-3.3",
    jars = ["gradle-version-info-3.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-native-3.3",
    jars = ["gradle-native-3.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-0.12",
    jars = ["native-platform-0.12.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-freebsd-amd64-libcpp-0.12",
    jars = ["native-platform-freebsd-amd64-libcpp-0.12.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-freebsd-amd64-libstdcpp-0.12",
    jars = ["native-platform-freebsd-amd64-libstdcpp-0.12.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-freebsd-i386-libcpp-0.12",
    jars = ["native-platform-freebsd-i386-libcpp-0.12.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-freebsd-i386-libstdcpp-0.12",
    jars = ["native-platform-freebsd-i386-libstdcpp-0.12.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-linux-amd64-0.12",
    jars = ["native-platform-linux-amd64-0.12.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-linux-amd64-ncurses5-0.12",
    jars = ["native-platform-linux-amd64-ncurses5-0.12.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-linux-amd64-ncurses6-0.12",
    jars = ["native-platform-linux-amd64-ncurses6-0.12.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-linux-i386-0.12",
    jars = ["native-platform-linux-i386-0.12.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-linux-i386-ncurses5-0.12",
    jars = ["native-platform-linux-i386-ncurses5-0.12.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-linux-i386-ncurses6-0.12",
    jars = ["native-platform-linux-i386-ncurses6-0.12.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-osx-amd64-0.12",
    jars = ["native-platform-osx-amd64-0.12.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-osx-i386-0.12",
    jars = ["native-platform-osx-i386-0.12.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-windows-amd64-0.12",
    jars = ["native-platform-windows-amd64-0.12.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-windows-i386-0.12",
    jars = ["native-platform-windows-i386-0.12.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jansi-1.14",
    jars = ["jansi-1.14.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
