java_import(
    name = "guava-jdk5-17.0",
    jars = ["guava-jdk5-17.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "commons-io-2.2",
    jars = ["commons-io-2.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "commons-lang-2.6",
    jars = ["commons-lang-2.6.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-0.14",
    jars = ["native-platform-0.14.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-freebsd-amd64-libcpp-0.14",
    jars = ["native-platform-freebsd-amd64-libcpp-0.14.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-freebsd-amd64-libstdcpp-0.14",
    jars = ["native-platform-freebsd-amd64-libstdcpp-0.14.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-freebsd-i386-libcpp-0.14",
    jars = ["native-platform-freebsd-i386-libcpp-0.14.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-freebsd-i386-libstdcpp-0.14",
    jars = ["native-platform-freebsd-i386-libstdcpp-0.14.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-linux-amd64-0.14",
    jars = ["native-platform-linux-amd64-0.14.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-linux-amd64-ncurses5-0.14",
    jars = ["native-platform-linux-amd64-ncurses5-0.14.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-linux-amd64-ncurses6-0.14",
    jars = ["native-platform-linux-amd64-ncurses6-0.14.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-linux-i386-0.14",
    jars = ["native-platform-linux-i386-0.14.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-linux-i386-ncurses5-0.14",
    jars = ["native-platform-linux-i386-ncurses5-0.14.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-linux-i386-ncurses6-0.14",
    jars = ["native-platform-linux-i386-ncurses6-0.14.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-osx-amd64-0.14",
    jars = ["native-platform-osx-amd64-0.14.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-osx-i386-0.14",
    jars = ["native-platform-osx-i386-0.14.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-windows-amd64-0.14",
    jars = ["native-platform-windows-amd64-0.14.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "native-platform-windows-i386-0.14",
    jars = ["native-platform-windows-i386-0.14.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jansi-1.14",
    jars = ["jansi-1.14.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-base-services-4.0",
    jars = ["gradle-base-services-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-base-services-groovy-4.0",
    jars = ["gradle-base-services-groovy-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-cli-4.0",
    jars = ["gradle-cli-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-core-4.0",
    jars = ["gradle-core-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-launcher-4.0",
    jars = ["gradle-launcher-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-logging-4.0",
    jars = ["gradle-logging-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-messaging-4.0",
    jars = ["gradle-messaging-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-model-core-4.0",
    jars = ["gradle-model-core-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-model-groovy-4.0",
    jars = ["gradle-model-groovy-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-process-services-4.0",
    jars = ["gradle-process-services-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-resources-4.0",
    jars = ["gradle-resources-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-tooling-api-4.0",
    jars = ["gradle-tooling-api-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-wrapper-4.0",
    jars = ["gradle-wrapper-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-native-4.0",
    jars = ["gradle-native-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
