java_import(
    name = "commons-io-2.2",
    jars = ["commons-io-2.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "commons-lang-2.6",
    jars = ["commons-lang-2.6.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-launcher-4.0",
    jars = ["gradle-launcher-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-wrapper-4.0",
    jars = ["gradle-wrapper-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-api-4.0",
    jars = ["gradle-api-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
