// Copyright 2000-2021 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE file.
package org.jetbrains.plugins.github.api

object GHGQLQueries {
  const val findOrganizationTeams = "findOrganizationTeams"
  const val findRepository = "findRepository"
  const val getProtectionRules = "getProtectionRules"
  const val commentBody = "commentBody"
  const val updateIssueComment = "updateIssueComment"
  const val deleteIssueComment = "deleteIssueComment"
  const val issueSearch = "issueSearch"
  const val createPullRequest = "createPullRequest"
  const val findPullRequest = "findPullRequest"
  const val findOpenPullRequestsByBranches = "findOpenPullRequestsByBranches"
  const val updatePullRequest = "updatePullRequest"
  const val markPullRequestReadyForReview = "markPullRequestReadyForReview"
  const val pullRequestTimeline = "pullRequestTimeline"
  const val pullRequestReviewThreads = "pullRequestReviewThreads"
  const val pullRequestCommits = "pullRequestCommits"
  const val pullRequestMergeabilityData = "findPullRequestMergeability"
  const val createReview = "createReview"
  const val submitReview = "submitReview"
  const val updateReview = "updateReview"
  const val deleteReview = "deleteReview"
  const val pendingReview = "findPendingReview"
  const val addReviewComment = "addReviewComment"
  const val deleteReviewComment = "deleteReviewComment"
  const val updateReviewComment = "updateReviewComment"
  const val addPullRequestReviewThread = "addPullRequestReviewThread"
  const val resolveReviewThread = "resolveReviewThread"
  const val unresolveReviewThread = "unresolveReviewThread"
}