load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "intellij.java.resources.en",
    srcs = ["src"],
    iml_files = ["intellij.java.resources.en.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
