load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "resources-en",
    srcs = ["src"],
    iml_files = ["resources-en.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
