version = "0.13.*"
upstream-repository = "https://github.com/geopandas/pyogrio"
# Requires a version of numpy with a `py.typed` file
dependencies = ["numpy>=1.20"]
optional-dependencies = ["types-geopandas"]
