load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.cucumber.jvmFormatter5",
    srcs = ["src"],
    iml_files = ["intellij.cucumber.jvmFormatter5.iml"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//tools/idea/plugins/cucumber-jvm-formatter:intellij.cucumber.jvmFormatter[module]",
        "//prebuilts/tools/common/m2/repository/io/cucumber/cucumber-core/5.0.0-RC1:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/cucumber-expressions/8.0.0:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/cucumber-java/5.0.0-RC1:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/cucumber-plugin/5.0.0-RC1:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/datatable-dependencies/3.0.0:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/datatable/3.0.0:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/docstring/5.0.0-RC1:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/gherkin-jvm-deps/1.0.6:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/gherkin/5.2.0:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/tag-expressions/2.0.2:jar",
        "//prebuilts/tools/common/m2/repository/org/apiguardian/apiguardian-api/1.1.0:jar",
        "//prebuilts/tools/common/m2/repository/org/hamcrest/hamcrest-core/2.1:jar",
        "//prebuilts/tools/common/m2/repository/org/hamcrest/hamcrest-library/2.1:jar",
        "//prebuilts/tools/common/m2/repository/org/hamcrest/hamcrest/2.1:jar",
    ],
)
