java_import(
    name = "optimizedFileManager",
    jars = ["optimizedFileManager.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "ant-build",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)
