java_import(
    name = "optimizedFileManager",
    jars = ["optimizedFileManager.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "jars",
    srcs = glob(["*.jar"]),
    visibility = ["//visibility:public"],
)
