version = "12.1.*"
extra_description = """\
  Type hints for GDB's \
  [Python API](https://sourceware.org/gdb/onlinedocs/gdb/Python-API.html). \
  Note that this API is available only when running Python scripts under GDB: \
  is is not possible to install the `gdb` package separately, for instance \
  using `pip`.\
"""

[tool.stubtest]
# Since the "gdb" Python package is available only inside GDB, it is not
# possible to install it through pip, so stub tests cannot install it.
skip = true
