from _typeshed import Incomplete
from enum import IntEnum

from kafka.producer.future import FutureProduceResult

class FinalState(IntEnum):
    ABORTED = 0
    FAILED = 1
    SUCCEEDED = 2

class ProducerBatch:
    max_record_size: int
    created: float
    drained: Incomplete | None
    attempts: int
    last_attempt: float
    last_append: float
    records: Incomplete
    topic_partition: Incomplete
    produce_future: FutureProduceResult
    def __init__(self, tp, records, now: float | None = None) -> None: ...
    @property
    def final_state(self): ...
    @property
    def record_count(self): ...
    @property
    def producer_id(self): ...
    @property
    def producer_epoch(self): ...
    @property
    def base_sequence(self): ...
    @property
    def has_sequence(self) -> bool: ...
    def try_append(self, timestamp_ms, key, value, headers, now=None): ...
    def abort(self, exception) -> None: ...
    def complete(self, base_offset, log_append_time) -> bool: ...
    def complete_exceptionally(self, top_level_exception, record_exceptions_fn) -> bool: ...
    def done(self, base_offset=None, timestamp_ms=None, top_level_exception=None, record_exceptions_fn=None) -> bool: ...
    def has_reached_delivery_timeout(self, delivery_timeout_ms, now=None) -> bool: ...
    def in_retry(self) -> bool: ...
    def retry(self, now=None) -> None: ...
    @property
    def is_done(self) -> bool: ...
    def __lt__(self, other) -> bool: ...
