from _typeshed import Incomplete

class AtomicInteger:
    def __init__(self, val: int = 0) -> None: ...
    def increment(self): ...
    def decrement(self): ...
    def get(self): ...

class RecordAccumulator:
    DEFAULT_CONFIG: dict[str, Incomplete]
    config: dict[str, Incomplete]
    muted: set[Incomplete]
    def __init__(self, **configs) -> None: ...
    @property
    def delivery_timeout_ms(self): ...
    @property
    def next_expiry_time_ms(self) -> float: ...
    def append(self, tp, timestamp_ms, key, value, headers, now: float | None = None, abort_on_new_batch: bool = False): ...
    def reset_next_batch_expiry_time(self) -> None: ...
    def maybe_update_next_batch_expiry_time(self, batch) -> None: ...
    def expired_batches(self, now=None) -> list[Incomplete]: ...
    def split_and_reenqueue(self, batch, now: float | None = None) -> int: ...
    def reenqueue(self, batch, now=None) -> None: ...
    def ready(self, cluster, now: float | None = None): ...
    def has_undrained(self) -> bool: ...
    def drain_batches_for_one_node(self, cluster, node_id, max_size, now: float | None = None) -> list[Incomplete]: ...
    def drain(self, cluster, nodes, max_size, now: float | None = None): ...
    def deallocate(self, batch) -> None: ...
    def flush_in_progress(self) -> bool: ...
    def begin_flush(self) -> None: ...
    def await_flush_completion(self, timeout=None) -> None: ...
    @property
    def has_incomplete(self) -> bool: ...
    def abort_incomplete_batches(self) -> None: ...
    def abort_batches(self, error) -> None: ...
    def abort_undrained_batches(self, error) -> None: ...
    def close(self) -> None: ...

class IncompleteProducerBatches:
    def __init__(self) -> None: ...
    def add(self, batch) -> None: ...
    def remove(self, batch) -> None: ...
    def all(self) -> list[Incomplete]: ...
    def __bool__(self) -> bool: ...
    __nonzero__ = __bool__
