module(
  name = "rules_ij_plugin",
  version = "0.1",
)

# this is needed to refer KtJvmInfo; it uses the same version of rules_kotlin as in community/MODULE.bazel
bazel_dep(name = "rules_kotlin", version = "2.2.2")
archive_override(
    module_name = "rules_kotlin",
    sha256 = "cd26fd62ec0d026ad4d143dedfef3e6ca858a2d0be483f57109897b27069b2c3",
    strip_prefix = "rules_kotlin-4db4cd06b0ca11742f7dccec5e19fd642c5c2cb1",
    url = "https://github.com/JetBrains/rules_kotlin/archive/4db4cd06b0ca11742f7dccec5e19fd642c5c2cb1.zip",
)
