load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.java.debugger.memory.agent",
    srcs = ["src"],
    iml_files = ["intellij.java.debugger.memory.agent.iml"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//tools/idea/platform/util:intellij.platform.util[module]",
        "//tools/idea/.idea/libraries:debugger-memory-agent",
        "//tools/idea/.idea/libraries:commons-io",
        "//tools/idea/.idea/libraries:kotlin-stdlib-jdk8",
    ],
)
