import os
from pathlib import Path
from typing import TypeAlias

_PathCompatible: TypeAlias = str | os.PathLike[str]

def makedirs(
    name: _PathCompatible, mode: int = 0o777, exist_ok: bool = False, *, parent_mode: int | None = None
) -> None: ...
def safe_makedirs(name: _PathCompatible, mode: int = 0o777, exist_ok: bool = False) -> None: ...
def safe_join(base: _PathCompatible, *paths: _PathCompatible) -> str: ...
def symlinks_supported() -> bool: ...
def to_path(value: Path | str) -> Path: ...
