from pathlib import Path

from _typeshed import StrPath

def makedirs(name: StrPath, mode: int = 0o777, exist_ok: bool = False, *, parent_mode: int | None = None) -> None: ...
def safe_makedirs(name: StrPath, mode: int = 0o777, exist_ok: bool = False) -> None: ...
def safe_join(base: StrPath, *paths: StrPath) -> str: ...
def symlinks_supported() -> bool: ...
def to_path(value: Path | str) -> Path: ...
