# managed by go/iml_to_build
java_import(
    name = "axis-1.4",
    jars = ["axis-1.4.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "axis-jaxrpc-1.4",
    jars = ["axis-jaxrpc-1.4.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "wsdl4j-1.4",
    jars = ["wsdl4j-1.4.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "axis-saaj-1.3",
    jars = ["axis-saaj-1.3.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "json-path-0.8.0",
    jars = ["json-path-0.8.0.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "json-smart-1.1.1",
    jars = ["json-smart-1.1.1.jar"],
    visibility = ["//visibility:public"],
)
