load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.cucumber.jvmFormatter",
    srcs = ["src"],
    iml_files = ["intellij.cucumber.jvmFormatter.iml"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//tools/idea/.idea/libraries:cucumber-core",
        "//tools/idea/.idea/libraries:cucumber-core_2.0.1",
        "//tools/idea/plugins/junit_rt:intellij.junit.rt[module]",
        "//tools/idea/java/java-runtime:intellij.java.rt[module]",
        "//tools/idea/.idea/libraries:JUnit4",
    ],
)
