version = "6.3.2"
upstream-repository = "https://github.com/collective/icalendar"
dependencies = ["types-python-dateutil", "types-pytz"]
obsolete-since = "7.0.0" # Released on 2026-02-11

[tool.stubtest]
stubtest-dependencies = ["pytz"]
