load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "forms_rt",
    srcs = ["src"],
    iml_files = ["forms_rt.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
