load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.java.guiForms.rt",
    srcs = ["src"],
    iml_files = ["intellij.java.guiForms.rt.iml"],
    visibility = ["//visibility:public"],
)
