test_suite(
    name = "bazel_rules_tests",
    tests = [
        "//platform/build-scripts/bazel-rules/ij-plugin-packager/tests:ij-plugin-packager-tests",
        "@jps_to_bazel//:bazel-generator-integration-tests",
        "@jps_to_bazel//:kotlinc-project-defaults-tests",
    ],
    visibility = ["//visibility:public"],
)
