// Copyright 2000-2025 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

package org.jetbrains.kotlin.idea.k2.highlighting;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.idea.base.plugin.KotlinPluginMode;
import org.jetbrains.kotlin.idea.base.test.TestRoot;
import org.jetbrains.kotlin.idea.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.idea.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

/**
 * This class is generated by {@link org.jetbrains.kotlin.testGenerator.generator.TestGenerator}.
 * DO NOT MODIFY MANUALLY.
 */
@SuppressWarnings("all")
@TestRoot("highlighting/highlighting-k2")
@TestDataPath("$CONTENT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
@TestMetadata("../../idea/tests/testData/highlighterMetaInfoWithBundledCompilerPlugins")
public class K2BundledCompilerPluginsHighlightingMetaInfoTestGenerated extends AbstractK2BundledCompilerPluginsHighlightingMetaInfoTest {
    @java.lang.Override
    @org.jetbrains.annotations.NotNull
    public final KotlinPluginMode getPluginMode() {
        return KotlinPluginMode.K2;
    }

    private void runTest(String testDataFilePath) throws Exception {
        KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
    }

    @TestMetadata("allOpen.kt")
    public void testAllOpen() throws Exception {
        runTest("../../idea/tests/testData/highlighterMetaInfoWithBundledCompilerPlugins/allOpen.kt");
    }

    @TestMetadata("allOpen_from_KOTLIN_BUNDLED.kt")
    public void testAllOpen_from_KOTLIN_BUNDLED() throws Exception {
        runTest("../../idea/tests/testData/highlighterMetaInfoWithBundledCompilerPlugins/allOpen_from_KOTLIN_BUNDLED.kt");
    }

    @TestMetadata("allOpen_oldRegistrar.kt")
    public void testAllOpen_oldRegistrar() throws Exception {
        runTest("../../idea/tests/testData/highlighterMetaInfoWithBundledCompilerPlugins/allOpen_oldRegistrar.kt");
    }

    @TestMetadata("compose.kt")
    public void testCompose() throws Exception {
        runTest("../../idea/tests/testData/highlighterMetaInfoWithBundledCompilerPlugins/compose.kt");
    }

    @TestMetadata("composeAgainstOldBinaries.kt")
    public void testComposeAgainstOldBinaries() throws Exception {
        runTest("../../idea/tests/testData/highlighterMetaInfoWithBundledCompilerPlugins/composeAgainstOldBinaries.kt");
    }

    @TestMetadata("dataframe.kt")
    public void testDataframe() throws Exception {
        runTest("../../idea/tests/testData/highlighterMetaInfoWithBundledCompilerPlugins/dataframe.kt");
    }

    @TestMetadata("dataframe_from_KOTLIN_BUNDLED.kt")
    public void testDataframe_from_KOTLIN_BUNDLED() throws Exception {
        runTest("../../idea/tests/testData/highlighterMetaInfoWithBundledCompilerPlugins/dataframe_from_KOTLIN_BUNDLED.kt");
    }

    @TestMetadata("lombok.kt")
    public void testLombok() throws Exception {
        runTest("../../idea/tests/testData/highlighterMetaInfoWithBundledCompilerPlugins/lombok.kt");
    }

    @TestMetadata("parcelize.kt")
    public void testParcelize() throws Exception {
        runTest("../../idea/tests/testData/highlighterMetaInfoWithBundledCompilerPlugins/parcelize.kt");
    }

    @TestMetadata("samWithReceiver.kt")
    public void testSamWithReceiver() throws Exception {
        runTest("../../idea/tests/testData/highlighterMetaInfoWithBundledCompilerPlugins/samWithReceiver.kt");
    }

    @TestMetadata("serialize.kt")
    public void testSerialize() throws Exception {
        runTest("../../idea/tests/testData/highlighterMetaInfoWithBundledCompilerPlugins/serialize.kt");
    }

    @TestMetadata("serialize_classFromJar.kt")
    public void testSerialize_classFromJar() throws Exception {
        runTest("../../idea/tests/testData/highlighterMetaInfoWithBundledCompilerPlugins/serialize_classFromJar.kt");
    }

    @TestMetadata("serialize_importFromGeneratedCompanion.kt")
    public void testSerialize_importFromGeneratedCompanion() throws Exception {
        runTest("../../idea/tests/testData/highlighterMetaInfoWithBundledCompilerPlugins/serialize_importFromGeneratedCompanion.kt");
    }

    @TestMetadata("serialize_non_existing_jar_from_kotlinDistForIde.kt")
    public void testSerialize_non_existing_jar_from_kotlinDistForIde() throws Exception {
        runTest("../../idea/tests/testData/highlighterMetaInfoWithBundledCompilerPlugins/serialize_non_existing_jar_from_kotlinDistForIde.kt");
    }

    @TestMetadata("violationViaPrimaryConstructorPointer.kt")
    public void testViolationViaPrimaryConstructorPointer() throws Exception {
        runTest("../../idea/tests/testData/highlighterMetaInfoWithBundledCompilerPlugins/violationViaPrimaryConstructorPointer.kt");
    }
}
