import socket as _socket
from typing_extensions import Self

async def create_connection(net, host, port, socket_options=(), proxy_url=None, timeout_at=None): ...

class KafkaNetSocket:
    @classmethod
    def register_class(cls, klass) -> None: ...
    def __init_subclass__(cls, **kw) -> None: ...
    def __new__(cls, proxy_url=None) -> Self: ...
    def __init__(self, proxy_url=None) -> None: ...
    def dns_lookup(self, host, port, raise_error: bool = False): ...
    def socket(self, family=..., sock_type=..., proto=...) -> _socket.socket: ...
    async def connect(self, net, addrinfo, socket_options=(), timeout_at=None): ...
    async def sock_connect(self, net, sock, sockaddr, timeout_at=None): ...
    def connect_ex(self, sock, sockaddr): ...
