from collections.abc import Callable
from typing import Any

from django.utils.functional import _StrOrPromise
from typing_extensions import override

UNUSABLE_PASSWORD_PREFIX: str
UNUSABLE_PASSWORD_SUFFIX_LENGTH: int

def is_password_usable(encoded: str | None) -> bool: ...
def verify_password(password: str | None, encoded: str, preferred: str = ...) -> tuple[bool, bool]: ...
def check_password(password: str | None, encoded: str, setter: Callable | None = ..., preferred: str = ...) -> bool: ...
async def acheck_password(
    password: str | None, encoded: str, setter: Callable | None = ..., preferred: str = ...
) -> bool: ...
def make_password(password: str | None, salt: str | None = ..., hasher: str | BasePasswordHasher = ...) -> str: ...
def get_hashers() -> list[BasePasswordHasher]: ...
def get_hashers_by_algorithm() -> dict[str, BasePasswordHasher]: ...
def reset_hashers(*, setting: str, **kwargs: Any) -> None: ...
def get_hasher(algorithm: str | BasePasswordHasher = ...) -> BasePasswordHasher: ...
def identify_hasher(encoded: str) -> BasePasswordHasher: ...
def mask_hash(hash: str, show: int = ..., char: str = ...) -> str: ...
def must_update_salt(salt: str, expected_entropy: int) -> bool: ...

class BasePasswordHasher:
    algorithm: str | None
    library: str | tuple[str, str] | None
    salt_entropy: int
    def salt(self) -> str: ...
    def verify(self, password: str, encoded: str) -> bool: ...
    def encode(self, password: str, salt: str) -> str: ...
    def decode(self, encoded: str) -> dict[str, Any]: ...
    def safe_summary(self, encoded: str) -> dict[_StrOrPromise, Any]: ...
    def must_update(self, encoded: str) -> bool: ...
    def harden_runtime(self, password: str, encoded: str) -> None: ...

class PBKDF2PasswordHasher(BasePasswordHasher):
    iterations: int
    digest: Any
    @override
    def encode(self, password: str, salt: str, iterations: int | None = ...) -> str: ...
    @override
    def decode(self, encoded: str) -> dict[str, str | int]: ...

class PBKDF2SHA1PasswordHasher(PBKDF2PasswordHasher): ...

class Argon2PasswordHasher(BasePasswordHasher):
    time_cost: int
    memory_cost: int
    parallelism: int
    def params(self) -> Any: ...

class BCryptSHA256PasswordHasher(BasePasswordHasher):
    digest: Any
    rounds: int
    @override
    def decode(self, encoded: str) -> dict[str, str | int]: ...

class BCryptPasswordHasher(BCryptSHA256PasswordHasher): ...

class ScryptPasswordHasher(BasePasswordHasher):
    block_size: int
    maxmem: int
    parallelism: int
    work_factor: int
    @override
    def encode(
        self, password: str, salt: str, n: int | None = ..., r: int | None = ..., p: int | None = ...
    ) -> str: ...
    @override
    def decode(self, encoded: str) -> dict[str, str | int]: ...

class MD5PasswordHasher(BasePasswordHasher):
    @override
    def decode(self, encoded: str) -> dict[str, str]: ...
