load("@community//build:tests-options.bzl", "jps_test")
load("@community//platform/build-scripts/bazel-rules:dev_dist_content.bzl", "dev_dist_plugin_content")
load("@rules_jvm//:jvm.bzl", "jvm_library", "jvm_provided_library", "resourcegroup")

jps_test(
    name = "tests_test",
    timeout = "moderate",
    tags = ["community-aggregator"],
    runtime_deps = [":tests_test_lib"],
)

### skip generation section `test intellij.performanceTesting.tests`

### skip generation section `build intellij.performanceTesting`

jvm_provided_library(
    name = "libraries_cli-parser_provided",
    lib = "//libraries/cli-parser",
)

jvm_library(
    name = "performanceTesting",
    srcs = glob(
        [
            "src/**/*.kt",
            "src/**/*.java",
            "src/**/*.form",
        ],
        allow_empty = True,
    ),
    module_name = "intellij.performanceTesting",
    resource_strip_prefix = "resources",
    resources = glob(["resources/**/*"]),
    visibility = ["//visibility:public"],
    deps = [
        ":libraries_cli-parser_provided",
        "//jps/model-api:model",
        "//libraries/caffeine",
        "//libraries/fastutil",
        "//libraries/jackson/databind",
        "//libraries/jackson/jackson",
        "//libraries/jackson/module-kotlin:libraries-jackson-module-kotlin",
        "//libraries/jbr",
        "//libraries/kotlinx/coroutines/core",
        "//libraries/netty/buffer",
        "//libraries/netty/codec-http:libraries-netty-codec-http",
        "//libraries/opentelemetry",
        "//libraries/opentelemetry-semconv",
        "//libraries/oshi-core",
        "//platform/analysis-api:analysis",
        "//platform/analysis-impl",
        "//platform/code-style-api:codeStyle",
        "//platform/core-api:core",
        "//platform/core-impl",
        "//platform/core-ui",
        "//platform/diagnostic/startUpPerformanceReporter",
        "//platform/diagnostic/telemetry",
        "//platform/editor-ui-api:editor-ui",
        "//platform/editor-ui-ex:editor-ex",
        "//platform/eel-impl",
        "//platform/eel-provider",
        "//platform/execution",
        "//platform/execution-impl",
        "//platform/forms_rt:java-guiForms-rt",
        "//platform/ide-core",
        "//platform/ide-core-impl",
        "//platform/indexing-api:indexing",
        "//platform/indexing-impl",
        "//platform/lang-api:lang",
        "//platform/lang-core",
        "//platform/lang-impl",
        "//platform/platform-impl:ide-impl",
        "//platform/platform-impl/codeinsight-inline:ide-codeinsight-inline",
        "//platform/platform-impl/concurrency",
        "//platform/platform-impl/internal",
        "//platform/progress/shared:ide-progress",
        "//platform/projectModel-api:projectModel",
        "//platform/projectModel-impl",
        "//platform/refactoring",
        "//platform/remote-driver/client",
        "//platform/remote-driver/core:driver-impl",
        "//platform/remote-driver/model",
        "//platform/service-container",
        "//platform/statistics",
        "//platform/usageView",
        "//platform/usageView-impl",
        "//platform/util:util-ui",
        "//platform/util-ex",
        "//platform/util/concurrency",
        "//platform/xdebugger-api:debugger",
        "//platform/xdebugger-impl:debugger-impl",
        "//platform/xdebugger-impl/shared",
        "//platform/xdebugger-impl/ui",
        "//plugins/performanceTesting/event-bus:tools-ide-starter-bus",
        "@community//platform/welcome-screen",
        "@lib//:kotlin-stdlib",
    ],
)

jvm_library(
    name = "performanceTesting_test_lib",
    testonly = True,
    srcs = glob(
        [],
        allow_empty = True,
    ),
    module_name = "intellij.performanceTesting",
    visibility = ["//visibility:public"],
    runtime_deps = [
        ":performanceTesting",
        "//jps/model-api:model_test_lib",
        "//libraries/caffeine:caffeine_test_lib",
        "//libraries/cli-parser",
        "//libraries/cli-parser:cli-parser_test_lib",
        "//libraries/fastutil:fastutil_test_lib",
        "//libraries/jackson/databind:databind_test_lib",
        "//libraries/jackson/jackson:jackson_test_lib",
        "//libraries/jackson/module-kotlin:libraries-jackson-module-kotlin_test_lib",
        "//libraries/jbr:jbr_test_lib",
        "//libraries/kotlinx/coroutines/core:core_test_lib",
        "//libraries/netty/buffer:buffer_test_lib",
        "//libraries/netty/codec-http:libraries-netty-codec-http_test_lib",
        "//platform/analysis-api:analysis_test_lib",
        "//platform/analysis-impl:analysis-impl_test_lib",
        "//platform/code-style-api:codeStyle_test_lib",
        "//platform/core-api:core_test_lib",
        "//platform/core-impl:core-impl_test_lib",
        "//platform/core-ui:core-ui_test_lib",
        "//platform/diagnostic/startUpPerformanceReporter:startUpPerformanceReporter_test_lib",
        "//platform/diagnostic/telemetry:telemetry_test_lib",
        "//platform/editor-ui-api:editor-ui_test_lib",
        "//platform/editor-ui-ex:editor-ex_test_lib",
        "//platform/eel-provider:eel-provider_test_lib",
        "//platform/execution:execution_test_lib",
        "//platform/execution-impl:execution-impl_test_lib",
        "//platform/forms_rt:java-guiForms-rt_test_lib",
        "//platform/ide-core:ide-core_test_lib",
        "//platform/ide-core-impl:ide-core-impl_test_lib",
        "//platform/indexing-api:indexing_test_lib",
        "//platform/indexing-impl:indexing-impl_test_lib",
        "//platform/lang-api:lang_test_lib",
        "//platform/lang-core:lang-core_test_lib",
        "//platform/lang-impl:lang-impl_test_lib",
        "//platform/platform-impl:ide-impl_test_lib",
        "//platform/platform-impl/codeinsight-inline:ide-codeinsight-inline_test_lib",
        "//platform/platform-impl/concurrency:concurrency_test_lib",
        "//platform/platform-impl/internal:internal_test_lib",
        "//platform/progress/shared:ide-progress_test_lib",
        "//platform/projectModel-api:projectModel_test_lib",
        "//platform/projectModel-impl:projectModel-impl_test_lib",
        "//platform/refactoring:refactoring_test_lib",
        "//platform/remote-driver/client:client_test_lib",
        "//platform/remote-driver/core:driver-impl_test_lib",
        "//platform/remote-driver/model:model_test_lib",
        "//platform/service-container:service-container_test_lib",
        "//platform/statistics:statistics_test_lib",
        "//platform/structure-view-impl:structureView_test_lib",
        "//platform/testFramework",
        "//platform/testFramework:testFramework_test_lib",
        "//platform/usageView:usageView_test_lib",
        "//platform/usageView-impl:usageView-impl_test_lib",
        "//platform/util:util-ui_test_lib",
        "//platform/util-ex:util-ex_test_lib",
        "//platform/util/concurrency:concurrency_test_lib",
        "//platform/xdebugger-api:debugger_test_lib",
        "//platform/xdebugger-impl:debugger-impl_test_lib",
        "//platform/xdebugger-impl/shared:shared_test_lib",
        "//platform/xdebugger-impl/ui:ui_test_lib",
        "//plugins/performanceTesting/backend",
        "//plugins/performanceTesting/event-bus:tools-ide-starter-bus_test_lib",
    ],
)

### auto-generated section `iml intellij.performanceTesting` start
exports_files(
    [
        "intellij.performanceTesting.iml",
        "resources/META-INF/plugin.xml",
        "plugin-content.yaml",
    ],
    visibility = ["//visibility:public"],
)
### auto-generated section `iml intellij.performanceTesting` end

### auto-generated section `dev content intellij.performanceTesting` start
dev_dist_plugin_content(
    name = "performanceTesting_dev_content",
    content_modules = [
        "//libraries/assertj-core",
        "//platform/remote-driver/client",
        "//platform/remote-driver/core:driver-impl",
        "//platform/remote-driver/model",
        "//plugins/performanceTesting/event-bus:tools-ide-starter-bus",
        "//plugins/performanceTesting/remote-driver",
    ],
    descriptor_module = ":performanceTesting",
    libraries = [
        "@lib//:com.fasterxml.jackson.core/jackson-core-2.19.0.jar",
        "@lib//:com.fasterxml.jackson.core/jackson-databind-2.19.0.jar",
        "@lib//:com.fasterxml.jackson.module/jackson-module-kotlin-2.19.0.jar",
        "@lib//:com.github.ben-manes.caffeine/caffeine-3.2.3.jar",
        "@lib//:com.github.oshi/oshi-core-6.9.2.jar",
        "@lib//:com.github.spullara.cli-parser/cli-parser-1.1.6.jar",
        "@lib//:com.google.errorprone/error_prone_annotations-2.43.0.jar",
        "@lib//:com.hankcs/aho-corasick-double-array-trie-1.2.3.jar",
        "@lib//:com.jetbrains.fus.reporting/ap-validation-all-2.0.242.jar",
        "@lib//:com.jetbrains.fus.reporting/fus-api-2.0.242.jar",
        "@lib//:com.jetbrains.fus.reporting/fus-api-jvm-2.0.242.jar",
        "@lib//:eawtstub.jar",
        "@lib//:io.netty/netty-buffer-4.2.16.Final.jar",
        "@lib//:io.netty/netty-codec-base-4.2.16.Final.jar",
        "@lib//:io.netty/netty-codec-compression-4.2.16.Final.jar",
        "@lib//:io.netty/netty-codec-http-4.2.16.Final.jar",
        "@lib//:io.netty/netty-codec-http2-4.2.16.Final.jar",
        "@lib//:io.netty/netty-common-4.2.16.Final.jar",
        "@lib//:io.netty/netty-handler-4.2.16.Final.jar",
        "@lib//:io.netty/netty-resolver-4.2.16.Final.jar",
        "@lib//:io.netty/netty-transport-4.2.16.Final.jar",
        "@lib//:io.netty/netty-transport-native-unix-common-4.2.16.Final.jar",
        "@lib//:io.opentelemetry.semconv/opentelemetry-semconv-1.30.0.jar",
        "@lib//:io.opentelemetry/opentelemetry-api-1.48.0.jar",
        "@lib//:io.opentelemetry/opentelemetry-context-1.48.0.jar",
        "@lib//:io.opentelemetry/opentelemetry-sdk-1.48.0.jar",
        "@lib//:io.opentelemetry/opentelemetry-sdk-common-1.48.0.jar",
        "@lib//:io.opentelemetry/opentelemetry-sdk-logs-1.48.0.jar",
        "@lib//:io.opentelemetry/opentelemetry-sdk-metrics-1.48.0.jar",
        "@lib//:io.opentelemetry/opentelemetry-sdk-trace-1.48.0.jar",
        "@lib//:org.apache.commons/commons-lang3-3.20.0.jar",
        "@lib//:org.assertj/assertj-core-4.0.0-M1.jar",
        "@lib//:org.assertj/assertj-swing-3.17.1.jar",
        "@lib//:org.jetbrains.diogen/diogen-analysis-0.5.0.jar",
        "@lib//:org.jetbrains.intellij.deps.fastutil/intellij-deps-fastutil-8.5.18-jb1.jar",
        "@lib//:org.jetbrains.intellij.deps.kotlinx/kotlinx-coroutines-core-jvm-1.10.2-intellij-2.jar",
        "@lib//:org.jetbrains.intellij.deps/intellij-deps-java-atk-wrapper-263.33.jar",
        "@lib//:org.jetbrains.kotlin/kotlin-reflect-2.4.10-RC2.jar",
        "@lib//:org.jetbrains.kotlin/kotlin-stdlib-2.4.10-RC2.jar",
        "@lib//:org.jetbrains.runtime/jbr-api-1.9.0.jar",
        "@lib//:org.jetbrains/annotations-26.0.2.jar",
        "@lib//:org.jmock/jmock-2.5.1.jar",
        "@lib//:org.jsoup/jsoup-1.22.1.jar",
        "@lib//:org.jspecify/jspecify-1.0.0.jar",
        "@lib//:org.slf4j/log4j-over-slf4j-1.7.36.jar",
        "@lib//:org.slf4j/slf4j-api-2.0.13.jar",
        "@lib//:org.slf4j/slf4j-jdk14-2.0.13.jar",
    ],
    prepacked_content_modules = {
        "//plugins/performanceTesting/backend": "modules/intellij.performanceTesting.backend.jar",
        "//plugins/performanceTesting/freezes": "modules/intellij.performanceTesting.freezes.jar",
        "//plugins/performanceTesting/frontend": "modules/intellij.performanceTesting.frontend.jar",
        "//plugins/performanceTesting/problemsView": "modules/intellij.performanceTesting.problemsView.jar",
        "//plugins/performanceTesting/remote-driver.compose": "modules/intellij.performanceTesting.remoteDriver.compose.jar",
        "//plugins/performanceTesting/remote-driver.jcef": "modules/intellij.performanceTesting.remoteDriver.jcef.jar",
        "//plugins/performanceTesting/structureView": "modules/intellij.performanceTesting.structureView.jar",
        "//plugins/performanceTesting/vcs": "modules/intellij.performanceTesting.vcs.jar",
    },
    visibility = ["//visibility:public"],
)
### auto-generated section `dev content intellij.performanceTesting` end

### auto-generated section `build intellij.performanceTesting.tests` start
jvm_library(
    name = "tests",
    srcs = glob(
        [],
        allow_empty = True,
    ),
    module_name = "intellij.performanceTesting.tests",
    visibility = ["//visibility:public"],
)

jvm_library(
    name = "tests_test_lib",
    testonly = True,
    srcs = glob(
        [
            "testSrc/**/*.kt",
            "testSrc/**/*.java",
            "testSrc/**/*.form",
        ],
        allow_empty = True,
    ),
    associates = [
        "//plugins/performanceTesting/core:performanceTesting",
        "//plugins/performanceTesting/core:performanceTesting_test_lib",
    ],
    resource_strip_prefix = "testResources",
    resources = glob(
        ["testResources/**/*"],
    ),
    visibility = ["//visibility:public"],
    runtime_deps = [
        # do not sort,
        ":tests",
        "//platform/platform-impl/concurrency:concurrency_test_lib",
        "//platform/ide-core-impl:ide-core-impl_test_lib",
        "//platform/platform-impl/codeinsight-inline:ide-codeinsight-inline_test_lib",
        "//platform/platform-impl/internal:internal_test_lib",
        "//platform/platform-impl:ide-impl_test_lib",
    ],
    deps = [
        # do not sort,
        "@lib//:kotlin-stdlib",
        "//platform/diagnostic/freezeAnalyzer",
        "//platform/diagnostic/freezeAnalyzer:freezeAnalyzer_test_lib",
        "//platform/remote-driver/model",
        "//platform/remote-driver/model:model_test_lib",
        "//platform/analysis-api:analysis",
        "//platform/analysis-api:analysis_test_lib",
        "//platform/code-style-api:codeStyle",
        "//platform/code-style-api:codeStyle_test_lib",
        "//platform/util/concurrency",
        "//platform/util/concurrency:concurrency_test_lib",
        "//platform/core-api:core",
        "//platform/core-api:core_test_lib",
        "//platform/core-impl",
        "//platform/core-impl:core-impl_test_lib",
        "//platform/projectModel-impl",
        "//platform/projectModel-impl:projectModel-impl_test_lib",
        "//platform/editor-ui-api:editor-ui",
        "//platform/editor-ui-api:editor-ui_test_lib",
        "//platform/indexing-api:indexing",
        "//platform/indexing-api:indexing_test_lib",
        "//platform/indexing-impl",
        "//platform/indexing-impl:indexing-impl_test_lib",
        "//jps/model-api:model",
        "//jps/model-api:model_test_lib",
        "//platform/lang-api:lang",
        "//platform/lang-api:lang_test_lib",
        "//platform/lang-core",
        "//platform/lang-core:lang-core_test_lib",
        "//platform/lang-impl",
        "//platform/lang-impl:lang-impl_test_lib",
        "//libraries/cli-parser",
        "//libraries/cli-parser:cli-parser_test_lib",
        "//platform/projectModel-api:projectModel",
        "//platform/projectModel-api:projectModel_test_lib",
        "//platform/platform-impl/concurrency",
        "//platform/testFramework",
        "//platform/testFramework:testFramework_test_lib",
        "//platform/usageView",
        "//platform/usageView:usageView_test_lib",
        "//libraries/jackson/jackson",
        "//libraries/jackson/jackson:jackson_test_lib",
        "//libraries/jackson/module-kotlin:libraries-jackson-module-kotlin",
        "//libraries/jackson/module-kotlin:libraries-jackson-module-kotlin_test_lib",
        "//platform/refactoring",
        "//platform/refactoring:refactoring_test_lib",
        "//platform/analysis-impl",
        "//platform/analysis-impl:analysis-impl_test_lib",
        "//libraries/jackson/databind",
        "//libraries/jackson/databind:databind_test_lib",
        "//platform/editor-ui-ex:editor-ex",
        "//platform/editor-ui-ex:editor-ex_test_lib",
        "//platform/ide-core-impl",
        "//platform/core-ui",
        "//platform/core-ui:core-ui_test_lib",
        "//platform/platform-impl/codeinsight-inline:ide-codeinsight-inline",
        "//platform/statistics",
        "//platform/statistics:statistics_test_lib",
        "//platform/execution-impl",
        "//platform/execution-impl:execution-impl_test_lib",
        "//platform/util-ex",
        "//platform/util-ex:util-ex_test_lib",
        "//platform/platform-impl/internal",
        "//libraries/opentelemetry",
        "//libraries/opentelemetry:opentelemetry_test_lib",
        "//libraries/opentelemetry-semconv",
        "//libraries/opentelemetry-semconv:opentelemetry-semconv_test_lib",
        "//libraries/kotlinx/coroutines/core",
        "//libraries/kotlinx/coroutines/core:core_test_lib",
        "//platform/diagnostic/telemetry",
        "//platform/diagnostic/telemetry:telemetry_test_lib",
        "//platform/platform-impl:ide-impl",
        "//libraries/fastutil",
        "//libraries/fastutil:fastutil_test_lib",
        "//platform/xdebugger-api:debugger",
        "//platform/xdebugger-api:debugger_test_lib",
        "//platform/xdebugger-impl:debugger-impl",
        "//platform/xdebugger-impl:debugger-impl_test_lib",
        "//libraries/caffeine",
        "//libraries/caffeine:caffeine_test_lib",
        "//platform/remote-driver/core:driver-impl",
        "//platform/remote-driver/core:driver-impl_test_lib",
        "//libraries/netty/codec-http:libraries-netty-codec-http",
        "//libraries/netty/codec-http:libraries-netty-codec-http_test_lib",
        "//libraries/netty/buffer",
        "//libraries/netty/buffer:buffer_test_lib",
        "//platform/diagnostic/startUpPerformanceReporter",
        "//platform/diagnostic/startUpPerformanceReporter:startUpPerformanceReporter_test_lib",
        "//platform/service-container",
        "//platform/service-container:service-container_test_lib",
        "//platform/remote-driver/client",
        "//platform/remote-driver/client:client_test_lib",
        "//platform/usageView-impl",
        "//platform/usageView-impl:usageView-impl_test_lib",
        "//plugins/performanceTesting/event-bus:tools-ide-starter-bus",
        "//plugins/performanceTesting/event-bus:tools-ide-starter-bus_test_lib",
        "//platform/eel-provider",
        "//platform/eel-provider:eel-provider_test_lib",
        "//libraries/jbr",
        "//libraries/jbr:jbr_test_lib",
        "//libraries/oshi-core",
        "//libraries/oshi-core:oshi-core_test_lib",
        "//platform/execution",
        "//platform/execution:execution_test_lib",
        "//platform/forms_rt:java-guiForms-rt",
        "//platform/forms_rt:java-guiForms-rt_test_lib",
        "//platform/xdebugger-impl/shared",
        "//platform/xdebugger-impl/shared:shared_test_lib",
        "//platform/xdebugger-impl/ui",
        "//platform/xdebugger-impl/ui:ui_test_lib",
        "//platform/structure-view-impl:structureView",
        "//platform/structure-view-impl:structureView_test_lib",
        "//platform/testFramework/teamCity",
        "//platform/testFramework/teamCity:teamCity_test_lib",
        "//plugins/performanceTesting/freezes",
        "//plugins/performanceTesting/freezes:freezes_test_lib",
        "//libraries/junit4",
        "//libraries/junit4:junit4_test_lib",
        "//libraries/junit5",
        "//libraries/junit5:junit5_test_lib",
        "//libraries/junit5-params",
        "//libraries/junit5-params:junit5-params_test_lib",
        "//libraries/misc/plugin",
        "//libraries/misc/plugin:plugin_test_lib",
    ],
)
### auto-generated section `build intellij.performanceTesting.tests` end

### auto-generated section `iml intellij.performanceTesting.tests` start
exports_files(
    [
        "intellij.performanceTesting.tests.iml",
    ],
    visibility = ["//visibility:public"],
)
### auto-generated section `iml intellij.performanceTesting.tests` end
