package com.intellij.codeInspection.tests.kotlin.logging

class K2LoggingPlaceholderCountMatchesArgumentCountInspectionSlf4JTest : KotlinLoggingPlaceholderCountMatchesArgumentCountInspectionSlf4JTest() {
}