package com.intellij.codeInspection.tests.kotlin.logging

class K2LoggingConditionDisagreesWithLogLevelStatementInspectionTest : KotlinLoggingConditionDisagreesWithLogLevelStatementInspectionTest() {
}