load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "groovy-rt-constants",
    srcs = ["src"],
    iml_files = ["groovy-rt-constants.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
