load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "intellij.groovy.constants.rt",
    srcs = ["src"],
    iml_files = ["intellij.groovy.constants.rt.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
