load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "debugger-agent-storage",
    srcs = ["src"],
    iml_files = ["debugger-agent-storage.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
