load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.java.debugger.agent.storage",
    srcs = ["src"],
    iml_files = ["intellij.java.debugger.agent.storage.iml"],
    javacopts = ["-Xep:CollectionIncompatibleType:WARN"],
    visibility = ["//visibility:public"],
)
