// Generated by delombok at Wed Oct 02 19:12:43 GMT 2019

class CleanupName {
	void test() {
		Object o = "Hello World!";
		try {
			System.out.println(o);
		} finally {
			if (java.util.Collections.singletonList(o).get(0) != null) {
				o.toString();
			}
		}
	}

	void test2() {
		Object o = "Hello World too!";
		try {
			System.out.println(o);
		} finally {
			if (java.util.Collections.singletonList(o).get(0) != null) {
				o.toString();
			}
		}
	}
}
