load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "antlayout",
    srcs = ["src"],
    iml_files = ["antlayout.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/.idea/libraries:Ant"],
)
