load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "intellij.tools.jps.antTasks",
    srcs = ["src"],
    iml_files = ["intellij.tools.jps.antTasks.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/.idea/libraries:Ant"],
)
