load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.tools.jps.antTasks",
    srcs = ["src"],
    iml_files = ["intellij.tools.jps.antTasks.iml"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/.idea/libraries:Ant"],
)
