load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "util-rt",
    srcs = ["src"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/platform/annotations[module]"],
)
