load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.jps.model",
    srcs = ["src"],
    iml_files = ["intellij.platform.jps.model.iml"],
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/.idea/libraries:jetbrains-annotations-java5"],
    # do not sort: must match IML order
    deps = [
        "//tools/idea/platform/util:intellij.platform.util[module]",
        "//tools/idea/.idea/libraries:jetbrains-annotations-java5",
    ],
)
