// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package org.jetbrains.kotlin.fir.testGenerator.codeinsight

import org.jetbrains.kotlin.idea.k2.codeinsight.fixes.AbstractHighLevelQuickFixMultiFileTest
import org.jetbrains.kotlin.idea.k2.codeinsight.fixes.AbstractHighLevelQuickFixMultiModuleTest
import org.jetbrains.kotlin.idea.k2.codeinsight.fixes.AbstractHighLevelQuickFixTest
import org.jetbrains.kotlin.testGenerator.model.*
import org.jetbrains.kotlin.testGenerator.model.GroupCategory.*
import org.jetbrains.kotlin.testGenerator.model.Patterns.DIRECTORY
import org.jetbrains.kotlin.testGenerator.model.Patterns.KT_WITHOUT_DOTS

internal fun MutableTWorkspace.generateK2FixTests() {
    val idea = "idea/tests/testData/"
    testGroup("code-insight/fixes-k2/tests", category = QUICKFIXES, testDataPath = "../../..") {
        testClass<AbstractHighLevelQuickFixTest> {
            val pattern = Patterns.forRegex("^([\\w\\-_]+)\\.kt$")
            model("$idea/quickfix/abstract", pattern = pattern)
            model("$idea/quickfix/addExclExclCall", pattern = pattern)
            model("$idea/quickfix/addInitializer", pattern = pattern)
            model("$idea/quickfix/addPropertyAccessors", pattern = pattern)
            model("$idea/quickfix/addValVar", pattern = pattern)
            model("$idea/quickfix/autoImports", pattern = KT_WITHOUT_DOTS, isRecursive = true)
            model("$idea/quickfix/checkArguments", pattern = pattern, isRecursive = false)
            model("$idea/quickfix/conflictingImports", pattern = pattern)
            model("$idea/quickfix/expressions", pattern = pattern)
            model("$idea/quickfix/lateinit", pattern = pattern)
            model("$idea/quickfix/localVariableWithTypeParameters", pattern = pattern)
            model("$idea/quickfix/modifiers", pattern = pattern, isRecursive = false)
            model("$idea/quickfix/modifiers/addOpenToClassDeclaration", pattern = pattern)
            model("$idea/quickfix/modifiers/suspend", pattern = pattern)
            model("$idea/quickfix/nullables", pattern = pattern)
            model("$idea/quickfix/override", pattern = pattern, isRecursive = false)
            model("$idea/quickfix/override/typeMismatchOnOverride", pattern = pattern, isRecursive = false)
            model("$idea/quickfix/removeRedundantSpreadOperator", pattern = pattern)
            model("$idea/quickfix/replaceInfixOrOperatorCall", pattern = pattern)
            model("$idea/quickfix/replaceWithArrayCallInAnnotation", pattern = pattern)
            model("$idea/quickfix/replaceWithDotCall", pattern = pattern)
            model("$idea/quickfix/replaceWithSafeCall", pattern = pattern)
            model("$idea/quickfix/specifyVisibilityInExplicitApiMode", pattern = pattern)
            model("$idea/quickfix/supercalls", pattern = pattern)
            model("$idea/quickfix/surroundWithArrayOfForNamedArgumentsToVarargs", pattern = pattern)
            model("$idea/quickfix/variables/changeMutability", pattern = pattern, isRecursive = false)
            model("$idea/quickfix/variables/removeValVarFromParameter", pattern = pattern)
            model("$idea/quickfix/when", pattern = pattern)
            model("$idea/quickfix/wrapWithSafeLetCall", pattern = pattern)
            model("$idea/quickfix/typeAddition", pattern = pattern)
            model("$idea/quickfix/typeMismatch/casts", pattern = pattern)
            model("$idea/quickfix/typeMismatch/componentFunctionReturnTypeMismatch", pattern = pattern)
            model("$idea/quickfix/typeMismatch/parameterTypeMismatch", pattern = pattern)
            model("$idea/quickfix/typeMismatch/typeMismatchOnReturnedExpression", pattern = pattern)
            model("$idea/quickfix/typeMismatch/wrongPrimitive", pattern = pattern)
            model("$idea/quickfix/typeMismatch", isRecursive = false, pattern = pattern)
            model("$idea/quickfix/toString", pattern = pattern)
            model("$idea/quickfix/specifySuperType", pattern = pattern)
            model("$idea/quickfix/convertToBlockBody", pattern = pattern)
            model("$idea/quickfix/supertypeInitialization", pattern = pattern)
            model("$idea/quickfix/dataClassPrivateConstructor", pattern = pattern)
            model("$idea/quickfix/addAnnotationTarget", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addAnnotationUseSiteTarget", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addConstructorParameter", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addConstructorParameterFromSuperTypeCall", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addConversionCall", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addCrossinline", pattern = pattern)
            model("$idea/quickfix/addDataModifier", pattern = pattern)
            model("$idea/quickfix/addDefaultConstructor", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addElseBranchToIf", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addEmptyArgumentList", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addEqEqTrue", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addFunModifier", pattern = pattern)
            model("$idea/quickfix/addGenericUpperBound", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addInline", pattern = pattern)
            model("$idea/quickfix/addInlineToReifiedFunctionFix", pattern = pattern)
            model("$idea/quickfix/addIsToWhenCondition", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addJvmInline", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addJvmStaticAnnotation", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addNewLineAfterAnnotations", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addNoinline", pattern = pattern)
            model("$idea/quickfix/addReifiedToTypeParameterOfFunctionFix", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addReturnExpression", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addReturnToLastExpressionInFunction", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addReturnToUnusedLastExpressionInFunction", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addRunBeforeLambda", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addSemicolonBeforeLambdaExpression", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addSpreadOperatorForArrayAsVarargAfterSam", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addStarProjections", pattern = pattern)
            model("$idea/quickfix/addSuspend", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addTypeAnnotationToValueParameter", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addUnsafeVarianceAnnotation", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addValVar", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/addVarianceModifier", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/assignToProperty", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/callFromPublicInline", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/canBeParameter", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/canBePrimaryConstructorProperty", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/castDueToProgressionResolveChange", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/changeObjectToClass", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/changeSignature", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/changeSuperTypeListEntryTypeArgument", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/changeToLabeledReturn", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/changeToMutableCollection", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/changeToUseSpreadOperator", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/compilerError", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/convertCollectionLiteralToIntArrayOf", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/convertIllegalEscapeToUnicodeEscape", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/convertJavaInterfaceToClass", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/convertLateinitPropertyToNotNullDelegate", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/convertPropertyInitializerToGetter", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/convertToAnonymousObject", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/convertToIsArrayOfCall", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/createFromUsage", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/createLabel", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/declarationCantBeInlined", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/declaringJavaClass", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/decreaseVisibility", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/deprecatedJavaAnnotation", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/deprecatedSymbolUsage", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/equalityNotApplicable", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/final", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/foldTryCatch", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/functionWithLambdaExpressionBody", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/implement", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/importAlias", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/increaseVisibility", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/initializeWithConstructorParameter", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/inlineClass", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/inlineTypeParameterFix", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/insertDelegationCall", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/isEnumEntry", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/javaClassOnCompanion", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/kdocMissingDocumentation", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/leakingThis", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/libraries", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/makeConstructorParameterProperty", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/makePrivateAndOverrideMember", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/makeTypeParameterReified", pattern = pattern)
            model("$idea/quickfix/makeUpperBoundNonNullable", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/memberVisibilityCanBePrivate", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/migration", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/missingConstructorBrackets", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/moveMemberToCompanionObject", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/moveReceiverAnnotation", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/moveToConstructorParameters", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/moveToSealedParent", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/moveTypeAliasToTopLevel", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/obsoleteKotlinJsPackages", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/optIn", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/optimizeImports", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/platformClasses", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/platformTypesInspection", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/primitiveCastToConversion", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/properties", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/protectedInFinal", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/redundantConst", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/redundantFun", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/redundantIf", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/redundantInline", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/redundantLateinit", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/redundantModalityModifier", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/redundantSuspend", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/redundantVisibilityModifier", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/removeAnnotation", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/removeArgument", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/removeAtFromAnnotationArgument", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/removeDefaultParameterValue", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/removeFinalUpperBound", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/removeNoConstructor", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/removeRedundantAssignment", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/removeRedundantInitializer", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/removeRedundantLabel", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/removeSingleLambdaParameter", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/removeSuspend", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/removeToStringInStringTemplate", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/removeTypeVariance", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/removeUnused", pattern = pattern)
            model("$idea/quickfix/removeUnusedParameter", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/removeUnusedReceiver", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/removeUseSiteTarget", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/renameToRem", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/renameToUnderscore", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/renameUnresolvedReference", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/reorderParameters", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/replaceJvmFieldWithConst", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/restrictedRetentionForExpressionAnnotation", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/simplifyComparison", pattern = pattern)
            model("$idea/quickfix/smartCastImpossibleInIfThen", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/specifyOverrideExplicitly", pattern = pattern)
            model("$idea/quickfix/specifySuperExplicitly", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/specifyTypeExplicitly", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/superTypeIsExtensionType", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/suppress", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/surroundWithNullCheck", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/suspiciousCollectionReassignment", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/tooLongCharLiteralToString", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/typeImports", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/typeInferenceExpectedTypeMismatch", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/typeOfAnnotationMember", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/typeParameters", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/typeProjection", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/unnecessaryLateinit", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/unusedSuppressAnnotation", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/useFullyqualifiedCall", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/variables", pattern = pattern, isRecursive = false, isIgnored = true)
            model("$idea/quickfix/variables/changeToPropertyAccess", pattern = pattern, isRecursive = false, isIgnored = true)
            model("$idea/quickfix/variables/changeToFunctionInvocation", pattern = pattern, isRecursive = false, isIgnored = true)
            model("$idea/quickfix/wrapArgumentWithParentheses", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/wrapWhenExpressionInParentheses", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/wrongLongSuffix", pattern = pattern, isIgnored = true)
            model("$idea/quickfix/yieldUnsupported", pattern = pattern, isIgnored = true)
        }

        testClass<AbstractHighLevelQuickFixMultiFileTest> {
            model(
                "$idea/quickfix/autoImports",
                pattern = Patterns.forRegex("""^(\w+)\.((before\.Main\.\w+)|(test))$"""),
                testMethodName = "doTestWithExtraFile"
            )
        }

        testClass<AbstractHighLevelQuickFixMultiModuleTest> {
            model("$idea/multiModuleQuickFix", pattern = DIRECTORY, depth = 1)
        }
    }
}
