from _typeshed import Incomplete
from logging import Logger
from typing import Final, overload
from typing_extensions import deprecated

ASSERTION_TYPE: Final[str]
log: Logger

class JWTBearerClientAssertion:
    CLIENT_ASSERTION_TYPE: Final[str]
    CLIENT_AUTH_METHOD: Final[str]
    token_url: str | None
    leeway: int

    @overload
    @deprecated("The `token_url` parameter is deprecated. Override `get_audiences` instead.")
    def __init__(self, token_url: str = ..., validate_jti: bool = True, leeway: int = 60) -> None: ...
    @overload
    def __init__(self, token_url: None = None, validate_jti: bool = True, leeway: int = 60) -> None: ...

    def __call__(self, query_client, request): ...
    def verify_claims(self, claims: dict[str, Incomplete]) -> None: ...
    def get_audiences(self) -> list[str]: ...
    def process_assertion_claims(self, assertion, resolve_key) -> dict[str, Incomplete]: ...
    def authenticate_client(self, client): ...
    def extract_assertion(self, assertion: str) -> tuple[dict[str, Incomplete], Incomplete]: ...
    def validate_jti(self, claims, jti): ...
    def resolve_client_public_key(self, client): ...
