#  Copyright 2000-2025 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

from typing import AnyStr, Iterator

def glob(pathname: AnyStr) -> list[AnyStr]: ...
def iglob(pathname: AnyStr) -> Iterator[AnyStr]: ...
def glob1(dirname: str | unicode, pattern: AnyStr) -> list[AnyStr]: ...
def glob0(dirname: str | unicode, basename: AnyStr) -> list[AnyStr]: ...
def has_magic(s: str | unicode) -> bool: ...  # undocumented
