#  Copyright 2000-2025 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

from typing import Any, Text

_ModuleGlobals = dict[str, Any]

def getline(filename: Text, lineno: int, module_globals: _ModuleGlobals | None = ...) -> str: ...
def clearcache() -> None: ...
def getlines(filename: Text, module_globals: _ModuleGlobals | None = ...) -> list[str]: ...
def checkcache(filename: Text | None = ...) -> None: ...
def updatecache(filename: Text, module_globals: _ModuleGlobals | None = ...) -> list[str]: ...
