#  Copyright 2000-2025 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

from typing import AnyStr

def url2pathname(url: AnyStr) -> AnyStr: ...
def pathname2url(p: AnyStr) -> AnyStr: ...
