#  Copyright 2000-2025 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

class RobotFileParser:
    def set_url(self, url: str): ...
    def read(self): ...
    def parse(self, lines: str): ...
    def can_fetch(self, user_agent: str, url: str): ...
    def mtime(self): ...
    def modified(self): ...
