package com.intellij.searchEverywhereMl.semantics.contributors

import com.intellij.ide.actions.searcheverywhere.AllTabExcludedSearchEverywhereContributor
import org.jetbrains.annotations.ApiStatus

@ApiStatus.Internal
interface SemanticSearchEverywhereContributor: AllTabExcludedSearchEverywhereContributor