from collections.abc import Generator
from typing import Any

def dataframe_to_rows(df, index: bool = ..., header: bool = ...) -> Generator[Any, None, None]: ...
def expand_index(index, header: bool = ...) -> Generator[Any, None, None]: ...
