from typing import Any

class IndexedList(list[Any]):
    clean: bool
    def __init__(self, iterable: Any | None = ...) -> None: ...
    def __contains__(self, value): ...
    def index(self, value): ...
    def append(self, value) -> None: ...
    def add(self, value): ...
