load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "jshell-protocol",
    srcs = ["src"],
    iml_files = ["jshell-protocol.iml"],
    tags = ["managed"],
    test_srcs = ["testStrc"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/.idea/libraries:JUnit4[test]"],
)
