load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.java.jshell.protocol",
    srcs = ["src"],
    iml_files = ["intellij.java.jshell.protocol.iml"],
    test_srcs = ["testStrc"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/.idea/libraries:JUnit4[test]"],
)
