// Copyright 2000-2025 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

package org.jetbrains.kotlin.idea.compose.k2.debugger.test.cases;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.idea.base.plugin.KotlinPluginMode;
import org.jetbrains.kotlin.idea.base.test.TestRoot;
import org.jetbrains.kotlin.idea.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.idea.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

/**
 * This class is generated by {@link org.jetbrains.kotlin.testGenerator.generator.TestGenerator}.
 * DO NOT MODIFY MANUALLY.
 */
@SuppressWarnings("all")
@TestRoot("jvm-debugger/test/compose")
@TestDataPath("$CONTENT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
@TestMetadata("../testData/stepping/compose")
public class K2IdeK1CodeClassLambdaComposeSteppingTestGenerated extends AbstractK2IdeK1CodeClassLambdaComposeSteppingTest {
    @java.lang.Override
    @org.jetbrains.annotations.NotNull
    public final KotlinPluginMode getPluginMode() {
        return KotlinPluginMode.K2;
    }

    private void runTest(String testDataFilePath) throws Exception {
        KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
    }

    @TestMetadata("composableLambda.kt")
    public void testComposableLambda() throws Exception {
        runTest("../testData/stepping/compose/composableLambda.kt");
    }

    @TestMetadata("composeCompositionLocal.kt")
    public void testComposeCompositionLocal() throws Exception {
        runTest("../testData/stepping/compose/composeCompositionLocal.kt");
    }

    @TestMetadata("composeSideEffects.kt")
    public void testComposeSideEffects() throws Exception {
        runTest("../testData/stepping/compose/composeSideEffects.kt");
    }

    @TestMetadata("composeStatefulComponent.kt")
    public void testComposeStatefulComponent() throws Exception {
        runTest("../testData/stepping/compose/composeStatefulComponent.kt");
    }
}
