version = "8.2.*"
upstream-repository = "https://github.com/lincolnloop/python-qrcode"
# must be a version of Pillow that is py.typed
dependencies = ["Pillow>=10.3.0"]

[tool.stubtest]
extras = ["pil"]
