java_import(
    name = "svnkit",
    jars = ["svnkit.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "sequence-library",
    jars = ["sequence-library.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "sqljet",
    jars = ["sqljet.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "antlr",
    jars = ["antlr.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "svnkit-javahl",
    jars = ["svnkit-javahl.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jsch.agentproxy.svnkit-trilead-ssh2",
    jars = ["jsch.agentproxy.svnkit-trilead-ssh2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "licenses",
    srcs = glob(["licenses/**"]),
    visibility = ["//visibility:public"],
)
