import asyncio
from collections.abc import Iterable
from types import TracebackType
from typing import Any
from typing_extensions import Self

from pycurl._pycurl import Curl

class AsyncCurlMulti:
    def __init__(self, close_handles: bool = False) -> None: ...
    def setopt(self, option: int, value: Any) -> None: ...  # type of value depends on the option
    def add_handle(self, curl: Curl) -> asyncio.Future[Curl]: ...
    def remove_handle(self, curl: Curl) -> None: ...
    async def perform(self, curl: Curl) -> Curl: ...
    def futures(self, curls: Iterable[Curl] | None = None) -> tuple[asyncio.Future[Curl], ...]: ...
    @property
    def closed(self) -> bool: ...
    async def aclose(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: TracebackType | None
    ) -> None: ...
