from typing import Any

def compare_operation(
    dn, attribute, value, auto_encode, schema: Any | None = ..., validator: Any | None = ..., check_names: bool = ...
): ...
def compare_request_to_dict(request): ...
def compare_response_to_dict(response): ...
