jewel:
  EqualityMembersRule:
    active: true
    functionsToCheck:
      - equals
      - hashCode
      - toString
    annotated:
      - GenerateDataFunctions
  MissingApiStatusAnnotationRule:
    active: true
