from _typeshed import Incomplete
from socket import AddressFamily
from typing import Final

from kafka.future import Future
from kafka.protocol.metadata import CoordinatorType, MetadataRequest

class ClusterMetadata:
    DEFAULT_CONFIG: dict[str, Incomplete]
    need_all_topic_metadata: bool
    unauthorized_topics: Incomplete
    internal_topics: Incomplete
    controller: Incomplete
    cluster_id: Incomplete
    config: dict[str, Incomplete]
    closed: bool
    def __init__(self, **configs) -> None: ...
    @property
    def metadata_refresh_in_progress(self) -> bool: ...
    def attach(self, manager) -> None: ...
    def close(self) -> None: ...
    def start_refresh_loop(self) -> None: ...
    async def refresh_metadata(self, node_id=None) -> None: ...
    def is_bootstrap(self, node_id) -> bool: ...
    def set_topics(self, topics) -> Future: ...
    def add_topic(self, topic: str) -> Future: ...
    def brokers(self) -> list[Incomplete]: ...
    def bootstrap_brokers(self) -> list[Incomplete]: ...
    def broker_metadata(self, broker_id): ...
    def partitions_for_topic(self, topic): ...
    def available_partitions_for_topic(self, topic): ...
    def leader_for_partition(self, partition): ...
    def is_replica_node(self, partition, node_id): ...
    def leader_epoch_for_partition(self, partition): ...
    def update_partition_leader(self, partition, leader_id: int, leader_epoch: int) -> bool: ...
    def partitions_for_broker(self, broker_id): ...
    def get_coordinator(self, key: str, key_type: CoordinatorType = CoordinatorType.GROUP): ...
    def ttl(self): ...
    def refresh_backoff(self): ...
    def request_update(self) -> Future: ...
    @property
    def need_update(self) -> bool: ...
    def topics(self, exclude_internal_topics: bool = True): ...
    def metadata_request(self) -> MetadataRequest: ...
    def topic_id(self, topic_name): ...
    def topic_name_for_id(self, topic_id): ...
    def failed_update(self, exception) -> None: ...
    def update_metadata(self, metadata): ...
    def add_listener(self, listener) -> None: ...
    def remove_listener(self, listener) -> None: ...
    def add_coordinator(self, response, key_type: CoordinatorType, key: str, synthesize_node_id: bool = True): ...

def collect_hosts(hosts, randomize: bool = True) -> list[Incomplete]: ...
def expand_to_canonical_bootstrap_hosts(hosts) -> list[Incomplete]: ...

DEFAULT_KAFKA_PORT: Final = 9092

def get_ip_port_afi(host_and_port_str: str) -> tuple[str, int, AddressFamily]: ...
