from _typeshed import Incomplete
from collections.abc import Generator
from typing_extensions import Self

class Future:
    __slots__ = ("is_done", "value", "exception", "_callbacks", "_errbacks", "_lock")
    error_on_callbacks: bool
    is_done: bool
    value: Incomplete
    exception: Incomplete
    def __init__(self) -> None: ...
    def succeeded(self) -> bool: ...
    def failed(self) -> bool: ...
    def retriable(self) -> bool: ...
    def success(self, value) -> Self: ...
    def failure(self, e) -> Self: ...
    def add_callback(self, f, *args, **kwargs) -> Self: ...
    def add_errback(self, f, *args, **kwargs) -> Self: ...
    def add_both(self, f, *args, **kwargs) -> Self: ...
    def chain(self, future) -> Self: ...
    def __await__(self) -> Generator[Self]: ...
