// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

package org.jetbrains.kotlin.idea.k2.highlighting;

import com.intellij.idea.IJIgnore;
import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.idea.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.idea.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TestMetadata;
import org.jetbrains.kotlin.idea.base.test.TestRoot;
import org.junit.runner.RunWith;

/**
 * This class is generated by {@link org.jetbrains.kotlin.testGenerator.generator.TestGenerator}.
 * DO NOT MODIFY MANUALLY.
 */
@SuppressWarnings("all")
@TestRoot("gradle/gradle-java/tests.k2")
@TestDataPath("$CONTENT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public abstract class K2GradleBuildFileHighlightingTestGenerated extends AbstractK2GradleBuildFileHighlightingTest {
    @RunWith(JUnit3RunnerWithInners.class)
    @TestMetadata("../../../idea/tests/testData/gradle/highlighting/gradle8")
    public static class Gradle8 extends AbstractK2GradleBuildFileHighlightingTest {
        private void runTest(String testDataFilePath) throws Exception {
            KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
        }

        @Override
        protected void setUp() {
            gradleVersion = "8.6";
            super.setUp();
        }

        @TestMetadata("gradleSampleMultiProject")
        @IJIgnore(issue = "KTIJ-29790")
        public void testGradleSampleMultiProject() throws Exception {
            runTest("../../../idea/tests/testData/gradle/highlighting/gradle8/gradleSampleMultiProject/");
        }

        @TestMetadata("javaLibraryPlugin")
        public void testJavaLibraryPlugin() throws Exception {
            runTest("../../../idea/tests/testData/gradle/highlighting/gradle8/javaLibraryPlugin/");
        }

        @TestMetadata("wizardMultiAllTargets")
        @IJIgnore(issue = "KTIJ-29790")
        public void testWizardMultiAllTargets() throws Exception {
            runTest("../../../idea/tests/testData/gradle/highlighting/gradle8/wizardMultiAllTargets/");
        }

        @TestMetadata("wizardNativeUiMultiplatformApp")
        @IJIgnore(issue = "KTIJ-29790")
        public void testWizardNativeUiMultiplatformApp() throws Exception {
            runTest("../../../idea/tests/testData/gradle/highlighting/gradle8/wizardNativeUiMultiplatformApp/");
        }

        @TestMetadata("wizardSharedUiMultiplatformApp")
        @IJIgnore(issue = "KTIJ-29790")
        public void testWizardSharedUiMultiplatformApp() throws Exception {
            runTest("../../../idea/tests/testData/gradle/highlighting/gradle8/wizardSharedUiMultiplatformApp/");
        }

        @TestMetadata("wizardSimpleKotlinProject")
        public void testWizardSimpleKotlinProject() throws Exception {
            runTest("../../../idea/tests/testData/gradle/highlighting/gradle8/wizardSimpleKotlinProject/");
        }
    }

    @RunWith(JUnit3RunnerWithInners.class)
    @TestMetadata("../../../idea/tests/testData/gradle/highlighting/gradle7")
    public static class Gradle7 extends AbstractK2GradleBuildFileHighlightingTest {
        private void runTest(String testDataFilePath) throws Exception {
            KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
        }

        @Override
        protected void setUp() {
            gradleVersion = "7.6.4";
            super.setUp();
        }

        @TestMetadata("gradleSampleMultiProject")
        @IJIgnore(issue = "KTIJ-29790")
        public void testGradleSampleMultiProject() throws Exception {
            runTest("../../../idea/tests/testData/gradle/highlighting/gradle7/gradleSampleMultiProject/");
        }

        @TestMetadata("javaLibraryPlugin")
        public void testJavaLibraryPlugin() throws Exception {
            runTest("../../../idea/tests/testData/gradle/highlighting/gradle7/javaLibraryPlugin/");
        }

        @TestMetadata("wizardSimpleKotlinProject")
        @IJIgnore(issue = "KTIJ-29790")
        public void testWizardSimpleKotlinProject() throws Exception {
            runTest("../../../idea/tests/testData/gradle/highlighting/gradle7/wizardSimpleKotlinProject/");
        }
    }
}
