version = "0.1.30"
upstream_repository = "https://github.com/asweigart/pyscreeze"
requires = ["Pillow>=10.3.0"]

[tool.stubtest]
# Linux has extra constants, win32 has different definitions
platforms = ["linux", "win32"]
# PyScreeze has an odd setup.py file
# that doesn't list Pillow as a dependency for py312+ yet:
# https://github.com/asweigart/pyscreeze/blob/eeca245a135cf171c163b3691300138518efa64e/setup.py#L38-L46
stubtest_requirements = ["Pillow"]
