load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.cucumber.jvmFormatter3",
    srcs = ["src"],
    iml_files = ["intellij.cucumber.jvmFormatter3.iml"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//prebuilts/tools/common/m2/repository/io/cucumber/cucumber-core/3.0.2:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/cucumber-expressions/5.0.19:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/cucumber-html/0.2.7:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/datatable-dependencies/1.0.3:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/datatable/1.0.3:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/gherkin/5.0.0:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/tag-expressions/1.1.1:jar",
        "//tools/idea/plugins/cucumber-jvm-formatter:intellij.cucumber.jvmFormatter[module]",
    ],
)
