load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.cucumber.jvmFormatter3",
    srcs = ["src"],
    iml_files = ["intellij.cucumber.jvmFormatter3.iml"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//tools/idea/.idea/libraries:cucumber-core_3.0.2",
        "//tools/idea/plugins/cucumber-jvm-formatter:intellij.cucumber.jvmFormatter[module]",
    ],
)
