source.dockerfile;keyword.other.special-method.dockerfile: [0, 3], {RUN}
source.dockerfile: [3, 37], { find . -maxdepth 1 -type f -name }
source.dockerfile;string.quoted.double.dockerfile: [37, 38], {"}
source.dockerfile;string.quoted.double.dockerfile: [38, 41], {.*"}
source.dockerfile: [41, 51], { -exec rm }
source.dockerfile;string.quoted.double.dockerfile: [51, 52], {"}
source.dockerfile;string.quoted.double.dockerfile: [52, 55], {{}"}
source.dockerfile: [55, 59], { \;
}
source.dockerfile: [59, 60], {
}
source.dockerfile;comment.line.number-sign.dockerfile;punctuation.definition.comment.dockerfile: [60, 61], {#}
source.dockerfile;comment.line.number-sign.dockerfile: [61, 93], { Remove few other files manually}