{
  parserClass="com.github.firsttimeinforever.mermaid.lang.parser._MermaidParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
  psiClassPrefix="Mermaid"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.firsttimeinforever.mermaid.lang.psi"
  psiImplPackage="com.github.firsttimeinforever.mermaid.lang.psi.impl"
  elementTypeHolderClass="com.github.firsttimeinforever.mermaid.lang.parser.MermaidElements"
  elementTypeClass="com.github.firsttimeinforever.mermaid.lang.psi.MermaidElementType"
  tokenTypeClass="com.github.firsttimeinforever.mermaid.lang.lexer.MermaidToken"
  parserImports=[
    'static com.github.firsttimeinforever.mermaid.lang.lexer.MermaidTokens.*'
    'static com.github.firsttimeinforever.mermaid.lang.lexer.MermaidTokens.Pie.*'
    'static com.github.firsttimeinforever.mermaid.lang.lexer.MermaidTokens.Journey.*'
    'static com.github.firsttimeinforever.mermaid.lang.lexer.MermaidTokens.Flowchart.*'
    'static com.github.firsttimeinforever.mermaid.lang.lexer.MermaidTokens.Sequence.*'
    'static com.github.firsttimeinforever.mermaid.lang.lexer.MermaidTokens.ClassDiagram.*'
    'static com.github.firsttimeinforever.mermaid.lang.lexer.MermaidTokens.StateDiagram.*'
    'static com.github.firsttimeinforever.mermaid.lang.lexer.MermaidTokens.EntityRelationship.*'
    'static com.github.firsttimeinforever.mermaid.lang.lexer.MermaidTokens.Gantt.*'
    'static com.github.firsttimeinforever.mermaid.lang.lexer.MermaidTokens.Requirement.*'
    'static com.github.firsttimeinforever.mermaid.lang.lexer.MermaidTokens.GitGraph.*'
  ]
  generateTokens=false
}

file ::= start
private start ::= EOL start | directive start | diagram

private diagram ::= pieHeader pieDocument
	| JOURNEY journeyDocument
	| flowchartHeader flowchartDocument
	| SEQUENCE sequenceDocument
	| CLASS_DIAGRAM classDocument
	| STATE_DIAGRAM stateDocument
	| ENTITY_RELATIONSHIP erDocument
	| GANTT ganttDocument
	| REQUIREMENT_DIAGRAM requirementDocument
	| GIT_GRAPH gitGraphDocument

titleStatement ::= TITLE complexTitleValue
complexTitleValue ::= TITLE_VALUE+

pieHeader ::= PIE [showDataRec]
private showDataRec ::= EOL showDataRec | SHOW_DATA


pieDocument ::= pieLines
private pieLines ::= pieLine [pieLines]
private pieLine ::= pieStatement [EOL] | EOL
pieStatement ::= string COLON VALUE
	| titleStatement
	| directive


journeyDocument ::= journeyLines
private journeyLines ::= (journeyLine | IGNORED) [journeyLines]
private journeyLine ::= journeyStatement [EOL] | EOL
journeyStatement ::= journeyDataStatement
	| journeySectionStatement
	| titleStatement
	| directive

journeyDataStatement ::= complexTaskName COLON (IGNORED | recTaskData (COLON recTaskData)+)

journeySectionStatement ::= SECTION complexSectionTitle journeySectionDocument
journeySectionDocument ::= journeySectionLines
private journeySectionLines ::= (journeySectionLine | IGNORED) [journeySectionLines]
private journeySectionLine ::= journeySectionInnerStatement [EOL] | EOL
journeySectionInnerStatement ::= journeyDataStatement

complexSectionTitle ::= SECTION_TITLE+
complexTaskName ::= TASK_NAME+
complexTaskData ::= TASK_DATA+
private recTaskData ::= complexTaskData [COMMA recTaskData]

flowchartHeader ::= FLOWCHART [DIR]

flowchartDocument ::= flowchartLines
private flowchartLines ::= (flowchartLine | IGNORED) [flowchartLines]
private flowchartLine ::= flowchartStatement [separator] | separator
flowchartStatement ::= vertexStatement (SEMICOLON vertexStatement)*
	| subgraphStatement
	| styleStatement
	| linkStyleStatement
	| classDefStatement
	| flowchartClassStatement
	| flowchartClickStatement
//	| directive

private separator ::= EOL | SEMICOLON
vertexStatement ::= nodeStatement [flowchartLinkStatement vertexStatement]
flowchartLinkStatement ::= START_ARROW complexLinkText ARROW | ARROW [SEP complexLinkText SEP]
nodeStatement ::= vertex STYLE_SEPARATOR STYLE_TARGET | vertex [AMPERSAND nodeStatement]
vertex ::= complexIdentifier [vertexText]
vertexText ::= OPEN_SQUARE nodeText CLOSE_SQUARE
							| OPEN_ROUND nodeText CLOSE_ROUND
							| STADIUM_START nodeText STADIUM_END
							| SUBROUTINE_START nodeText SUBROUTINE_END
							| CYLINDER_START nodeText CYLINDER_END
							| CIRCLE_START nodeText CIRCLE_END
							| ASYMMETRIC_START nodeText CLOSE_SQUARE
							| DIAMOND_START nodeText DIAMOND_END
							| HEXAGON_START nodeText HEXAGON_END
							| TRAP_START nodeText INV_TRAP_END
              | INV_TRAP_START nodeText TRAP_END
							| TRAP_START nodeText TRAP_END
							| INV_TRAP_START nodeText INV_TRAP_END
							| DOUBLE_CIRCLE_START nodeText DOUBLE_CIRCLE_END
nodeText ::= ALIAS+ | DOUBLE_QUOTE ALIAS+ DOUBLE_QUOTE
complexLinkText ::= LINK_TEXT+

subgraphStatement ::= subgraphHeader EOL subgraphDocument? END
subgraphHeader ::= SUBGRAPH subgraphName
subgraphName ::= complexIdentifier
subgraphDocument ::= subgraphLines
private subgraphLines ::= (subgraphLine | IGNORED) [subgraphLines]
private subgraphLine ::= subgraphInnerStatement [separator] | separator
private subgraphInnerStatement ::= flowchartStatement
	| directionStatement

styleStatement ::= STYLE STYLE_TARGET styleOptions

linkStyleStatement ::= LINK_STYLE linkStyleTarget styleOptions
private linkStyleTarget ::= STYLE_TARGET (COMMA STYLE_TARGET)* | DEFAULT

classDefStatement ::= CLASS_DEF (STYLE_TARGET | DEFAULT) styleOptions

flowchartClassStatement ::= CLASS ID (COMMA ID)* STYLE_TARGET

styleOptions ::= STYLE_OPT COLON STYLE_VAL (COMMA STYLE_OPT COLON STYLE_VAL)*


sequenceDocument ::= sequenceLines
private sequenceLines ::= (sequenceLine | IGNORED) [sequenceLines]
private sequenceLine ::= sequenceStatement [separator] | separator
sequenceStatement ::= actorStatement
	| signalStatement
	| AUTONUMBER
	| ACTIVATE complexIdentifier
	| DEACTIVATE complexIdentifier
	| noteStatement
	| linksStatement
	| linkStatement
	| LOOP [complexMessage] EOL sequenceDocument? END
	| RECT [complexMessage] EOL sequenceDocument? END
	| OPT [complexMessage] EOL sequenceDocument? END
	| ALT [complexMessage] EOL elseSections END
	| PAR [complexMessage] EOL parSections END
	| directive

idAlias ::= ALIAS+

actorStatement ::= (PARTICIPANT | ACTOR) complexIdentifier [AS idAlias]

signalStatement ::= complexIdentifier signal complexIdentifier COLON complexMessage
signal ::= signalType [PLUS | MINUS]
signalType ::= SOLID_OPEN_ARROW
  | DOTTED_OPEN_ARROW
  | SOLID_ARROW
  | DOTTED_ARROW
  | SOLID_CROSS
  | DOTTED_CROSS
  | SOLID_POINT
  | DOTTED_POINT

noteStatement ::= NOTE (RIGHT_OF | LEFT_OF) complexIdentifier COLON complexMessage
  | NOTE OVER complexIdentifier [COMMA complexIdentifier] COLON complexMessage

linksStatement ::= LINKS complexIdentifier COLON linksValues
linksValues ::= OPEN_CURLY linkContent CLOSE_CURLY
private linkContent ::= string COLON string [COMMA linkContent]

linkStatement ::= LINK complexIdentifier COLON complexMessage

elseSections ::= sequenceDocument? [ELSE [complexMessage] EOL elseSections]
parSections ::= sequenceDocument? [AND [complexMessage] EOL parSections]

complexMessage ::= MESSAGE+

classDocument ::= classLines
private classLines ::= classLine [classLines]
private classLine ::= classDiagramStatement [EOL] | EOL
classDiagramStatement ::= directionStatement
  | classStatement
  | relationStatement
  | memberStatement
  | annotationStatement
  | directive
  | classDiagramClickStatement

classStatement ::= CLASS identifier [TILDA GENERIC_TYPE TILDA] [STYLE_SEPARATOR identifier] [OPEN_CURLY EOL classMembersDocument? CLOSE_CURLY]

memberStatement ::= identifier COLON attrOrMethod

relationStatement ::= identifier relation identifier [COLON complexLabel]
complexLabel ::= LABEL+

annotationStatement ::= annotation identifier
annotation ::= ANNOTATION_START ANNOTATION_VALUE ANNOTATION_END

classMembersDocument ::= memberLines
private memberLines ::= memberLine [memberLines]
private memberLine ::= classMemberStatement [EOL] | EOL
classMemberStatement ::= attrOrMethod | annotation | directive
attrOrMethod ::= [visibilityAtStart] (method | attribute)
private visibilityAtStart ::= PLUS | MINUS | POUND | TILDA
private visibilityAtEnd ::= STAR | DOLLAR

attribute ::= (attrTypeWithGeneric | attrType) attrName [visibilityAtEnd] | attrName [COLON (attrTypeWithGeneric | attrType)]
method ::= attrName OPEN_ROUND [attribute] CLOSE_ROUND [visibilityAtEnd] [attrTypeWithGeneric | attrType]
attrType ::= ID
attrTypeWithGeneric ::= attrType TILDA GENERIC_TYPE TILDA
attrName ::= ID


relation ::= [cardinality] [relationTypeLeft] lineType [relationTypeRight] [cardinality]
cardinality ::= string

relationTypeLeft ::= AGGREGATION
    | EXTENSION_START
    | COMPOSITION
    | DEPENDENCY_START

relationTypeRight ::= AGGREGATION
    | EXTENSION_END
    | COMPOSITION
    | DEPENDENCY_END

lineType ::= LINE | DOTTED_LINE


stateDocument ::= stateLines
private stateLines ::= stateLine [stateLines]
private stateLine ::= stateDiagramStatement [EOL] | EOL
stateDiagramStatement ::= stateDeclaration
  | stateId ARROW stateId [COLON complexLabel]
  | stateId
  | noteHeader noteContent
  | directionStatement
  | directive

stateDeclaration ::= stateId COLON complexLabel
  | STATE description AS stateId
  | STATE stateId OPEN_CURLY innerStateDocument CLOSE_CURLY
  | STATE stateId ANNOTATION_START ANNOTATION_VALUE ANNOTATION_END

innerStateDocument ::= innerStateLines
private innerStateLines ::= innerStateLine [innerStateLines]
private innerStateLine ::= innerStateDiagramStatement [EOL] | EOL
private innerStateDiagramStatement ::= stateDiagramStatement | dividerStatement

dividerStatement ::= DIVIDER

stateId ::= identifier | OPEN_SQUARE STAR CLOSE_SQUARE
description ::= string
noteHeader ::= NOTE (RIGHT_OF | LEFT_OF) stateId
private noteContent ::= EOL complexNoteContent? END
  | COLON [simpleNoteContent]

simpleNoteContent ::= NOTE_CONTENT+
complexNoteContent ::= noteLines
private noteLines ::= noteLine [noteLines]
private noteLine ::= simpleNoteContent [EOL] | EOL


erDocument ::= erLines
private erLines ::= erLine [erLines]
private erLine ::= erStatement [EOL] | EOL
erStatement ::= identifier relationship identifier COLON (complexLabel | string)
	| entityDeclaration
	| identifier
	| directive

entityDeclaration ::= identifier OPEN_CURLY EOL erAttributesDocument? CLOSE_CURLY

relationship ::= relationshipLeft (IDENTIFYING | NON_IDENTIFYING) relationshipRight
private relationshipLeft ::= ZERO_OR_ONE_LEFT | ONE_OR_MORE_LEFT | ZERO_OR_MORE_LEFT | ONLY_ONE
private relationshipRight ::= ZERO_OR_ONE_RIGHT | ONE_OR_MORE_RIGHT | ZERO_OR_MORE_RIGHT | ONLY_ONE

erAttributesDocument ::= erAttributesLines
private erAttributesLines ::= erAttributeLine [erAttributesLines]
private erAttributeLine ::= erAttribute [EOL] | EOL
erAttribute ::= attrType attrName [ATTR_KEY] [string]


ganttDocument ::= ganttLines
private ganttLines ::= ganttLine [ganttLines]
private ganttLine ::= ganttStatement [IGNORED] [EOL] | [IGNORED] EOL
ganttStatement ::= DATE_FORMAT
  | titleStatement
  | EXCLUDES
  | INCLUDES
  | AXIS_FORMAT
  | TODAY_MARKER
  | ganttSectionStatement
  | ganttDataStatement
	| directive
	| ganttClickStatement

ganttDataStatement ::= complexTaskName COLON recTaskData

ganttSectionStatement ::= SECTION complexSectionTitle ganttSectionDocument
ganttSectionDocument ::= ganttSectionLines
private ganttSectionLines ::= (ganttSectionLine | IGNORED) [ganttSectionLines]
private ganttSectionLine ::= ganttSectionInnerStatement [EOL] | EOL
ganttSectionInnerStatement ::= ganttDataStatement


requirementDocument ::= requirementLines
private requirementLines ::= requirementLine [requirementLines]
private requirementLine ::= requirementStatement [EOL] | EOL
requirementStatement ::= requirementDef
  | elementDef
  | relationshipDef
	| directive

requirementDef ::= requirementType identifier OPEN_CURLY EOL requirementBody? CLOSE_CURLY
requirementType ::= REQUIREMENT
  | FUNCTIONAL_REQUIREMENT
  | INTERFACE_REQUIREMENT
  | PERFORMANCE_REQUIREMENT
  | PHYSICAL_REQUIREMENT
  | DESIGN_CONSTRAINT
private requirementValue ::= complexLabel | string

requirementBody ::= requirementBodyLines
private requirementBodyLines ::= requirementBodyLine [requirementBodyLines]
private requirementBodyLine ::= requirementBodyStatement [EOL] | EOL
requirementBodyStatement ::= ID_KEYWORD COLON requirementValue
  | TEXT COLON requirementValue
  | RISK COLON riskLevel
  | VERIFY_METHOD COLON verifyType

riskLevel ::= LOW | MEDIUM | HIGH
verifyType ::= ANALYSIS | DEMONSTRATION | INSPECTION | TEST

elementDef ::= ELEMENT identifier OPEN_CURLY EOL elementBody? CLOSE_CURLY

elementBody ::= elementBodyLines
private elementBodyLines ::= elementBodyLine [elementBodyLines]
private elementBodyLine ::= elementBodyStatement [EOL] | EOL
elementBodyStatement ::= TYPE COLON requirementValue
  | DOCREF COLON requirementValue

relationshipDef ::= identifier ARROW_LEFT reqRelationship REQ_LINE identifier
  | identifier REQ_LINE reqRelationship ARROW_RIGHT identifier

reqRelationship ::= CONTAINS | COPIES | DERIVES | SATISFIES | VERIFIES | REFINES | TRACES


gitGraphDocument ::= gitGraphLines
private gitGraphLines ::= gitGraphLine [gitGraphLines]
private gitGraphLine ::= gitGraphStatement [IGNORED] [EOL] | [IGNORED] EOL
gitGraphStatement ::= commitStatement
	| mergeStatement
	| cherryPickStatement
	| branchStatement
	| checkoutStatement
	| directive

branchStatement ::= BRANCH identifier [branchOrder]
cherryPickStatement ::= CHERRY_PICK commitIdAttribute
mergeStatement ::= MERGE identifier [commitTagAttribute]
checkoutStatement ::= CHECKOUT identifier
commitStatement ::=
    COMMIT commitIdAttribute commitTagAttribute [commitTypeAttribute]
  | COMMIT commitIdAttribute [commitTypeAttribute] [commitTagAttribute]
  | COMMIT commitTagAttribute commitTypeAttribute [commitIdAttribute]
  | COMMIT commitTagAttribute [commitIdAttribute] [commitTypeAttribute]
  | COMMIT commitTypeAttribute commitIdAttribute [commitTagAttribute]
  | COMMIT commitTypeAttribute [commitTagAttribute] [commitIdAttribute]
  | COMMIT [commit_arg]

branchOrder ::= ORDER COLON NUM
commitIdAttribute ::= ID_KEYWORD COLON string
commitTypeAttribute ::= TYPE COLON commitType
commitTagAttribute ::= TAG COLON string
commit_arg ::= string
private commitType ::= NORMAL | REVERSE | HIGHLIGHT


directive ::= OPEN_DIRECTIVE directiveContent? CLOSE_DIRECTIVE
private directiveContent ::= property [COMMA directiveContent]
property ::= directiveKey COLON directiveValue
directiveKey ::= string | DIRECTIVE_TEXT
directiveValue ::= string | DIRECTIVE_TEXT | object
object ::= OPEN_CURLY directiveContent CLOSE_CURLY

flowchartClickStatement ::= CLICK [CLICK_DATA] [HREF] string [string] [LINK_TARGET]
	| CLICK [CALL] CLICK_DATA [callbackArgs] string
	| CLICK CLICK_DATA [CALL? CLICK_DATA callbackArgs?] [string]

ganttClickStatement ::= CLICK CLICK_DATA (CALL CLICK_DATA callbackArgs | HREF string)

classDiagramClickStatement ::= CLICK CLICK_DATA CALL CLICK_DATA callbackArgs [string]
	| CLICK CLICK_DATA HREF string [string] [LINK_TARGET]
	| CALLBACK CLICK_DATA string [string]
	| LINK CLICK_DATA string [string] [LINK_TARGET]

callbackArgs ::= OPEN_ROUND [callbackArg] (COMMA callbackArg)* CLOSE_ROUND
private callbackArg ::= CLICK_DATA | string

directionStatement ::= DIRECTION DIR

string ::= DOUBLE_QUOTE STRING_VALUE? DOUBLE_QUOTE
complexIdentifier ::= (ID | AMPERSAND)+ {
	mixin="com.github.firsttimeinforever.mermaid.lang.psi.impl.MermaidNamedPsiElement"
	implements="com.github.firsttimeinforever.mermaid.lang.psi.MermaidNamedElement"
}
identifier ::= ID {
	mixin="com.github.firsttimeinforever.mermaid.lang.psi.impl.MermaidNamedPsiElement"
	implements="com.github.firsttimeinforever.mermaid.lang.psi.MermaidNamedElement"
}

