load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "community-resources",
    iml_files = ["community-resources.iml"],
    resources = ["src"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
