load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "intellij.idea.community.resources",
    iml_files = ["intellij.idea.community.resources.iml"],
    resources = ["src"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
