load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.idea.community.resources",
    iml_files = ["intellij.idea.community.resources.iml"],
    resources = ["src"],
    visibility = ["//visibility:public"],
)
