load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "colorSchemes",
    srcs = ["src"],
    iml_files = ["colorSchemes.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
