load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "intellij.platform.colorSchemes",
    srcs = ["src"],
    iml_files = ["intellij.platform.colorSchemes.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
