from _typeshed import StrPath, Unused
from collections.abc import Callable, Iterable, Mapping
from typing import Literal
from typing_extensions import TypeVarTuple, Unpack

from .compilers.platform import detect, macos

_Ts = TypeVarTuple("_Ts")

get_host_platform = detect.get_host_platform
get_platform = detect.get_platform
is_mingw = detect.is_mingw
MACOSX_VERSION_VAR = macos.VERSION_VAR
get_macosx_target_ver = macos.target_ver
get_macosx_target_ver_from_syscfg = macos._target_ver_from_syscfg

def split_version(s: str) -> list[int]: ...
def convert_path(pathname: StrPath) -> str: ...
def change_root(new_root: StrPath, pathname: StrPath) -> str: ...
def check_environ() -> None: ...
def subst_vars(s: str, local_vars: Mapping[str, object]) -> str: ...
def grok_environment_error(exc: object, prefix: str = "error: ") -> str: ...
def split_quoted(s: str) -> list[str]: ...
def execute(
    func: Callable[[Unpack[_Ts]], Unused], args: tuple[Unpack[_Ts]], msg: str | None = None, verbose: bool = False
) -> None: ...
def strtobool(val: str) -> Literal[0, 1]: ...
def byte_compile(
    py_files: Iterable[str],
    optimize: int = 0,
    force: bool = False,
    prefix: str | None = None,
    base_dir: str | None = None,
    verbose: bool = True,
    direct: bool | None = None,
) -> None: ...
def rfc822_escape(header: str) -> str: ...
def is_freethreaded() -> bool: ...
