version = "1.3.*"
upstream-repository = "https://github.com/pika/pika"
stub-distribution = "types-pika-ts" # https://github.com/python/typeshed/issues/9246
extra-description = """\
The `types-pika` package contains alternate, more complete type stubs, that \
are maintained outside of typeshed.\
"""

[tool.stubtest]
stubtest-dependencies = ["gevent", "tornado", "twisted"]
