filegroup(
    name = "mockJDK",
    srcs = glob(
        [
            "mockJDK-1.4/**",
            "mockJDK-1.7/**",
            "mockJDK-1.8/**",
            "mockJDK-1.9/**",
        ],
        allow_empty = False,
    ) + [
        # Written by plugin-model-tool into the `dev intellij.java.jdkAnnotations` section, because the Java plugin
        # layout declares the directory with `withResourceArchiveFromModule`.
        "//java/jdkAnnotations:dev_dist_resources",
    ],
    visibility = ["//visibility:public"],
)
