filegroup(
    name = "mockJDK",
    srcs = glob(
        [
            "mockJDK-1.4/**",
            "mockJDK-1.7/**",
            "mockJDK-1.8/**",
            "mockJDK-1.9/**",
        ],
        allow_empty = False,
    ) + ["//java/jdkAnnotations:dev_dist_resources"],
    visibility = ["//visibility:public"],
)
