[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))']
rustflags = ["-C", "link-arg=-mmacosx-version-min=12.0"]

[target.'cfg(all(target_os = "macos", target_arch = "x86_64"))']
rustflags = ["-C", "link-arg=-mmacosx-version-min=10.15"]

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "target-feature=+crt-static"]
