version = "4.6.0"
upstream_repository = "https://github.com/redis/redis-py"
# Requires a version of cryptography with a `py.typed` file
requires = ["cryptography>=35.0.0", "types-pyOpenSSL"]
partial_stub = true
obsolete_since = "5.0.0" # Released on 2023-08-15, marked obsolete 2024-07-25

[tool.stubtest]
ignore_missing_stub = true
# The runtime has an undeclared dependency on setuptools
stubtest_requirements = ["setuptools"]
extras = ["ocsp"]
