apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-dev
  labels:
    app: jaeger-dev
spec:
  selector:
    matchLabels:
      app: jaeger-dev
  template:
    metadata:
      labels:
        app: jaeger-dev
    spec:
      securityContext:
        runAsUser: 65533
        runAsGroup: 65534
        fsGroup: 65532
      volumes:
        - name: jaeger-dev-data
          emptyDir: { }
      containers:
        - name: jaeger-dev
          image: jaegertracing/all-in-one:latest
          ports:
            - containerPort: 16686
              protocol: TCP
            - containerPort: 4318
              protocol: TCP
          volumeMounts:
            - name: jaeger-dev-data
              mountPath: /badger
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: 'true'
            - name: SPAN_STORAGE_TYPE
              value: badger
            - name: BADGER_EPHEMERAL
              value: 'false'
            - name: BADGER_DIRECTORY_VALUE
              value: '/badger/data'
            - name: BADGER_DIRECTORY_KEY
              value: '/badger/key'
            - name: BADGER_SPAN_STORE_TTL
              value: '336h'
          resources:
            limits:
              cpu: 200m
              ephemeral-storage: 1Gi
              memory: 1Gi
            requests:
              cpu: 50m
              ephemeral-storage: 100Mi
              memory: 150Mi
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-dev
  labels:
    app: jaeger-dev
spec:
  ports:
    - name: http
      port: 16686
      protocol: TCP
    - name: otlp-http
      port: 4318
      protocol: TCP
  selector:
    app: jaeger-dev
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-labs-jb-gg-dns
spec:
  ingressClassName: internal-nginx
  tls:
    - secretName: jaeger-dev-labs-jb-gg-tls
      hosts:
        - jaeger-dev.labs.jb.gg
  rules:
    - host: jaeger-dev.labs.jb.gg
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jaeger-dev
                port:
                  number: 16686
          - path: /v1/traces
            pathType: Prefix
            backend:
              service:
                name: jaeger-dev
                port:
                  number: 4318