java_binary(
    name = "BazelAntLauncher",
    srcs = ["com/android/tools/BazelAntLauncher.java"],
    main_class = "com.android.tools.BazelAntLauncher",
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/lib/ant/lib:ant-launcher"],
)
