/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <libnotify/notify.h>
/* Header for class com_intellij_ui_LibNotifyWrapper */

#ifndef _Included_com_intellij_ui_LibNotifyWrapper
#define _Included_com_intellij_ui_LibNotifyWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intellij_ui_LibNotifyWrapper
 * Method:    showNotification
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intellij_ui_LibNotifyWrapper_showNotification
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
