load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "intellij.java.googleAppEngine.runtime",
    srcs = ["source"],
    iml_files = ["intellij.java.googleAppEngine.runtime.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
