load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "appEngine-runtime",
    srcs = ["source"],
    iml_files = ["appEngine-runtime.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
