load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.java.googleAppEngine.runtime",
    srcs = ["source"],
    iml_files = ["intellij.java.googleAppEngine.runtime.iml"],
    visibility = ["//visibility:public"],
)
