// Copyright 2000-2026 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

package org.jetbrains.kotlin.idea.fir.navigation;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.idea.base.plugin.KotlinPluginMode;
import org.jetbrains.kotlin.idea.base.test.TestRoot;
import org.jetbrains.kotlin.idea.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.idea.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

/**
 * This class is generated by {@link org.jetbrains.kotlin.testGenerator.generator.TestGenerator}.
 * DO NOT MODIFY MANUALLY.
 */
@SuppressWarnings("all")
@TestRoot("fir/tests")
@TestDataPath("$CONTENT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
@TestMetadata("../../idea/tests/testData/navigation/gotoDeclaration")
public class FirGotoDeclarationTestGenerated extends AbstractFirGotoDeclarationTest {
    @java.lang.Override
    @org.jetbrains.annotations.NotNull
    public final KotlinPluginMode getPluginMode() {
        return KotlinPluginMode.K2;
    }

    private void runTest(String testDataFilePath) throws Exception {
        KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
    }

    @TestMetadata("annotationCallWithMissedTypeArgs.test")
    public void testAnnotationCallWithMissedTypeArgs() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/annotationCallWithMissedTypeArgs.test");
    }

    @TestMetadata("breakInDoWhileLoop.test")
    public void testBreakInDoWhileLoop() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/breakInDoWhileLoop.test");
    }

    @TestMetadata("breakInForNested.test")
    public void testBreakInForNested() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/breakInForNested.test");
    }

    @TestMetadata("breakInForNested2.test")
    public void testBreakInForNested2() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/breakInForNested2.test");
    }

    @TestMetadata("breakInForWithLocalProperty.test")
    public void testBreakInForWithLocalProperty() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/breakInForWithLocalProperty.test");
    }

    @TestMetadata("breakInNestedWhileLoop.test")
    public void testBreakInNestedWhileLoop() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/breakInNestedWhileLoop.test");
    }

    @TestMetadata("breakInOuterForLoop.test")
    public void testBreakInOuterForLoop() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/breakInOuterForLoop.test");
    }

    @TestMetadata("breakInOuterWhileLoop.test")
    public void testBreakInOuterWhileLoop() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/breakInOuterWhileLoop.test");
    }

    @TestMetadata("breakSimple.test")
    public void testBreakSimple() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/breakSimple.test");
    }

    @TestMetadata("breakWithLabeledLoop.test")
    public void testBreakWithLabeledLoop() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/breakWithLabeledLoop.test");
    }

    @TestMetadata("breakWithLabeledWhileLoop.test")
    public void testBreakWithLabeledWhileLoop() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/breakWithLabeledWhileLoop.test");
    }

    @TestMetadata("breakinWhileLoop.test")
    public void testBreakinWhileLoop() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/breakinWhileLoop.test");
    }

    @TestMetadata("continueInDoWhileLoop.test")
    public void testContinueInDoWhileLoop() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/continueInDoWhileLoop.test");
    }

    @TestMetadata("continueInForNested.test")
    public void testContinueInForNested() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/continueInForNested.test");
    }

    @TestMetadata("continueInForNested2.test")
    public void testContinueInForNested2() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/continueInForNested2.test");
    }

    @TestMetadata("continueInNestedWhileLoop.test")
    public void testContinueInNestedWhileLoop() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/continueInNestedWhileLoop.test");
    }

    @TestMetadata("continueInOuterWhileLoop.test")
    public void testContinueInOuterWhileLoop() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/continueInOuterWhileLoop.test");
    }

    @TestMetadata("continueInWhileLoop.test")
    public void testContinueInWhileLoop() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/continueInWhileLoop.test");
    }

    @TestMetadata("continueOuterForLoop.test")
    public void testContinueOuterForLoop() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/continueOuterForLoop.test");
    }

    @TestMetadata("continueSimple.test")
    public void testContinueSimple() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/continueSimple.test");
    }

    @TestMetadata("continueWithLabeledLoop.test")
    public void testContinueWithLabeledLoop() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/continueWithLabeledLoop.test");
    }

    @TestMetadata("continueWithLabeledWhileLoop.test")
    public void testContinueWithLabeledWhileLoop() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/continueWithLabeledWhileLoop.test");
    }

    @TestMetadata("dataClassToString.test")
    public void testDataClassToString() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/dataClassToString.test");
    }

    @TestMetadata("destructuringDeclarationInitializer.test")
    public void testDestructuringDeclarationInitializer() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/destructuringDeclarationInitializer.test");
    }

    @TestMetadata("enumEntries.test")
    public void testEnumEntries() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/enumEntries.test");
    }

    @TestMetadata("flexibleType.test")
    public void testFlexibleType() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/flexibleType.test");
    }

    @TestMetadata("importAlias.test")
    public void testImportAlias() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/importAlias.test");
    }

    @TestMetadata("itExtensionLambda.test")
    public void testItExtensionLambda() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/itExtensionLambda.test");
    }

    @TestMetadata("itExtensionLambdaInBrackets.test")
    public void testItExtensionLambdaInBrackets() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/itExtensionLambdaInBrackets.test");
    }

    @TestMetadata("itInLambdaAsDefaultArgument.test")
    public void testItInLambdaAsDefaultArgument() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/itInLambdaAsDefaultArgument.test");
    }

    @TestMetadata("itInLambdaWithoutCall.test")
    public void testItInLambdaWithoutCall() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/itInLambdaWithoutCall.test");
    }

    @TestMetadata("itParameterInLambda.test")
    public void testItParameterInLambda() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/itParameterInLambda.test");
    }

    @TestMetadata("labeledThisToClass.test")
    public void testLabeledThisToClass() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/labeledThisToClass.test");
    }

    @TestMetadata("labeledThisToMemberExtension.test")
    public void testLabeledThisToMemberExtension() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/labeledThisToMemberExtension.test");
    }

    @TestMetadata("listFlexibleType.test")
    public void testListFlexibleType() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/listFlexibleType.test");
    }

    @TestMetadata("navigationToLibrary.test")
    public void testNavigationToLibrary() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/navigationToLibrary.test");
    }

    @TestMetadata("thisExtensionFunction.test")
    public void testThisExtensionFunction() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/thisExtensionFunction.test");
    }

    @TestMetadata("thisExtensionLambda.test")
    public void testThisExtensionLambda() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/thisExtensionLambda.test");
    }

    @TestMetadata("thisInExtensionPropertyAccessor.test")
    public void testThisInExtensionPropertyAccessor() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/thisInExtensionPropertyAccessor.test");
    }

    @TestMetadata("valClass.test")
    public void testValClass() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/valClass.test");
    }

    @TestMetadata("valGeneric.test")
    public void testValGeneric() throws Exception {
        runTest("../../idea/tests/testData/navigation/gotoDeclaration/valGeneric.test");
    }
}
