# managed by go/iml_to_build
java_import(
    name = "jsr305",
    jars = ["jsr305.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "httpcore-4.4.5",
    jars = ["httpcore-4.4.5.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "httpmime-4.5.2",
    jars = ["httpmime-4.5.2.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "httpclient-4.5.2",
    jars = ["httpclient-4.5.2.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "fluent-hc-4.5.2",
    jars = ["fluent-hc-4.5.2.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "gherkin-2.12.2",
    jars = ["gherkin-2.12.2.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "cucumber-core-1.2.4",
    jars = ["cucumber-core-1.2.4.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "asm-all",
    jars = ["asm-all.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jdom",
    jars = ["jdom.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jgoodies-forms",
    jars = ["jgoodies-forms.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "coverage-agent",
    jars = ["coverage-agent.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "coverage-instrumenter",
    jars = ["coverage-instrumenter.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "coverage-util",
    jars = ["coverage-util.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "eawtstub",
    jars = ["eawtstub.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "log4j",
    jars = ["log4j.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jna",
    jars = ["jna.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jna-platform",
    jars = ["jna-platform.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "snappy-in-java-0.5.1",
    jars = ["snappy-in-java-0.5.1.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "batik-all",
    jars = ["batik-all.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "xstream-1.4.8",
    jars = ["xstream-1.4.8.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "picocontainer",
    jars = ["picocontainer.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "xercesImpl",
    jars = ["xercesImpl.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "automaton",
    jars = ["automaton.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "cglib-nodep-3.2.4",
    jars = ["cglib-nodep-3.2.4.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "pty4j-0.7.1",
    jars = ["pty4j-0.7.1.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "microba",
    jars = ["microba.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jsr173_1.0_api",
    jars = ["jsr173_1.0_api.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "xbean",
    jars = ["xbean.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "resolver",
    jars = ["resolver.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "velocity",
    jars = ["velocity.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "xpp3-1.1.4-min",
    jars = ["xpp3-1.1.4-min.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jh",
    jars = ["jh.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "miglayout-core-5.0",
    jars = ["miglayout-core-5.0.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "miglayout-swing-5.0",
    jars = ["miglayout-swing-5.0.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jayatana-1.2.4",
    jars = ["jayatana-1.2.4.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "slf4j-api-1.7.10",
    jars = ["slf4j-api-1.7.10.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "slf4j-log4j12-1.7.10",
    jars = ["slf4j-log4j12-1.7.10.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "purejavacomm",
    jars = ["purejavacomm.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "serviceMessages",
    jars = ["serviceMessages.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "minlog-1.2",
    jars = ["minlog-1.2.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "kryo-2.22",
    jars = ["kryo-2.22.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "reflectasm-1.07",
    jars = ["reflectasm-1.07.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "objenesis-1.2",
    jars = ["objenesis-1.2.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "ecj-4.7.2",
    jars = ["ecj-4.7.2.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "nekohtml-1.9.14",
    jars = ["nekohtml-1.9.14.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "commons-httpclient-3.1-patched",
    jars = ["commons-httpclient-3.1-patched.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "markdownj-core-0.4.2-SNAPSHOT",
    jars = ["markdownj-core-0.4.2-SNAPSHOT.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jediterm-pty-2.7",
    jars = ["jediterm-pty-2.7.jar"],
    visibility = ["//visibility:public"],
)

exports_files(["src/trove4j_src.jar"])

# TODO: When using ant to package all the libraries are included, and if they are not present
# there is no error. We will need to revisit both, and acually make sure we only bundle what
# we need.
filegroup(
    name = "all-libs",
    srcs = ["//tools/idea/lib/ant:ant-all"] + glob(["**"]),
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "netty-all-4.1.13.Final",
    jars = ["netty-all-4.1.13.Final.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "proxy-vole-1.0.3",
    jars = ["proxy-vole-1.0.3.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "aether-1.1.0-all",
    jars = ["aether-1.1.0-all.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "maven-aether-provider-3.3.9-all",
    jars = ["maven-aether-provider-3.3.9-all.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "wadl-core",
    jars = ["wadl-core.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jshell-frontend",
    jars = ["jshell-frontend.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jaxb-api",
    jars = ["jaxb-api.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jaxb-impl",
    jars = ["jaxb-impl.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "lz4-java-1.3",
    jars = ["lz4-java-1.3.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "test-discovery-agent",
    jars = ["test-discovery-agent.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "test-discovery-instrumenter",
    jars = ["test-discovery-instrumenter.jar"],
    visibility = ["//visibility:public"],
)
