@startuml
start
partition #green/white files {

  :read files;
  :setup maven wrapper;

}

partition #yellow "resolve dependencies" {
 :embedder.customiseForResolve();
 :embedder.resolve();

  while (for each MavenImporter)
    rectangle mavenImporter.resolve() {
      :embedder.resolve();
    }
  endwhile

}


partition #yellow "resolve plugins" {
 :embedder.customiseForResolve();
 :embedder.resolvePlugin();

}

partition #pink/white "commit workspace model" {
 :import project;

  while (for each module)
    :import module;
    :configure maven projects;
   endwhile

 :commit;

  while (for each module)
    while (for each MavenImporter))
     :MavenImporter.preprocess();
     :MavenImporter.process();
     :MavenImporter.postprocess();
    endwhile
  endwhile

}

partition #pink/white "update project manager" {
   :update project manager;
}

partition #pink/white "configure maven projects" {
 while (for each MavenConfigurer)
    :MavenConfigurer.configure();
  endwhile
}

@enduml
