#  Copyright 2000-2025 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

class Generator:
    def __init__(self, outfp, mangle_from_: bool = ..., maxheaderlen: int = ...) -> None: ...
    def write(self, s) -> None: ...
    def flatten(self, msg, unixfrom: bool = ...) -> None: ...
    def clone(self, fp): ...

class DecodedGenerator(Generator):
    def __init__(self, outfp, mangle_from_: bool = ..., maxheaderlen: int = ..., fmt=...) -> None: ...
