// Copyright 2000-2023 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package org.jetbrains.plugins.gradle.statistics

import com.intellij.gradle.toolingExtension.impl.modelBuilder.Messages
import com.intellij.internal.statistic.eventLog.EventLogGroup
import com.intellij.internal.statistic.eventLog.events.EventFields
import com.intellij.internal.statistic.service.fus.collectors.CounterUsagesCollector
import com.intellij.openapi.project.Project
import org.jetbrains.annotations.ApiStatus.Internal

@Internal
object GradleModelBuilderMessageCollector : CounterUsagesCollector() {

  override fun getGroup(): EventLogGroup = GROUP

  private val GROUP: EventLogGroup = EventLogGroup("build.gradle.errors", 22)

  private val ACTIVITY_ID = EventFields.Long("ide_activity_id")
  private val MESSAGE_KIND = EventFields.Enum<FailureKind>("message_kind")
  private val MESSAGE_GROUP = EventFields.Enum<FailureGroup>("message_group") { it.group }

  private val MODEL_BUILDER_MESSAGE_RECEIVED_EVENT = GROUP.registerEvent("model.builder.message.received", ACTIVITY_ID, MESSAGE_KIND, MESSAGE_GROUP)

  fun logFailure(project: Project?, activityId: Long, kind: FailureKind, group: FailureGroup) {
    MODEL_BUILDER_MESSAGE_RECEIVED_EVENT.log(project, activityId, kind, group)
  }

  enum class FailureKind {
    ERROR, WARNING, INFO
  }

  enum class FailureGroup(val group: String) {
    PROJECT_MODEL_GROUP(Messages.PROJECT_MODEL_GROUP),

    SCALA_PROJECT_MODEL_GROUP(Messages.SCALA_PROJECT_MODEL_GROUP),

    TASK_WARM_UP_GROUP(Messages.TASK_WARM_UP_GROUP),
    TASK_MODEL_GROUP(Messages.TASK_MODEL_GROUP),

    SOURCE_SET_MODEL_GROUP(Messages.SOURCE_SET_MODEL_GROUP),
    SOURCE_SET_MODEL_PROJECT_TASK_ARTIFACT_GROUP(Messages.SOURCE_SET_MODEL_PROJECT_TASK_ARTIFACT_GROUP),
    SOURCE_SET_MODEL_SKIPPED_PROJECT_TASK_ARTIFACT_GROUP(Messages.SOURCE_SET_MODEL_SKIPPED_PROJECT_TASK_ARTIFACT_GROUP),
    SOURCE_SET_MODEL_NON_SOURCE_SET_ARTIFACT_GROUP(Messages.SOURCE_SET_MODEL_NON_SOURCE_SET_ARTIFACT_GROUP),
    SOURCE_SET_MODEL_SKIPPED_NON_SOURCE_SET_ARTIFACT_GROUP(Messages.SOURCE_SET_MODEL_SKIPPED_NON_SOURCE_SET_ARTIFACT_GROUP),
    SOURCE_SET_MODEL_PROJECT_CONFIGURATION_ARTIFACT_GROUP(Messages.SOURCE_SET_MODEL_PROJECT_CONFIGURATION_ARTIFACT_GROUP),
    SOURCE_SET_MODEL_SKIPPED_PROJECT_CONFIGURATION_ARTIFACT_GROUP(Messages.SOURCE_SET_MODEL_SKIPPED_PROJECT_CONFIGURATION_ARTIFACT_GROUP),
    SOURCE_SET_MODEL_SOURCE_SET_ARTIFACT_GROUP(Messages.SOURCE_SET_MODEL_SOURCE_SET_ARTIFACT_GROUP),
    SOURCE_SET_MODEL_SKIPPED_SOURCE_SET_ARTIFACT_GROUP(Messages.SOURCE_SET_MODEL_SKIPPED_SOURCE_SET_ARTIFACT_GROUP),

    RESOURCE_FILTER_MODEL_GROUP(Messages.RESOURCE_FILTER_MODEL_GROUP),

    DEPENDENCY_DOWNLOAD_POLICY_MODEL_GROUP(Messages.DEPENDENCY_DOWNLOAD_POLICY_MODEL_GROUP),
    DEPENDENCY_DOWNLOAD_POLICY_MODEL_CACHE_GET_GROUP(Messages.DEPENDENCY_DOWNLOAD_POLICY_MODEL_CACHE_GET_GROUP),
    DEPENDENCY_DOWNLOAD_POLICY_MODEL_CACHE_SET_GROUP(Messages.DEPENDENCY_DOWNLOAD_POLICY_MODEL_CACHE_SET_GROUP),

    SOURCE_SET_ARTIFACT_INDEX_GROUP(Messages.SOURCE_SET_ARTIFACT_INDEX_GROUP),
    SOURCE_SET_ARTIFACT_INDEX_CACHE_SET_GROUP(Messages.SOURCE_SET_ARTIFACT_INDEX_CACHE_SET_GROUP),

    SOURCE_SET_DEPENDENCY_MODEL_GROUP(Messages.SOURCE_SET_DEPENDENCY_MODEL_GROUP),

    EAR_CONFIGURATION_MODEL_GROUP(Messages.EAR_CONFIGURATION_MODEL_GROUP),
    WAR_CONFIGURATION_MODEL_GROUP(Messages.WAR_CONFIGURATION_MODEL_GROUP),

    DEPENDENCY_RESOLUTION_GROUP(Messages.DEPENDENCY_RESOLUTION_GROUP),
    DEPENDENCY_CLASSPATH_MODEL_GROUP(Messages.DEPENDENCY_CLASSPATH_MODEL_GROUP),
    DEPENDENCY_ACCESSOR_MODEL_GROUP(Messages.DEPENDENCY_ACCESSOR_MODEL_GROUP),
    DEPENDENCY_GRAPH_MODEL_GROUP(Messages.DEPENDENCY_GRAPH_MODEL_GROUP),

    INTELLIJ_SETTINGS_MODEL_GROUP(Messages.INTELLIJ_SETTINGS_MODEL_GROUP),
    INTELLIJ_PROJECT_SETTINGS_MODEL_GROUP(Messages.INTELLIJ_PROJECT_SETTINGS_MODEL_GROUP),

    BUILDSCRIPT_CLASSPATH_MODEL_GROUP(Messages.BUILDSCRIPT_CLASSPATH_MODEL_GROUP),
    BUILDSCRIPT_CLASSPATH_MODEL_CACHE_GET_GROUP(Messages.BUILDSCRIPT_CLASSPATH_MODEL_CACHE_GET_GROUP),
    BUILDSCRIPT_CLASSPATH_MODEL_CACHE_SET_GROUP(Messages.BUILDSCRIPT_CLASSPATH_MODEL_CACHE_SET_GROUP),

    TEST_MODEL_GROUP(Messages.TEST_MODEL_GROUP),
    MAVEN_REPOSITORY_MODEL_GROUP(Messages.MAVEN_REPOSITORY_MODEL_GROUP),
    ANNOTATION_PROCESSOR_MODEL_GROUP(Messages.ANNOTATION_PROCESSOR_MODEL_GROUP),
    PROJECT_EXTENSION_MODEL_GROUP(Messages.PROJECT_EXTENSION_MODEL_GROUP),
    VERSION_CATALOG_MODEL_GROUP(Messages.VERSION_CATALOG_MODEL_GROUP),

    GRADLE_SYNC_FAILURE_GROUP("gradle.sync.failure.group");

    companion object {
      @JvmStatic
      fun findByMessageOrNull(message: String?): FailureGroup? {
        if (message == null) {
          return null
        }
        return entries.firstOrNull { it.group == message }
      }
    }
  }
}