version = "0.2.*"
# There is no web portal for the source, this is the official source link:
# upstream-repository = "https://people.csail.mit.edu/hubert/pyaudio/#sources"

[tool.stubtest]
# linux and win32 are equivalent
ci-platforms = ["darwin", "linux"]
apt-dependencies = ["portaudio19-dev"]
brew-dependencies = ["portaudio"]
