from types import ModuleType
from typing import Any, NoReturn

class WarnOnDeprecatedModuleAttributes(ModuleType):
    def __call__(self) -> NoReturn: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
