classDiagram
  class Class1
  class Class2
  Class1 : Object[] elementData
  Class2 : Obj ect[] element Data
  class Class3 {
    Object[] elementData
  }
  class Class4 {
    Obj ect[] element Data
  }