version = "4.3.*"
upstream_repository = "https://github.com/django/channels"
requires = ["django-stubs>=4.2,<5.3", "asgiref"]

[tool.stubtest]
mypy_plugins = ['mypy_django_plugin.main']
mypy_plugins_config = {"django-stubs" = {"django_settings_module" = "@tests.django_settings"}}
stubtest_requirements = ["daphne"]
