version = "4.3.*"
upstream-repository = "https://github.com/django/channels"
dependencies = ["django-stubs>=4.2", "asgiref"]

[tool.stubtest]
mypy-plugins = ['mypy_django_plugin.main']
mypy-plugins-config = {"django-stubs" = {"django_settings_module" = "@tests.django_settings"}}
stubtest-dependencies = ["daphne"]
