# Stubs for binascii

# Based on http://docs.python.org/3.2/library/binascii.html

from typing import Union

def a2b_uu(string: Union[str, bytes]) -> bytes: ...
def b2a_uu(data: bytes) -> bytes: ...
def a2b_base64(string: Union[str, bytes]) -> bytes: ...
def b2a_base64(data: bytes) -> bytes: ...
def a2b_qp(string: Union[str, bytes], header: bool = ...) -> bytes: ...
def b2a_qp(data: bytes, quotetabs: bool = ..., istext: bool = ...,
             header: bool = ...) -> bytes: ...
def a2b_hqx(string: Union[str, bytes]) -> bytes: ...
def rledecode_hqx(data: bytes) -> bytes: ...
def rlecode_hqx(data: bytes) -> bytes: ...
def b2a_hqx(data: bytes) -> bytes: ...
def crc_hqx(data: bytes, crc: int) -> int: ...
def crc32(data: bytes, crc: int = ...) -> int: ...
def b2a_hex(data: bytes) -> bytes: ...
def hexlify(data: bytes) -> bytes: ...
def a2b_hex(hexstr: Union[str, bytes]) -> bytes: ...
def unhexlify(hexlify: Union[str, bytes]) -> bytes: ...

class Error(Exception): ...
class Incomplete(Exception): ...
