import abc
from typing_extensions import Self

class Struct(metaclass=abc.ABCMeta):
    @property
    @abc.abstractmethod
    def SCHEMA(self): ...
    ALIASES: dict[str, str]
    def __init__(self, *args, **kwargs) -> None: ...
    def encode(self): ...
    @classmethod
    def decode(cls, data) -> Self: ...
    def get_item(self, name): ...
    def __hash__(self) -> int: ...
    def __eq__(self, other) -> bool: ...
