import re
import sys
import types
from _typeshed import Incomplete, StrOrBytesPath
from sqlite3 import Connection as _Connection
from typing import Any, ClassVar, overload

from pony.orm import dbapiprovider, dbschema
from pony.orm.dbapiprovider import DBAPIProvider, Pool
from pony.orm.sqlbuilding import SQLBuilder, Value
from pony.orm.sqltranslation import SQLTranslator
from pony.utils import localbase

class SqliteExtensionUnavailable(Exception): ...

NoneType: type[None]

class SQLiteForeignKey(dbschema.ForeignKey):
    def get_create_command(self) -> None: ...

class SQLiteSchema(dbschema.DBSchema):
    dialect: ClassVar[str]
    fk_class: ClassVar[type[SQLiteForeignKey]]

def make_overriden_string_func(sqlop): ...

class SQLiteTranslator(SQLTranslator):
    dialect: ClassVar[str]
    sqlite_version: tuple[int, int, int]
    StringMixin_UPPER: Incomplete
    StringMixin_LOWER: Incomplete

class SQLiteValue(Value):
    __slots__: list[str] = []

class SQLiteBuilder(SQLBuilder):
    dialect: ClassVar[str]
    least_func_name: ClassVar[str]
    greatest_func_name: ClassVar[str]
    value_class: ClassVar[type[SQLiteValue]]
    def __init__(self, provider, ast) -> None: ...
    def SELECT_FOR_UPDATE(self, nowait, skip_locked, *sections): ...
    def INSERT(self, table_name, columns, values, returning=None): ...
    def STRING_SLICE(self, expr, start, stop): ...
    def IN(self, expr1, x): ...
    def NOT_IN(self, expr1, x): ...
    def TODAY(self): ...
    def NOW(self): ...
    def YEAR(self, expr): ...
    def MONTH(self, expr): ...
    def DAY(self, expr): ...
    def HOUR(self, expr): ...
    def MINUTE(self, expr): ...
    def SECOND(self, expr): ...
    def datetime_add(self, funcname, expr, td): ...
    def DATE_ADD(self, expr, delta): ...
    def DATE_SUB(self, expr, delta): ...
    def DATE_DIFF(self, expr1, expr2): ...
    def DATETIME_ADD(self, expr, delta): ...
    def DATETIME_SUB(self, expr, delta): ...
    def DATETIME_DIFF(self, expr1, expr2): ...
    def RANDOM(self): ...
    PY_UPPER: Incomplete
    PY_LOWER: Incomplete
    def FLOAT_EQ(self, a, b): ...
    def FLOAT_NE(self, a, b): ...
    def JSON_QUERY(self, expr, path): ...
    json_value_type_mapping: Incomplete
    def JSON_VALUE(self, expr, path, type): ...
    def JSON_NONZERO(self, expr): ...
    def JSON_ARRAY_LENGTH(self, value): ...
    def JSON_CONTAINS(self, expr, path, key): ...
    def ARRAY_INDEX(self, col, index): ...
    def ARRAY_CONTAINS(self, key, not_in, col): ...
    def ARRAY_SUBSET(self, array1, not_in, array2): ...
    def ARRAY_LENGTH(self, array): ...
    def ARRAY_SLICE(self, array, start, stop): ...
    def MAKE_ARRAY(self, *items): ...

class SQLiteIntConverter(dbapiprovider.IntConverter):
    def sql_type(self): ...

class SQLiteDecimalConverter(dbapiprovider.DecimalConverter):
    inf: Incomplete
    neg_inf: Incomplete
    NaN: Incomplete
    def sql2py(self, val): ...
    def py2sql(self, val): ...

class SQLiteDateConverter(dbapiprovider.DateConverter):
    def sql2py(self, val): ...
    def py2sql(self, val): ...

class SQLiteTimeConverter(dbapiprovider.TimeConverter):
    def sql2py(self, val): ...
    def py2sql(self, val): ...

class SQLiteTimedeltaConverter(dbapiprovider.TimedeltaConverter):
    def sql2py(self, val): ...
    def py2sql(self, val): ...

class SQLiteDatetimeConverter(dbapiprovider.DatetimeConverter):
    def sql2py(self, val): ...
    def py2sql(self, val): ...

class SQLiteJsonConverter(dbapiprovider.JsonConverter):
    json_kwargs: Incomplete

def dumps(items): ...

class SQLiteArrayConverter(dbapiprovider.ArrayConverter):
    array_types: Incomplete
    def dbval2val(self, dbval, obj=None): ...
    def val2dbval(self, val, obj=None): ...

class LocalExceptions(localbase):
    exc_info: Incomplete
    keep_traceback: bool
    def __init__(self) -> None: ...

local_exceptions: LocalExceptions

def keep_exception(func): ...

class SQLiteProvider(DBAPIProvider):
    dialect: ClassVar[str]
    local_exceptions: LocalExceptions
    dbapi_module: ClassVar[types.ModuleType]
    dbschema_cls: ClassVar[type[SQLiteSchema]]
    translator_cls: ClassVar[type[SQLiteTranslator]]
    sqlbuilder_cls: ClassVar[type[SQLiteBuilder]]
    array_converter_cls: ClassVar[type[SQLiteArrayConverter]]
    server_version: tuple[int, int, int]
    converter_classes: Incomplete
    def __init__(self, database, filename, **kwargs) -> None: ...
    def inspect_connection(self, conn) -> None: ...
    def restore_exception(self) -> None: ...
    def acquire_lock(self) -> None: ...
    def release_lock(self) -> None: ...
    def set_transaction_mode(self, connection: _Connection, cache) -> None: ...
    def commit(self, connection: _Connection, cache=None) -> None: ...
    def rollback(self, connection: _Connection, cache=None) -> None: ...
    def drop(self, connection: _Connection, cache=None) -> None: ...
    def release(self, connection: _Connection, cache=None) -> None: ...
    def get_pool(self, is_shared_memory_db, filename, create_db: bool = False, **kwargs): ...
    def table_exists(self, connection: _Connection, table_name: str, case_sensitive: bool = True): ...
    def index_exists(self, connection: _Connection, table_name: str, index_name, case_sensitive: bool = True): ...
    def fk_exists(self, connection: _Connection, table_name: str, fk_name) -> None: ...  # type: ignore[override]
    def check_json1(self, connection: _Connection) -> bool: ...

provider_cls = SQLiteProvider

def make_string_function(name, base_func): ...

py_upper: Incomplete
py_lower: Incomplete

@overload
def py_json_unwrap(value: str) -> str | None: ...
@overload
def py_json_unwrap(value: Any) -> None: ...

path_cache: Incomplete
json_path_re: re.Pattern[str]

def py_json_extract(expr, *paths): ...
def py_json_query(expr, path, with_wrapper): ...
def py_json_value(expr, path): ...
def py_json_contains(expr, path, key): ...
def py_json_nonzero(expr, path): ...
def py_json_array_length(expr, path=None): ...
def wrap_array_func(func): ...
def py_array_index(array, index): ...
def py_array_contains(array, item): ...
def py_array_subset(array, items): ...
def py_array_length(array): ...
def py_array_slice(array, start, stop): ...
def py_make_array(*items): ...

@overload
def py_string_slice(s: None, start: str | int | None, end: str | int | None) -> None: ...
@overload
def py_string_slice(s: str, start: str | int | None, end: str | int | None) -> str: ...

class SQLitePool(Pool):
    is_shared_memory_db: bool | None
    filename: StrOrBytesPath
    create_db: bool | None
    kwargs: dict[str, Incomplete]
    if sys.version_info >= (3, 12):
        def __init__(
            self,
            is_shared_memory_db: bool | None,
            filename: StrOrBytesPath,
            create_db: bool | None,
            *,
            timeout: float = 5.0,
            detect_types: int = 0,
            check_same_thread: bool = True,
            factory: type[_Connection],
            cached_statements: int = 128,
            uri: bool = False,
            autocommit: bool = ...,
        ) -> None: ...
    else:
        def __init__(
            self,
            is_shared_memory_db: bool | None,
            filename: StrOrBytesPath,
            create_db: bool | None,
            *,
            timeout: float = 5.0,
            detect_types: int = 0,
            check_same_thread: bool = True,
            factory: type[_Connection],
            cached_statements: int = 128,
            uri: bool = False,
        ) -> None: ...

    def disconnect(self) -> None: ...
    def drop(self, con: _Connection) -> None: ...
