// Copyright 2000-2020 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE file.
package com.jetbrains.python.formatter;

import com.intellij.application.options.CodeStyleAbstractPanel;
import com.intellij.openapi.editor.colors.EditorColorsScheme;
import com.intellij.openapi.editor.highlighter.EditorHighlighter;
import com.intellij.openapi.fileTypes.FileType;
import com.intellij.openapi.util.NlsContexts.TabTitle;
import com.intellij.psi.codeStyle.CodeStyleSettings;
import com.intellij.ui.IdeBorderFactory;
import com.intellij.ui.components.JBCheckBox;
import com.intellij.ui.components.JBRadioButton;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.jetbrains.python.PySyntaxBundle;
import com.jetbrains.python.PythonFileType;
import com.jetbrains.python.PythonLanguage;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.swing.AbstractButton;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.border.TitledBorder;
import java.awt.Color;
import java.awt.Insets;
import java.lang.reflect.Method;
import java.util.ResourceBundle;

/**
 * @author Mikhail Golubev
 */
public class PyImportsCodeStylePanel extends CodeStyleAbstractPanel {
  private final JBCheckBox mySortImports;
  private final JBCheckBox mySortNamesInFromImports;
  private final JBCheckBox mySortImportsByTypeFirst;
  private final JPanel myRootPanel;
  private final JBCheckBox mySortCaseInsensitively;
  private final JBRadioButton myDoNothingWithFromImports;
  private final JBRadioButton myJoinFromImportsWithSameSource;
  private final JBRadioButton myAlwaysSplitFromImports;

  public PyImportsCodeStylePanel(@NotNull CodeStyleSettings settings) {
    super(PythonLanguage.getInstance(), null, settings);
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myRootPanel = new JPanel();
      myRootPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 10, 10, 10), -1, -1));
      final Spacer spacer1 = new Spacer();
      myRootPanel.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      final JPanel panel1 = new JPanel();
      panel1.setLayout(new GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
      panel1.putClientProperty("BorderFactoryClass", "com.intellij.ui.IdeBorderFactory$PlainSmallWithIndent");
      myRootPanel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                  GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null,
                                                  null, 0, false));
      panel1.setBorder(IdeBorderFactory.PlainSmallWithIndent.createTitledBorder(null,
                                                                                this.$$$getMessageFromBundle$$$("messages/PySyntaxBundle",
                                                                                                                "formatter.imports.panel.optimize.imports"),
                                                                                TitledBorder.DEFAULT_JUSTIFICATION,
                                                                                TitledBorder.DEFAULT_POSITION, null, null));
      mySortImports = new JBCheckBox();
      this.$$$loadButtonText$$$(mySortImports,
                                this.$$$getMessageFromBundle$$$("messages/PySyntaxBundle", "formatter.imports.panel.sort.imports"));
      panel1.add(mySortImports,
                 new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                     GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      mySortNamesInFromImports = new JBCheckBox();
      this.$$$loadButtonText$$$(mySortNamesInFromImports, this.$$$getMessageFromBundle$$$("messages/PySyntaxBundle",
                                                                                          "formatter.imports.panel.sort.names.in.from.imports"));
      panel1.add(mySortNamesInFromImports,
                 new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                     GridConstraints.SIZEPOLICY_FIXED, null, null, null, 2, false));
      mySortImportsByTypeFirst = new JBCheckBox();
      this.$$$loadButtonText$$$(mySortImportsByTypeFirst,
                                this.$$$getMessageFromBundle$$$("messages/PySyntaxBundle", "formatter.imports.panel.sort.by.type"));
      panel1.add(mySortImportsByTypeFirst,
                 new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                     GridConstraints.SIZEPOLICY_FIXED, null, null, null, 2, false));
      mySortCaseInsensitively = new JBCheckBox();
      mySortCaseInsensitively.setSelected(false);
      this.$$$loadButtonText$$$(mySortCaseInsensitively, this.$$$getMessageFromBundle$$$("messages/PySyntaxBundle",
                                                                                         "formatter.imports.panel.sort.case.insensitively"));
      panel1.add(mySortCaseInsensitively,
                 new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                     GridConstraints.SIZEPOLICY_FIXED, null, null, null, 2, false));
      final JPanel panel2 = new JPanel();
      panel2.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
      panel2.putClientProperty("BorderFactoryClass", "com.intellij.ui.IdeBorderFactory$PlainSmallWithIndent");
      panel1.add(panel2, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                             GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                             GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null,
                                             0, false));
      panel2.setBorder(IdeBorderFactory.PlainSmallWithIndent.createTitledBorder(BorderFactory.createEtchedBorder(),
                                                                                this.$$$getMessageFromBundle$$$("messages/PySyntaxBundle",
                                                                                                                "formatter.imports.panel.from.imports.structure.title"),
                                                                                TitledBorder.DEFAULT_JUSTIFICATION,
                                                                                TitledBorder.DEFAULT_POSITION, null, new Color(-16777216)));
      myDoNothingWithFromImports = new JBRadioButton();
      this.$$$loadButtonText$$$(myDoNothingWithFromImports, this.$$$getMessageFromBundle$$$("messages/PySyntaxBundle",
                                                                                            "formatter.imports.panel.from.imports.leave.as.is"));
      panel2.add(myDoNothingWithFromImports, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                 GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                 GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                                 null, null, null, 0, false));
      final Spacer spacer2 = new Spacer();
      panel2.add(spacer2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                              GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      myJoinFromImportsWithSameSource = new JBRadioButton();
      myJoinFromImportsWithSameSource.setSelected(false);
      this.$$$loadButtonText$$$(myJoinFromImportsWithSameSource, this.$$$getMessageFromBundle$$$("messages/PySyntaxBundle",
                                                                                                 "formatter.imports.panel.from.imports.join.with.same.source"));
      panel2.add(myJoinFromImportsWithSameSource, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE,
                                                                      GridConstraints.SIZEPOLICY_CAN_SHRINK |
                                                                      GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
                                                                      null, null, null, 0, false));
      myAlwaysSplitFromImports = new JBRadioButton();
      this.$$$loadButtonText$$$(myAlwaysSplitFromImports, this.$$$getMessageFromBundle$$$("messages/PySyntaxBundle",
                                                                                          "formatter.imports.panel.from.imports.always.split"));
      panel2.add(myAlwaysSplitFromImports, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                               GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                               GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      final Spacer spacer3 = new Spacer();
      myRootPanel.add(spacer3, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                   GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
      ButtonGroup buttonGroup;
      buttonGroup = new ButtonGroup();
      buttonGroup.add(myDoNothingWithFromImports);
      buttonGroup.add(myJoinFromImportsWithSameSource);
      buttonGroup.add(myAlwaysSplitFromImports);
    }
    addPanelToWatch(myRootPanel);

    mySortImports.addActionListener(e -> {
      final boolean sortingEnabled = mySortImports.isSelected();
      mySortNamesInFromImports.setEnabled(sortingEnabled);
      mySortImportsByTypeFirst.setEnabled(sortingEnabled);
      mySortCaseInsensitively.setEnabled(sortingEnabled);
    });
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadButtonText$$$(AbstractButton component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myRootPanel; }

  @Override
  protected @TabTitle @NotNull String getTabTitle() {
    return PySyntaxBundle.message("formatter.imports.panel.title");
  }

  @Override
  protected @NotNull FileType getFileType() {
    return PythonFileType.INSTANCE;
  }

  @Override
  protected @Nullable EditorHighlighter createHighlighter(@NotNull EditorColorsScheme scheme) {
    return null;
  }

  @Override
  protected @Nullable String getPreviewText() {
    return null;
  }

  @Override
  protected int getRightMargin() {
    return 0;
  }

  @Override
  public void apply(@NotNull CodeStyleSettings settings) {
    final PyCodeStyleSettings pySettings = settings.getCustomSettings(PyCodeStyleSettings.class);

    pySettings.OPTIMIZE_IMPORTS_SORT_IMPORTS = mySortImports.isSelected();
    pySettings.OPTIMIZE_IMPORTS_SORT_NAMES_IN_FROM_IMPORTS = mySortNamesInFromImports.isSelected();
    pySettings.OPTIMIZE_IMPORTS_SORT_BY_TYPE_FIRST = mySortImportsByTypeFirst.isSelected();
    pySettings.OPTIMIZE_IMPORTS_JOIN_FROM_IMPORTS_WITH_SAME_SOURCE = myJoinFromImportsWithSameSource.isSelected();
    pySettings.OPTIMIZE_IMPORTS_ALWAYS_SPLIT_FROM_IMPORTS = myAlwaysSplitFromImports.isSelected();
    pySettings.OPTIMIZE_IMPORTS_CASE_INSENSITIVE_ORDER = mySortCaseInsensitively.isSelected();
  }

  @Override
  public boolean isModified(CodeStyleSettings settings) {
    final PyCodeStyleSettings pySettings = settings.getCustomSettings(PyCodeStyleSettings.class);

    return mySortImports.isSelected() != pySettings.OPTIMIZE_IMPORTS_SORT_IMPORTS ||
           mySortNamesInFromImports.isSelected() != pySettings.OPTIMIZE_IMPORTS_SORT_NAMES_IN_FROM_IMPORTS ||
           mySortImportsByTypeFirst.isSelected() != pySettings.OPTIMIZE_IMPORTS_SORT_BY_TYPE_FIRST ||
           myJoinFromImportsWithSameSource.isSelected() != pySettings.OPTIMIZE_IMPORTS_JOIN_FROM_IMPORTS_WITH_SAME_SOURCE ||
           myAlwaysSplitFromImports.isSelected() != pySettings.OPTIMIZE_IMPORTS_ALWAYS_SPLIT_FROM_IMPORTS ||
           mySortCaseInsensitively.isSelected() != pySettings.OPTIMIZE_IMPORTS_CASE_INSENSITIVE_ORDER;
  }

  @Override
  public @Nullable JComponent getPanel() {
    return myRootPanel;
  }

  @Override
  protected void resetImpl(@NotNull CodeStyleSettings settings) {
    final PyCodeStyleSettings pySettings = settings.getCustomSettings(PyCodeStyleSettings.class);

    mySortImports.setSelected(pySettings.OPTIMIZE_IMPORTS_SORT_IMPORTS);
    mySortNamesInFromImports.setSelected(pySettings.OPTIMIZE_IMPORTS_SORT_NAMES_IN_FROM_IMPORTS);
    mySortNamesInFromImports.setEnabled(mySortImports.isSelected());
    mySortImportsByTypeFirst.setSelected(pySettings.OPTIMIZE_IMPORTS_SORT_BY_TYPE_FIRST);
    mySortImportsByTypeFirst.setEnabled(mySortImports.isSelected());
    mySortCaseInsensitively.setSelected(pySettings.OPTIMIZE_IMPORTS_CASE_INSENSITIVE_ORDER);

    if (pySettings.OPTIMIZE_IMPORTS_JOIN_FROM_IMPORTS_WITH_SAME_SOURCE) {
      myJoinFromImportsWithSameSource.setSelected(true);
    }
    else if (pySettings.OPTIMIZE_IMPORTS_ALWAYS_SPLIT_FROM_IMPORTS) {
      myAlwaysSplitFromImports.setSelected(true);
    }
    else {
      myDoNothingWithFromImports.setSelected(true);
    }
  }
}
