from argparse import ArgumentParser, Namespace

from kafka.admin._acls import ACL, ACLFilter

def add_acl_filter_args(parser: ArgumentParser) -> None: ...
def add_acl_args(parser: ArgumentParser, required: bool = False) -> None: ...
def acl_filter_from_args(args: Namespace) -> ACLFilter: ...
def acl_from_args(args: Namespace) -> ACL: ...
