# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET https://package-search.services.jetbrains.com/api/package?query=ktor
Accept: application/json+com.jetbrains.packagesearch.standard

###

GET https://package-search.services.jetbrains.com/api/package?range=org.junit.jupiter:junit-jupiter,com.willowtreeapps.assertk:assertk-jvm,com.squareup.okhttp3:mockwebserver
Accept: application/json+com.jetbrains.packagesearch.standard

###