[package]
name = "utils"
version = "0.1.0"
edition = "2021"
rust-version = "1.62.1"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.62", features = ["std", "backtrace"] }
log = "0.4.14"