name: Remove unused stubtest whitelist entries

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * SAT'

jobs:
  stubtest:
    if: github.repository == 'python/typeshed'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: [3.6, 3.7, 3.8, 3.9]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U git+git://github.com/python/mypy@24fdf343
      - name: Run stubtest
        shell: bash
        run: ./tests/stubtest_unused.py | tee stubtest-output-${{ matrix.os }}-${{ matrix.python-version }} || true
      - name: Store output
        uses: actions/upload-artifact@v2
        with:
          name: stubtest-output
          path: stubtest-output-${{ matrix.os }}-${{ matrix.python-version }}

  collate:
    if: github.repository == 'python/typeshed'
    runs-on: ubuntu-latest
    needs: stubtest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Get stubtest outputs
        uses: actions/download-artifact@v2
        with:
          name: stubtest-output
      - name: Collate duplicates
        run: cat stubtest-output-* | sort -u | tee stubtest-output
      - name: Remove entries from whitelists
        run: python scripts/update-stubtest-whitelist.py stubtest-output
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Remove unused stubtest whitelist entries
          title: "[gh-action] Remove unused stubtest whitelist entries"
