// Copyright 2000-2023 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package com.intellij.openapi.project;

/**
 * For statistics purposes only.
 * When nothing suits, use `Other`
 */
public enum DumbModeBlockedFunctionality {
  Action,
  ActionWithoutId,
  Android,
  CDI,
  CodeCompletion,
  CtrlMouseHandler,
  DupLocator,
  EditorGutterComponent,
  FindUsages,
  FrameworkDetection,
  GlobalInspectionContext,
  GotoClass,
  GotoDeclaration,
  GotoDeclarationOnly,
  GotoDeclarationOrUsage,
  GotoImplementations,
  GotoSuperMethod,
  GotoTarget,
  GotoTypeDeclaration,
  GroovyMarkers,
  Gwt,
  Intentions,
  JfrStackFrames,
  Jpa,
  Kotlin,
  LineProfiler,
  MemberInplaceRenamer,
  Micronaut,
  MultipleActionIds,
  Other,
  PackageDependencies,
  PostCommitCheck,
  ProjectView,
  RDClientHyperlink,
  Refactoring,
  RefactoringDialog,
  RemoteDebuggingFileFinder,
  SafeDeleteDialog,
  SearchEverywhere,
  Spring,
  TmsFilter,
  Uml,
  UsageInfoSearcherAdapter,
}