# managed by go/iml_to_build
java_library(
    name = "protobuf",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/com/google/protobuf/protobuf-java/3.5.1:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/com/google/protobuf/protobuf-java/3.5.1:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "JUnit4",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/junit/junit/4.12:jar",
        "//prebuilts/tools/common/m2/repository/org/hamcrest/hamcrest-core/1.3:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/junit/junit/4.12:jar",
        "//prebuilts/tools/common/m2/repository/org/hamcrest/hamcrest-core/1.3:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "truth",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/com/google/truth/truth/0.42:jar",
        "//prebuilts/tools/common/m2/repository/com/googlecode/java-diff-utils/diffutils/1.3.0:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/com/google/truth/truth/0.42:jar",
        "//prebuilts/tools/common/m2/repository/com/googlecode/java-diff-utils/diffutils/1.3.0:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "gson",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/com/google/code/gson/gson/2.8.6:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/com/google/code/gson/gson/2.8.6:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "http-client",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/org/apache/httpcomponents/httpclient/4.5.12:jar",
        "//prebuilts/tools/common/m2/repository/org/apache/httpcomponents/httpcore/4.4.13:jar",
        "//prebuilts/tools/common/m2/repository/org/apache/httpcomponents/httpmime/4.5.12:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/org/apache/httpcomponents/httpclient/4.5.12:jar",
        "//prebuilts/tools/common/m2/repository/org/apache/httpcomponents/httpcore/4.4.13:jar",
        "//prebuilts/tools/common/m2/repository/org/apache/httpcomponents/httpmime/4.5.12:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "Guava",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/com/google/guava/failureaccess/1.0.1:jar",
        "//prebuilts/tools/common/m2/repository/com/google/guava/guava/29.0-jre:jar",
        "//prebuilts/tools/common/m2/repository/com/google/j2objc/j2objc-annotations/1.3:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/com/google/guava/failureaccess/1.0.1:jar",
        "//prebuilts/tools/common/m2/repository/com/google/guava/guava/29.0-jre:jar",
        "//prebuilts/tools/common/m2/repository/com/google/j2objc/j2objc-annotations/1.3:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "ASM",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/jetbrains/intellij/deps/asm-all/8.0.1:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/jetbrains/intellij/deps/asm-all/8.0.1:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "jetbrains-annotations-java5",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/jetbrains/annotations-java5/19.0.0:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/jetbrains/annotations-java5/19.0.0:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "javax.activation",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/com/sun/activation/javax.activation/1.2.0:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/com/sun/activation/javax.activation/1.2.0:jar"],
)
