# managed by go/iml_to_build
java_library(
    name = "protobuf",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/com/google/protobuf/protobuf-java/3.5.1:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/com/google/protobuf/protobuf-java/3.5.1:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "JUnit4",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/junit/junit/4.12:jar",
        "//prebuilts/tools/common/m2/repository/org/hamcrest/hamcrest-core/1.3:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/junit/junit/4.12:jar",
        "//prebuilts/tools/common/m2/repository/org/hamcrest/hamcrest-core/1.3:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "truth",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/com/google/truth/truth/0.42:jar",
        "//prebuilts/tools/common/m2/repository/com/googlecode/java-diff-utils/diffutils/1.3.0:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/com/google/truth/truth/0.42:jar",
        "//prebuilts/tools/common/m2/repository/com/googlecode/java-diff-utils/diffutils/1.3.0:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "gson",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/com/google/code/gson/gson/2.8.6:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/com/google/code/gson/gson/2.8.6:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "http-client",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/org/apache/httpcomponents/httpclient/4.5.12:jar",
        "//prebuilts/tools/common/m2/repository/org/apache/httpcomponents/httpcore/4.4.13:jar",
        "//prebuilts/tools/common/m2/repository/org/apache/httpcomponents/httpmime/4.5.12:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/org/apache/httpcomponents/httpclient/4.5.12:jar",
        "//prebuilts/tools/common/m2/repository/org/apache/httpcomponents/httpcore/4.4.13:jar",
        "//prebuilts/tools/common/m2/repository/org/apache/httpcomponents/httpmime/4.5.12:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "Ant",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//tools/idea/lib/ant/lib:ant-antlr",
        "//tools/idea/lib/ant/lib:ant-apache-bcel",
        "//tools/idea/lib/ant/lib:ant-apache-bsf",
        "//tools/idea/lib/ant/lib:ant-apache-log4j",
        "//tools/idea/lib/ant/lib:ant-apache-oro",
        "//tools/idea/lib/ant/lib:ant-apache-regexp",
        "//tools/idea/lib/ant/lib:ant-apache-resolver",
        "//tools/idea/lib/ant/lib:ant-apache-xalan2",
        "//tools/idea/lib/ant/lib:ant-commons-logging",
        "//tools/idea/lib/ant/lib:ant-commons-net",
        "//tools/idea/lib/ant/lib:ant-jai",
        "//tools/idea/lib/ant/lib:ant-javamail",
        "//tools/idea/lib/ant/lib:ant-jdepend",
        "//tools/idea/lib/ant/lib:ant-jmf",
        "//tools/idea/lib/ant/lib:ant-jsch",
        "//tools/idea/lib/ant/lib:ant-junit",
        "//tools/idea/lib/ant/lib:ant-junit4",
        "//tools/idea/lib/ant/lib:ant-junitlauncher",
        "//tools/idea/lib/ant/lib:ant-launcher",
        "//tools/idea/lib/ant/lib:ant-netrexx",
        "//tools/idea/lib/ant/lib:ant-swing",
        "//tools/idea/lib/ant/lib:ant-testutil",
        "//tools/idea/lib/ant/lib:ant-xz",
        "//tools/idea/lib/ant/lib:ant",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//tools/idea/lib/ant/lib:ant-antlr",
        "//tools/idea/lib/ant/lib:ant-apache-bcel",
        "//tools/idea/lib/ant/lib:ant-apache-bsf",
        "//tools/idea/lib/ant/lib:ant-apache-log4j",
        "//tools/idea/lib/ant/lib:ant-apache-oro",
        "//tools/idea/lib/ant/lib:ant-apache-regexp",
        "//tools/idea/lib/ant/lib:ant-apache-resolver",
        "//tools/idea/lib/ant/lib:ant-apache-xalan2",
        "//tools/idea/lib/ant/lib:ant-commons-logging",
        "//tools/idea/lib/ant/lib:ant-commons-net",
        "//tools/idea/lib/ant/lib:ant-jai",
        "//tools/idea/lib/ant/lib:ant-javamail",
        "//tools/idea/lib/ant/lib:ant-jdepend",
        "//tools/idea/lib/ant/lib:ant-jmf",
        "//tools/idea/lib/ant/lib:ant-jsch",
        "//tools/idea/lib/ant/lib:ant-junit",
        "//tools/idea/lib/ant/lib:ant-junit4",
        "//tools/idea/lib/ant/lib:ant-junitlauncher",
        "//tools/idea/lib/ant/lib:ant-launcher",
        "//tools/idea/lib/ant/lib:ant-netrexx",
        "//tools/idea/lib/ant/lib:ant-swing",
        "//tools/idea/lib/ant/lib:ant-testutil",
        "//tools/idea/lib/ant/lib:ant-xz",
        "//tools/idea/lib/ant/lib:ant",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "Guava",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/com/google/guava/failureaccess/1.0.1:jar",
        "//prebuilts/tools/common/m2/repository/com/google/guava/guava/29.0-jre:jar",
        "//prebuilts/tools/common/m2/repository/com/google/j2objc/j2objc-annotations/1.3:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/com/google/guava/failureaccess/1.0.1:jar",
        "//prebuilts/tools/common/m2/repository/com/google/guava/guava/29.0-jre:jar",
        "//prebuilts/tools/common/m2/repository/com/google/j2objc/j2objc-annotations/1.3:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "kotlin-stdlib-jdk8",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.4.10:jar",
        "//prebuilts/tools/common/m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.4.10:jar",
        "//prebuilts/tools/common/m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.4.10:jar",
        "//prebuilts/tools/common/m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.4.10:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.4.10:jar",
        "//prebuilts/tools/common/m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.4.10:jar",
        "//prebuilts/tools/common/m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.4.10:jar",
        "//prebuilts/tools/common/m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.4.10:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "ASM",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/jetbrains/intellij/deps/asm-all/8.0.1:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/jetbrains/intellij/deps/asm-all/8.0.1:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "hamcrest",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = ["//prebuilts/tools/common/m2/repository/org/hamcrest/hamcrest-library/1.3:jar"],
    # do not sort: must match IML order
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/hamcrest/hamcrest-library/1.3:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "org.codehaus.groovy_groovy",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/codehaus/groovy/groovy/2.5.11:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/codehaus/groovy/groovy/2.5.11:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "auto-value-annotations",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/com/google/auto/value/auto-value-annotations/1.6.2:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/com/google/auto/value/auto-value-annotations/1.6.2:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "sqlite",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/xerial/sqlite-jdbc/3.21.0.1:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/xerial/sqlite-jdbc/3.21.0.1:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "jetbrains-annotations-java5",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/jetbrains/annotations-java5/19.0.0:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/jetbrains/annotations-java5/19.0.0:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "javax.activation",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/com/sun/activation/javax.activation/1.2.0:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/com/sun/activation/javax.activation/1.2.0:jar"],
)
