# managed by go/iml_to_build
java_library(
    name = "javax-inject",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/javax/inject/javax.inject/1:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/javax/inject/javax.inject/1:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "protobuf",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/com/google/protobuf/protobuf-java/3.0.0:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/com/google/protobuf/protobuf-java/3.0.0:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "JUnit4",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/junit/junit/4.12:jar",
        "//prebuilts/tools/common/m2/repository/org/hamcrest/hamcrest-core/1.3:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/junit/junit/4.12:jar",
        "//prebuilts/tools/common/m2/repository/org/hamcrest/hamcrest-core/1.3:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "truth",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/com/google/truth/truth/0.34:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/com/google/truth/truth/0.34:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "equalsverifier",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/nl/jqno/equalsverifier/equalsverifier/2.1.5:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/nl/jqno/equalsverifier/equalsverifier/2.1.5:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "easymock-tools",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/easymock-tools:easymock-3.1"],
    runtime_deps = ["//prebuilts/tools/common/easymock-tools:easymock-3.1"],
)

# managed by go/iml_to_build
java_library(
    name = "mockito",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/net/bytebuddy/byte-buddy-agent/1.7.4:jar",
        "//prebuilts/tools/common/m2/repository/net/bytebuddy/byte-buddy/1.7.4:jar",
        "//prebuilts/tools/common/m2/repository/org/mockito/mockito-core/2.11.0:jar",
        "//prebuilts/tools/common/m2/repository/org/objenesis/objenesis/2.6:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/net/bytebuddy/byte-buddy-agent/1.7.4:jar",
        "//prebuilts/tools/common/m2/repository/net/bytebuddy/byte-buddy/1.7.4:jar",
        "//prebuilts/tools/common/m2/repository/org/mockito/mockito-core/2.11.0:jar",
        "//prebuilts/tools/common/m2/repository/org/objenesis/objenesis/2.6:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "gson",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/com/google/code/gson/gson/2.8.2:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/com/google/code/gson/gson/2.8.2:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "kxml2",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/net/sf/kxml/kxml2/2.3.0:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/net/sf/kxml/kxml2/2.3.0:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "Trove4j",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/jetbrains/intellij/deps/trove4j/1.0.20160824:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/jetbrains/intellij/deps/trove4j/1.0.20160824:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "jsr305",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = ["//tools/idea/lib:jsr305"],
    # do not sort: must match IML order
    runtime_deps = ["//tools/idea/lib:jsr305"],
)

# managed by go/iml_to_build
java_library(
    name = "JUnit3",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/junit/junit/3.8.1:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/junit/junit/3.8.1:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "commons-compress",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/apache/commons/commons-compress/1.10:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/apache/commons/commons-compress/1.10:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "jimfs",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/com/google/jimfs/jimfs/1.1:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/com/google/jimfs/jimfs/1.1:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "http-client",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//tools/idea/lib:fluent-hc-4.5.2",
        "//tools/idea/lib:httpclient-4.5.2",
        "//tools/idea/lib:httpcore-4.4.5",
        "//tools/idea/lib:httpmime-4.5.2",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//tools/idea/lib:fluent-hc-4.5.2",
        "//tools/idea/lib:httpclient-4.5.2",
        "//tools/idea/lib:httpcore-4.4.5",
        "//tools/idea/lib:httpmime-4.5.2",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "bouncy-castle",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/org/bouncycastle/bcpkix-jdk15on/1.56:jar",
        "//prebuilts/tools/common/m2/repository/org/bouncycastle/bcprov-jdk15on/1.56:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/org/bouncycastle/bcpkix-jdk15on/1.56:jar",
        "//prebuilts/tools/common/m2/repository/org/bouncycastle/bcprov-jdk15on/1.56:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "bouncy-castle-provider",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/bouncycastle/bcprov-jdk15on/1.56:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/bouncycastle/bcprov-jdk15on/1.56:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "XmlRPC",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/apache/ws/xmlrpc/xmlrpc/2.0.1:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/apache/ws/xmlrpc/xmlrpc/2.0.1:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "Ant",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//tools/idea/lib/ant/lib:ant-antlr",
        "//tools/idea/lib/ant/lib:ant-apache-bcel",
        "//tools/idea/lib/ant/lib:ant-apache-bsf",
        "//tools/idea/lib/ant/lib:ant-apache-log4j",
        "//tools/idea/lib/ant/lib:ant-apache-oro",
        "//tools/idea/lib/ant/lib:ant-apache-regexp",
        "//tools/idea/lib/ant/lib:ant-apache-resolver",
        "//tools/idea/lib/ant/lib:ant-apache-xalan2",
        "//tools/idea/lib/ant/lib:ant-commons-logging",
        "//tools/idea/lib/ant/lib:ant-commons-net",
        "//tools/idea/lib/ant/lib:ant-jai",
        "//tools/idea/lib/ant/lib:ant-javamail",
        "//tools/idea/lib/ant/lib:ant-jdepend",
        "//tools/idea/lib/ant/lib:ant-jmf",
        "//tools/idea/lib/ant/lib:ant-jsch",
        "//tools/idea/lib/ant/lib:ant-junit",
        "//tools/idea/lib/ant/lib:ant-junit4",
        "//tools/idea/lib/ant/lib:ant-launcher",
        "//tools/idea/lib/ant/lib:ant-netrexx",
        "//tools/idea/lib/ant/lib:ant-swing",
        "//tools/idea/lib/ant/lib:ant-testutil",
        "//tools/idea/lib/ant/lib:ant",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//tools/idea/lib/ant/lib:ant-antlr",
        "//tools/idea/lib/ant/lib:ant-apache-bcel",
        "//tools/idea/lib/ant/lib:ant-apache-bsf",
        "//tools/idea/lib/ant/lib:ant-apache-log4j",
        "//tools/idea/lib/ant/lib:ant-apache-oro",
        "//tools/idea/lib/ant/lib:ant-apache-regexp",
        "//tools/idea/lib/ant/lib:ant-apache-resolver",
        "//tools/idea/lib/ant/lib:ant-apache-xalan2",
        "//tools/idea/lib/ant/lib:ant-commons-logging",
        "//tools/idea/lib/ant/lib:ant-commons-net",
        "//tools/idea/lib/ant/lib:ant-jai",
        "//tools/idea/lib/ant/lib:ant-javamail",
        "//tools/idea/lib/ant/lib:ant-jdepend",
        "//tools/idea/lib/ant/lib:ant-jmf",
        "//tools/idea/lib/ant/lib:ant-jsch",
        "//tools/idea/lib/ant/lib:ant-junit",
        "//tools/idea/lib/ant/lib:ant-junit4",
        "//tools/idea/lib/ant/lib:ant-launcher",
        "//tools/idea/lib/ant/lib:ant-netrexx",
        "//tools/idea/lib/ant/lib:ant-swing",
        "//tools/idea/lib/ant/lib:ant-testutil",
        "//tools/idea/lib/ant/lib:ant",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "Guava",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/com/google/guava/guava/21.0:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/com/google/guava/guava/21.0:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "commons-io",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/commons-io/commons-io/2.4:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/commons-io/commons-io/2.4:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "KotlinJavaRuntime",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/kotlin-plugin-ij:Kotlin/kotlinc/lib/kotlin-reflect",
        "//prebuilts/tools/common/kotlin-plugin-ij:Kotlin/kotlinc/lib/kotlin-runtime",
        "//prebuilts/tools/common/kotlin-plugin-ij:Kotlin/kotlinc/lib/kotlin-test",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/kotlin-plugin-ij:Kotlin/kotlinc/lib/kotlin-reflect",
        "//prebuilts/tools/common/kotlin-plugin-ij:Kotlin/kotlinc/lib/kotlin-runtime",
        "//prebuilts/tools/common/kotlin-plugin-ij:Kotlin/kotlinc/lib/kotlin-test",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "ASM",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:asm-all"],
    runtime_deps = ["//tools/idea/lib:asm-all"],
)

# managed by go/iml_to_build
java_library(
    name = "JDOM",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:jdom"],
    runtime_deps = ["//tools/idea/lib:jdom"],
)

# managed by go/iml_to_build
java_library(
    name = "jgoodies-forms",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:jgoodies-forms"],
    runtime_deps = ["//tools/idea/lib:jgoodies-forms"],
)

# managed by go/iml_to_build
java_library(
    name = "hamcrest",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = ["//prebuilts/tools/common/m2/repository/org/hamcrest/hamcrest-library/1.3:jar"],
    # do not sort: must match IML order
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/hamcrest/hamcrest-library/1.3:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "TestNG",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//tools/idea/plugins/testng/lib:jcommander",
        "//tools/idea/plugins/testng/lib:testng",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//tools/idea/plugins/testng/lib:jcommander",
        "//tools/idea/plugins/testng/lib:testng",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "Coverage",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//tools/idea/lib:coverage-agent",
        "//tools/idea/lib:coverage-instrumenter",
        "//tools/idea/lib:coverage-util",
        "//tools/idea/lib:test-discovery-agent",
        "//tools/idea/lib:test-discovery-instrumenter",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//tools/idea/lib:coverage-agent",
        "//tools/idea/lib:coverage-instrumenter",
        "//tools/idea/lib:coverage-util",
        "//tools/idea/lib:test-discovery-agent",
        "//tools/idea/lib:test-discovery-instrumenter",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "Mac",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:eawtstub"],
    runtime_deps = ["//tools/idea/lib:eawtstub"],
)

# managed by go/iml_to_build
java_library(
    name = "Log4J",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:log4j"],
    runtime_deps = ["//tools/idea/lib:log4j"],
)

# managed by go/iml_to_build
java_library(
    name = "picocontainer",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:picocontainer"],
    runtime_deps = ["//tools/idea/lib:picocontainer"],
)

# managed by go/iml_to_build
java_library(
    name = "jna",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//tools/idea/lib:jna-platform",
        "//tools/idea/lib:jna",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//tools/idea/lib:jna-platform",
        "//tools/idea/lib:jna",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "OroMatcher",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/oro/oro/2.0.8:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/oro/oro/2.0.8:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "Snappy-Java",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:snappy-in-java-0.5.1"],
    runtime_deps = ["//tools/idea/lib:snappy-in-java-0.5.1"],
)

# managed by go/iml_to_build
java_library(
    name = "imgscalr",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/imgscalr/imgscalr-lib/4.2:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/imgscalr/imgscalr-lib/4.2:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "batik",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:batik-all"],
    runtime_deps = ["//tools/idea/lib:batik-all"],
)

# managed by go/iml_to_build
java_library(
    name = "xmlgraphics-commons",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/apache/xmlgraphics/xmlgraphics-commons/1.5:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/apache/xmlgraphics/xmlgraphics-commons/1.5:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "XStream",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:xstream-1.4.8"],
    runtime_deps = ["//tools/idea/lib:xstream-1.4.8"],
)

# managed by go/iml_to_build
java_library(
    name = "Xerces",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = ["//tools/idea/lib:xercesImpl"],
    # do not sort: must match IML order
    runtime_deps = ["//tools/idea/lib:xercesImpl"],
)

# managed by go/iml_to_build
java_library(
    name = "CGLIB",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:cglib-nodep-3.2.4"],
    runtime_deps = ["//tools/idea/lib:cglib-nodep-3.2.4"],
)

# managed by go/iml_to_build
java_library(
    name = "NanoXML",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/be/cyberelf/nanoxml/nanoxml/2.2.3:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/be/cyberelf/nanoxml/nanoxml/2.2.3:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "commons-codec",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/commons-codec/commons-codec/1.9:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/commons-codec/commons-codec/1.9:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "Netty",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:netty-all-4.1.13.Final"],
    runtime_deps = ["//tools/idea/lib:netty-all-4.1.13.Final"],
)

# managed by go/iml_to_build
java_library(
    name = "proxy-vole",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:proxy-vole-1.0.3"],
    runtime_deps = ["//tools/idea/lib:proxy-vole-1.0.3"],
)

# managed by go/iml_to_build
java_library(
    name = "pty4j",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:pty4j-0.7.1"],
    runtime_deps = ["//tools/idea/lib:pty4j-0.7.1"],
)

# managed by go/iml_to_build
java_library(
    name = "Mocks",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//tools/idea/lib/dev:easymock-3.4",
        "//tools/idea/lib/dev:jmock-2.5.1",
        "//tools/idea/lib/dev:jmock-junit4-2.5.1",
        "//tools/idea/lib/dev:jmock-legacy-2.5.1",
        "//tools/idea/lib/dev:objenesis-1.0",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//tools/idea/lib/dev:easymock-3.4",
        "//tools/idea/lib/dev:jmock-2.5.1",
        "//tools/idea/lib/dev:jmock-junit4-2.5.1",
        "//tools/idea/lib/dev:jmock-legacy-2.5.1",
        "//tools/idea/lib/dev:objenesis-1.0",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "microba",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:microba"],
    runtime_deps = ["//tools/idea/lib:microba"],
)

# managed by go/iml_to_build
java_library(
    name = "asm-tools",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//tools/adt/idea/android/lib:asm-5.0.3",
        "//tools/adt/idea/android/lib:asm-analysis-5.0.3",
        "//tools/adt/idea/android/lib:asm-tree-5.0.3",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//tools/adt/idea/android/lib:asm-5.0.3",
        "//tools/adt/idea/android/lib:asm-analysis-5.0.3",
        "//tools/adt/idea/android/lib:asm-tree-5.0.3",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "layoutlib",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/studio/layoutlib:data/layoutlib"],
    runtime_deps = ["//prebuilts/studio/layoutlib:data/layoutlib"],
)

# managed by go/iml_to_build
java_library(
    name = "Groovy",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/codehaus/groovy/groovy-all/2.4.12:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/codehaus/groovy/groovy-all/2.4.12:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "assertJ",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/assertj/assertj-core/3.6.1:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/assertj/assertj-core/3.6.1:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "Jaxen",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/jaxen/jaxen/1.1.3:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/jaxen/jaxen/1.1.3:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "XmlBeans",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//tools/idea/lib:jsr173_1.0_api",
        "//tools/idea/lib:resolver",
        "//tools/idea/lib:xbean",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//tools/idea/lib:jsr173_1.0_api",
        "//tools/idea/lib:resolver",
        "//tools/idea/lib:xbean",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "jcip",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/net/jcip/jcip-annotations/1.0:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/net/jcip/jcip-annotations/1.0:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "swingx",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/swinglabs/swingx-core/1.6.2-2:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/swinglabs/swingx-core/1.6.2-2:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "Velocity",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:velocity"],
    runtime_deps = ["//tools/idea/lib:velocity"],
)

# managed by go/iml_to_build
java_library(
    name = "xpp3-1.1.4-min",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:xpp3-1.1.4-min"],
    runtime_deps = ["//tools/idea/lib:xpp3-1.1.4-min"],
)

# managed by go/iml_to_build
java_library(
    name = "cli-parser",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/com/github/spullara/cli-parser/cli-parser/1.1:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/com/github/spullara/cli-parser/cli-parser/1.1:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "commons-logging",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/commons-logging/commons-logging/1.2:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/commons-logging/commons-logging/1.2:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "JavaHelp",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:jh"],
    runtime_deps = ["//tools/idea/lib:jh"],
)

# managed by go/iml_to_build
java_library(
    name = "winp",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/jvnet/winp/winp/1.25:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/jvnet/winp/winp/1.25:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "miglayout-swing",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//tools/idea/lib:miglayout-core-5.0",
        "//tools/idea/lib:miglayout-swing-5.0",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//tools/idea/lib:miglayout-core-5.0",
        "//tools/idea/lib:miglayout-swing-5.0",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "jayatana",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:jayatana-1.2.4"],
    runtime_deps = ["//tools/idea/lib:jayatana-1.2.4"],
)

# managed by go/iml_to_build
java_library(
    name = "Slf4j",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//tools/idea/lib:slf4j-api-1.7.10",
        "//tools/idea/lib:slf4j-log4j12-1.7.10",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//tools/idea/lib:slf4j-api-1.7.10",
        "//tools/idea/lib:slf4j-log4j12-1.7.10",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "KotlinTest",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/kotlin-plugin-ij:Kotlin/kotlinc/lib/kotlin-test"],
    runtime_deps = ["//prebuilts/tools/common/kotlin-plugin-ij:Kotlin/kotlinc/lib/kotlin-test"],
)

# managed by go/iml_to_build
java_library(
    name = "Kryo",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//tools/idea/lib:kryo-2.22",
        "//tools/idea/lib:minlog-1.2",
        "//tools/idea/lib:objenesis-1.2",
        "//tools/idea/lib:reflectasm-1.07",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//tools/idea/lib:kryo-2.22",
        "//tools/idea/lib:minlog-1.2",
        "//tools/idea/lib:objenesis-1.2",
        "//tools/idea/lib:reflectasm-1.07",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "tcServiceMessages",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:serviceMessages"],
    runtime_deps = ["//tools/idea/lib:serviceMessages"],
)

# managed by go/iml_to_build
java_library(
    name = "Eclipse",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:ecj-4.7.2"],
    runtime_deps = ["//tools/idea/lib:ecj-4.7.2"],
)

# managed by go/iml_to_build
java_library(
    name = "Groovy-Eclipse-Batch",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/plugins/groovy/lib:groovy-eclipse-batch-2.3.4-01"],
    runtime_deps = ["//tools/idea/plugins/groovy/lib:groovy-eclipse-batch-2.3.4-01"],
)

# managed by go/iml_to_build
java_library(
    name = "nekohtml",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:nekohtml-1.9.14"],
    runtime_deps = ["//tools/idea/lib:nekohtml-1.9.14"],
)

# managed by go/iml_to_build
java_library(
    name = "freemarker",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/freemarker/freemarker/2.3.20:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/freemarker/freemarker/2.3.20:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "baksmali",
    visibility = ["//visibility:public"],
    exports = ["//tools/adt/idea/android/lib:baksmali-2.2.1"],
    runtime_deps = ["//tools/adt/idea/android/lib:baksmali-2.2.1"],
)

# managed by go/iml_to_build
java_library(
    name = "dexlib2",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//tools/adt/idea/android/lib:dexlib2-2.2.1",
        "//tools/adt/idea/android/lib:util-2.2.1",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//tools/adt/idea/android/lib:dexlib2-2.2.1",
        "//tools/adt/idea/android/lib:util-2.2.1",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "studio-profiler-grpc-1.0-jarjar",
    visibility = ["//visibility:public"],
    exports = ["//tools/base/profiler:studio-profiler-grpc-1.0-jarjar"],
    runtime_deps = ["//tools/base/profiler:studio-profiler-grpc-1.0-jarjar"],
)

# managed by go/iml_to_build
java_library(
    name = "junit5_rt",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/org/apiguardian/apiguardian-api/1.0.0:jar",
        "//prebuilts/tools/common/m2/repository/org/junit/platform/junit-platform-commons/1.0.0:jar",
        "//prebuilts/tools/common/m2/repository/org/junit/platform/junit-platform-engine/1.0.0:jar",
        "//prebuilts/tools/common/m2/repository/org/junit/platform/junit-platform-launcher/1.0.0:jar",
        "//prebuilts/tools/common/m2/repository/org/opentest4j/opentest4j/1.0.0:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/org/apiguardian/apiguardian-api/1.0.0:jar",
        "//prebuilts/tools/common/m2/repository/org/junit/platform/junit-platform-commons/1.0.0:jar",
        "//prebuilts/tools/common/m2/repository/org/junit/platform/junit-platform-engine/1.0.0:jar",
        "//prebuilts/tools/common/m2/repository/org/junit/platform/junit-platform-launcher/1.0.0:jar",
        "//prebuilts/tools/common/m2/repository/org/opentest4j/opentest4j/1.0.0:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "imageio-tiff",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/com/twelvemonkeys/common/common-image/3.2.1:jar",
        "//prebuilts/tools/common/m2/repository/com/twelvemonkeys/common/common-io/3.2.1:jar",
        "//prebuilts/tools/common/m2/repository/com/twelvemonkeys/common/common-lang/3.2.1:jar",
        "//prebuilts/tools/common/m2/repository/com/twelvemonkeys/imageio/imageio-core/3.2.1:jar",
        "//prebuilts/tools/common/m2/repository/com/twelvemonkeys/imageio/imageio-metadata/3.2.1:jar",
        "//prebuilts/tools/common/m2/repository/com/twelvemonkeys/imageio/imageio-tiff/3.2.1:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/com/twelvemonkeys/common/common-image/3.2.1:jar",
        "//prebuilts/tools/common/m2/repository/com/twelvemonkeys/common/common-io/3.2.1:jar",
        "//prebuilts/tools/common/m2/repository/com/twelvemonkeys/common/common-lang/3.2.1:jar",
        "//prebuilts/tools/common/m2/repository/com/twelvemonkeys/imageio/imageio-core/3.2.1:jar",
        "//prebuilts/tools/common/m2/repository/com/twelvemonkeys/imageio/imageio-metadata/3.2.1:jar",
        "//prebuilts/tools/common/m2/repository/com/twelvemonkeys/imageio/imageio-tiff/3.2.1:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "purejavacomm",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:purejavacomm"],
    runtime_deps = ["//tools/idea/lib:purejavacomm"],
)

# managed by go/iml_to_build
java_library(
    name = "cucumber-core",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//tools/idea/lib:cucumber-core-1.2.4",
        "//tools/idea/lib:gherkin-2.12.2",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//tools/idea/lib:cucumber-core-1.2.4",
        "//tools/idea/lib:gherkin-2.12.2",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "cucumber-java",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/info/cukes/cucumber-java/1.2.4:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/info/cukes/cucumber-java/1.2.4:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "cucumber-testing",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/info/cukes/cucumber-jvm-deps/1.0.3:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/info/cukes/cucumber-jvm-deps/1.0.3:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "JSch",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/com/jcraft/jsch/0.1.54:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/com/jcraft/jsch/0.1.54:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "tightvnc",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/tightvnc:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/tightvnc:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "http-client-3.1",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = ["//tools/idea/lib:commons-httpclient-3.1-patched"],
    # do not sort: must match IML order
    runtime_deps = ["//tools/idea/lib:commons-httpclient-3.1-patched"],
)

# managed by go/iml_to_build
java_library(
    name = "markdownj",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:markdownj-core-0.4.2-SNAPSHOT"],
    runtime_deps = ["//tools/idea/lib:markdownj-core-0.4.2-SNAPSHOT"],
)

# managed by go/iml_to_build
java_library(
    name = "JaCoCo",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//tools/idea/plugins/coverage/lib:jacocoagent",
        "//tools/idea/plugins/coverage/lib:jacocoant",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//tools/idea/plugins/coverage/lib:jacocoagent",
        "//tools/idea/plugins/coverage/lib:jacocoant",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "automaton",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:automaton"],
    runtime_deps = ["//tools/idea/lib:automaton"],
)

# managed by go/iml_to_build
java_library(
    name = "StreamEx",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/one/util/streamex/0.6.5:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/one/util/streamex/0.6.5:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "memoryfilesystem",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/com/github/marschall/memoryfilesystem/1.0.0:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/com/github/marschall/memoryfilesystem/1.0.0:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "snakeyaml",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/yaml/snakeyaml/1.17:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/yaml/snakeyaml/1.17:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "Gradle",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/org/jetbrains/intellij/deps/gradle-api-impldep/4.4:jar",
        "//prebuilts/tools/common/m2/repository/org/jetbrains/intellij/deps/gradle-api/4.4:jar",
        "//prebuilts/tools/common/m2/repository/org/jetbrains/intellij/deps/gradle-launcher/4.4:jar",
        "//prebuilts/tools/common/m2/repository/org/jetbrains/intellij/deps/gradle-wrapper/4.4:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/org/jetbrains/intellij/deps/gradle-api-impldep/4.4:jar",
        "//prebuilts/tools/common/m2/repository/org/jetbrains/intellij/deps/gradle-api/4.4:jar",
        "//prebuilts/tools/common/m2/repository/org/jetbrains/intellij/deps/gradle-launcher/4.4:jar",
        "//prebuilts/tools/common/m2/repository/org/jetbrains/intellij/deps/gradle-wrapper/4.4:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "guava-testlib",
    visibility = ["//visibility:public"],
    exports = ["//tools/adt/idea/android/lib:guava-testlib-21.0"],
    runtime_deps = ["//tools/adt/idea/android/lib:guava-testlib-21.0"],
)

# managed by go/iml_to_build
java_library(
    name = "jediterm-pty",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:jediterm-pty-2.7"],
    runtime_deps = ["//tools/idea/lib:jediterm-pty-2.7"],
)

# managed by go/iml_to_build
java_library(
    name = "gradle-api",
    visibility = ["//visibility:public"],
    exports = ["//tools/base/build-system:gradle-api_neverlink"],
    runtime_deps = ["//tools/base/build-system:gradle-api_neverlink"],
)

# managed by go/iml_to_build
java_library(
    name = "auto-value-1.4.1",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/com/google/auto/value/auto-value/1.4.1:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/com/google/auto/value/auto-value/1.4.1:jar"],
)

filegroup(
    name = "xmls",
    srcs = glob(["**/*.xml"]),
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_library(
    name = "kotlin-stdlib-jre8",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.2.10:jar",
        "//prebuilts/tools/common/m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jre8/1.2.10:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.2.10:jar",
        "//prebuilts/tools/common/m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jre8/1.2.10:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "commons-lang",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/commons-lang/commons-lang/2.6:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/commons-lang/commons-lang/2.6:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "cucumber-core_2.0.1",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/info/cukes/cucumber-html/0.2.6:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/cucumber-core/2.0.1:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/cucumber-jvm-deps/1.0.6:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/gherkin/4.1.3:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/tag-expressions/1.0.1:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/info/cukes/cucumber-html/0.2.6:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/cucumber-core/2.0.1:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/cucumber-jvm-deps/1.0.6:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/gherkin/4.1.3:jar",
        "//prebuilts/tools/common/m2/repository/io/cucumber/tag-expressions/1.0.1:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "trilead-ssh2",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/net/i2p/crypto/eddsa/0.2.0:jar",
        "//prebuilts/tools/common/m2/repository/org/connectbot/jbcrypt/jbcrypt/1.0.0:jar",
        "//prebuilts/tools/common/m2/repository/org/jenkins-ci/trilead-ssh2/build-217-jenkins-11:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/net/i2p/crypto/eddsa/0.2.0:jar",
        "//prebuilts/tools/common/m2/repository/org/connectbot/jbcrypt/jbcrypt/1.0.0:jar",
        "//prebuilts/tools/common/m2/repository/org/jenkins-ci/trilead-ssh2/build-217-jenkins-11:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "ini4j",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/jetbrains/intellij/deps/ini4j/0.5.5-2:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/jetbrains/intellij/deps/ini4j/0.5.5-2:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "commons-imaging",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/jetbrains/intellij/deps/commons-imaging/1.0-RC:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/jetbrains/intellij/deps/commons-imaging/1.0-RC:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "precompiled_jshell-frontend",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:jshell-frontend"],
    runtime_deps = ["//tools/idea/lib:jshell-frontend"],
)

# managed by go/iml_to_build
java_library(
    name = "JUnit5",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/org/apiguardian/apiguardian-api/1.0.0:jar",
        "//prebuilts/tools/common/m2/repository/org/junit/jupiter/junit-jupiter-api/5.0.0:jar",
        "//prebuilts/tools/common/m2/repository/org/junit/platform/junit-platform-commons/1.0.0:jar",
        "//prebuilts/tools/common/m2/repository/org/opentest4j/opentest4j/1.0.0:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/org/apiguardian/apiguardian-api/1.0.0:jar",
        "//prebuilts/tools/common/m2/repository/org/junit/jupiter/junit-jupiter-api/5.0.0:jar",
        "//prebuilts/tools/common/m2/repository/org/junit/platform/junit-platform-commons/1.0.0:jar",
        "//prebuilts/tools/common/m2/repository/org/opentest4j/opentest4j/1.0.0:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "sqlite",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/xerial/sqlite-jdbc/3.20.1:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/xerial/sqlite-jdbc/3.20.1:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "xml-apis-ext",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/xml-apis/xml-apis-ext/1.3.04:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/xml-apis/xml-apis-ext/1.3.04:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "aapt-proto-jarjar",
    visibility = ["//visibility:public"],
    exports = ["//tools/base/sdk-common/aapt-proto-jar-generator:aapt-proto-jarjar"],
    runtime_deps = ["//tools/base/sdk-common/aapt-proto-jar-generator:aapt-proto-jarjar"],
)

# managed by go/iml_to_build
java_library(
    name = "aia-manifest-proto-1.0-jarjar",
    visibility = ["//visibility:public"],
    exports = ["//tools/base/sdk-common/aia-manifest-jar-generator:aia-manifest-proto-1.0-jarjar"],
    runtime_deps = ["//tools/base/sdk-common/aia-manifest-jar-generator:aia-manifest-proto-1.0-jarjar"],
)

# managed by go/iml_to_build
java_library(
    name = "gant-groovy",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/codehaus/gant/gant_groovy2.3/1.9.11:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/codehaus/gant/gant_groovy2.3/1.9.11:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "kotlinx-coroutines-core",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/jetbrains/kotlinx/kotlinx-coroutines-core/0.20:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/jetbrains/kotlinx/kotlinx-coroutines-core/0.20:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "kotlinx-coroutines-jdk8",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/org/jetbrains/kotlinx/kotlinx-coroutines-jdk8/0.20:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/org/jetbrains/kotlinx/kotlinx-coroutines-jdk8/0.20:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "javaxdelta",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/com/nothome/javaxdelta/2.0.1:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/com/nothome/javaxdelta/2.0.1:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "fastutil",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/it/unimi/dsi/fastutil/7.2.1:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/it/unimi/dsi/fastutil/7.2.1:jar"],
)

# managed by go/iml_to_build
java_library(
    name = "lz4-java",
    visibility = ["//visibility:public"],
    exports = ["//tools/idea/lib:lz4-java-1.3"],
    runtime_deps = ["//tools/idea/lib:lz4-java-1.3"],
)

# managed by go/iml_to_build
java_library(
    name = "de.ruedigermoeller_fst",
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    exports = [
        "//prebuilts/tools/common/m2/repository/com/fasterxml/jackson/core/jackson-core/2.8.8:jar",
        "//prebuilts/tools/common/m2/repository/de/ruedigermoeller/fst/2.56:jar",
        "//prebuilts/tools/common/m2/repository/org/javassist/javassist/3.21.0-GA:jar",
        "//prebuilts/tools/common/m2/repository/org/objenesis/objenesis/2.5.1:jar",
    ],
    # do not sort: must match IML order
    runtime_deps = [
        "//prebuilts/tools/common/m2/repository/com/fasterxml/jackson/core/jackson-core/2.8.8:jar",
        "//prebuilts/tools/common/m2/repository/de/ruedigermoeller/fst/2.56:jar",
        "//prebuilts/tools/common/m2/repository/org/javassist/javassist/3.21.0-GA:jar",
        "//prebuilts/tools/common/m2/repository/org/objenesis/objenesis/2.5.1:jar",
    ],
)

# managed by go/iml_to_build
java_library(
    name = "jetifier-core",
    visibility = ["//visibility:public"],
    exports = ["//prebuilts/tools/common/m2/repository/com/android/tools/build/jetifier/jetifier-core/0.0.1:jar"],
    runtime_deps = ["//prebuilts/tools/common/m2/repository/com/android/tools/build/jetifier/jetifier-core/0.0.1:jar"],
)
