load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "instrumentation-util-8",
    srcs = ["src"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/java/compiler/instrumentation-util[module]"],
)
