load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.java.compiler.instrumentationUtil.java8",
    srcs = ["src"],
    iml_files = ["intellij.java.compiler.instrumentationUtil.java8.iml"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/java/compiler/instrumentation-util:intellij.java.compiler.instrumentationUtil[module]"],
)
