inputs:
  os:
    description: 'linux, windows or mac'
    required: true
  extension:
    description: 'tar.gz, exe or sit'
    required: true
runs:
  using: composite
  steps:
    - name: Checkout JetBrains/android
      uses: actions/checkout@v4.2.2
      with:
        repository: JetBrains/android
        path: android
        # It isn't possible to push release tags to both Community and Android repositories atomically.
        # Therefore, a checkout may fail with the `couldn't find remote ref` error - the next attempt will succeed.
        ref: ${{github.ref}}
    - name: Build environment
      shell: bash
      # language=bash
      run: docker build . --target intellij_idea --tag intellij_idea
    - name: Build .${{inputs.extension}}
      shell: bash
      # language=bash
      run: docker run --rm --user "$(id -u)" --volume "${PWD}:/community" intellij_idea -Dintellij.build.target.os=${{inputs.os}}