inputs:
  os:
    description: 'linux, windows or mac'
    required: true
  arch:
    description: 'x64 or aarch64'
    required: true
  extension:
    description: 'tar.gz, exe or sit'
    required: true
  product:
    description: 'a product, available options: intellij_idea, pycharm'
    required: true
runs:
  using: composite
  steps:
    - name: Checkout JetBrains/android
      uses: actions/checkout@v4.2.2
      with:
        repository: JetBrains/android
        path: android
        ref: ${{github.ref}}
    - name: Build environment
      shell: bash
      # language=bash
      run: docker build . --target ${{inputs.product}} --tag ${{inputs.product}}
    - name: Build ${{inputs.arch}}.${{inputs.extension}}
      shell: bash
      # language=bash
      run: docker run --rm --user "$(id -u)" --volume "${PWD}:/community" ${{inputs.product}} -Dintellij.build.target.os=${{inputs.os}} -Dintellij.build.target.arch=${{inputs.arch}}