inputs:
  product:
    description: 'a product, available options: intellij_idea, pycharm'
    required: true
  system_properties:
    default: ''
    description: 'any custom system properties'
    required: false
runs:
  using: composite
  steps:
    - name: Checkout JetBrains/android
      uses: actions/checkout@v4.2.2
      with:
        repository: JetBrains/android
        path: android
        ref: ${{github.ref}}
    - name: Build environment
      shell: bash
      # language=bash
      run: docker build . --target ${{inputs.product}} --tag ${{inputs.product}}
    - name: Build
      shell: bash
      # language=bash
      run: docker run --rm --user "$(id -u)" --volume "${PWD}:/community" ${{inputs.product}} ${{inputs.system_properties}}