from _typeshed import Incomplete
from typing import Final

class ClientRegistrationEndpoint:
    ENDPOINT_NAME: Final = "client_registration"
    software_statement_alg_values_supported: Incomplete
    server: Incomplete
    claims_classes: list[type[Incomplete]]
    def __init__(self, server=None, claims_classes: list[type[Incomplete]] | None = None) -> None: ...
    def __call__(self, request) -> tuple[int, dict[Incomplete, Incomplete], list[tuple[str, str]]]: ...
    def create_registration_response(self, request) -> tuple[int, dict[Incomplete, Incomplete], list[tuple[str, str]]]: ...
    def extract_client_metadata(self, request) -> dict[Incomplete, Incomplete]: ...
    def extract_software_statement(self, software_statement, request) -> dict[str, Incomplete]: ...
    def generate_client_info(self, request) -> dict[str, Incomplete]: ...
    def generate_client_registration_info(self, client, request) -> Incomplete | None: ...
    def create_endpoint_request(self, request): ...
    def generate_client_id(self, request) -> str: ...
    def generate_client_secret(self, request) -> str: ...
    def get_server_metadata(self): ...
    def authenticate_token(self, request): ...
    def resolve_public_key(self, request): ...
    def save_client(self, client_info, client_metadata, request): ...
