load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "tests_bootstrap",
    srcs = ["src"],
    iml_files = ["tests_bootstrap.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/.idea/libraries:JUnit4"],
)
