load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.tools.testsBootstrap",
    srcs = ["src"],
    iml_files = ["intellij.tools.testsBootstrap.iml"],
    visibility = ["//visibility:public"],
    runtime_deps = ["//tools/idea/platform/boot:intellij.platform.boot"],
    deps = ["//tools/idea/.idea/libraries:JUnit4"],
)
