def i8(c): ...
def o8(i): ...
def i16le(c, o: int = ...): ...
def si16le(c, o: int = ...): ...
def i32le(c, o: int = ...): ...
def si32le(c, o: int = ...): ...
def i16be(c, o: int = ...): ...
def i32be(c, o: int = ...): ...
def o16le(i): ...
def o32le(i): ...
def o16be(i): ...
def o32be(i): ...
