load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "intellij.nodeRpcClient",
    iml_files = ["intellij.nodeRpcClient.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
