load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.nodeRpcClient",
    iml_files = ["intellij.nodeRpcClient.iml"],
    visibility = ["//visibility:public"],
)
