load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "node-rpc-client",
    iml_files = ["node-rpc-client.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
