# managed by go/iml_to_build
java_import(
    name = "plexus-utils-1.5.5",
    jars = ["plexus-utils-1.5.5.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "maven-dependency-tree-1.2",
    jars = ["maven-dependency-tree-1.2.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "archetype-common-2.0-alpha-4-SNAPSHOT",
    jars = ["archetype-common-2.0-alpha-4-SNAPSHOT.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "mercury-artifact-1.0-alpha-6",
    jars = ["mercury-artifact-1.0-alpha-6.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "nexus-indexer-1.2.3",
    jars = ["nexus-indexer-1.2.3.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "commons-beanutils",
    jars = ["commons-beanutils.jar"],
    visibility = ["//visibility:public"],
)
