java_import(
    name = "plexus-utils-1.5.5",
    jars = ["plexus-utils-1.5.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "maven-dependency-tree-1.2",
    jars = ["maven-dependency-tree-1.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "archetype-common-2.0-alpha-4-SNAPSHOT",
    jars = ["archetype-common-2.0-alpha-4-SNAPSHOT.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "mercury-artifact-1.0-alpha-6",
    jars = ["mercury-artifact-1.0-alpha-6.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "nexus-indexer-1.2.3",
    jars = ["nexus-indexer-1.2.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "activation-1.1",
    jars = ["activation-1.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "commons-beanutils",
    jars = ["commons-beanutils.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
