' https://plantuml-documentation.readthedocs.io/en/latest/formatting/all-skin-params.html
skinparam monochrome true
skinparam shadowing true

skinparam DefaultFontName Roboto
skinparam DefaultMonospacedFontName "Roboto Mono"

' https://material.io/design/typography/the-type-system.html
' Body 2
skinparam DefaultFontSize 14
skinparam DefaultTextAlignment center
skinparam NoteTextAlignment left

' default 1.5
skinparam ActivityBorderThickness 1
' default 2
skinparam PartitionBorderThickness 1.5