load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.java.compiler.instrumentationUtil",
    srcs = ["src"],
    iml_files = ["intellij.java.compiler.instrumentationUtil.iml"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/.idea/libraries:ASM"],
)
