load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "instrumentation-util",
    srcs = ["src"],
    iml_files = ["instrumentation-util.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/.idea/libraries:ASM"],
)
