# managed by go/iml_to_build
java_import(
    name = "log4j-api-2.6.2",
    jars = ["log4j-api-2.6.2.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "log4j-core-2.6.2",
    jars = ["log4j-core-2.6.2.jar"],
    visibility = ["//visibility:public"],
)
