java_import(
    name = "log4j-api-2.6.2",
    jars = ["log4j-api-2.6.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "log4j-core-2.6.2",
    jars = ["log4j-core-2.6.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
