// Generated by delombok at Wed Oct 02 19:12:43 GMT 2019

public final class UtilityClassPlain {
  private static final int CONSTANT = 5;

  public static int addSomething(int in) {
    return in + CONSTANT;
  }

  @java.lang.SuppressWarnings("all")
  private UtilityClassPlain() {
    throw new java.lang.UnsupportedOperationException("This is a utility class and cannot be instantiated");
  }
}
