from _typeshed import Incomplete

from .abc import SaslMechanism

class SaslMechanismPlain(SaslMechanism):
    username: Incomplete
    password: Incomplete
    def __init__(self, **config) -> None: ...
    def auth_bytes(self): ...
    def receive(self, auth_bytes) -> None: ...
    def is_done(self): ...
    def is_authenticated(self): ...
    def auth_details(self): ...
