// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

package org.jetbrains.kotlin.idea.k2.debugger.test.cases;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.idea.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.idea.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TestMetadata;
import org.jetbrains.kotlin.idea.base.test.TestRoot;
import org.junit.runner.RunWith;

/**
 * This class is generated by {@link org.jetbrains.kotlin.testGenerator.generator.TestGenerator}.
 * DO NOT MODIFY MANUALLY.
 */
@SuppressWarnings("all")
@TestRoot("jvm-debugger/test/k2")
@TestDataPath("$CONTENT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
@TestMetadata("../testData/classNameCalculator")
public class K2ClassNameCalculatorTestGenerated extends AbstractK2ClassNameCalculatorTest {
    private void runTest(String testDataFilePath) throws Exception {
        KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
    }

    @TestMetadata("callableReferences.kt")
    public void testCallableReferences() throws Exception {
        runTest("../testData/classNameCalculator/callableReferences.kt");
    }

    @TestMetadata("delegates.kt")
    public void testDelegates() throws Exception {
        runTest("../testData/classNameCalculator/delegates.kt");
    }

    @TestMetadata("inline.kt")
    public void testInline() throws Exception {
        runTest("../testData/classNameCalculator/inline.kt");
    }

    @TestMetadata("nested.kt")
    public void testNested() throws Exception {
        runTest("../testData/classNameCalculator/nested.kt");
    }

    @TestMetadata("objectLiterals.kt")
    public void testObjectLiterals() throws Exception {
        runTest("../testData/classNameCalculator/objectLiterals.kt");
    }

    @TestMetadata("simple.kt")
    public void testSimple() throws Exception {
        runTest("../testData/classNameCalculator/simple.kt");
    }

    @TestMetadata("suspend.kt")
    public void testSuspend() throws Exception {
        runTest("../testData/classNameCalculator/suspend.kt");
    }

    @TestMetadata("topLevel.kt")
    public void testTopLevel() throws Exception {
        runTest("../testData/classNameCalculator/topLevel.kt");
    }
}
