import abc
import select
from collections.abc import Callable, Sequence
from logging import Logger
from typing import ClassVar, Final, Literal, TypeAlias, TypedDict

import pika.compat
from pika.adapters.base_connection import BaseConnection
from pika.adapters.utils.connection_workflow import AbstractAMQPConnectionWorkflow, AMQPConnectorException
from pika.adapters.utils.nbio_interface import AbstractIOServices
from pika.adapters.utils.selector_ioloop_adapter import AbstractSelectorIOLoop
from pika.connection import Connection, Parameters

SELECT_ERROR_T: TypeAlias = OSError | IOError | InterruptedError | select.error

class POLLER_PARAMS(TypedDict):
    get_wait_seconds: Callable[[], float | None]
    process_timeouts: Callable[[], None]

LOGGER: Logger
SELECT_TYPE: Literal["epoll", "kqueue", "poll"] | None

class SelectConnection(BaseConnection[IOLoop]):
    def __init__(
        self,
        parameters: Parameters | None = None,
        on_open_callback: Callable[[Connection], object] | None = None,
        on_open_error_callback: Callable[[Connection, BaseException], object] | None = None,
        on_close_callback: Callable[[Connection, BaseException], object] | None = None,
        custom_ioloop: IOLoop | AbstractIOServices | None = None,
        internal_connection_workflow: bool = True,
    ) -> None: ...
    @classmethod
    def create_connection(
        cls,
        connection_configs: Sequence[Parameters],
        on_done: Callable[[Connection | AMQPConnectorException], object],
        custom_ioloop: IOLoop | None = None,
        workflow: AbstractAMQPConnectionWorkflow | None = None,
    ) -> AbstractAMQPConnectionWorkflow: ...

class _Timeout:
    __slots__ = ("deadline", "callback")
    deadline: float
    callback: Callable[[], None]
    def __init__(self, deadline: float, callback: Callable[[], None]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...

class _Timer:
    def __init__(self) -> None: ...
    def close(self) -> None: ...
    def call_later(self, delay: float, callback: Callable[[], None]) -> _Timeout: ...
    def remove_timeout(self, timeout: _Timeout) -> None: ...
    def get_remaining_interval(self) -> float | None: ...
    def process_timeouts(self) -> None: ...

class PollEvents:
    READ: Final[int]
    WRITE: Final[int]
    ERROR: Final[int]
    HANGUP: Final[int]

class IOLoop(AbstractSelectorIOLoop[_Timeout]):
    READ: Final[int]
    WRITE: Final[int]
    ERROR: Final[int]
    def __init__(self) -> None: ...
    def close(self) -> None: ...
    def call_later(self, delay: float, callback: Callable[[], object]) -> _Timeout: ...
    def remove_timeout(self, timeout_handle: _Timeout) -> None: ...
    def add_callback_threadsafe(self, callback: Callable[[], object]) -> None: ...
    add_callback = add_callback_threadsafe
    def process_timeouts(self) -> None: ...
    def add_handler(self, fd: int, handler: Callable[[int, int], None], events: int) -> None: ...
    def update_handler(self, fd: int, events: int) -> None: ...
    def remove_handler(self, fd: int) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def activate_poller(self) -> None: ...
    def deactivate_poller(self) -> None: ...
    def poll(self) -> None: ...

class _PollerBase(pika.compat.AbstractBase, metaclass=abc.ABCMeta):
    POLL_TIMEOUT_MULT: ClassVar[int]
    def __init__(self, get_wait_seconds: Callable[[], float | None], process_timeouts: Callable[[], None]) -> None: ...
    def close(self) -> None: ...
    def wake_threadsafe(self) -> None: ...
    def add_handler(self, fileno: int, handler: Callable[[int, int], None], events: int) -> None: ...
    def update_handler(self, fileno: int, events: int) -> None: ...
    def remove_handler(self, fileno: int) -> None: ...
    def activate_poller(self) -> None: ...
    def deactivate_poller(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    @abc.abstractmethod
    def poll(self) -> None: ...

class SelectPoller(_PollerBase):
    POLL_TIMEOUT_MULT: ClassVar[int]
    def poll(self) -> None: ...

class KQueuePoller(_PollerBase):
    def __init__(self, get_wait_seconds: Callable[[], float | None], process_timeouts: Callable[[], None]) -> None: ...
    def poll(self) -> None: ...

class PollPoller(_PollerBase):
    POLL_TIMEOUT_MULT: ClassVar[int]
    def __init__(self, get_wait_seconds: Callable[[], float | None], process_timeouts: Callable[[], None]) -> None: ...
    def poll(self) -> None: ...

class EPollPoller(PollPoller):
    POLL_TIMEOUT_MULT: ClassVar[int]
