from .abstract import Deserializer, Serializer

class DefaultSerializer(Serializer, Deserializer):
    encoding: str
    def __init__(self, encoding: str = "utf-8") -> None: ...
    def serialize(self, topic: str, headers: list[tuple[str, bytes]], data: str | bytes | bytearray | memoryview | None): ...
    def deserialize(self, topic: str, headers: list[tuple[str, bytes]], data: bytes | None) -> str | None: ...
