from .default import DefaultSerializer

class JsonSerializer(DefaultSerializer):
    def serialize(self, topic: str, headers: list[tuple[str, bytes]], data): ...
    def deserialize(self, topic: str, headers: list[tuple[str, bytes]], data): ...
