// Copyright 2000-2021 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE file.
package org.jetbrains.kotlin.idea.artifacts

object KotlinArtifactNames {
    const val JETBRAINS_ANNOTATIONS = "annotations-13.0.jar"
    const val KOTLIN_STDLIB = "kotlin-stdlib.jar"
    const val KOTLIN_STDLIB_MINIMAL_FOR_TESTS = "kotlin-stdlib-minimal-for-test.jar"
    const val KOTLIN_STDLIB_SOURCES = "kotlin-stdlib-sources.jar"
    const val KOTLIN_STDLIB_JDK7 = "kotlin-stdlib-jdk7.jar"
    const val KOTLIN_STDLIB_JDK7_SOURCES = "kotlin-stdlib-jdk7-sources.jar"
    const val KOTLIN_STDLIB_JDK8 = "kotlin-stdlib-jdk8.jar"
    const val KOTLIN_STDLIB_JDK8_SOURCES = "kotlin-stdlib-jdk8-sources.jar"
    const val KOTLIN_REFLECT = "kotlin-reflect.jar"
    const val KOTLIN_STDLIB_JS = "kotlin-stdlib-js.jar"
    const val KOTLIN_STDLIB_JS_SOURCES = "kotlin-stdlib-js-sources.jar"
    const val KOTLIN_TEST = "kotlin-test.jar"
    const val KOTLIN_TEST_JUNIT = "kotlin-test-junit.jar"
    const val KOTLIN_TEST_JS = "kotlin-test-js.jar"
    const val KOTLIN_MAIN_KTS = "kotlin-main-kts.jar"
    const val KOTLIN_SCRIPT_RUNTIME = "kotlin-script-runtime.jar"
    const val KOTLIN_SCRIPTING_COMMON = "kotlin-scripting-common.jar"
    const val KOTLIN_SCRIPTING_JVM = "kotlin-scripting-jvm.jar"
    const val KOTLIN_COMPILER = "kotlin-compiler.jar"
    const val LOMBOK_COMPILER_PLUGIN = "lombok-compiler-plugin.jar"
    const val KOTLIN_ANNOTATIONS_JVM = "kotlin-annotations-jvm.jar"
    const val TROVE4J = "trove4j.jar"
    const val KOTLIN_DAEMON = "kotlin-daemon.jar"
    const val KOTLIN_SCRIPTING_COMPILER = "kotlin-scripting-compiler.jar"
    const val KOTLIN_SCRIPTING_COMPILER_IMPL = "kotlin-scripting-compiler-impl.jar"
    const val ALLOPEN_COMPILER_PLUGIN = "allopen-compiler-plugin.jar"
    const val NOARG_COMPILER_PLUGIN = "noarg-compiler-plugin.jar"
    const val SAM_WITH_RECEIVER_COMPILER_PLUGIN = "sam-with-receiver-compiler-plugin.jar"
    const val KOTLINX_SERIALIZATION_COMPILER_PLUGIN = "kotlinx-serialization-compiler-plugin.jar"
}