# IntelliJ Laf MacOs specific settings
PopupMenuUI=com.intellij.ide.ui.laf.intellij.MacPopupMenuUI

# Android Studio: temporary fix. Until we switch to JDK11, we override the
# MenuBarUI definition in intellijlaf.properties which uses Swing's BasicMenuBarUI.
MenuBarUI=com.apple.laf.AquaMenuBarUI