#  Copyright 2000-2025 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

from typing import Any

CANCEL: Any
NO_RETVAL: Any

def listen(target, identifier, fn, *args, **kw) -> None: ...
def listens_for(target, identifier, *args, **kw): ...
def remove(target, identifier, fn) -> None: ...
def contains(target, identifier, fn): ...
