java_import(
    name = "testng",
    jars = ["testng.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jcommander",
    jars = ["jcommander.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
