# managed by go/iml_to_build
java_import(
    name = "testng",
    jars = ["testng.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jcommander",
    jars = ["jcommander.jar"],
    visibility = ["//visibility:public"],
)
