from collections.abc import Callable
from contextlib import AbstractContextManager
from typing import Any

from django.contrib.staticfiles.testing import StaticLiveServerTestCase
from django.test.selenium import SeleniumTestCase
from django.utils.csp import CSP as CSP
from django.utils.functional import _StrOrPromise

class AdminSeleniumTestCase(SeleniumTestCase, StaticLiveServerTestCase):
    def wait_until(self, callback: Callable[..., Any], timeout: int = 10) -> None: ...
    def wait_for_and_switch_to_popup(self, num_windows: int = 2, timeout: int = 10) -> None: ...
    def wait_for(self, css_selector: str, timeout: int = 10) -> None: ...
    def wait_for_text(self, css_selector: str, text: str, timeout: int = 10) -> None: ...
    def wait_for_value(self, css_selector: str, text: str, timeout: int = 10) -> None: ...
    def wait_until_visible(self, css_selector: str, timeout: int = 10) -> None: ...
    def wait_until_invisible(self, css_selector: str, timeout: int = 10) -> None: ...
    def wait_page_ready(self, timeout: int = 10) -> None: ...
    def wait_page_loaded(self, timeout: int = 10) -> AbstractContextManager[None]: ...
    def trigger_resize(self) -> None: ...
    def admin_login(self, username: str, password: str, login_url: _StrOrPromise = "/admin/") -> None: ...
    def select_option(self, selector: str, value: Any) -> None: ...
    def deselect_option(self, selector: str, value: Any) -> None: ...
    def assertCountSeleniumElements(self, selector: str, count: int, root_element: Any = None) -> None: ...
    def assertSelectOptions(self, selector: str, values: Any) -> None: ...
    def assertSelectedOptions(self, selector: str, values: Any) -> None: ...
    def is_disabled(self, selector: str) -> bool: ...
