load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.externalSystem.rt",
    srcs = ["src"],
    iml_files = ["intellij.platform.externalSystem.rt.iml"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//tools/idea/.idea/libraries:jetbrains-annotations-java5",
        "//tools/idea/platform/object-serializer:intellij.platform.objectSerializer.annotations[module]",
    ],
)
