load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "intellij.platform.externalSystem.rt",
    srcs = ["src"],
    iml_files = ["intellij.platform.externalSystem.rt.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/platform/annotations:intellij.platform.annotations.java5[module]"],
)
