load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "external-system-rt",
    srcs = ["src"],
    iml_files = ["external-system-rt.iml"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/platform/annotations[module]"],
)
