# suppress inspection "UnusedProperty" for whole file
darcula.selectionBackground=2F65CA
SplitPaneUI=com.intellij.ide.ui.laf.darcula.ui.DarculaSplitPaneUI

# Android Studio: temporary fix. Until we switch to JDK11, we override the
# MenuBarUI definition in darcula.properties which uses Swing's BasicMenuBarUI.
MenuBarUI=com.apple.laf.AquaMenuBarUI

MenuItem.border=0,5,2,5
Menu.border=0,5,2,5

PopupMenuSeparatorUI=com.intellij.ide.ui.laf.darcula.ui.DarculaMenuSeparatorUI
PopupMenuSeparator.height=12
PopupMenuSeparator.stripeWidth=2
PopupMenuSeparator.stripeIndent=5

PopupMenuUI=com.intellij.ide.ui.laf.intellij.MacPopupMenuUI
PopupMenu.borderInsets=4,0,4,0
PopupMenu.borderWidth=0

EditorTabs.underlinedTabBackground=4e5254

HelpTooltip.descriptionSizeDelta=-1
HelpTooltip.mouseCursorOffset=17