package icons;

import com.intellij.openapi.util.IconLoader;

import javax.swing.*;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class UIDesignerNewIcons {
  private static Icon load(String path) {
    return IconLoader.getIcon(path, UIDesignerNewIcons.class);
  }

  public static final Icon ToolWindow = load("/com/intellij/designer/icons/toolWindow.png"); // 13x13
}
