// Copyright 2000-2024 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

package org.jetbrains.kotlin.idea.k2;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.idea.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.idea.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TestMetadata;
import org.jetbrains.kotlin.idea.base.test.TestRoot;
import org.junit.runner.RunWith;

/**
 * This class is generated by {@link org.jetbrains.kotlin.testGenerator.generator.TestGenerator}.
 * DO NOT MODIFY MANUALLY.
 */
@SuppressWarnings("all")
@TestRoot("code-insight/kotlin.code-insight.k2")
@TestDataPath("$CONTENT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
@TestMetadata("../../idea/tests/testData/codeInsight/expressionType")
public class K2ExpressionTypeTestGenerated extends AbstractK2ExpressionTypeTest {
    private void runTest(String testDataFilePath) throws Exception {
        KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
    }

    @TestMetadata("AnonymousObject.kt")
    public void testAnonymousObject() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/AnonymousObject.kt");
    }

    @TestMetadata("ArgumentName.kt")
    public void testArgumentName() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/ArgumentName.kt");
    }

    @TestMetadata("BlockBodyFunction.kt")
    public void testBlockBodyFunction() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/BlockBodyFunction.kt");
    }

    @TestMetadata("IfAsExpression.kt")
    public void testIfAsExpression() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/IfAsExpression.kt");
    }

    @TestMetadata("IfAsExpressionInsideBlock.kt")
    public void testIfAsExpressionInsideBlock() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/IfAsExpressionInsideBlock.kt");
    }

    @TestMetadata("IntersectionTypeWithStarProjection.kt")
    public void testIntersectionTypeWithStarProjection() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/IntersectionTypeWithStarProjection.kt");
    }

    @TestMetadata("Kt11601.kt")
    public void testKt11601() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/Kt11601.kt");
    }

    @TestMetadata("Lambda.kt")
    public void testLambda() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/Lambda.kt");
    }

    @TestMetadata("LambdaParameterWithType.kt")
    public void testLambdaParameterWithType() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/LambdaParameterWithType.kt");
    }

    @TestMetadata("LambdaParameterWithoutType.kt")
    public void testLambdaParameterWithoutType() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/LambdaParameterWithoutType.kt");
    }

    @TestMetadata("LoopVariableWithType.kt")
    public void testLoopVariableWithType() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/LoopVariableWithType.kt");
    }

    @TestMetadata("LoopVariableWithoutType.kt")
    public void testLoopVariableWithoutType() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/LoopVariableWithoutType.kt");
    }

    @TestMetadata("MethodName.kt")
    public void testMethodName() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/MethodName.kt");
    }

    @TestMetadata("MethodReference.kt")
    public void testMethodReference() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/MethodReference.kt");
    }

    @TestMetadata("MultiDeclaration.kt")
    public void testMultiDeclaration() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/MultiDeclaration.kt");
    }

    @TestMetadata("MultiDeclarationInLambda.kt")
    public void testMultiDeclarationInLambda() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/MultiDeclarationInLambda.kt");
    }

    @TestMetadata("MultiDeclarationInLoop.kt")
    public void testMultiDeclarationInLoop() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/MultiDeclarationInLoop.kt");
    }

    @TestMetadata("PropertyAccessor.kt")
    public void testPropertyAccessor() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/PropertyAccessor.kt");
    }

    @TestMetadata("SmartCast.kt")
    public void testSmartCast() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/SmartCast.kt");
    }

    @TestMetadata("SoftSmartCast.kt")
    public void testSoftSmartCast() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/SoftSmartCast.kt");
    }

    @TestMetadata("SoftSmartCastMultipleTypes.kt")
    public void testSoftSmartCastMultipleTypes() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/SoftSmartCastMultipleTypes.kt");
    }

    @TestMetadata("ThisInLambda.kt")
    public void testThisInLambda() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/ThisInLambda.kt");
    }

    @TestMetadata("typeOfLambda.kt")
    public void testTypeOfLambda() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/typeOfLambda.kt");
    }

    @TestMetadata("VariableDeclaration.kt")
    public void testVariableDeclaration() throws Exception {
        runTest("../../idea/tests/testData/codeInsight/expressionType/VariableDeclaration.kt");
    }
}
