version = "1.3.*"
upstream_repository = "https://github.com/afonasev/flake8-plugin-utils"
partial_stub = true
obsolete_since = "1.3.3" # Released on 2023-06-26

[tool.stubtest]
ignore_missing_stub = true
