<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>toml</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>TOML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#groups</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#key_pair</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#invalid</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=#)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.toml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.toml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.number-sign.toml</string>
				</dict>
			</array>
		</dict>
		<key>groups</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.section.begin.toml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>[^\s.]+</string>
									<key>name</key>
									<string>entity.name.section.toml</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.section.begin.toml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(\[)([^\[\]]*)(\])</string>
					<key>name</key>
					<string>meta.group.toml</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.section.begin.toml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>[^\s.]+</string>
									<key>name</key>
									<string>entity.name.section.toml</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.section.begin.toml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(\[\[)([^\[\]]*)(\]\])</string>
					<key>name</key>
					<string>meta.group.double.toml</string>
				</dict>
			</array>
		</dict>
		<key>invalid</key>
		<dict>
			<key>match</key>
			<string>\S+(\s*(?=\S))?</string>
			<key>name</key>
			<string>invalid.illegal.not-allowed-here.toml</string>
		</dict>
		<key>key_pair</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([A-Za-z0-9_-]+)\s*(=)\s*</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.key.toml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.toml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=\S)(?&lt;!=)|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#primatives</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((")(.*?)("))\s*(=)\s*</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.key.toml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.toml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\\([btnfr"\\]|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})</string>
									<key>name</key>
									<string>constant.character.escape.toml</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\\[^btnfr"\\]</string>
									<key>name</key>
									<string>invalid.illegal.escape.toml</string>
								</dict>
								<dict>
									<key>match</key>
									<string>"</string>
									<key>name</key>
									<string>invalid.illegal.not-allowed-here.toml</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.end.toml</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.toml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=\S)(?&lt;!=)|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#primatives</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((')([^']*)('))\s*(=)\s*</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.key.toml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.begin.toml</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.end.toml</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.toml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=\S)(?&lt;!=)|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#primatives</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x)
						(
							(
								(?:
									[A-Za-z0-9_-]+				# Bare key
								  | "  (?:[^"\\]|\\.)* "		# Double quoted key
								  | ' [^']*          '		# Sindle quoted key
								)
								(?:
									\s* \. \s*					# Dot
								  | (?= \s* =)					#   or look-ahead for equals
								)
							){2,}								# Ensure at least one dot
						)
						\s*(=)\s*
					</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.key.toml</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\.</string>
									<key>name</key>
									<string>punctuation.separator.variable.toml</string>
								</dict>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.variable.begin.toml</string>
										</dict>
										<key>2</key>
										<dict>
											<key>patterns</key>
											<array>
												<dict>
													<key>match</key>
													<string>\\([btnfr"\\]|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})</string>
													<key>name</key>
													<string>constant.character.escape.toml</string>
												</dict>
												<dict>
													<key>match</key>
													<string>\\[^btnfr"\\]</string>
													<key>name</key>
													<string>invalid.illegal.escape.toml</string>
												</dict>
											</array>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.variable.end.toml</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(")((?:[^"\\]|\\.)*)(")</string>
								</dict>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.variable.begin.toml</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.variable.end.toml</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(')[^']*(')</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.toml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Dotted key</string>
					<key>end</key>
					<string>(?&lt;=\S)(?&lt;!=)|$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#primatives</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>primatives</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.toml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"{3,5}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.toml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.triple.double.toml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\([btnfr"\\]|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})</string>
							<key>name</key>
							<string>constant.character.escape.toml</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\[^btnfr"\\\n]</string>
							<key>name</key>
							<string>invalid.illegal.escape.toml</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\G"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.toml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.toml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.toml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\([btnfr"\\]|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})</string>
							<key>name</key>
							<string>constant.character.escape.toml</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\[^btnfr"\\]</string>
							<key>name</key>
							<string>invalid.illegal.escape.toml</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\G'''</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.toml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'{3,5}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.toml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.triple.single.toml</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\G'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.toml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.toml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.toml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\G(?x)
						[0-9]{4}
						-
						(0[1-9]|1[012])
						-
						(?!00|3[2-9])[0-3][0-9]
						(
							[Tt ]
							(?!2[5-9])[0-2][0-9]
							:
							[0-5][0-9]
							:
							(?!6[1-9])[0-6][0-9]
							(\.[0-9]+)?
							(
								Z
							  | [+-](?!2[5-9])[0-2][0-9]:[0-5][0-9]
							)?
						)?
					</string>
					<key>name</key>
					<string>constant.other.date.toml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\G(?x)
						(?!2[5-9])[0-2][0-9]
						:
						[0-5][0-9]
						:
						(?!6[1-9])[0-6][0-9]
						(\.[0-9]+)?
					</string>
					<key>name</key>
					<string>constant.other.time.toml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\G(true|false)</string>
					<key>name</key>
					<string>constant.language.boolean.toml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\G0x\h(\h|_\h)*</string>
					<key>name</key>
					<string>constant.numeric.hex.toml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\G0o[0-7]([0-7]|_[0-7])*</string>
					<key>name</key>
					<string>constant.numeric.octal.toml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\G0b[01]([01]|_[01])*</string>
					<key>name</key>
					<string>constant.numeric.binary.toml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\G[+-]?(inf|nan)</string>
					<key>name</key>
					<string>constant.numeric.toml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)
						\G
						(
						    [+-]?
						    (
								0
							  | ([1-9](([0-9]|_[0-9])+)?)
							)
						)
						(?=[.eE])
						(
						    \.
						    ([0-9](([0-9]|_[0-9])+)?)
						)?
						(
						    [eE]
						    ([+-]?[0-9](([0-9]|_[0-9])+)?)
						)?
					</string>
					<key>name</key>
					<string>constant.numeric.float.toml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)
						\G
						(
						    [+-]?
						    (
								0
							  | ([1-9](([0-9]|_[0-9])+)?)
							)
						)
					</string>
					<key>name</key>
					<string>constant.numeric.integer.toml</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\G\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.begin.toml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.end.toml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.array.toml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?=["'']|[+-]?[0-9]|[+-]?(inf|nan)|true|false|\[|\{)</string>
							<key>end</key>
							<string>,|(?=])</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.array.toml</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#primatives</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#comments</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#invalid</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#invalid</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\G\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.inline-table.begin.toml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.inline-table.end.toml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.inline-table.toml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?=\S)</string>
							<key>end</key>
							<string>,|(?=})</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.inline-table.toml</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#key_pair</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.toml</string>
	<key>uuid</key>
	<string>7DEF2EDB-5BB7-4DD2-9E78-3541A26B7923</string>
</dict>
</plist>
