from _typeshed import Incomplete, ReadableBuffer, Unused
from collections.abc import Iterable
from typing import SupportsIndex

class EncodeBuffer:
    __slots__ = ("buf", "pos")
    buf: bytearray
    pos: int
    def __init__(self, size: Iterable[SupportsIndex] | SupportsIndex | ReadableBuffer = 65536) -> None: ...
    def reset(self) -> None: ...
    def ensure(self, needed: int) -> None: ...
    def result(self) -> bytearray: ...

class EncodeBufferPool:
    @classmethod
    def acquire(cls) -> _PooledBuffer: ...

class _PooledBuffer:
    __slots__ = ("_pool", "_buf")
    def __init__(self, pool: EncodeBufferPool) -> None: ...
    def __enter__(self) -> EncodeBuffer | Incomplete: ...
    def __exit__(self, *exc: Unused): ...
