from _typeshed import Incomplete

class TaggedFields:
    def __init__(self, fields) -> None: ...
    def encode(self, item, version=None) -> bytes: ...
    def encode_into(self, item, out, version=None) -> None: ...
    def decode(self, data, version=None) -> dict[str, Incomplete]: ...
    @classmethod
    def decode_empty(cls, data) -> None: ...
    @classmethod
    def encode_empty(cls) -> bytes: ...
