from _typeshed import Incomplete

from ..rfc7662 import IntrospectionEndpoint
from .claims import JWTAccessTokenClaims

class JWTIntrospectionEndpoint(IntrospectionEndpoint):
    ENDPOINT_NAME: str
    issuer: Incomplete
    def __init__(self, issuer, server=None, *args, **kwargs) -> None: ...
    def create_endpoint_response(self, request): ...
    def authenticate_token(self, request, client) -> JWTAccessTokenClaims | None: ...
    def create_introspection_payload(self, token: JWTAccessTokenClaims) -> dict[str, Incomplete]: ...
    def get_jwks(self): ...
    def get_username(self, user_id: str) -> str: ...
