simple_brackets = [abcdef
// simple_brackets = [abcdef]
simple_parethesis = (a, b, c, d
// simple_parethesis = (a, b, c, d)
simple_braces = { a, b,
// simple_braces = { a, b,}
simple_string = "hello world"
// simple_string = "hello world"
string_param = ("abc
// string_param = ("abc")
abracadabra = "())a({)))"a({[")((a)(({)b[]{"
// abracadabra = "())a({)))"a({[")((a)(({)b[]{"]})
bracket_in_string = "(" + "("
// bracket_in_string = "(" + "("
closing_bracket_in_string = (`)`
// closing_bracket_in_string = (`)`)
closing_bracket_in_regex = (/)/
// closing_bracket_in_regex = (/)/)
escaped_quotes_in_string = "\"" + x + "\""
// escaped_quotes_in_string = "\"" + x + "\""
incorrect_code = ""Hello world
// incorrect_code = ""Hello world
closing_slash_in_regex = /dfagasdfg
// closing_slash_in_regex = /dfagasdfg/
closing_back_quote = `asdffasd ${x}
// closing_back_quote = `asdffasd ${x}`
