from ctypes import c_char_p
from typing import Any

class gdal_char_p(c_char_p): ...

def bool_output(func: Any, argtypes: Any, errcheck: Any | None = ...) -> Any: ...
def double_output(func: Any, argtypes: Any, errcheck: bool = ..., strarg: bool = ..., cpl: bool = ...) -> Any: ...
def geom_output(func: Any, argtypes: Any, offset: Any | None = ...) -> Any: ...
def int_output(func: Any, argtypes: Any, errcheck: Any | None = ...) -> Any: ...
def int64_output(func: Any, argtypes: Any) -> Any: ...
def srs_output(func: Any, argtypes: Any) -> Any: ...
def const_string_output(
    func: Any, argtypes: Any, offset: Any | None = ..., decoding: Any | None = ..., cpl: bool = ...
) -> Any: ...
def string_output(
    func: Any, argtypes: Any, offset: int = ..., str_result: bool = ..., decoding: Any | None = ...
) -> Any: ...
def void_output(func: Any, argtypes: Any, errcheck: bool = ..., cpl: bool = ...) -> Any: ...
def voidptr_output(func: Any, argtypes: Any, errcheck: bool = ...) -> Any: ...
def chararray_output(func: Any, argtypes: Any, errcheck: bool = ...) -> Any: ...
