from distutils.cmd import Command
from typing import Any, Dict, Iterable, Mapping, Optional, Tuple, Type

class Distribution:
    cmdclass: Dict[str, Type[Command]]
    def __init__(self, attrs: Optional[Mapping[str, Any]] = ...) -> None: ...
    def get_option_dict(self, command: str) -> Dict[str, Tuple[str, str]]: ...
    def parse_config_files(self, filenames: Optional[Iterable[str]] = ...) -> None: ...
    def get_command_obj(self, command: str, create: bool = ...) -> Optional[Command]: ...
