java_import(
    name = "gradle-build-init-3.1",
    jars = ["gradle-build-init-3.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-ide-3.1",
    jars = ["gradle-ide-3.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-dependency-management-3.1",
    jars = ["gradle-dependency-management-3.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-language-java-3.1",
    jars = ["gradle-language-java-3.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-language-jvm-3.1",
    jars = ["gradle-language-jvm-3.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-platform-base-3.1",
    jars = ["gradle-platform-base-3.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-platform-jvm-3.1",
    jars = ["gradle-platform-jvm-3.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-plugins-3.1",
    jars = ["gradle-plugins-3.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-testing-base-3.1",
    jars = ["gradle-testing-base-3.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-testing-jvm-3.1",
    jars = ["gradle-testing-jvm-3.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-scala-3.1",
    jars = ["gradle-scala-3.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-language-scala-3.1",
    jars = ["gradle-language-scala-3.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
