java_import(
    name = "gradle-build-init-3.2",
    jars = ["gradle-build-init-3.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-ide-3.2",
    jars = ["gradle-ide-3.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-language-java-3.2",
    jars = ["gradle-language-java-3.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-language-jvm-3.2",
    jars = ["gradle-language-jvm-3.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-platform-base-3.2",
    jars = ["gradle-platform-base-3.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-platform-jvm-3.2",
    jars = ["gradle-platform-jvm-3.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-plugins-3.2",
    jars = ["gradle-plugins-3.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-testing-base-3.2",
    jars = ["gradle-testing-base-3.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-testing-jvm-3.2",
    jars = ["gradle-testing-jvm-3.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-scala-3.2",
    jars = ["gradle-scala-3.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-language-scala-3.2",
    jars = ["gradle-language-scala-3.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
