java_import(
    name = "gradle-build-init-4.0",
    jars = ["gradle-build-init-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-dependency-management-4.0",
    jars = ["gradle-dependency-management-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-ide-4.0",
    jars = ["gradle-ide-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-language-java-4.0",
    jars = ["gradle-language-java-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-language-jvm-4.0",
    jars = ["gradle-language-jvm-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-language-scala-4.0",
    jars = ["gradle-language-scala-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-platform-base-4.0",
    jars = ["gradle-platform-base-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-platform-jvm-4.0",
    jars = ["gradle-platform-jvm-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-plugins-4.0",
    jars = ["gradle-plugins-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-scala-4.0",
    jars = ["gradle-scala-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-testing-base-4.0",
    jars = ["gradle-testing-base-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gradle-testing-jvm-4.0",
    jars = ["gradle-testing-jvm-4.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
