java_import(
    name = "guava-18.0",
    jars = ["guava-18.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "cdi-api-1.0",
    jars = ["cdi-api-1.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jsoup-1.7.2",
    jars = ["jsoup-1.7.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "commons-io-2.2",
    jars = ["commons-io-2.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "javax.inject-1",
    jars = ["javax.inject-1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jsr250-api-1.0",
    jars = ["jsr250-api-1.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "wagon-file-2.8",
    jars = ["wagon-file-2.8.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "aopalliance-1.0",
    jars = ["aopalliance-1.0.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "commons-cli-1.2",
    jars = ["commons-cli-1.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "slf4j-api-1.7.5",
    jars = ["slf4j-api-1.7.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "commons-lang-2.6",
    jars = ["commons-lang-2.6.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "maven-core-3.2.5",
    jars = ["maven-core-3.2.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "maven-model-3.2.5",
    jars = ["maven-model-3.2.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "plexus-cipher-1.7",
    jars = ["plexus-cipher-1.7.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "maven-compat-3.2.5",
    jars = ["maven-compat-3.2.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "slf4j-simple-1.7.5",
    jars = ["slf4j-simple-1.7.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "plexus-utils-3.0.20",
    jars = ["plexus-utils-3.0.20.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "maven-artifact-3.2.5",
    jars = ["maven-artifact-3.2.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "maven-embedder-3.2.5",
    jars = ["maven-embedder-3.2.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "maven-settings-3.2.5",
    jars = ["maven-settings-3.2.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "wagon-http-2.8-shaded",
    jars = ["wagon-http-2.8-shaded.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "wagon-http-shared-2.8",
    jars = ["wagon-http-shared-2.8.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "maven-plugin-api-3.2.5",
    jars = ["maven-plugin-api-3.2.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "wagon-provider-api-2.8",
    jars = ["wagon-provider-api-2.8.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "sisu-guice-3.2.3-no_aop",
    jars = ["sisu-guice-3.2.3-no_aop.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "maven-model-builder-3.2.5",
    jars = ["maven-model-builder-3.2.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "plexus-interpolation-1.21",
    jars = ["plexus-interpolation-1.21.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "plexus-sec-dispatcher-1.3",
    jars = ["plexus-sec-dispatcher-1.3.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "aether-api-1.0.0.v20140518",
    jars = ["aether-api-1.0.0.v20140518.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "aether-spi-1.0.0.v20140518",
    jars = ["aether-spi-1.0.0.v20140518.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "aether-impl-1.0.0.v20140518",
    jars = ["aether-impl-1.0.0.v20140518.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "aether-util-1.0.0.v20140518",
    jars = ["aether-util-1.0.0.v20140518.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "maven-aether-provider-3.2.5",
    jars = ["maven-aether-provider-3.2.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "maven-settings-builder-3.2.5",
    jars = ["maven-settings-builder-3.2.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "maven-repository-metadata-3.2.5",
    jars = ["maven-repository-metadata-3.2.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "org.eclipse.sisu.inject-0.3.0.M1",
    jars = ["org.eclipse.sisu.inject-0.3.0.M1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "org.eclipse.sisu.plexus-0.3.0.M1",
    jars = ["org.eclipse.sisu.plexus-0.3.0.M1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "plexus-component-annotations-1.5.5",
    jars = ["plexus-component-annotations-1.5.5.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "aether-connector-basic-1.0.0.v20140518",
    jars = ["aether-connector-basic-1.0.0.v20140518.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "aether-transport-wagon-1.0.0.v20140518",
    jars = ["aether-transport-wagon-1.0.0.v20140518.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
