# managed by go/iml_to_build
java_import(
    name = "coverage-report",
    jars = ["coverage-report.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "coverage-report-idea",
    jars = ["coverage-report-idea.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "freemarker",
    jars = ["freemarker.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jacocoant",
    jars = ["jacocoant.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "jacocoagent",
    jars = ["jacocoagent.jar"],
    visibility = ["//visibility:public"],
)
