// Copyright 2000-2021 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE file.
package org.jetbrains.plugins.github.api

object GHGQLQueries {
  const val findOrganizationTeams = "graphql/query/findOrganizationTeams.graphql"
  const val findUser = "graphql/query/findUser.graphql"
  const val findRepository = "graphql/query/findRepository.graphql"
  const val getPullRequestTemplates = "graphql/query/getPullRequestTemplates.graphql"
  const val getProtectionRules = "graphql/query/getProtectionRules.graphql"
  const val updateIssueComment = "graphql/query/updateIssueComment.graphql"
  const val deleteIssueComment = "graphql/query/deleteIssueComment.graphql"
  const val issueSearch = "graphql/query/issueSearch.graphql"
  const val metrics = "graphql/query/metrics.graphql"
  const val createPullRequest = "graphql/query/createPullRequest.graphql"
  const val findPullRequest = "graphql/query/findPullRequest.graphql"
  const val findPullRequestId = "graphql/query/findPullRequestId.graphql"
  const val updatePullRequest = "graphql/query/updatePullRequest.graphql"
  const val markPullRequestReadyForReview = "graphql/query/markPullRequestReadyForReview.graphql"
  const val pullRequestTimeline = "graphql/query/pullRequestTimeline.graphql"
  const val pullRequestReviewThreads = "graphql/query/pullRequestReviewThreads.graphql"
  const val pullRequestCommits = "graphql/query/pullRequestCommits.graphql"
  const val pullRequestMergeabilityData = "graphql/query/findPullRequestMergeability.graphql"
  const val pullRequestFiles = "graphql/query/pullRequestFiles.graphql"
  const val markFileAsViewed = "graphql/query/markFileAsViewed.graphql"
  const val unmarkFileAsViewed = "graphql/query/unmarkFileAsViewed.graphql"
  const val createReview = "graphql/query/createReview.graphql"
  const val submitReview = "graphql/query/submitReview.graphql"
  const val updateReview = "graphql/query/updateReview.graphql"
  const val deleteReview = "graphql/query/deleteReview.graphql"
  const val pendingReview = "graphql/query/findPendingReview.graphql"
  const val addReviewComment = "graphql/query/addReviewComment.graphql"
  const val deleteReviewComment = "graphql/query/deleteReviewComment.graphql"
  const val updateReviewComment = "graphql/query/updateReviewComment.graphql"
  const val addPullRequestReviewThread = "graphql/query/addPullRequestReviewThread.graphql"
  const val resolveReviewThread = "graphql/query/resolveReviewThread.graphql"
  const val unresolveReviewThread = "graphql/query/unresolveReviewThread.graphql"
  const val addReaction = "graphql/query/addReaction.graphql"
  const val removeReaction = "graphql/query/removeReaction.graphql"
  const val getRepositoryCommitStatus = "graphql/query/getRepositoryCommitStatusShort.graphql"
  const val getRepositoryCommitStatusContexts = "graphql/query/getRepositoryCommitStatusContexts.graphql"
}