{

  parserClass="com.jetbrains.typoscript.lang.TypoScriptGeneratedParser"
  stubParserClass="com.jetbrains.typoscript.lang.TypoScriptParserUtil"
  generateStubParser = true
 // generateFirstCheck = true
  tokenTypeClass="com.jetbrains.typoscript.lang.TypoScriptTokenType"
  elementTypeClass="com.jetbrains.typoscript.lang.TypoScriptTokenType"
  elementTypeHolderClass="com.jetbrains.typoscript.lang.TypoScriptElementTypes"
  generateTokens=false
  parserImports="static com.jetbrains.typoscript.lang.TypoScriptTokenTypes.*"

  generatePsi=true
  implements="com.jetbrains.typoscript.lang.psi.TypoScriptCompositeElement"
  extends="com.jetbrains.typoscript.lang.psi.TypoScriptCompositeElementImpl"

  psiImplClassSuffix="Impl"
  psiPackage="com.jetbrains.typoscript.lang.psi"
  psiImplPackage="com.jetbrains.typoscript.lang.psi.impl"
}


c_style_comment_element ::= C_STYLE_COMMENT
one_line_comment_element ::= ONE_LINE_COMMENT
include_statement_element ::= ONE_LINE_COMMENT
condition_element ::= CONDITION


object_path ::= OBJECT_PATH_ENTITY (OBJECT_PATH_SEPARATOR OBJECT_PATH_ENTITY)*
private internal_object_path ::= object_path | OBJECT_PATH_SEPARATOR object_path

assignment ::= ASSIGNMENT ASSIGNMENT_VALUE

value_modification ::= MODIFICATION_OPERATOR MODIFICATION_OPERATOR_FUNCTION MODIFICATION_OPERATOR_FUNCTION_PARAM_BEGIN MODIFICATION_OPERATOR_FUNCTION_ARGUMENT MODIFICATION_OPERATOR_FUNCTION_PARAM_END

multiline_value_assignment ::= MULTILINE_VALUE_OPERATOR_BEGIN IGNORED_TEXT? (MULTILINE_VALUE)* MULTILINE_VALUE_OPERATOR_END IGNORED_TEXT?

copying ::=  COPYING_OPERATOR object_path

unsetting ::=  UNSETTING_OPERATOR IGNORED_TEXT?

private internal_expression ::= internal_object_path { assignment | value_modification | multiline_value_assignment | copying | unsetting | code_block}

code_block ::= object_path CODE_BLOCK_OPERATOR_BEGIN IGNORED_TEXT? (internal_expression)* CODE_BLOCK_OPERATOR_END IGNORED_TEXT?






