java_import(
    name = "nexus-indexer-3.0.4",
    jars = ["nexus-indexer-3.0.4.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "maven-dependency-tree-1.2",
    jars = ["maven-dependency-tree-1.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "archetype-common-2.2",
    jars = ["archetype-common-2.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "archetype-catalog-2.2",
    jars = ["archetype-catalog-2.2.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "nexus-indexer-artifact-1.0.1",
    jars = ["nexus-indexer-artifact-1.0.1.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
