---
title: Title example
---
<diagram_name>flowchart</diagram_name> <constant>LR</constant>
<id>A</id> <arrow>--></arrow> <id>B</id>
<keyword>subgraph</keyword> <id>name</id>
<id>C</id> <arrow>--></arrow> <id>D</id>
<keyword>end</keyword>
<id>id1</id>([<string>This is the text in the box</string>])
<id>id2</id>[<string>"This is the (text) in the box"</string>]

<diagram_name>stateDiagram-v2</diagram_name>
<id>S1</id><t>:</t> <string>The state with a note</string>
<keyword>note</keyword> <keyword>right of</keyword> <id>S1</id>
<note>This is note</note>
<keyword>end note</keyword>

<diagram_name>classDiagram</diagram_name>
<id>Square</id><t>:</t> <op>+</op><t>getDistanceMatrix() List</t><op>~</op><generic>List</generic><op>~</op><generic>int</generic><op>~</op><op>~</op>

<comment>%% This is comment</comment>
<keyword>title</keyword> <title>Title example</title>