load("//tools/base/bazel:bazel.bzl", "iml_module")

iml_module(
    name = "platform-resources-en",
    iml_files = ["platform-resources-en.iml"],
    resources = ["src"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
