load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.resources.en",
    iml_files = ["intellij.platform.resources.en.iml"],
    resources = ["src"],
    visibility = ["//visibility:public"],
)
