# managed by go/iml_to_build
java_import(
    name = "rngom-20051226-patched",
    jars = ["rngom-20051226-patched.jar"],
    visibility = ["//visibility:public"],
)

# managed by go/iml_to_build
java_import(
    name = "trang-core",
    jars = ["trang-core.jar"],
    visibility = ["//visibility:public"],
)
