java_import(
    name = "rngom-20051226-patched",
    jars = ["rngom-20051226-patched.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "isorelax",
    jars = ["isorelax.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "trang-core",
    jars = ["trang-core.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "jing",
    jars = ["jing.jar"],
    tags = ["managed"],
    visibility = ["//visibility:public"],
)
