// Copyright 2000-2022 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

package org.jetbrains.kotlin.idea.caches.resolve;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.idea.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.idea.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TestMetadata;
import org.jetbrains.kotlin.idea.test.TestRoot;
import org.junit.runner.RunWith;
import static org.jetbrains.kotlin.idea.artifacts.AdditionalKotlinArtifacts.compilerTestData;

/**
 * This class is generated by {@link org.jetbrains.kotlin.testGenerator.generator.TestGenerator}.
 * DO NOT MODIFY MANUALLY.
 */
@SuppressWarnings("all")
@TestRoot("idea/tests")
@TestDataPath("$CONTENT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
@TestMetadata("testData/compiler/asJava/lightClasses")
public abstract class IdeLightClassTestGenerated extends AbstractIdeLightClassTest {
    @RunWith(JUnit3RunnerWithInners.class)
    @TestMetadata("../../../intellij/out/kotlinc-testdata/testData/compiler/testData/asJava/lightClasses/compilationErrors")
    public static class CompilationErrors extends AbstractIdeLightClassTest {
        private void runTest(String testDataFilePath) throws Exception {
            KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
        }

        @Override
        protected void setUp() {
            compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors");
            super.setUp();
        }

        @TestMetadata("ActualClass.kt")
        public void testActualClass() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors/ActualClass.kt"));
        }

        @TestMetadata("ActualTypeAlias.kt")
        public void testActualTypeAlias() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors/ActualTypeAlias.kt"));
        }

        @TestMetadata("ActualTypeAliasCustomJvmPackageName.kt")
        public void testActualTypeAliasCustomJvmPackageName() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors/ActualTypeAliasCustomJvmPackageName.kt"));
        }

        @TestMetadata("AllInlineOnly.kt")
        public void testAllInlineOnly() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors/AllInlineOnly.kt"));
        }

        @TestMetadata("AnnotationModifiers.kt")
        public void testAnnotationModifiers() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors/AnnotationModifiers.kt"));
        }

        @TestMetadata("EnumNameOverride.kt")
        public void testEnumNameOverride() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors/EnumNameOverride.kt"));
        }

        @TestMetadata("ExpectClass.kt")
        public void testExpectClass() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors/ExpectClass.kt"));
        }

        @TestMetadata("ExpectObject.kt")
        public void testExpectObject() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors/ExpectObject.kt"));
        }

        @TestMetadata("ExpectedNestedClass.kt")
        public void testExpectedNestedClass() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors/ExpectedNestedClass.kt"));
        }

        @TestMetadata("ExpectedNestedClassInObject.kt")
        public void testExpectedNestedClassInObject() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors/ExpectedNestedClassInObject.kt"));
        }

        @TestMetadata("JvmPackageName.kt")
        public void testJvmPackageName() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors/JvmPackageName.kt"));
        }

        @TestMetadata("LocalInAnnotation.kt")
        public void testLocalInAnnotation() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors/LocalInAnnotation.kt"));
        }

        @TestMetadata("PrivateInTrait.kt")
        public void testPrivateInTrait() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors/PrivateInTrait.kt"));
        }

        @TestMetadata("RepetableAnnotations.kt")
        public void testRepetableAnnotations() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors/RepetableAnnotations.kt"));
        }

        @TestMetadata("SameName.kt")
        public void testSameName() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors/SameName.kt"));
        }

        @TestMetadata("TopLevelDestructuring.kt")
        public void testTopLevelDestructuring() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors/TopLevelDestructuring.kt"));
        }

        @TestMetadata("TraitClassObjectField.kt")
        public void testTraitClassObjectField() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors/TraitClassObjectField.kt"));
        }

        @TestMetadata("TwoOverrides.kt")
        public void testTwoOverrides() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors/TwoOverrides.kt"));
        }

        @TestMetadata("WrongAnnotations.kt")
        public void testWrongAnnotations() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/compilationErrors/WrongAnnotations.kt"));
        }
    }

    @RunWith(JUnit3RunnerWithInners.class)
    @TestMetadata("../../../intellij/out/kotlinc-testdata/testData/compiler/testData/asJava/lightClasses/facades")
    public static class Facades extends AbstractIdeLightClassTest {
        private void runTest(String testDataFilePath) throws Exception {
            KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
        }

        @Override
        protected void setUp() {
            compilerTestData("compiler/testData/asJava/lightClasses/facades");
            super.setUp();
        }

        @TestMetadata("AllPrivate.kt")
        public void testAllPrivate() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/facades/AllPrivate.kt"));
        }

        @TestMetadata("MultiFile.kt")
        public void testMultiFile() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/facades/MultiFile.kt"));
        }

        @TestMetadata("SingleFile.kt")
        public void testSingleFile() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/facades/SingleFile.kt"));
        }

        @TestMetadata("SingleJvmClassName.kt")
        public void testSingleJvmClassName() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/facades/SingleJvmClassName.kt"));
        }
    }

    @RunWith(JUnit3RunnerWithInners.class)
    @TestMetadata("../../../intellij/out/kotlinc-testdata/testData/compiler/testData/asJava/lightClasses/ideRegression")
    public static class IdeRegression extends AbstractIdeLightClassTest {
        private void runTest(String testDataFilePath) throws Exception {
            KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
        }

        @Override
        protected void setUp() {
            compilerTestData("compiler/testData/asJava/lightClasses/ideRegression");
            super.setUp();
        }

        @TestMetadata("AllOpenAnnotatedClasses.kt")
        public void testAllOpenAnnotatedClasses() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/ideRegression/AllOpenAnnotatedClasses.kt"));
        }

        @TestMetadata("ImplementingCharSequenceAndNumber.kt")
        public void testImplementingCharSequenceAndNumber() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/ideRegression/ImplementingCharSequenceAndNumber.kt"));
        }

        @TestMetadata("ImplementingMap.kt")
        public void testImplementingMap() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/ideRegression/ImplementingMap.kt"));
        }

        @TestMetadata("ImplementingMutableSet.kt")
        public void testImplementingMutableSet() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/ideRegression/ImplementingMutableSet.kt"));
        }

        @TestMetadata("InheritingInterfaceDefaultImpls.kt")
        public void testInheritingInterfaceDefaultImpls() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/ideRegression/InheritingInterfaceDefaultImpls.kt"));
        }

        @TestMetadata("OverridingFinalInternal.kt")
        public void testOverridingFinalInternal() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/ideRegression/OverridingFinalInternal.kt"));
        }

        @TestMetadata("OverridingInternal.kt")
        public void testOverridingInternal() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/ideRegression/OverridingInternal.kt"));
        }

        @TestMetadata("OverridingProtected.kt")
        public void testOverridingProtected() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/ideRegression/OverridingProtected.kt"));
        }
    }

    @RunWith(JUnit3RunnerWithInners.class)
    @TestMetadata("../../../intellij/out/kotlinc-testdata/testData/compiler/testData/asJava/lightClasses/nullabilityAnnotations")
    public static class NullabilityAnnotations extends AbstractIdeLightClassTest {
        private void runTest(String testDataFilePath) throws Exception {
            KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
        }

        @Override
        protected void setUp() {
            compilerTestData("compiler/testData/asJava/lightClasses/nullabilityAnnotations");
            super.setUp();
        }

        @TestMetadata("Class.kt")
        public void testClass() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/nullabilityAnnotations/Class.kt"));
        }

        @TestMetadata("ClassObjectField.kt")
        public void testClassObjectField() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/nullabilityAnnotations/ClassObjectField.kt"));
        }

        @TestMetadata("ClassWithConstructor.kt")
        public void testClassWithConstructor() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/nullabilityAnnotations/ClassWithConstructor.kt"));
        }

        @TestMetadata("ClassWithConstructorAndProperties.kt")
        public void testClassWithConstructorAndProperties() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/nullabilityAnnotations/ClassWithConstructorAndProperties.kt"));
        }

        @TestMetadata("FileFacade.kt")
        public void testFileFacade() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/nullabilityAnnotations/FileFacade.kt"));
        }

        @TestMetadata("Generic.kt")
        public void testGeneric() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/nullabilityAnnotations/Generic.kt"));
        }

        @TestMetadata("IntOverridesAny.kt")
        public void testIntOverridesAny() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/nullabilityAnnotations/IntOverridesAny.kt"));
        }

        @TestMetadata("JvmOverloads.kt")
        public void testJvmOverloads() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/nullabilityAnnotations/JvmOverloads.kt"));
        }

        @TestMetadata("NullableUnitReturn.kt")
        public void testNullableUnitReturn() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/nullabilityAnnotations/NullableUnitReturn.kt"));
        }

        @TestMetadata("OverrideAnyWithUnit.kt")
        public void testOverrideAnyWithUnit() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/nullabilityAnnotations/OverrideAnyWithUnit.kt"));
        }

        @TestMetadata("PlatformTypes.kt")
        public void testPlatformTypes() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/nullabilityAnnotations/PlatformTypes.kt"));
        }

        @TestMetadata("Primitives.kt")
        public void testPrimitives() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/nullabilityAnnotations/Primitives.kt"));
        }

        @TestMetadata("PrivateInClass.kt")
        public void testPrivateInClass() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/nullabilityAnnotations/PrivateInClass.kt"));
        }

        @TestMetadata("Synthetic.kt")
        public void testSynthetic() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/nullabilityAnnotations/Synthetic.kt"));
        }

        @TestMetadata("Trait.kt")
        public void testTrait() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/nullabilityAnnotations/Trait.kt"));
        }

        @TestMetadata("UnitAsGenericArgument.kt")
        public void testUnitAsGenericArgument() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/nullabilityAnnotations/UnitAsGenericArgument.kt"));
        }

        @TestMetadata("UnitParameter.kt")
        public void testUnitParameter() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/nullabilityAnnotations/UnitParameter.kt"));
        }

        @TestMetadata("VoidReturn.kt")
        public void testVoidReturn() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/nullabilityAnnotations/VoidReturn.kt"));
        }
    }

    @RunWith(JUnit3RunnerWithInners.class)
    @TestMetadata("../../../intellij/out/kotlinc-testdata/testData/compiler/testData/asJava/lightClasses/object")
    public static class Object extends AbstractIdeLightClassTest {
        private void runTest(String testDataFilePath) throws Exception {
            KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
        }

        @Override
        protected void setUp() {
            compilerTestData("compiler/testData/asJava/lightClasses/object");
            super.setUp();
        }

        @TestMetadata("SimpleObject.kt")
        public void testSimpleObject() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/object/SimpleObject.kt"));
        }
    }

    @RunWith(JUnit3RunnerWithInners.class)
    @TestMetadata("../../../intellij/out/kotlinc-testdata/testData/compiler/testData/asJava/lightClasses/publicField")
    public static class PublicField extends AbstractIdeLightClassTest {
        private void runTest(String testDataFilePath) throws Exception {
            KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
        }

        @Override
        protected void setUp() {
            compilerTestData("compiler/testData/asJava/lightClasses/publicField");
            super.setUp();
        }

        @TestMetadata("CompanionObject.kt")
        public void testCompanionObject() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/publicField/CompanionObject.kt"));
        }

        @TestMetadata("Simple.kt")
        public void testSimple() throws Exception {
            runTest(compilerTestData("compiler/testData/asJava/lightClasses/publicField/Simple.kt"));
        }
    }

    @RunWith(JUnit3RunnerWithInners.class)
    @TestMetadata("testData/compiler/asJava/lightClasses")
    public static class Uncategorized extends AbstractIdeLightClassTest {
        private void runTest(String testDataFilePath) throws Exception {
            KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
        }

        @TestMetadata("AnnotatedParameterInEnumConstructor.kt")
        public void testAnnotatedParameterInEnumConstructor() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/AnnotatedParameterInEnumConstructor.kt");
        }

        @TestMetadata("AnnotatedParameterInInnerClassConstructor.kt")
        public void testAnnotatedParameterInInnerClassConstructor() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/AnnotatedParameterInInnerClassConstructor.kt");
        }

        @TestMetadata("AnnotatedPropertyWithSites.kt")
        public void testAnnotatedPropertyWithSites() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/AnnotatedPropertyWithSites.kt");
        }

        @TestMetadata("AnnotationClass.kt")
        public void testAnnotationClass() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/AnnotationClass.kt");
        }

        @TestMetadata("Constructors.kt")
        public void testConstructors() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/Constructors.kt");
        }

        @TestMetadata("DataClassWithCustomImplementedMembers.kt")
        public void testDataClassWithCustomImplementedMembers() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/DataClassWithCustomImplementedMembers.kt");
        }

        @TestMetadata("DelegatedNested.kt")
        public void testDelegatedNested() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/DelegatedNested.kt");
        }

        @TestMetadata("Delegation.kt")
        public void testDelegation() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/Delegation.kt");
        }

        @TestMetadata("DeprecatedEnumEntry.kt")
        public void testDeprecatedEnumEntry() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/DeprecatedEnumEntry.kt");
        }

        @TestMetadata("DeprecatedNotHiddenInClass.kt")
        public void testDeprecatedNotHiddenInClass() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/DeprecatedNotHiddenInClass.kt");
        }

        @TestMetadata("DollarsInName.kt")
        public void testDollarsInName() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/DollarsInName.kt");
        }

        @TestMetadata("DollarsInNameNoPackage.kt")
        public void testDollarsInNameNoPackage() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/DollarsInNameNoPackage.kt");
        }

        @TestMetadata("ExtendingInterfaceWithDefaultImpls.kt")
        public void testExtendingInterfaceWithDefaultImpls() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/ExtendingInterfaceWithDefaultImpls.kt");
        }

        @TestMetadata("HiddenDeprecated.kt")
        public void testHiddenDeprecated() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/HiddenDeprecated.kt");
        }

        @TestMetadata("HiddenDeprecatedInClass.kt")
        public void testHiddenDeprecatedInClass() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/HiddenDeprecatedInClass.kt");
        }

        @TestMetadata("InheritingInterfaceDefaultImpls.kt")
        public void testInheritingInterfaceDefaultImpls() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/InheritingInterfaceDefaultImpls.kt");
        }

        @TestMetadata("InlineReified.kt")
        public void testInlineReified() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/InlineReified.kt");
        }

        @TestMetadata("JvmNameOnMember.kt")
        public void testJvmNameOnMember() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/JvmNameOnMember.kt");
        }

        @TestMetadata("JvmStatic.kt")
        public void testJvmStatic() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/JvmStatic.kt");
        }

        @TestMetadata("NestedObjects.kt")
        public void testNestedObjects() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/NestedObjects.kt");
        }

        @TestMetadata("NonDataClassWithComponentFunctions.kt")
        public void testNonDataClassWithComponentFunctions() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/NonDataClassWithComponentFunctions.kt");
        }

        @TestMetadata("OnlySecondaryConstructors.kt")
        public void testOnlySecondaryConstructors() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/OnlySecondaryConstructors.kt");
        }

        @TestMetadata("PublishedApi.kt")
        public void testPublishedApi() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/PublishedApi.kt");
        }

        @TestMetadata("SpecialAnnotationsOnAnnotationClass.kt")
        public void testSpecialAnnotationsOnAnnotationClass() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/SpecialAnnotationsOnAnnotationClass.kt");
        }

        @TestMetadata("SpecialAnnotationsOnAnnotationClass_1_6.kt")
        public void testSpecialAnnotationsOnAnnotationClass_1_6() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/SpecialAnnotationsOnAnnotationClass_1_6.kt");
        }

        @TestMetadata("StubOrderForOverloads.kt")
        public void testStubOrderForOverloads() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/StubOrderForOverloads.kt");
        }

        @TestMetadata("TypePararametersInClass.kt")
        public void testTypePararametersInClass() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/TypePararametersInClass.kt");
        }

        @TestMetadata("VarArgs.kt")
        public void testVarArgs() throws Exception {
            runTest("testData/compiler/asJava/lightClasses/VarArgs.kt");
        }
    }
}
