from typing import Any

class GraphCommands:
    def commit(self): ...
    version: Any
    def query(self, q, params: Any | None = ..., timeout: Any | None = ..., read_only: bool = ..., profile: bool = ...): ...
    def merge(self, pattern): ...
    def delete(self): ...
    nodes: Any
    edges: Any
    def flush(self) -> None: ...
    def explain(self, query, params: Any | None = ...): ...
    def bulk(self, **kwargs) -> None: ...
    def profile(self, query): ...
    def slowlog(self): ...
    def config(self, name, value: Any | None = ..., set: bool = ...): ...
    def list_keys(self): ...
