@startjson
{
  "intellij.angularJS" : {
    "name" : "intellij.angularJS",
    "package" : null,
    "descriptor" : "contrib/AngularJS/resources/META-INF/plugin.xml",
    "content" : [ {
      "name" : "intellij.angularJS/diagram",
      "package" : "org.angularjs.diagram",
      "descriptor" : "contrib/AngularJS/resources/intellij.angularJS.diagram.xml",
      "dependencies" : [ {
        "plugin" : "com.intellij.diagram"
      }, {
        "module" : "intellij.javascript.impl/diagrams"
      } ]
    } ]
  },
  "intellij.cloudFormation" : {
    "name" : "intellij.cloudFormation",
    "package" : "com.intellij.aws.cloudformation",
    "descriptor" : "contrib/CloudFormation/src/main/resources/META-INF/plugin.xml"
  },
  "intellij.clouds.docker.impl" : {
    "name" : "intellij.clouds.docker.impl",
    "package" : "com.intellij.docker",
    "descriptor" : "plugins/Docker/resources/META-INF/plugin.xml",
    "content" : [ {
      "name" : "intellij.clouds.docker.java",
      "package" : "com.intellij.docker.java",
      "descriptor" : "plugins/Docker/Docker-java-impl/resources/intellij.clouds.docker.java.xml",
      "dependencies" : [ {
        "plugin" : "com.intellij.java"
      } ]
    }, {
      "name" : "intellij.clouds.docker.compose",
      "package" : "com.intellij.docker.composeFile",
      "descriptor" : "plugins/Docker/Docker-compose/resources/intellij.clouds.docker.compose.xml",
      "dependencies" : [ {
        "plugin" : "org.jetbrains.plugins.yaml"
      }, {
        "plugin" : "Docker"
      } ]
    }, {
      "name" : "intellij.clouds.docker.file",
      "package" : "com.intellij.docker.dockerFile",
      "descriptor" : "plugins/Docker/Docker-file/resources/intellij.clouds.docker.file.xml"
    }, {
      "name" : "intellij.clouds.docker.remoteRun",
      "package" : "com.intellij.docker.remote",
      "descriptor" : "plugins/Docker/Docker-remote-run/resources/intellij.clouds.docker.remoteRun.xml"
    } ],
    "dependencies" : [ {
      "plugin" : "com.intellij.modules.lang"
    }, {
      "plugin" : "com.intellij.modules.json"
    }, {
      "plugin" : "com.intellij.modules.remoteServers"
    } ]
  },
  "intellij.clouds.kubernetes" : {
    "name" : "intellij.clouds.kubernetes",
    "package" : "com.intellij.kubernetes",
    "descriptor" : "plugins/kubernetes/resources/META-INF/plugin.xml",
    "dependencies" : [ {
      "module" : "intellij.clouds.docker.compose"
    } ]
  },
  "intellij.coffeescript" : {
    "name" : "intellij.coffeescript",
    "package" : "org.coffeescript",
    "descriptor" : "plugins/coffeescript/coffeescript-core/resources/META-INF/plugin.xml"
  },
  "intellij.configurationScript" : {
    "name" : "intellij.configurationScript",
    "package" : "com.intellij.configurationScript",
    "descriptor" : "community/plugins/configuration-script/resources/META-INF/plugin.xml"
  },
  "intellij.diagram.impl" : {
    "name" : "intellij.diagram.impl",
    "package" : "com.intellij.uml",
    "descriptor" : "plugins/uml/resources/META-INF/plugin.xml"
  },
  "intellij.fileWatcher" : {
    "name" : "intellij.fileWatcher",
    "package" : "com.intellij.plugins.watcher",
    "descriptor" : "plugins/fileWatcher/resources/META-INF/plugin.xml"
  },
  "intellij.freemarker" : {
    "name" : "intellij.freemarker",
    "package" : "com.intellij.freemarker",
    "descriptor" : "plugins/freemarker/core/resources/META-INF/plugin.xml"
  },
  "intellij.go.ide" : {
    "name" : "intellij.go.ide",
    "package" : "com.goide.ide",
    "descriptor" : "goland/intellij-go/ide/resources/META-INF/plugin.xml"
  },
  "intellij.go.plugin" : {
    "name" : "intellij.go.plugin",
    "package" : "com.goide",
    "descriptor" : "goland/intellij-go/plugin/resources/META-INF/plugin.xml"
  },
  "intellij.go.sharedIndexes.bundled" : {
    "name" : "intellij.go.sharedIndexes.bundled",
    "package" : "com.goide.index.shared.bundled",
    "descriptor" : "goland/intellij-go/go-shared-indexes-bundled/resources/META-INF/plugin.xml"
  },
  "intellij.go.template" : {
    "name" : "intellij.go.template",
    "package" : "com.goide.template",
    "descriptor" : "goland/intellij-go/template/resources/META-INF/plugin.xml"
  },
  "intellij.gradle.ext" : {
    "name" : "intellij.gradle.ext",
    "package" : null,
    "descriptor" : "plugins/gradle-ext/src/main/resources/META-INF/plugin.xml",
    "content" : [ {
      "name" : "intellij.gradle.ext/profiler",
      "package" : "org.jetbrains.idea.gradle.ext.profiler",
      "descriptor" : "plugins/gradle-ext/src/main/resources/intellij.gradle.ext.profiler.xml",
      "dependencies" : [ {
        "module" : "intellij.profiler.ultimate"
      } ]
    } ]
  },
  "intellij.gradle.javaee" : {
    "name" : "intellij.gradle.javaee",
    "package" : "com.intellij.javaee.gradle",
    "descriptor" : "plugins/javaee/gradle-integration/resources/META-INF/plugin.xml",
    "content" : [ {
      "name" : "intellij.gradle.javaee/javaee",
      "package" : "com.intellij.javaee.gradle.javaee",
      "descriptor" : "plugins/javaee/gradle-integration/resources/intellij.gradle.javaee.javaee.xml",
      "dependencies" : [ {
        "plugin" : "com.intellij.javaee"
      } ]
    }, {
      "name" : "intellij.gradle.javaee/javaee.web",
      "package" : "com.intellij.javaee.gradle.javaeeWeb",
      "descriptor" : "plugins/javaee/gradle-integration/resources/intellij.gradle.javaee.javaee.web.xml",
      "dependencies" : [ {
        "plugin" : "com.intellij.javaee.web"
      } ]
    } ],
    "dependencies" : [ {
      "plugin" : "org.jetbrains.plugins.gradle"
    }, {
      "plugin" : "com.intellij.javaee"
    } ]
  },
  "intellij.grazie" : {
    "name" : "intellij.grazie",
    "package" : "com.intellij.grazie",
    "descriptor" : "community/plugins/grazie/resources/META-INF/plugin.xml",
    "content" : [ {
      "name" : "intellij.grazie.java",
      "package" : "com.intellij.grazie.ide.language.java",
      "descriptor" : "community/plugins/grazie/java/src/main/resources/intellij.grazie.java.xml",
      "dependencies" : [ {
        "plugin" : "com.intellij.java"
      } ]
    }, {
      "name" : "intellij.grazie.json",
      "package" : "com.intellij.grazie.ide.language.json",
      "descriptor" : "community/plugins/grazie/json/src/main/resources/intellij.grazie.json.xml",
      "dependencies" : [ {
        "plugin" : "com.intellij.modules.json"
      } ]
    }, {
      "name" : "intellij.grazie.markdown",
      "package" : "com.intellij.grazie.ide.language.markdown",
      "descriptor" : "community/plugins/grazie/markdown/src/main/resources/intellij.grazie.markdown.xml",
      "dependencies" : [ {
        "plugin" : "org.intellij.plugins.markdown"
      } ]
    }, {
      "name" : "intellij.grazie.properties",
      "package" : "com.intellij.grazie.ide.language.properties",
      "descriptor" : "community/plugins/grazie/properties/src/main/resources/intellij.grazie.properties.xml",
      "dependencies" : [ {
        "plugin" : "com.intellij.properties"
      } ]
    }, {
      "name" : "intellij.grazie.xml",
      "package" : "com.intellij.grazie.ide.language.xml",
      "descriptor" : "community/plugins/grazie/xml/main/resources/intellij.grazie.xml.xml",
      "dependencies" : [ {
        "plugin" : "com.intellij.modules.xml"
      } ]
    }, {
      "name" : "intellij.grazie.yaml",
      "package" : "com.intellij.grazie.ide.language.yaml",
      "descriptor" : "community/plugins/grazie/yaml/main/resources/intellij.grazie.yaml.xml",
      "dependencies" : [ {
        "plugin" : "org.jetbrains.plugins.yaml"
      } ]
    } ]
  },
  "intellij.groovy" : {
    "name" : "intellij.groovy",
    "package" : "org.jetbrains.plugins.groovy",
    "descriptor" : "community/plugins/groovy/src/META-INF/plugin.xml"
  },
  "intellij.grpc" : {
    "name" : "intellij.grpc",
    "package" : "com.intellij.grpc",
    "descriptor" : "plugins/frameworks/grpc/resources/META-INF/plugin.xml"
  },
  "intellij.guice" : {
    "name" : "intellij.guice",
    "package" : "com.intellij.guice",
    "descriptor" : "plugins/frameworks/Guice/resources/META-INF/plugin.xml"
  },
  "intellij.haml" : {
    "name" : "intellij.haml",
    "package" : "org.jetbrains.plugins.haml",
    "descriptor" : "plugins/haml/resources/META-INF/plugin.xml"
  },
  "intellij.helidon" : {
    "name" : "intellij.helidon",
    "package" : "com.intellij.helidon",
    "descriptor" : "plugins/frameworks/helidon/resources/META-INF/plugin.xml"
  },
  "intellij.jade" : {
    "name" : "intellij.jade",
    "package" : "com.jetbrains.plugins.jade",
    "descriptor" : "plugins/Jade/resources/META-INF/plugin.xml"
  },
  "intellij.java.plugin" : {
    "name" : "intellij.java.plugin",
    "package" : null,
    "descriptor" : "community/java/plugin/resources/META-INF/plugin.xml",
    "content" : [ {
      "name" : "intellij.profiler.ultimate",
      "package" : "com.intellij.profiler.ultimate",
      "descriptor" : "plugins/profiler/ultimate/resources/intellij.profiler.ultimate.xml",
      "dependencies" : [ {
        "plugin" : "com.intellij.modules.profiler"
      } ]
    } ]
  },
  "intellij.javaFX.css" : {
    "name" : "intellij.javaFX.css",
    "package" : "org.jetbrains.plugins.javaFX",
    "descriptor" : "plugins/javaFX-CSS/src/META-INF/plugin.xml"
  },
  "intellij.javaHttpClients" : {
    "name" : "intellij.javaHttpClients",
    "package" : "com.intellij.javahttp",
    "descriptor" : "plugins/frameworks/java-http-clients/resources/META-INF/plugin.xml"
  },
  "intellij.javaee.app.servers.impl" : {
    "name" : "intellij.javaee.app.servers.impl",
    "package" : null,
    "descriptor" : "plugins/javaee/core/javaee-app-server-integration/app-server-integration-impl/resources/META-INF/plugin.xml",
    "content" : [ {
      "name" : "intellij.javaee.app.servers.impl/profiler",
      "package" : "com.intellij.javaee.appServers.run.profiler",
      "descriptor" : "plugins/javaee/core/javaee-app-server-integration/app-server-integration-impl/resources/intellij.javaee.app.servers.impl.profiler.xml",
      "dependencies" : [ {
        "module" : "intellij.profiler.ultimate"
      } ]
    } ]
  },
  "intellij.javaee.appServers.tomcat" : {
    "name" : "intellij.javaee.appServers.tomcat",
    "package" : null,
    "descriptor" : "plugins/tomcat/resources/META-INF/plugin.xml",
    "content" : [ {
      "name" : "intellij.javaee.appServers.tomcat/profiler",
      "package" : "org.jetbrains.idea.tomcat.profiler",
      "descriptor" : "plugins/tomcat/resources/intellij.javaee.appServers.tomcat.profiler.xml",
      "dependencies" : [ {
        "module" : "intellij.profiler.ultimate"
      } ]
    } ]
  },
  "intellij.javaee.beanValidation" : {
    "name" : "intellij.javaee.beanValidation",
    "package" : "com.intellij.beanValidation",
    "descriptor" : "plugins/javaee/bean-validation/bv-core/resources/META-INF/plugin.xml"
  },
  "intellij.javaee.cdi" : {
    "name" : "intellij.javaee.cdi",
    "package" : "com.intellij.cdi",
    "descriptor" : "plugins/javaee/cdi/cdi-core/resources/META-INF/plugin.xml"
  },
  "intellij.javaee.ejb.impl" : {
    "name" : "intellij.javaee.ejb.impl",
    "package" : "com.intellij.javaee.ejb",
    "descriptor" : "plugins/javaee/ejb/ejb-impl/resources/META-INF/plugin.xml"
  },
  "intellij.javaee.jax.rs" : {
    "name" : "intellij.javaee.jax.rs",
    "package" : "com.intellij.ws.rest",
    "descriptor" : "plugins/javaee/web-services/rs/resources/META-INF/plugin.xml"
  },
  "intellij.javaee.jax.ws" : {
    "name" : "intellij.javaee.jax.ws",
    "package" : "com.intellij.ws.xml",
    "descriptor" : "plugins/javaee/web-services/ws/resources/META-INF/plugin.xml"
  },
  "intellij.javaee.jpa.impl" : {
    "name" : "intellij.javaee.jpa.impl",
    "package" : "com.intellij.jpa",
    "descriptor" : "plugins/javaee/jpa/jpa-impl/resources/META-INF/plugin.xml"
  },
  "intellij.javaee.jsf" : {
    "name" : "intellij.javaee.jsf",
    "package" : "com.intellij.jsf",
    "descriptor" : "plugins/javaee/jsf/jsf-core/src/META-INF/plugin.xml"
  },
  "intellij.javaee.web.impl" : {
    "name" : "intellij.javaee.web.impl",
    "package" : "com.intellij.javaee.web",
    "descriptor" : "plugins/javaee/web/web-impl/resources/META-INF/plugin.xml"
  },
  "intellij.javascript.impl" : {
    "name" : "intellij.javascript.impl",
    "package" : null,
    "descriptor" : "plugins/JavaScriptLanguage/src/META-INF/plugin.xml",
    "content" : [ {
      "name" : "intellij.javascript.impl/diagrams",
      "package" : "com.intellij.lang.javascript.modules.diagram",
      "descriptor" : "plugins/JavaScriptLanguage/src/intellij.javascript.impl.diagrams.xml",
      "dependencies" : [ {
        "plugin" : "com.intellij.diagram"
      } ]
    } ]
  },
  "intellij.jboss.arquillian" : {
    "name" : "intellij.jboss.arquillian",
    "package" : "com.intellij.plugins.jboss.arquillian",
    "descriptor" : "plugins/frameworks/jboss/arquillian/arquillian-core/src/META-INF/plugin.xml"
  },
  "intellij.jboss.jbpm" : {
    "name" : "intellij.jboss.jbpm",
    "package" : "com.intellij.jboss.bpmn",
    "descriptor" : "plugins/frameworks/jboss/bpmn/jbpm/resources/META-INF/plugin.xml"
  },
  "intellij.less" : {
    "name" : "intellij.less",
    "package" : "org.jetbrains.plugins.less",
    "descriptor" : "plugins/less/resources/META-INF/plugin.xml"
  },
  "intellij.maven.ext" : {
    "name" : "intellij.maven.ext",
    "package" : null,
    "descriptor" : "plugins/maven-ext/src/main/resources/META-INF/plugin.xml",
    "content" : [ {
      "name" : "intellij.maven.ext/profiler",
      "package" : "org.jetbrains.idea.maven.ext.profiler",
      "descriptor" : "plugins/maven-ext/src/main/resources/intellij.maven.ext.profiler.xml",
      "dependencies" : [ {
        "module" : "intellij.profiler.ultimate"
      } ]
    } ]
  },
  "intellij.micronaut" : {
    "name" : "intellij.micronaut",
    "package" : "com.intellij.micronaut",
    "descriptor" : "plugins/frameworks/micronaut/micronaut-core/resources/META-INF/plugin.xml"
  },
  "intellij.nodeJS.remoteInterpreter" : {
    "name" : "intellij.nodeJS.remoteInterpreter",
    "package" : "com.jetbrains.nodejs.remote",
    "descriptor" : "plugins/NodeJS/node-remote-interpreter/resources/META-INF/plugin.xml"
  },
  "intellij.php.docker" : {
    "name" : "intellij.php.docker",
    "package" : "com.jetbrains.php.remote.docker",
    "descriptor" : "phpstorm/phpstorm-docker/resources/META-INF/plugin.xml",
    "dependencies" : [ {
      "module" : "intellij.clouds.docker.remoteRun"
    } ]
  },
  "intellij.phpspec" : {
    "name" : "intellij.phpspec",
    "package" : "com.jetbrains.php.phpspec",
    "descriptor" : "phpstorm/phpspec/resources/META-INF/plugin.xml"
  },
  "intellij.play" : {
    "name" : "intellij.play",
    "package" : "com.intellij.play",
    "descriptor" : "plugins/frameworks/play/resources/META-INF/plugin.xml"
  },
  "intellij.properties" : {
    "name" : "intellij.properties",
    "package" : "com.intellij.lang.properties",
    "descriptor" : "community/plugins/properties/src/META-INF/plugin.xml"
  },
  "intellij.protoeditor" : {
    "name" : "intellij.protoeditor",
    "package" : "com.intellij.protobuf",
    "descriptor" : "contrib/protobuf/resources/META-INF/plugin.xml"
  },
  "intellij.puppet" : {
    "name" : "intellij.puppet",
    "package" : "com.intellij.lang.puppet",
    "descriptor" : "plugins/puppet/resources/META-INF/plugin.xml"
  },
  "intellij.quarkus" : {
    "name" : "intellij.quarkus",
    "package" : "com.intellij.quarkus",
    "descriptor" : "plugins/frameworks/quarkus/quarkus-core/resources/META-INF/plugin.xml"
  },
  "intellij.reactivestreams.core" : {
    "name" : "intellij.reactivestreams.core",
    "package" : "com.intellij.reactivestreams",
    "descriptor" : "plugins/frameworks/reactive/reactive-streams-core/resources/META-INF/plugin.xml"
  },
  "intellij.remoteRun" : {
    "name" : "intellij.remoteRun",
    "package" : "com.jetbrains.plugins.remotesdk",
    "descriptor" : "plugins/remote-run/resources/META-INF/plugin.xml"
  },
  "intellij.ruby.plugin" : {
    "name" : "intellij.ruby.plugin",
    "package" : null,
    "descriptor" : "ruby/pluginResources/META-INF/plugin.xml",
    "content" : [ {
      "name" : "intellij.ruby.copyright",
      "package" : "org.jetbrains.plugins.ruby.copyright",
      "descriptor" : "ruby/ruby-copyright/resources/intellij.ruby.copyright.xml",
      "dependencies" : [ {
        "plugin" : "com.intellij.copyright"
      } ]
    }, {
      "name" : "intellij.ruby.coverage",
      "package" : "org.jetbrains.plugins.ruby.coverage",
      "descriptor" : "ruby/coverage/ruby-coverage-common/resources/intellij.ruby.coverage.xml",
      "dependencies" : [ {
        "plugin" : "com.intellij.modules.coverage"
      } ]
    }, {
      "name" : "intellij.ruby.database",
      "package" : "org.jetbrains.plugins.ruby.rails.database.impl",
      "descriptor" : "ruby/ruby-database/resources/intellij.ruby.database.xml",
      "dependencies" : [ {
        "plugin" : "com.intellij.modules.database"
      } ]
    }, {
      "name" : "intellij.ruby.puppet.shared",
      "package" : "com.intellij.lang.puppet.rubyShared",
      "descriptor" : "ruby/ruby-puppet-shared/src/intellij.ruby.puppet.shared.xml"
    }, {
      "name" : "intellij.ruby.java",
      "package" : "org.jetbrains.plugins.ruby.java",
      "descriptor" : "ruby/ruby-java/src/intellij.ruby.java.xml",
      "dependencies" : [ {
        "plugin" : "com.intellij.java"
      } ]
    }, {
      "name" : "intellij.ruby.puppet.java",
      "package" : "com.intellij.lang.puppet.ruby.java.ide",
      "descriptor" : "ruby/ruby-puppet-java/resources/intellij.ruby.puppet.java.xml",
      "dependencies" : [ {
        "plugin" : "com.intellij.java"
      }, {
        "plugin" : "com.intellij.lang.puppet"
      }, {
        "module" : "intellij.ruby.puppet.shared"
      } ]
    }, {
      "name" : "intellij.ruby.cucumber",
      "package" : "org.jetbrains.plugins.ruby.cucumber",
      "descriptor" : "ruby/ruby-cucumber/resources/intellij.ruby.cucumber.xml",
      "dependencies" : [ {
        "plugin" : "gherkin"
      } ]
    }, {
      "name" : "intellij.ruby.uml",
      "package" : "com.intellij.diagram.ruby",
      "descriptor" : "ruby/ruby-uml/resources/intellij.ruby.uml.xml",
      "dependencies" : [ {
        "plugin" : "com.intellij.diagram"
      } ]
    }, {
      "name" : "intellij.ruby.wsl",
      "package" : "com.intellij.wsl.remote.ruby",
      "descriptor" : "ruby/ruby-wsl/resources/intellij.ruby.wsl.xml",
      "dependencies" : [ {
        "plugin" : "org.jetbrains.plugins.wsl"
      }, {
        "module" : "intellij.ruby.remoteInterpreter"
      } ]
    }, {
      "name" : "intellij.ruby.remoteInterpreter",
      "package" : "org.jetbrains.plugins.ruby.remote.impl",
      "descriptor" : "ruby/remote-interpreter/resources/intellij.ruby.remoteInterpreter.xml",
      "dependencies" : [ {
        "plugin" : "org.jetbrains.plugins.remote-run"
      } ]
    }, {
      "name" : "intellij.ruby.docker",
      "package" : "com.intellij.docker.remote.ruby",
      "descriptor" : "ruby/ruby-docker/resources/intellij.ruby.docker.xml",
      "dependencies" : [ {
        "plugin" : "Docker"
      }, {
        "module" : "intellij.ruby.remoteInterpreter"
      }, {
        "module" : "intellij.ruby.coverage"
      } ]
    }, {
      "name" : "intellij.ruby.terminal",
      "package" : "org.jetbrains.plugins.ruby.terminal",
      "descriptor" : "ruby/ruby-terminal/resources/intellij.ruby.terminal.xml",
      "dependencies" : [ {
        "plugin" : "org.jetbrains.plugins.terminal"
      } ]
    }, {
      "name" : "intellij.ruby.puppet",
      "package" : "com.intellij.lang.puppet.ruby",
      "descriptor" : "ruby/ruby-puppet/resources/intellij.ruby.puppet.xml",
      "dependencies" : [ {
        "plugin" : "com.intellij.lang.puppet"
      }, {
        "module" : "intellij.ruby.puppet.shared"
      } ]
    }, {
      "name" : "intellij.ruby.performanceTesting",
      "package" : "org.jetbrains.ruby.performanceTesting",
      "descriptor" : "ruby/performanceTesting/src/intellij.ruby.performanceTesting.xml",
      "dependencies" : [ {
        "plugin" : "com.jetbrains.performancePlugin"
      } ]
    }, {
      "name" : "intellij.ruby.intelliLang",
      "package" : "org.jetbrains.plugins.ruby.ruby.intelliLang",
      "descriptor" : "ruby/ruby-intelliLang/resources/intellij.ruby.intelliLang.xml",
      "dependencies" : [ {
        "plugin" : "org.intellij.intelliLang"
      } ]
    }, {
      "name" : "intellij.ruby.featuresTrainer",
      "package" : "org.jetbrains.ruby.ift",
      "descriptor" : "contrib/ide-features-trainer/ruby-features-trainer/resources/intellij.ruby.featuresTrainer.xml",
      "dependencies" : [ {
        "plugin" : "training"
      } ]
    }, {
      "name" : "intellij.ruby.haml",
      "package" : "org.jetbrains.plugins.haml.ruby",
      "descriptor" : "ruby/ruby-haml/resources/intellij.ruby.haml.xml",
      "dependencies" : [ {
        "plugin" : "org.jetbrains.plugins.haml"
      } ]
    }, {
      "name" : "intellij.ruby.slim",
      "package" : "org.jetbrains.plugins.slim.ruby",
      "descriptor" : "ruby/ruby-slim/resources/intellij.ruby.slim.xml",
      "dependencies" : [ {
        "plugin" : "org.jetbrains.plugins.slim"
      } ]
    } ]
  },
  "intellij.safe.push" : {
    "name" : "intellij.safe.push",
    "package" : "com.intellij.safepush",
    "descriptor" : "plugins/safe-push/resources/META-INF/plugin.xml"
  },
  "intellij.selenium" : {
    "name" : "intellij.selenium",
    "package" : "com.intellij.selenium",
    "descriptor" : "plugins/frameworks/selenium/selenium/resources/META-INF/plugin.xml",
    "content" : [ {
      "name" : "intellij.selenium.jvm",
      "package" : "com.intellij.selenium.jvm",
      "descriptor" : "plugins/frameworks/selenium/selenium-jvm/resources/intellij.selenium.jvm.xml",
      "dependencies" : [ {
        "plugin" : "com.intellij.java"
      }, {
        "plugin" : "com.intellij.modules.ultimate"
      }, {
        "plugin" : "com.intellij.modules.json"
      }, {
        "plugin" : "org.intellij.intelliLang"
      }, {
        "plugin" : "com.intellij.properties"
      } ]
    }, {
      "name" : "intellij.selenium.docker",
      "package" : "com.intellij.selenium.docker",
      "descriptor" : "plugins/frameworks/selenium/selenium-docker/resources/intellij.selenium.docker.xml",
      "dependencies" : [ {
        "plugin" : "Docker"
      } ]
    }, {
      "name" : "intellij.selenium.python",
      "package" : "com.intellij.selenium.python",
      "descriptor" : "plugins/frameworks/selenium/selenium-python/resources/intellij.selenium.python.xml"
    } ]
  },
  "intellij.sh" : {
    "name" : "intellij.sh",
    "package" : "com.intellij.sh",
    "descriptor" : "community/plugins/sh/resources/META-INF/plugin.xml"
  },
  "intellij.slim" : {
    "name" : "intellij.slim",
    "package" : "org.jetbrains.plugins.slim",
    "descriptor" : "plugins/slim-lang/resources/META-INF/plugin.xml"
  },
  "intellij.space" : {
    "name" : "intellij.space",
    "package" : "com.intellij.space",
    "descriptor" : "plugins/space/src/main/resources/META-INF/plugin.xml",
    "content" : [ {
      "name" : "intellij.space.kotlin",
      "package" : "com.intellij.space.kotlin",
      "descriptor" : "plugins/space/kotlin/resources/intellij.space.kotlin.xml",
      "dependencies" : [ {
        "plugin" : "org.jetbrains.kotlin"
      } ]
    }, {
      "name" : "intellij.space.index",
      "package" : "com.intellij.space.index",
      "descriptor" : "plugins/space/index/resources/intellij.space.index.xml",
      "dependencies" : [ {
        "plugin" : "intellij.indexing.shared"
      } ]
    } ]
  },
  "intellij.spring.batch" : {
    "name" : "intellij.spring.batch",
    "package" : "com.intellij.spring.batch",
    "descriptor" : "plugins/spring/spring-batch/resources/META-INF/plugin.xml"
  },
  "intellij.spring.boot.core" : {
    "name" : "intellij.spring.boot.core",
    "package" : "com.intellij.spring.boot",
    "descriptor" : "plugins/spring/spring-boot/spring-boot-core/resources/META-INF/plugin.xml"
  },
  "intellij.spring.core" : {
    "name" : "intellij.spring.core",
    "package" : "com.intellij.spring",
    "descriptor" : "plugins/spring/spring-framework/spring-core/resources/META-INF/plugin.xml"
  },
  "intellij.spring.data" : {
    "name" : "intellij.spring.data",
    "package" : "com.intellij.spring.data",
    "descriptor" : "plugins/spring/spring-data/resources/META-INF/plugin.xml"
  },
  "intellij.spring.integration.core" : {
    "name" : "intellij.spring.integration.core",
    "package" : "com.intellij.spring.integration",
    "descriptor" : "plugins/spring/spring-integration/spring-integration-core/resources/META-INF/plugin.xml"
  },
  "intellij.spring.mvc.impl" : {
    "name" : "intellij.spring.mvc.impl",
    "package" : "com.intellij.spring.mvc",
    "descriptor" : "plugins/spring/spring-mvc-support/spring-mvc/resources/META-INF/plugin.xml"
  },
  "intellij.spring.security" : {
    "name" : "intellij.spring.security",
    "package" : "com.intellij.spring.security",
    "descriptor" : "plugins/spring/spring-security/resources/META-INF/plugin.xml"
  },
  "intellij.spring.webflow" : {
    "name" : "intellij.spring.webflow",
    "package" : "com.intellij.spring.webflow",
    "descriptor" : "plugins/spring/spring-webflow/resources/META-INF/plugin.xml"
  },
  "intellij.spring.websocket" : {
    "name" : "intellij.spring.websocket",
    "package" : "com.intellij.spring.websocket",
    "descriptor" : "plugins/spring/spring-websocket/resources/META-INF/plugin.xml"
  },
  "intellij.struts2" : {
    "name" : "intellij.struts2",
    "package" : "com.intellij.struts2",
    "descriptor" : "contrib/struts2/plugin/resources/META-INF/plugin.xml"
  },
  "intellij.swagger" : {
    "name" : "intellij.swagger",
    "package" : "com.intellij.swagger",
    "descriptor" : "plugins/frameworks/swagger/swagger-core/resources/META-INF/plugin.xml",
    "content" : [ {
      "name" : "intellij.swagger/endpoints",
      "package" : "com.intellij.swagger.providers.endpoints",
      "descriptor" : "plugins/frameworks/swagger/swagger-core/resources/intellij.swagger.endpoints.xml",
      "dependencies" : [ {
        "plugin" : "com.intellij.microservices.ui"
      } ]
    } ]
  },
  "intellij.thymeleaf" : {
    "name" : "intellij.thymeleaf",
    "package" : "com.intellij.thymeleaf",
    "descriptor" : "plugins/frameworks/thymeleaf/thymeleaf-core/resources/META-INF/plugin.xml"
  },
  "intellij.vcs.git" : {
    "name" : "intellij.vcs.git",
    "package" : "git4idea",
    "descriptor" : "community/plugins/git4idea/resources/META-INF/plugin.xml"
  },
  "intellij.vcs.github" : {
    "name" : "intellij.vcs.github",
    "package" : "org.jetbrains.plugins.github",
    "descriptor" : "community/plugins/github/resources/META-INF/plugin.xml"
  },
  "intellij.vuejs" : {
    "name" : "intellij.vuejs",
    "package" : "org.jetbrains.vuejs",
    "descriptor" : "contrib/vuejs/resources/META-INF/plugin.xml"
  },
  "intellij.w3validators" : {
    "name" : "intellij.w3validators",
    "package" : "org.jetbrains.w3validators",
    "descriptor" : "plugins/w3validators/src/META-INF/plugin.xml"
  },
  "intellij.wsl" : {
    "name" : "intellij.wsl",
    "package" : "com.intellij.wsl",
    "descriptor" : "plugins/WSL/resources/META-INF/plugin.xml"
  },
  "intellij.wsl.fs.helper" : {
    "name" : "intellij.wsl.fs.helper",
    "package" : "com.intellij.wsl.fs",
    "descriptor" : "plugins/wsl-file-system-helper/resources/META-INF/plugin.xml"
  },
  "intellij.yaml" : {
    "name" : "intellij.yaml",
    "package" : "org.jetbrains.yaml",
    "descriptor" : "community/plugins/yaml/resources/META-INF/plugin.xml",
    "dependencies" : [ {
      "plugin" : "com.intellij.modules.lang"
    } ]
  }
}
@endjson