version = "10.1.*"
upstream_repository = "https://github.com/python-pillow/Pillow"

[tool.stubtest]
stubtest_requirements = ["olefile"]
# darwin checks don't affect stubtest
platforms = ["linux", "win32"]
