load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.platform.bootstrap",
    srcs = ["src"],
    iml_files = ["intellij.platform.bootstrap.iml"],
    visibility = ["//visibility:public"],
    deps = ["//tools/idea/platform/util:intellij.platform.util[module]"],
)
