{
  parserClass="ru.adelf.idea.dotenv.parser.DotEnvParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="DotEnv"
  psiImplClassSuffix="Impl"
  psiPackage="ru.adelf.idea.dotenv.psi"
  psiImplPackage="ru.adelf.idea.dotenv.psi.impl"

  elementTypeHolderClass="ru.adelf.idea.dotenv.psi.DotEnvTypes"
  elementTypeClass="ru.adelf.idea.dotenv.psi.DotEnvElementType"
  tokenTypeClass="ru.adelf.idea.dotenv.psi.DotEnvTokenType"
}

dotEnvFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

key ::= KEY_CHARS

value ::= VALUE_CHARS | QUOTE VALUE_CHARS? QUOTE?

property ::= (key SEPARATOR value? COMMENT?) | key COMMENT?