class DataSourceError(RuntimeError): ...
class DataLayerError(RuntimeError): ...
class CRSError(DataLayerError): ...
class FeatureError(DataLayerError): ...
class GeometryError(DataLayerError): ...
class FieldError(DataLayerError): ...
