version = "68.2.*"
upstream_repository = "https://github.com/pypa/setuptools"
partial_stub = true

[tool.stubtest]
# darwin is equivalent to linux for OS-specific methods
platforms = ["linux", "win32"]
