version = "23.0.*"
upstream_repository = "https://github.com/benoitc/gunicorn"
requires = ["types-gevent"]

[tool.stubtest]
supported_platforms = ["linux", "darwin"]
ci_platforms = ["linux", "darwin"]
stubtest_requirements = ["gevent>=1.4.0", "eventlet>=0.24.1,!=0.36.0", "tornado>=0.2", "setproctitle", "PasteDeploy", "inotify"]
