/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package p1.p2;

public final class R {
    public static final class drawable {
        public static final int p<caret>ng=0x7f020000;
    }
}
