load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.junit.rt",
    srcs = ["src"],
    iml_files = ["intellij.junit.rt.iml"],
    visibility = ["//visibility:public"],
    # do not sort: must match IML order
    deps = [
        "//tools/idea/.idea/libraries:JUnit4",
        "//tools/idea/java/java-runtime:intellij.java.rt[module]",
    ],
)
