flowchart LR
  A-->B
  click A callback "Tooltip for a callback"
  click A clbk "Tooltip for a callback"
  click clbk "Tooltip for a callback"
  click A callback
  click callback() "Tooltip for a callback"
  click B "https://www.github.com" "This is a tooltip for a link"
  click "https://www.github.com" "This is a tooltip for a link"
  click B "https://www.github.com"
  click A call callback() "Tooltip for a callback"
  click A call callback()
  click B href "https://www.github.com" "This is a tooltip for a link"
  click B href "https://www.github.com"
  click href "https://www.github.com" "This is a tooltip for a link"