from authlib.integrations.base_client.sync_openid import _LogoutData
from authlib.oidc.core.claims import UserInfo

__all__ = ["AsyncOpenIDMixin"]

class AsyncOpenIDMixin:
    async def fetch_jwk_set(self, force: bool = False): ...
    async def userinfo(self, **kwargs) -> UserInfo: ...
    async def parse_id_token(self, token, nonce, claims_options=None, claims_cls=None, leeway: int = 120) -> UserInfo: ...
    async def create_logout_url(
        self, post_logout_redirect_uri=None, id_token_hint=None, state=None, *, client_id=None, logout_hint=None, ui_locales=None
    ) -> _LogoutData: ...
