class OpenIDMixin:
    def fetch_jwk_set(self, force: bool = False): ...
    def userinfo(self, **kwargs): ...
    def parse_id_token(self, token, nonce, claims_options=None, claims_cls=None, leeway: int = 120): ...
    def create_load_key(self): ...
