name: Jewel Checks

on:
  pull_request:
    paths:
      - "platform/jewel/**"

defaults:
  run:
    working-directory: platform/jewel

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run :check task
        run: ./gradlew :decorated-window:check :detekt-plugin:check :foundation:check :ide-laf-bridge:check :int-ui:int-ui-decorated-window:check :int-ui:int-ui-standalone:check :markdown:core:check :markdown:extensions:autolink:check :markdown:extensions:gfm-alerts:check :markdown:extensions:gfm-strikethrough:check :markdown:extensions:gfm-tables:check :markdown:ide-laf-bridge-styling:check :markdown:int-ui-standalone-styling:check :samples:ide-plugin:ktfmtCheck :samples:showcase:check :samples:standalone:check :ui:check :ui-tests:check --continue --no-daemon