name: Jewel Checks

on:
  pull_request:
    paths:
      - "platform/jewel/**"

defaults:
  run:
    working-directory: platform/jewel

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run :check task
        # Run checks for all modules except the IDE plugin sample, as that is bound to have missing APIs issues
        run: ./gradlew check -x :samples:ide-plugin:check --continue --no-daemon

      - name: Run detektMain and detektTest tasks
        # Run detekt checks for all modules except the IDE plugin sample, as that is bound to have missing APIs issues
        run: ./gradlew detektMain detektTest -x :samples:ide-plugin:detektMain -x :samples:ide-plugin:detektTest --continue --no-daemon

      - name: Run ktfmt and ktlint checks on IDE plugin
        # We can only use static analysis that doesn't depend on compilation in the IDE plugin
        run: ./gradlew :samples:ide-plugin:ktfmtCheck :samples:ide-plugin:lintKotlinMain --continue --no-daemon
