load("//tools/base/bazel:bazel.bzl", "iml_module")

# managed by go/iml_to_build
iml_module(
    name = "intellij.gradle.toolingLoaderRt",
    srcs = ["src"],
    iml_files = ["intellij.gradle.toolingLoaderRt.iml"],
    visibility = ["//visibility:public"],
)
